/* ══════════════════════════════════════════════════
   JAVASCRIPT EXERCISES — CH6-CH10 (nodes 21-42)
   Expanded: 4-5 exercises per node, diverse types
   University-aligned: MIT 6.006, Stanford CS106B, Princeton COS226
   ══════════════════════════════════════════════════ */
export const jsExercisesCh6to10 = {
    // ═══ CH6: ALGORITHMS I ═══
    21: [
        { type: 'algostep', prompt: 'Selection sort begins on [64,25,12,22,11]', array: [64, 25, 12, 22, 11], step: 1, description: 'Pass 1 scans the whole array for the smallest value.', question: 'What does pass 1 do?', options: ['11→index 0', '12→index 0', '22→index 1', '25→index 0'], correct: 0, explanation: 'Selection sort scans for the minimum of the unsorted part and swaps it to the front — pass 1 finds 11 and puts it at index 0. Each pass fixes exactly one position for good, which is why it always takes n-1 passes no matter how sorted the input already is.', hint: 'Scan the whole array once. What is the smallest value, and where does this algorithm put it?' },
        { type: 'trace', prompt: 'After ONE bubble pass, what is guaranteed?', code: [{ text: '// Compare adjacent, swap if needed' }, { text: '[5,1]→swap [1,5,4,2,8]' }, { text: '[5,4]→swap [1,4,5,2,8]' }, { text: '[5,2]→swap [1,4,2,5,8]' }, { text: '[5,8]→ok   [1,4,2,5,8]', highlight: true }], options: ['Largest at end', 'Array sorted', 'Smallest at start', 'Nothing guaranteed'], correct: 0, explanation: 'Watch what travels: the 5 gets carried rightward by every swap until something bigger stops it — so after one pass the largest element has bubbled to the end, and only that much is promised. The rest is still scrambled. That one-guarantee-per-pass is why bubble sort needs up to n-1 passes.', hint: 'Follow the 5 through the swaps. Where does the biggest value always end up?' },
        { type: 'pair', prompt: 'Match each sort to its cost', pairs: [{ id: 1, left: 'Bubble, worst case', right: 'O(n²)' }, { id: 2, left: 'Merge, always', right: 'O(n log n)' }, { id: 3, left: 'Insertion, best case', right: 'O(n)' }, { id: 4, left: 'Array.sort()', right: 'Timsort' }], explanation: 'The qualifier matters as much as the number: merge sort is O(n log n) in EVERY case, insertion sort ranges from O(n) on sorted input to O(n²) on reversed. V8 runs Timsort under Array.sort, and since ES2019 the spec requires sort to be stable — equal elements keep their order.' },
        { type: 'scramble', prompt: 'Assemble insertion sort', pieces: [{ id: 'a', text: 'function insertionSort(arr) {' }, { id: 'b', text: '    for (let i = 1; i < arr.length; i++) {' }, { id: 'c', text: '        let key = arr[i];' }, { id: 'd', text: '        let j = i - 1;' }, { id: 'e', text: '        while (j >= 0 && arr[j] > key) {' }, { id: 'f', text: '            arr[j+1] = arr[j]; j--;' }, { id: 'g', text: '        }' }, { id: 'h', text: '        arr[j+1] = key;' }, { id: 'i', text: '    }' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        arr[j] = key;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'key has to be saved BEFORE the shifting starts, because the shift overwrites arr[i]. The while walks left moving bigger elements one slot right, and when it stops, j+1 is the hole where key belongs. The spare line writes to arr[j] instead of arr[j+1] — off by one slot, quietly overwriting an element instead of filling the hole.', hint: 'When the while loop stops, where exactly is the empty slot — at j, or at j+1?' },
        { type: 'bug', prompt: '[10,9,1,2,100] comes back as [1,10,100,2,9]. Which line?', code: [{ text: 'function sort(arr) {', hasError: false }, { text: '    return arr.sort();', hasError: true }, { text: '}', hasError: false }, { text: 'sort([10,9,1,2,100]); // → [1,10,100,2,9]', hasError: false }], correctLine: 1, explanation: 'sort() with no comparator converts every element to a STRING and compares those — and "10" < "2" lexicographically, exactly like "apple" < "banana". Numbers need the comparator spelled out: arr.sort((a, b) => a - b). This is arguably the most famous footgun in the language, and it never throws; it just quietly mis-sorts.', hint: 'Look at the output: 1, 10, 100, 2, 9. Read them as words instead of numbers — what order is that?' },
    ],
    22: [
        { type: 'algostep', prompt: 'Binary search for 7 in [1,3,5,7,9,11,13]', array: [1, 3, 5, 7, 9, 11, 13], step: 1, description: 'lo=0, hi=6, so mid=3 — and arr[3] is checked first.', question: 'How many comparisons does finding 7 take?', options: ['1', '2', '3', '7'], correct: 0, explanation: 'The first midpoint of a 7-element array is index 3, and arr[3] happens to BE the 7 — one comparison, done. That is luck, not the general cost: the guarantee is at most ⌈log₂(n)⌉+1 comparisons, about 3 here. 7 is what linear search would need if the target were last.', hint: 'Work out which index gets checked first. What value lives there?' },
        { type: 'trace', prompt: '6 is not in the array. What does the search do?', code: [{ text: 'function bsearch(arr, t) {' }, { text: '    let lo = 0, hi = arr.length - 1;' }, { text: '    while (lo <= hi) {' }, { text: '        const mid = Math.floor((lo+hi)/2);' }, { text: '        if (arr[mid] === t) return mid;' }, { text: '        else if (arr[mid] < t) lo = mid+1;' }, { text: '        else hi = mid-1;' }, { text: '    }' }, { text: '    return -1;', highlight: true }, { text: '}' }], options: ['Returns 2', 'Returns 3', 'Returns -1', 'Infinite loop'], correct: 2, explanation: 'Trace it: mid=2 → arr[2]=5 < 6 so lo=3; mid=3 → arr[3]=7 > 6 so hi=2. Now lo > hi, the while fails, -1 comes back. Termination is no accident — the +1/-1 on every move is what guarantees the window closes. Drop either and you get the infinite-loop option.', hint: 'Run two iterations by hand. What are lo and hi after each, and when does the while stop?' },
        { type: 'errordecode', prompt: 'This search returns -1 for values that ARE in the array. Why?', errorText: 'const mid = (lo + hi) / 2;\narr[mid]   // mid = 4.5 → arr[4.5] is undefined\n           // undefined === t is false → search walks off', question: 'Safe midpoint?', options: ['lo + Math.floor((hi-lo)/2)', '(lo+hi) % 2', 'hi - lo', 'lo * hi'], correct: 0, explanation: 'JavaScript division produces 4.5, and arr[4.5] is not an error — it is undefined, which never equals the target, so the search quietly fails. No crash, no warning, just wrong answers: the worst kind of bug. Math.floor (or (lo+hi) >> 1) fixes it. In Java and C the same line has a DIFFERENT disease — integer overflow of lo+hi, a bug that sat in the JDK for nine years — but that one cannot happen to a JS array, whose length maxes out at 2³²−1, far below Number.MAX_SAFE_INTEGER.', hint: 'What is arr[4.5]? And does that throw, or do something quieter and worse?' },
        { type: 'realworld', prompt: 'What must be true of the array before binary search works?', scenario: '⚠️ Break the precondition and the search silently misses values that ARE there.', options: [{ code: 'arr.sort((a,b) => a-b)', label: 'It is sorted' }, { code: 'new Set(arr).size === arr.length', label: 'All elements unique' }, { code: 'arr.length < 1000', label: 'It is small' }, { code: 'Array.isArray(arr)', label: 'It is an array' }], correct: 0, explanation: 'Halving only works because comparing against the middle tells you WHICH half the target must be in — an inference only valid on sorted data. On unsorted data the search returns wrong answers silently. Duplicates are fine (you get one of the positions), size is irrelevant, and anything indexable works. Note even the sort in the option needs its comparator, per the previous lesson.', hint: 'The algorithm throws half the array away after one comparison. What justifies that?' },
        { type: 'bug', prompt: 'This search sometimes hangs forever. Which line?', code: [{ text: 'function bs(arr, t) {', hasError: false }, { text: '    let lo = 0, hi = arr.length;', hasError: false }, { text: '    while (lo < hi) {', hasError: false }, { text: '        const mid = (lo + hi) >> 1;', hasError: false }, { text: '        if (arr[mid] < t) lo = mid;', hasError: true }, { text: '        else hi = mid;', hasError: false }, { text: '    }', hasError: false }], correctLine: 4, explanation: 'When the window narrows to two elements, mid computes to lo — and if arr[mid] < t, the update lo = mid changes NOTHING. Same window, same mid, forever. It must be lo = mid + 1, which is legal precisely because arr[mid] was just ruled out. The else branch is fine as-is: in this half-open style mid was not ruled out there, so hi = mid keeps it in range. Every binary search variant lives or dies on this progress argument.', hint: 'Set lo=3, hi=4 and walk one iteration where arr[mid] < t. What changed?' },
    ],
    23: [
        { type: 'trace', prompt: 'How does the work grow when n doubles?', code: [{ text: 'for (let i = 0; i < n; i++) {' }, { text: '    for (let j = 0; j < n; j++) {' }, { text: '        console.log(i, j);' }, { text: '    }' }, { text: '}' }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'], correct: 1, explanation: 'The inner loop runs n times for each of the n outer passes — n × n = n². The practical meaning: double n and the work quadruples. O(n log n) would need the inner range to shrink or halve; O(2ⁿ) is a different universe, where adding ONE to n doubles the work.', hint: 'Count total logs for n=10, then for n=20. What is the ratio?' },
        { type: 'pair', prompt: 'Match each algorithm to its complexity', pairs: [{ id: 1, left: 'Binary Search', right: 'O(log n)' }, { id: 2, left: 'Bubble Sort', right: 'O(n²)' }, { id: 3, left: 'Merge Sort', right: 'O(n log n)' }, { id: 4, left: 'Map/Set lookup', right: 'O(1) average' }], explanation: 'A useful reading: log n means "halves the problem each step", n² means "compares pairs", n log n means "divides, then touches everything per level". The average on the hash lookup is honest — a pathological set of colliding keys degrades it to O(n), and includes() on an ARRAY is always O(n), which is the one people mix up with Set.has.' },
        { type: 'trace', prompt: 'i is halved each pass. What is the complexity?', code: [{ text: 'let i = n;' }, { text: 'while (i > 0) {' }, { text: '    console.log(i);' }, { text: '    i = Math.floor(i / 2);', highlight: true }, { text: '}' }], options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1, explanation: 'The loop variable is divided, not decremented — that single character difference is the whole answer. From n it takes log₂(n) halvings to reach 0. Change the line to i -= 2 and it becomes O(n). The Math.floor also matters here: without it i approaches 0 forever without hitting it, and the loop never ends.', hint: 'Look only at the highlighted line. Is i shrinking by a constant amount, or by a constant factor?' },
        { type: 'refactor', prompt: 'The membership check runs thousands of times. Which rewrite pays off?', originalCode: '// Runs in a hot loop:\nif (arr.includes(x)) {\n    ...\n}', options: [{ code: 'const lookup = new Set(arr); // once\nif (lookup.has(x)) {\n    ...\n}', label: 'Build a Set, check the Set' }, { code: 'arr.sort((a,b) => a-b); // once\n// then binary search each time', label: 'Sort once, bisect each time' }, { code: 'let found = false;\nfor (const item of arr) {\n    if (item === x) { found = true; break; }\n}', label: 'Loop with early exit' }], correct: 0, explanation: 'The Set costs O(n) once, then every check is O(1) — thousands of checks amortise the build immediately. The sort+bisect route genuinely works at O(log n) per check, but it mutates the array (sort is in-place) and JavaScript ships no built-in bisect, so you write and maintain one. The manual loop is exactly what includes() already does — same O(n), more code.', hint: 'Separate the one-time cost from the per-check cost. Which option has the cheapest per-check?' },
        { type: 'output', prompt: 'How much EXTRA memory does this reversal use?', code: [{ text: 'function reverse(str) {' }, { text: '    return [...str].reverse().join("");' }, { text: '}' }], terminalOutput: 'O(n)', options: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'], correct: 1, explanation: 'The spread builds an n-element array of characters, and join builds an n-character string — both proportional to the input, so O(n) extra space. O(1) reversal by swapping in place is impossible here for a deeper reason: JavaScript strings are immutable, so ANY string reversal must allocate. In-place is only an option for arrays.', hint: 'Count the new containers this line creates, and how big each one is relative to the input.' },
    ],
    24: [
        { type: 'trace', prompt: 'Which pair does the brute force return first?', code: [{ text: 'function twoSum(nums, t) {' }, { text: '    for (let i = 0; i < nums.length; i++) {' }, { text: '        for (let j = i+1; j < nums.length; j++) {' }, { text: '            if (nums[i]+nums[j] === t)' }, { text: '                return [i, j];' }, { text: '        }' }, { text: '    }' }, { text: '}' }, { text: 'console.log(twoSum([2,7,11,15], 9));', highlight: true }], options: ['[0, 1]', '[1, 2]', '[0, 3]', 'undefined'], correct: 0, explanation: 'The very first pair tried is i=0, j=1: 2+7 = 9 — immediate hit, and the function returns INDICES, not values. j starts at i+1, which prevents both using the same element twice and checking each pair twice. undefined is what the function yields when every pair misses, since there is no explicit return at the end.', hint: 'What is the first (i, j) the loops generate, and what do those two values sum to?' },
        { type: 'refactor', prompt: 'Which rewrite makes two-sum a single pass AND keeps the indices right?', originalCode: 'for (let i=0; i<nums.length; i++)\n    for (let j=i+1; j<nums.length; j++)\n        if (nums[i]+nums[j]===target) return [i,j];', options: [{ code: 'const seen = new Map();\nfor (let i = 0; i < nums.length; i++) {\n    const comp = target - nums[i];\n    if (seen.has(comp)) return [seen.get(comp), i];\n    seen.set(nums[i], i);\n}', label: 'Map of value→index' }, { code: 'nums.sort((a,b) => a-b);\n// then walk two pointers inward', label: 'Sort, then two pointers' }, { code: 'return nums.map(n =>\n    nums.indexOf(target - n));', label: 'map with indexOf' }], correct: 0, explanation: 'The Map answers "have I already seen my complement?" in O(1), one pass total. The two-pointer version is genuinely O(n log n) and elegant — but sort() mutates nums and destroys the original indices the problem asks for. The map/indexOf one hides an O(n) scan inside every iteration, so it is still quadratic, and returns a malformed answer anyway (one entry per element, -1 for misses).', hint: 'Two of these are faster than the original. Which one still returns the ORIGINAL indices without extra bookkeeping?' },
        { type: 'scramble', prompt: 'Assemble the one-pass two-sum', pieces: [{ id: 'a', text: 'function twoSum(nums, target) {' }, { id: 'b', text: '    const seen = new Map();' }, { id: 'c', text: '    for (let i = 0; i < nums.length; i++) {' }, { id: 'd', text: '        const comp = target - nums[i];' }, { id: 'e', text: '        if (seen.has(comp)) {' }, { id: 'f', text: '            return [seen.get(comp), i];' }, { id: 'g', text: '        }' }, { id: 'h', text: '        seen.set(nums[i], i);' }, { id: 'i', text: '    }' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        seen.set(i, nums[i]);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'The has-check must come BEFORE the set — check-then-add is what stops an element pairing with itself when target is twice its value. The Map goes value→index so seen.get(comp) retrieves a position. The spare line stores index→value, backwards: seen.has(comp) would then ask whether the complement is an INDEX. A Map is the right container here rather than {} because object keys stringify — numeric keys survive a Map intact.', hint: 'The Map is asked "where did I see this VALUE?". Which way round must the keys go?' },
        { type: 'bug', prompt: 'This version cannot even be finished. Which line doomed it?', code: [{ text: 'function twoSum(nums, t) {', hasError: false }, { text: '    const map = {};', hasError: false }, { text: '    for (const n of nums) {', hasError: true }, { text: '        if (map[t-n] !== undefined)' }, { text: '            return [map[t-n], /* i?? */];', hasError: false }, { text: '        map[n] = /* i?? */;', hasError: false }], correctLine: 2, explanation: 'for...of hands you the VALUES only — and this algorithm needs the index twice: to store under each value and to return on a hit. With for...of there is simply no i to write, which is what the /* i?? */ holes show. The fix is the loop, not the body: for (const [i, n] of nums.entries()) or a classic indexed for. Choosing the iteration style is part of designing the algorithm, not a cosmetic detail.', hint: 'Look at the two holes in the body. What variable do they both need, and does this loop provide it anywhere?' },
    ],
    // ═══ CH7: DATA STRUCTURES II ═══
    25: [
        { type: 'trace', prompt: 'Push 1, 2, 3, then pop twice. What remains?', code: [{ text: 'const stack = [];' }, { text: 'stack.push(1); stack.push(2); stack.push(3);' }, { text: 'stack.pop(); stack.pop();' }, { text: 'console.log(stack);', highlight: true }], options: ['[1]', '[3]', '[1,2]', '[]'], correct: 0, explanation: 'pop() removes from the END — last in, first out. The two pops take 3 then 2, leaving [1]. Answering [3] means thinking of a queue, where the earliest items leave first; that is exactly the distinction this question tests. A plain array IS the JS stack idiom: push and pop both work at the tail in O(1).', hint: 'Which end does pop() take from? Remove twice from that end.' },
        { type: 'pair', prompt: 'Match each structure to its discipline', pairs: [{ id: 1, left: 'Stack', right: 'Last in, first out' }, { id: 2, left: 'Queue', right: 'First in, first out' }, { id: 3, left: 'Deque', right: 'Both ends open' }, { id: 4, left: 'Priority Queue', right: 'Best out first' }], explanation: 'The discipline — who leaves first — is the entire difference; the storage underneath can be identical. A priority queue is the odd one out: departure depends on a comparison, not arrival time, which is why it is heap-backed. JS note: shift() on an array re-indexes every element, so heavy queues want a real deque or an index-based ring.' },
        { type: 'scramble', prompt: 'Assemble the balanced-brackets checker', pieces: [{ id: 'a', text: 'function isValid(s) {' }, { id: 'b', text: '    const stack = [];' }, { id: 'c', text: '    const pairs = {")":"(", "]":"[", "}":"{"};' }, { id: 'd', text: '    for (const c of s) {' }, { id: 'e', text: '        if ("([{".includes(c)) stack.push(c);' }, { id: 'f', text: '        else if (!stack.length || stack.pop() !== pairs[c])' }, { id: 'g', text: '            return false;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return stack.length === 0;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '    return true;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'Two subtleties carry the algorithm. !stack.length must be checked before popping — a closer with nothing open (")(" ) would otherwise compare against undefined. And the final line must verify the stack is EMPTY: plain return true passes "(((", where openers never closed. The three failure modes are wrong pair, early closer, unclosed opener — one line each.', hint: 'Three ways to be unbalanced: wrong match, closer-first, opener never closed. Find the line that catches each.' },
        { type: 'realworld', prompt: 'Which of these is LIFO by nature?', scenario: '🧠 The structure should mirror how the task actually behaves.', options: [{ code: 'undo history, the call stack, bracket matching', label: 'Undo / calls / brackets' }, { code: 'a print queue: first job submitted prints first', label: 'A print queue' }, { code: 'browser autocomplete suggestions', label: 'Autocomplete ranking' }, { code: 'a leaderboard ordered by score', label: 'A leaderboard' }], correct: 0, explanation: 'Undo reverses the MOST RECENT action, a return leaves the MOST RECENT call, and a closing bracket matches the MOST RECENT opener — all three are literally last-in-first-out. The print queue is the textbook FIFO counterexample, and the other two are ordered by relevance and score, not by arrival at all.', hint: 'For each one ask: when something leaves, is it the newest or the oldest?' },
        { type: 'errordecode', prompt: 'The CALL STACK is a stack. What overflowed it?', errorText: 'RangeError: Maximum call stack size exceeded\n    at factorial (main.js:2)\n    at factorial (main.js:2)\n    at factorial (main.js:2)', question: 'Cause?', options: ['Recursion that never reaches a base case', 'An array grew too large', 'A memory leak', 'A syntax error'], correct: 0, explanation: 'Every call pushes a frame onto the call stack and every return pops one — the same LIFO structure this chapter is about. Recursion with no reachable base case pushes forever, and the repeated identical line in the trace is the giveaway. A big array would fail with a different error (out of memory), and syntax errors happen before anything runs.', hint: 'Read the stack trace: the same line, again and again. What does each repetition represent?' },
    ],
    26: [
        { type: 'trace', prompt: 'What is a.next.val in this chain?', code: [{ text: 'class Node {' }, { text: '    constructor(val) { this.val=val; this.next=null; }' }, { text: '}' }, { text: 'const a=new Node(1), b=new Node(2), c=new Node(3);' }, { text: 'a.next=b; b.next=c;' }, { text: 'console.log(a.next.val);', highlight: true }], options: ['1', '2', '3', 'null'], correct: 1, explanation: 'a.next points at b, and b.val is 2. Reading a chain of dots left to right — a, then .next (b), then .val — is the core skill for every linked-structure problem. a.next.next.val would be 3, and c.next is null, which is how the end of a list announces itself.', hint: 'Resolve one dot at a time: what object is a.next? Then take its val.' },
        { type: 'scramble', prompt: 'Assemble the list traversal', pieces: [{ id: 'a', text: 'function traverse(head) {' }, { id: 'b', text: '    let curr = head;' }, { id: 'c', text: '    while (curr) {' }, { id: 'd', text: '        console.log(curr.val);' }, { id: 'e', text: '        curr = curr.next;' }, { id: 'f', text: '    }' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '        curr = curr.prev;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The loop condition is while (curr), not while (curr.next) — the latter stops one node early and never prints the last value, the most common traversal off-by-one. Advancing via a separate curr keeps head intact for whoever still needs the list. The spare line needs .prev, which singly-linked nodes do not have.', hint: 'When should the loop stop: at the last node, or after it? Check which condition prints the final value.' },
        { type: 'realworld', prompt: 'Where does a linked list actually beat an array?', scenario: '🤔 Same data, different dominant operation.', options: [{ code: 'insert/remove at the FRONT, constantly', label: 'Heavy work at the head' }, { code: 'data[i] for random i, constantly', label: 'Random access by index' }, { code: 'sort the data repeatedly', label: 'Frequent sorting' }, { code: 'binary search over sorted data', label: 'Binary search' }], correct: 0, explanation: 'Inserting at a list head is relinking two pointers — O(1) — where an array must shift everything. Everything else favours the array: indexing a linked list walks i nodes, sorting wants cheap swaps and locality, and binary search NEEDS O(1) indexing to jump to mid. One honest niche, not a general upgrade.', hint: 'Three of these need to jump to arbitrary positions. Which one only ever touches the front?' },
        { type: 'bug', prompt: 'This reversal loses the whole list. Which line?', code: [{ text: 'function reverse(head) {', hasError: false }, { text: '    let prev = null, curr = head;', hasError: false }, { text: '    while (curr) {', hasError: false }, { text: '        curr.next = prev;', hasError: true }, { text: '        prev = curr; curr = curr.next;', hasError: false }], correctLine: 3, explanation: 'The overwrite happens before anything saved where the list continues. By the time curr = curr.next runs, curr.next has already been redirected BACKWARDS to prev — so the walk revisits the node it came from and the rest of the list is unreachable. The fix is one line before the overwrite: const next = curr.next, then advance with curr = next. Order of operations IS the algorithm here.', hint: 'After line 4 runs, where does curr.next point? Now execute line 5 with that in mind.' },
    ],
    27: [
        { type: 'trace', prompt: 'In-order traversal of this BST prints what?', code: [{ text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '//    / \\' }, { text: '//   1   3' }, { text: '// in-order: visit left subtree, node, right subtree', highlight: true }], options: ['4 2 1 3 6', '1 2 3 4 6', '1 3 2 6 4', '4 2 6 1 3'], correct: 1, explanation: 'In-order goes fully left first: 1, back to 2, then 3, up to 4, then 6 — ascending order. That is not luck: BST invariant (left < node < right) plus in-order = sorted output, always. The first option is pre-order, the third post-order, the last level-order.', hint: 'Fully left before every node, right after. Start at the deepest left leaf.' },
        { type: 'pair', prompt: 'Match each traversal to its visiting order', pairs: [{ id: 1, left: 'In-order', right: 'Left, root, right' }, { id: 2, left: 'Pre-order', right: 'Root, left, right' }, { id: 3, left: 'Post-order', right: 'Left, right, root' }, { id: 4, left: 'Level-order', right: 'Layer by layer (BFS)' }], explanation: 'The name says where the ROOT goes: pre (first), in (middle), post (last). Each has a job — pre-order copies a tree, post-order deletes one safely (children before parent), and level-order is the odd one out: it needs a queue, not recursion, because it crosses branches.' },
        { type: 'fillgap', prompt: 'val is SMALLER than this node — which way does the search go?', codeParts: [{ text: 'function search(node, val) {\n    if (!node) return null;\n    if (val === node.val) return node;\n    return val < node.val\n        ? ', type: 'fixed' }, { text: 'search(node.left, val)', type: 'gap', id: 'g1' }, { text: '\n        : search(node.right, val);\n}', type: 'fixed' }], bank: ['search(node.left, val)', 'search(node.right, val)', 'search(node, val-1)', 'node.left'], correctFill: { g1: 'search(node.left, val)' }, explanation: 'Smaller values live left — that is the BST invariant, and the recursion simply follows it. Recursing right on the smaller branch searches where the value cannot be. search(node, val-1) mutates the TARGET, hunting a different number on the same node forever. And bare node.left returns a node without checking it: the ?: needs two calls of the same shape.', hint: 'The condition already told you val < node.val. Where does the invariant say smaller values live?' },
        { type: 'output', prompt: 'Inserting 5 — which empty slot does it land in?', code: [{ text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '// insert 5: compare at 4, then at 6' }], terminalOutput: 'Left child of 6', options: ['Left child of 6', 'Right child of 4', 'Left child of 2', 'Root'], correct: 0, explanation: 'Walk it: 5 > 4 so go right; 5 < 6 so go left — and left of 6 is empty, so that is home. BST insert is just a failed search that plants the value where the search fell off. "Right child of 4" is taken (by 6): insertion never displaces an existing node.', hint: 'Insert = search until you fall off the tree. Run the comparisons: 5 vs 4, then 5 vs 6.' },
    ],
    28: [
        { type: 'video', title: 'Data Structures Visualized', description: 'Stacks, queues, linked lists, trees — when to use each, trade-offs, and real-world applications.', duration: '4:00', thumbnail: '🎥' },
        { type: 'pair', prompt: 'Match each operation to its cost', pairs: [{ id: 1, left: 'array[i]', right: 'O(1)' }, { id: 2, left: 'List: insert at head', right: 'O(1), two pointers move' }, { id: 3, left: 'BST search, balanced', right: 'O(log n)' }, { id: 4, left: 'array.unshift(x)', right: 'O(n), everything shifts' }], explanation: 'Each structure buys one cheap operation by making another expensive: the array\'s O(1) indexing costs it O(n) unshift, and the linked list makes the opposite trade. The BST\'s log n carries a hidden condition — "balanced" — which is why self-balancing variants exist at all.' },
        { type: 'realworld', prompt: 'Back AND Forward must both work. What state do you keep?', scenario: '🌐 Visit A→B→C, press Back, then Forward, then visit D — Forward must now be empty.', options: [{ code: 'backStack + forwardStack;\n// Back: push current to fwd, pop back\n// new visit: clear fwd', label: 'Two stacks' }, { code: 'const history = []; // append only', label: 'One growing array' }, { code: 'const q = []; // shift() oldest out', label: 'A queue' }, { code: 'let last = url; // remember one page', label: 'A single variable' }], correct: 0, explanation: 'Back undoes the most recent navigation and Forward undoes the most recent Back — two LIFO histories feeding each other, and a fresh visit clears the forward stack, which is exactly the behaviour browsers have. An append-only array cannot express that clearing without extra index bookkeeping (at which point it is two stacks in disguise). A queue surrenders the OLDEST page, and one variable cannot go back twice.', hint: 'Press Back twice, then Forward once, then visit a new page. Track what each candidate must remember.' },
        { type: 'trace', prompt: 'push, push, push, shift, push — what remains?', code: [{ text: 'const q = [];' }, { text: 'q.push(1); q.push(2); q.push(3);' }, { text: 'q.shift();' }, { text: 'q.push(4);' }, { text: 'console.log(q);', highlight: true }], options: ['[2,3,4]', '[1,2,3,4]', '[4,3,2]', '[1,3,4]'], correct: 0, explanation: 'push adds at the tail, shift removes from the HEAD — so 1 leaves and 4 joins the back: [2,3,4]. That is queue behaviour built on an array. The cost worth knowing: shift() re-indexes every remaining element, O(n) per call, so a busy queue is better served by a ring buffer or a linked deque.', hint: 'shift takes from which end? Remove there, then append the 4.' },
    ],
    // ═══ CH8: ALGORITHMS II ═══
    29: [
        { type: 'trace', prompt: 'Tower of Hanoi with 3 disks — how many moves?', code: [{ text: 'function hanoi(n) {' }, { text: '    if (n === 1) return 1;' }, { text: '    return 2 * hanoi(n-1) + 1;' }, { text: '}' }, { text: 'console.log(hanoi(3));', highlight: true }], options: ['3', '5', '7', '8'], correct: 2, explanation: 'Unfold it: hanoi(1)=1, hanoi(2)=3, hanoi(3)=7 — each disk added DOUBLES the work plus one, because the whole smaller tower moves twice (off the big disk, then back on). The closed form is 2ⁿ−1, and the exponential growth is genuine: 64 disks is 2⁶⁴−1 moves.', hint: 'Compute hanoi(1), then hanoi(2), then hanoi(3), each from the previous.' },
        { type: 'trace', prompt: 'What does sumDigits(1234) return?', code: [{ text: 'function sumDigits(n) {' }, { text: '    if (n < 10) return n;' }, { text: '    return n%10 + sumDigits(Math.floor(n/10));' }, { text: '}' }, { text: 'console.log(sumDigits(1234));', highlight: true }], options: ['10', '1234', '4', '24'], correct: 0, explanation: 'Each level peels the last digit and recurses on the rest: 4 + (3 + (2 + 1)) = 10. Math.floor is essential — JS division gives 123.4, and without flooring the recursion never reaches a clean single digit. 4 is just the first digit peeled.', hint: 'Write the four levels out: what does each call contribute?' },
        { type: 'output', prompt: 'e is halved on even steps. What is the complexity?', code: [{ text: 'function power(b, e) {' }, { text: '    if (e === 0) return 1;' }, { text: '    if (e % 2 === 0) {' }, { text: '        const h = power(b, e/2);' }, { text: '        return h * h;' }, { text: '    }' }, { text: '    return b * power(b, e-1);' }, { text: '}' }], terminalOutput: 'O(log n)', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1, explanation: 'The even branch halves e, and an odd e becomes even after one subtraction — so at least every second step halves, giving O(log e). The crucial detail is computing h ONCE and squaring it: write power(b,e/2) * power(b,e/2) and each level doubles its calls, collapsing back to O(e).', hint: 'How fast does e shrink? And why does saving h into a const matter so much?' },
        { type: 'bug', prompt: 'flatten works on every normal input. Which line names its killer?', code: [{ text: 'function flatten(arr) {', hasError: false }, { text: '    const result = [];', hasError: false }, { text: '    for (const item of arr) {', hasError: false }, { text: '        if (Array.isArray(item)) result.push(...flatten(item));', hasError: false }, { text: '        else result.push(item);', hasError: false }, { text: '    }', hasError: false }, { text: '    return result;', hasError: false }, { text: '}', hasError: false }, { text: '// const a = [1]; a.push(a); flatten(a);', hasError: true }], correctLine: 8, explanation: 'a contains itself, so flatten(a) reaches a inside a and recurses forever — the base case ("not an array") is never met on a cyclic structure. Structural recursion terminates only when the structure is finite and acyclic. Real APIs face this too: JSON.stringify throws TypeError on circular references, while structuredClone handles them by tracking visited objects — which is exactly the fix here, a Set of seen arrays.', hint: 'Recursion stops when it reaches a non-array. Can this input ever provide one?' },
        { type: 'fillgap', prompt: 'Complete the RECURSIVE definition of sum', codeParts: [{ text: 'function sum(arr) {\n    if (arr.length === 0) return 0;\n    return ', type: 'fixed' }, { text: 'arr[0] + sum(arr.slice(1));', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['arr[0] + sum(arr.slice(1));', 'sum(arr) + arr[0];', 'arr.reduce((a,b) => a+b, 1);', 'arr[0] + arr[1];'], correctFill: { g1: 'arr[0] + sum(arr.slice(1));' }, explanation: 'Head plus sum-of-tail, with the empty array as base case — the canonical structural recursion. sum(arr) + arr[0] recurses on the SAME array: nothing shrinks, stack overflow. The reduce would nearly work but its seed is 1, so every answer is off by one — the seed is the empty-case value and must be 0. And arr[0] + arr[1] adds two elements, not all of them.', hint: 'The recursive case must call sum on something strictly smaller. Which options do?' },
    ],
    30: [
        { type: 'algostep', prompt: 'Merging sorted [1,3,5] and [2,4,6]', array: [1, 3, 5, 2, 4, 6], step: 1, description: 'Both lists are sorted. Compare the two FRONTS: 1 vs 2 — take 1.', question: 'Which comparison happens next?', options: ['3 vs 2', '1 vs 2', '5 vs 6', '3 vs 4'], correct: 0, explanation: 'Taking 1 advances only the LEFT pointer, so the fronts are now 3 and 2. Merge never looks deeper than the two fronts — each comparison retires exactly one element, which is why the whole merge is O(n). It only works because both inputs are already sorted.', hint: 'Only the list that surrendered an element advances. What are the two fronts now?' },
        { type: 'trace', prompt: 'log n levels, O(n) work per level — total?', code: [{ text: '// splitting halves the array: log₂(n) levels deep' }, { text: '// merging touches every element once per level: O(n)' }, { text: '// total = levels × work per level = ?', highlight: true }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'], correct: 2, explanation: 'log n levels times n work per level is n log n — the multiplication IS the analysis. This shape generalises: any divide-and-conquer that halves and does linear work per level lands on n log n. Picking O(n) counts one level only; O(log n) counts the levels but forgets the merging.', hint: 'Two numbers are given. The answer is what you do with them.' },
        { type: 'pair', prompt: 'Match each algorithm to its divide step', pairs: [{ id: 1, left: 'Merge sort', right: 'Split in half, sort both' }, { id: 2, left: 'Quick sort', right: 'Partition around a pivot' }, { id: 3, left: 'Binary search', right: 'Discard half each probe' }, { id: 4, left: 'Strassen', right: 'Split matrices into blocks' }], explanation: 'Same family, different divide: merge sort splits by POSITION and works while combining; quicksort splits by VALUE and works while dividing, so its combine step is free. Binary search is the degenerate case — it divides but only ever keeps one half, which is why it is log n rather than n log n.' },
        { type: 'scramble', prompt: 'Assemble the merge step', pieces: [{ id: 'a', text: 'function merge(left, right) {' }, { id: 'b', text: '    const result = [];' }, { id: 'c', text: '    let i = 0, j = 0;' }, { id: 'd', text: '    while (i < left.length && j < right.length) {' }, { id: 'e', text: '        if (left[i] <= right[j]) result.push(left[i++]);' }, { id: 'f', text: '        else result.push(right[j++]);' }, { id: 'g', text: '    }' }, { id: 'h', text: '    return [...result, ...left.slice(i), ...right.slice(j)];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    return left.concat(right).sort();' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], explanation: 'The tail spreads are not optional: the while stops when ONE side empties, and the survivors — all larger than everything taken — must be appended or data is silently dropped. The <= keeps the merge stable. The spare line calls sort(), which defeats the point twice over: merge exists to AVOID re-sorting, and comparator-less sort() is lexicographic anyway.', hint: 'When the while exits, what state are the two arrays in? Something is left over — where does it go?' },
    ],
    31: [
        { type: 'trace', prompt: 'How many times is fib() entered for fib(5), no memo?', code: [{ text: 'function fib(n) {' }, { text: '    if (n <= 1) return n;' }, { text: '    return fib(n-1) + fib(n-2);' }, { text: '}' }, { text: '// count every call in the tree for fib(5)', highlight: true }], options: ['5', '9', '15', '25'], correct: 2, explanation: 'Count bottom-up: calls(0)=1, calls(1)=1, then calls(n)=1+calls(n-1)+calls(n-2) → 3, 5, 9, 15. Fifteen calls to compute six values — fib(1) alone is entered five times. That redundancy is the whole case for memoisation, which collapses the tree to one call per distinct n.', hint: 'Build a small table: how many calls does fib(2) take? fib(3)? Each row uses the two before it.' },
        { type: 'refactor', prompt: 'Which rewrite stops recomputing the same values?', originalCode: 'function fib(n) {\n    if (n<=1) return n;\n    return fib(n-1)+fib(n-2);\n}', options: [{ code: 'const memo = {};\nfunction fib(n) {\n    if (n in memo) return memo[n];\n    if (n<=1) return n;\n    memo[n] = fib(n-1)+fib(n-2);\n    return memo[n];\n}', label: 'Cache results in an object' }, { code: 'const fib = n =>\n    n<=1 ? n : fib(n-1)+fib(n-2);', label: 'Compress to an arrow' }, { code: 'function fib(n) {\n    let a = 0, b = 1;\n    for (let i = 0; i < n; i++) {\n        [a, b] = [b, a + b];\n    }\n    return b;\n}', label: 'Iterate with two variables' }], correct: 0, explanation: 'The memo makes each distinct n computed once — O(n). The arrow is the SAME algorithm in fewer characters; syntax does not change complexity. The iterative version is genuinely O(n) with O(1) space — but it returns b, which is fib(n+1): run n=0 and it gives 1 where fib(0) is 0. Off by one exactly at the boundary. The memo version is the one that is both fast and correct as written.', hint: 'Two of these are fast. Run the loop version by hand for n = 0 before trusting it.' },
        { type: 'fillgap', prompt: 'Each step comes from 1 or 2 below — fill the recurrence', codeParts: [{ text: 'function climb(n) {\n    if (n <= 2) return n;\n    const dp = new Array(n+1).fill(0);\n    dp[1] = 1; dp[2] = 2;\n    for (let i = 3; i <= n; i++) {\n        ', type: 'fixed' }, { text: 'dp[i] = dp[i-1] + dp[i-2];', type: 'gap', id: 'g1' }, { text: '\n    }\n    return dp[n];\n}', type: 'fixed' }], bank: ['dp[i] = dp[i-1] + dp[i-2];', 'dp[i] = dp[i-1] * 2;', 'dp[i] = i;', 'dp[i] = dp[i-1];'], correctFill: { g1: 'dp[i] = dp[i-1] + dp[i-2];' }, explanation: 'You arrive at step i from i-1 (one step) or i-2 (a double) — and those two pools of routes are disjoint, so they ADD. Doubling overcounts: it pretends every route to i-1 splits in two, but a route ending in a double-step never passes through i-1 at all. dp[i]=i counts steps, not routes.', hint: 'From where can you reach step i in exactly one move? Combine the ways of getting to THOSE places.' },
        { type: 'errordecode', prompt: 'The memo is in place — why does fib(100000) still crash?', errorText: 'RangeError: Maximum call stack size exceeded\n    at fib (main.js:4)', question: 'Root cause?', options: ['100,000 stacked frames before any call returns', 'The memo object ran out of keys', 'The result exceeds Number.MAX_VALUE', 'Objects cannot hold that many entries'], correct: 0, explanation: 'Memoisation fixes the CALL COUNT, not the DEPTH: the first descent still goes fib(100000) → fib(99999) → … with every frame held open, and engines cap the stack around ten thousand frames. The fix is tabulation — a loop filling dp[0..n] bottom-up, zero recursion. (The result does exceed Number precision too, but that produces Infinity, not this error.)', hint: 'Before ANY call returns, how many are stacked? The memo only helps calls that come back.' },
        { type: 'realworld', prompt: 'Same recurrence, two implementations — what actually differs?', scenario: '🧠 One recurses with a cache; one loops over a table.', options: [{ code: '// memo: recursion + cache, computes on demand\n// table: iteration, computes everything up to n', label: 'Direction and stack usage' }, { code: '// the memo version is asymptotically faster', label: 'The memo is faster' }, { code: '// the table version gives different answers', label: 'They differ in results' }, { code: '// the memo uses less memory, always', label: 'Memo saves memory' }], correct: 0, explanation: 'Both are O(n) time and produce identical answers — the differences are operational. Top-down computes ONLY the subproblems actually reached (a win when the space is sparse) but carries recursion depth. Bottom-up pays for every cell up to n but never touches the stack, and often admits an O(1)-space squeeze — keep just the last two values. Neither dominates; the problem shape decides.', hint: 'Rule out the claims about speed and answers first — measure both in your head. What is left?' },
    ],
    32: [
        { type: 'trace', prompt: 'What does power(2, 10) return?', code: [{ text: 'function power(b, e) {' }, { text: '    if (e===0) return 1;' }, { text: '    if (e%2===0) { const h=power(b,e/2); return h*h; }' }, { text: '    return b*power(b,e-1);' }, { text: '}' }, { text: 'console.log(power(2, 10));', highlight: true }], options: ['20', '100', '512', '1024'], correct: 3, explanation: '2¹⁰ = 1024 — the algorithm changes the route, not the value. 20 is 2×10, 100 is 10², 512 is 2⁹, one halving misplaced. Knowing 2¹⁰ ≈ 10³ is independently useful: it is why 1 KB is 1024 bytes and why every 10 halvings knock three digits off n.', hint: 'The recursion computes 2 to the 10th, just cleverly. What IS 2¹⁰?' },
        { type: 'realworld', prompt: 'Fib benefits from DP; merge sort does not. What is the difference?', scenario: '🧠 Both recurse. Only one is worth caching.', options: [{ code: '// fib(n-1) and fib(n-2) RESHARE subcalls\n// merge sort halves never overlap', label: 'Overlapping subproblems' }, { code: '// fib is arithmetic, sorting is not', label: 'Arithmetic vs rearranging' }, { code: '// fib recurses twice, merge sort once', label: 'Number of recursive calls' }, { code: '// fib is defined on integers', label: 'Integer inputs' }], correct: 0, explanation: 'Caching pays only when the same subproblem RECURS: fib(5) and fib(4) both need fib(3). Merge sort\'s halves are disjoint — no subarray is sorted twice, so a cache would only ever miss. That plus optimal substructure is the two-part test for DP. Merge sort also recurses twice, which kills the third option.', hint: 'A cache helps only if something is asked twice. Which algorithm ever repeats a subproblem?' },
        { type: 'scramble', prompt: 'Assemble the coin-change DP', pieces: [{ id: 'a', text: 'function coinChange(coins, amount) {' }, { id: 'b', text: '    const dp = new Array(amount+1).fill(Infinity);' }, { id: 'c', text: '    dp[0] = 0;' }, { id: 'd', text: '    for (let i = 1; i <= amount; i++) {' }, { id: 'e', text: '        for (const c of coins) {' }, { id: 'f', text: '            if (i-c >= 0) dp[i] = Math.min(dp[i], dp[i-c]+1);' }, { id: 'g', text: '        }' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return dp[amount] === Infinity ? -1 : dp[amount];' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '    dp[0] = 1;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'Two sentinels carry the algorithm: Infinity means "not yet reachable" (and survives Math.min untouched), while dp[0] = 0 says making zero needs zero coins. The spare line seeds dp[0] = 1 — every answer comes out one too high, and nothing crashes to tell you. The final line converts the sentinel into the API\'s -1 for "impossible".', hint: 'What does dp[0] mean in words? How many coins does it take to make amount zero?' },
        { type: 'trace', prompt: 'Fewest coins to make 6 from [1, 3, 4]?', code: [{ text: 'const coins = [1, 3, 4];' }, { text: 'const dp = new Array(7).fill(Infinity);' }, { text: 'dp[0] = 0;' }, { text: 'for (let a = 1; a <= 6; a++)' }, { text: '    for (const c of coins)' }, { text: '        if (c <= a) dp[a] = Math.min(dp[a], dp[a - c] + 1);' }, { text: 'console.log(dp[6]);', highlight: true }], options: ['3', '2', '11', '6'], correct: 1, explanation: 'dp[6] = 2, via 3+3. Greedy would take the 4 first and be stuck with 4+1+1 = 3 coins. The inner loop tries every coin at every amount, which is what lets it find the 3+3 route that greedy never considers.', hint: 'Fill dp[1..6] by hand — each cell is 1 + the cheapest reachable smaller cell.' },
    ],
    // ═══ CH9: ADVANCED ═══
    33: [
        { type: 'pair', prompt: 'Match graph terms', pairs: [{ id: 1, left: 'Adjacency List', right: 'Object of arrays' }, { id: 2, left: 'Adjacency Matrix', right: '2D array' }, { id: 3, left: 'Directed', right: 'One-way edges' }, { id: 4, left: 'Undirected', right: 'Two-way edges' }] },
        { type: 'output', prompt: 'Adjacency list for A→B, A→C, B→C?', code: [{ text: 'const graph = {' }, { text: '    A: ["B", "C"],' }, { text: '    B: ["C"],' }, { text: '    C: []' }, { text: '};' }, { text: 'console.log(graph.A.length);' }], terminalOutput: '2', options: ['1', '2', '3', '0'], correct: 1 },
        { type: 'fillgap', prompt: 'Build adjacency list from edges', codeParts: [{ text: 'function buildGraph(edges) {\n    const graph = {};\n    for (const [u, v] of edges) {\n        if (!graph[u]) graph[u] = [];\n        if (!graph[v]) graph[v] = [];\n        ', type: 'fixed' }, { text: 'graph[u].push(v);', type: 'gap', id: 'g1' }, { text: '\n    }\n    return graph;\n}', type: 'fixed' }], bank: ['graph[u].push(v);', 'graph[v].push(u);', 'graph[u] = v;', 'graph.push([u,v]);'], correctFill: { g1: 'graph[u].push(v);' } },
        { type: 'realworld', prompt: 'Graph in real life?', scenario: '🌍 Real-world graph applications', options: [{ code: '// Social network: users=nodes, friends=edges\n// Maps: intersections=nodes, roads=edges', label: 'Social networks, maps' }, { code: '// Sorting numbers', label: 'No graph needed' }, { code: '// Reading files', label: 'Sequential, not graph' }, { code: '// Calculator', label: 'No relationships' }], correct: 0 },
    ],
    34: [
        { type: 'trace', prompt: 'BFS from A. Visit order?', code: [{ text: '// A→[B,C], B→[D], C→[D], D→[]' }, { text: 'function bfs(start, graph) {' }, { text: '    const q = [start]; const seen = new Set([start]);' }, { text: '    while (q.length) {' }, { text: '        const node = q.shift(); console.log(node);' }, { text: '        for (const n of graph[node]) {' }, { text: '            if (!seen.has(n)) { seen.add(n); q.push(n); }' }, { text: '        }' }, { text: '    }', highlight: true }, { text: '}' }], options: ['A B C D', 'A B D C', 'A C B D', 'D B C A'], correct: 0 },
        { type: 'pair', prompt: 'BFS vs DFS', pairs: [{ id: 1, left: 'BFS', right: 'Queue (FIFO)' }, { id: 2, left: 'DFS', right: 'Stack (LIFO)' }, { id: 3, left: 'BFS use', right: 'Shortest path' }, { id: 4, left: 'DFS use', right: 'Cycle detection' }] },
        { type: 'bug', prompt: 'BFS bug — why visit nodes twice?', code: [{ text: 'function bfs(graph, start) {', hasError: false }, { text: '    const q = [start];', hasError: false }, { text: '    while (q.length) {', hasError: false }, { text: '        const node = q.shift();', hasError: false }, { text: '        console.log(node);', hasError: false }, { text: '        for (const n of graph[node]) q.push(n);', hasError: true }], correctLine: 5 },
        { type: 'scramble', prompt: 'Build DFS with stack', pieces: [{ id: 'a', text: 'function dfs(graph, start) {' }, { id: 'b', text: '    const stack = [start];' }, { id: 'c', text: '    const visited = new Set();' }, { id: 'd', text: '    while (stack.length) {' }, { id: 'e', text: '        const node = stack.pop();' }, { id: 'f', text: '        if (visited.has(node)) continue;' }, { id: 'g', text: '        visited.add(node);' }, { id: 'h', text: '        for (const n of graph[node]) stack.push(n);' }, { id: 'i', text: '    }' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        const node = stack.shift();' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
    ],
    35: [
        { type: 'trace', prompt: 'Two-pointer: pair summing to 6 in [1,2,3,4,6]?', code: [{ text: 'let lo = 0, hi = 4; // 1+6=7>6' }, { text: 'hi--;              // 1+4=5<6' }, { text: 'lo++;              // 2+4=6 ✓', highlight: true }], options: ['indices [1,5]', 'indices [0,4]', 'indices [1,3]', 'indices [2,3]'], correct: 2 },
        { type: 'refactor', prompt: 'O(n²) duplicates → O(n)?', originalCode: 'for (let i = 0; i < arr.length; i++)\n    for (let j = i+1; j < arr.length; j++)\n        if (arr[i]===arr[j]) return true;', options: [{ code: 'return arr.length !== new Set(arr).size;', label: 'Set — O(n)' }, { code: 'arr.sort();\nfor (let i=0;i<arr.length-1;i++)\n    if (arr[i]===arr[i+1]) return true;', label: 'Sort — O(n log n)' }, { code: 'return [...new Set(arr)].length < arr.length;', label: 'Set spread — O(n)' }], correct: 0 },
        { type: 'fillgap', prompt: 'Sliding window: max sum of k consecutive', codeParts: [{ text: 'function maxSum(arr, k) {\n    let window = arr.slice(0,k).reduce((a,b)=>a+b,0);\n    let best = window;\n    for (let i = k; i < arr.length; i++) {\n        ', type: 'fixed' }, { text: 'window += arr[i] - arr[i-k];', type: 'gap', id: 'g1' }, { text: '\n        best = Math.max(best, window);\n    }\n    return best;\n}', type: 'fixed' }], bank: ['window += arr[i] - arr[i-k];', 'window = arr.slice(i-k,i).reduce((a,b)=>a+b);', 'window += arr[i];', 'window = arr[i];'], correctFill: { g1: 'window += arr[i] - arr[i-k];' } },
        { type: 'realworld', prompt: 'Sliding window best for?', scenario: '🔍 When to use sliding window pattern', options: [{ code: '// Contiguous subarray problems:\n// max sum, min length, longest substring', label: 'Contiguous subarray/substring' }, { code: '// Tree traversal', label: 'Trees — different' }, { code: '// Sorting', label: 'Sorting — different' }, { code: '// Hash table', label: 'Different pattern' }], correct: 0 },
    ],
    36: [
        { type: 'scramble', prompt: 'Build BFS shortest path', pieces: [{ id: 'a', text: 'function bfs(graph, start) {' }, { id: 'b', text: '    const q = [start];' }, { id: 'c', text: '    const visited = new Set([start]);' }, { id: 'd', text: '    while (q.length) {' }, { id: 'e', text: '        const node = q.shift();' }, { id: 'f', text: '        for (const nb of graph[node]) {' }, { id: 'g', text: '            if (!visited.has(nb)) {' }, { id: 'h', text: '                visited.add(nb); q.push(nb);' }, { id: 'i', text: '            }' }, { id: 'j', text: '        }' }, { id: 'k', text: '    }' }, { id: 'l', text: '}' }], distractors: [{ id: 'm', text: '        q.push(node);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'] },
        { type: 'trace', prompt: 'DFS from A?', code: [{ text: '// A→[B,C], B→[D], C→[], D→[]' }, { text: 'function dfs(node, graph, seen=new Set()) {' }, { text: '    if (seen.has(node)) return;' }, { text: '    seen.add(node); console.log(node);' }, { text: '    for (const n of graph[node]) dfs(n,graph,seen);', highlight: true }, { text: '}' }], options: ['A B D C', 'A B C D', 'A C B D', 'D B C A'], correct: 0 },
        { type: 'errordecode', prompt: 'Graph cycle detection issue', errorText: 'InternalError: too much recursion\n    at dfs (graph.js:3)', question: 'Cause?', options: ['No visited check — cycles cause infinite recursion', 'Graph too large', 'Wrong data type', 'Missing return'], correct: 0 },
        { type: 'pair', prompt: 'Graph algorithm applications', pairs: [{ id: 1, left: 'BFS', right: 'Shortest path unweighted' }, { id: 2, left: 'DFS', right: 'Topological sort' }, { id: 3, left: 'Dijkstra', right: 'Shortest weighted path' }, { id: 4, left: 'Union-Find', right: 'Connected components' }] },
    ],
    // ═══ CH10: MASTERY ═══
    37: [
        { type: 'trace', prompt: 'Climbing stairs n=4?', code: [{ text: '// dp[0]=1, dp[1]=1' }, { text: '// dp[2] = dp[1]+dp[0] = 2' }, { text: '// dp[3] = dp[2]+dp[1] = 3' }, { text: '// dp[4] = dp[3]+dp[2] = ?', highlight: true }], options: ['4', '5', '6', '8'], correct: 1 },
        { type: 'pair', prompt: 'Match DP patterns', pairs: [{ id: 1, left: 'Fibonacci', right: 'dp[i]=dp[i-1]+dp[i-2]' }, { id: 2, left: 'Knapsack', right: 'Include or exclude item' }, { id: 3, left: 'LCS', right: 'Match or skip chars' }, { id: 4, left: 'Coin Change', right: 'min(dp[amt-coin]+1)' }] },
        { type: 'fillgap', prompt: 'Longest Common Subsequence', codeParts: [{ text: 'function lcs(a, b) {\n    const dp = Array(a.length+1).fill(null).map(()=>Array(b.length+1).fill(0));\n    for (let i=1; i<=a.length; i++)\n        for (let j=1; j<=b.length; j++)\n            dp[i][j] = a[i-1]===b[j-1]\n                ? ', type: 'fixed' }, { text: 'dp[i-1][j-1] + 1', type: 'gap', id: 'g1' }, { text: '\n                : Math.max(dp[i-1][j], dp[i][j-1]);\n    return dp[a.length][b.length];\n}', type: 'fixed' }], bank: ['dp[i-1][j-1] + 1', 'dp[i][j] + 1', 'dp[i-1][j-1]', 'i + j'], correctFill: { g1: 'dp[i-1][j-1] + 1' } },
        { type: 'bug', prompt: '0-1 Knapsack bug?', code: [{ text: 'for (let i = 1; i <= n; i++)', hasError: false }, { text: '    for (let w = 0; w <= W; w++)', hasError: true }, { text: '        if (weights[i-1] <= w)', hasError: false }, { text: '            dp[i][w] = Math.max(dp[i-1][w], values[i-1]+dp[i-1][w-weights[i-1]]);', hasError: false }], correctLine: 1 },
    ],
    38: [
        { type: 'pair', prompt: 'Match pattern to problem', pairs: [{ id: 1, left: 'Sliding window', right: 'Max subarray of size k' }, { id: 2, left: 'Two pointer', right: 'Pair sum sorted' }, { id: 3, left: 'BFS', right: 'Shortest path unweighted' }, { id: 4, left: 'DP', right: 'Min coins for amount' }] },
        { type: 'realworld', prompt: 'Problem-solving strategy?', scenario: '🎯 You get a hard problem in an interview.', options: [{ code: '// 1. Brute force first\n// 2. Identify pattern\n// 3. Optimize with right DS\n// 4. Code + test edge cases', label: 'Structured approach' }, { code: '// Jump to optimal solution', label: 'Risky' }, { code: '// Give up', label: 'Never!' }, { code: '// Memorize solutions', label: 'Not scalable' }], correct: 0 },
        { type: 'refactor', prompt: 'Max subarray — which algo?', originalCode: '// Brute: O(n²)\nfor (let i=0;i<n;i++) {\n    let curr = 0;\n    for (let j=i;j<n;j++) {\n        curr += arr[j];\n        best = Math.max(best, curr);\n    }\n}', options: [{ code: "// Kadane's: O(n)\nlet curr = arr[0], best = arr[0];\nfor (let i=1; i<arr.length; i++) {\n    curr = Math.max(arr[i], curr+arr[i]);\n    best = Math.max(best, curr);\n}", label: "Kadane's — O(n)" }, { code: '// Sort + take last k', label: 'Sorting' }, { code: '// Recursion no memo', label: 'O(2ⁿ)' }], correct: 0 },
        { type: 'trace', prompt: 'Kadane on [-2,1,-3,4,-1,2,1,-5,4]?', code: [{ text: '// curr: -2,1,-2,4,3,5,6,1,5' }, { text: '// best: -2,1,1,4,4,5,6,6,6', highlight: true }], options: ['6', '5', '4', '7'], correct: 0 },
    ],
    39: [
        { type: 'fillgap', prompt: 'Reverse string in-place', codeParts: [{ text: 'function reverse(arr) {\n    let lo = 0, hi = arr.length - 1;\n    while (lo < hi) {\n        ', type: 'fixed' }, { text: '[arr[lo], arr[hi]] = [arr[hi], arr[lo]];', type: 'gap', id: 'g1' }, { text: '\n        lo++; hi--;\n    }\n}', type: 'fixed' }], bank: ['[arr[lo], arr[hi]] = [arr[hi], arr[lo]];', 'arr.reverse();', 'lo, hi = hi, lo;', 'arr[lo] = arr[hi];'], correctFill: { g1: '[arr[lo], arr[hi]] = [arr[hi], arr[lo]];' } },
        { type: 'trace', prompt: 'Valid palindrome check?', code: [{ text: 'function isPalindrome(s) {' }, { text: '    s = s.toLowerCase().replace(/[^a-z0-9]/g, "");' }, { text: '    return s === [...s].reverse().join("");' }, { text: '}' }, { text: 'console.log(isPalindrome("A man, a plan, a canal: Panama"));', highlight: true }], options: ['true', 'false', 'Error', 'undefined'], correct: 0 },
        { type: 'scramble', prompt: 'Build valid anagram checker', pieces: [{ id: 'a', text: 'function isAnagram(s, t) {' }, { id: 'b', text: '    if (s.length !== t.length) return false;' }, { id: 'c', text: '    return [...s].sort().join("") === [...t].sort().join("");' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    return s === t;' }], correctOrder: ['a', 'b', 'c', 'd'] },
        { type: 'bug', prompt: 'Why is this O(n²) not O(n)?', code: [{ text: 'function removeDuplicates(arr) {', hasError: false }, { text: '    return arr.filter((item, index) =>', hasError: false }, { text: '        arr.indexOf(item) === index', hasError: true }, { text: '    );', hasError: false }], correctLine: 2 },
    ],
    40: [
        { type: 'trace', prompt: 'Matrix search (sorted rows+cols)?', code: [{ text: 'function search(m, t) {' }, { text: '    let r = 0, c = m[0].length - 1;' }, { text: '    while (r < m.length && c >= 0) {' }, { text: '        if (m[r][c] === t) return true;' }, { text: '        else if (m[r][c] > t) c--;' }, { text: '        else r++;' }, { text: '    }' }, { text: '    return false;' }, { text: '}' }, { text: 'console.log(search([[1,4,7],[2,5,8],[3,6,9]], 5));', highlight: true }], options: ['true', 'false', 'Error', '[1,1]'], correct: 0 },
        { type: 'refactor', prompt: 'Max subarray — Kadane vs brute?', originalCode: '// Brute: O(n²)', options: [{ code: "// Kadane's: O(n)\nlet curr = arr[0], best = arr[0];\nfor (let i=1; i<arr.length; i++) {\n    curr = Math.max(arr[i], curr+arr[i]);\n    best = Math.max(best, curr);\n}", label: "Kadane's — O(n)" }, { code: '// Sort + take last k', label: 'Sorting' }, { code: '// Recursion no memo', label: 'O(2ⁿ)' }], correct: 0 },
        { type: 'scramble', prompt: 'Build binary search iterative', pieces: [{ id: 'a', text: 'function search(nums, target) {' }, { id: 'b', text: '    let lo = 0, hi = nums.length - 1;' }, { id: 'c', text: '    while (lo <= hi) {' }, { id: 'd', text: '        const mid = lo + ((hi - lo) >> 1);' }, { id: 'e', text: '        if (nums[mid] === target) return mid;' }, { id: 'f', text: '        else if (nums[mid] < target) lo = mid + 1;' }, { id: 'g', text: '        else hi = mid - 1;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return -1;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        lo = mid;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'errordecode', prompt: 'Why does this give wrong answer?', errorText: 'Expected: [0,1] for twoSum([3,2,4], 6)\nGot: undefined', question: 'Fix?', options: ['HashMap approach needed — [3,2,4] has no sorted guarantee', 'Sort first', 'Use binary search', 'Use brute force'], correct: 0 },
    ],
    41: [
        { type: 'pair', prompt: 'Advanced concepts', pairs: [{ id: 1, left: 'Amortized O(1)', right: 'Avg cost over many ops' }, { id: 2, left: 'NP-Complete', right: 'No known fast solution' }, { id: 3, left: 'Space-Time Tradeoff', right: 'Memory saves time' }, { id: 4, left: 'Greedy', right: 'Local optimal choices' }] },
        { type: 'trace', prompt: 'Greedy: activity selection?', code: [{ text: '// Activities: (start, end)' }, { text: '// [(1,4),(3,5),(0,6),(5,7),(8,9),(5,9)]' }, { text: '// Sort by end time, pick non-overlapping' }, { text: '// Pick: (1,4),(5,7),(8,9)', highlight: true }], options: ['3 activities', '2 activities', '4 activities', '6 activities'], correct: 0 },
        { type: 'realworld', prompt: 'When does greedy FAIL?', scenario: '⚠️ Greedy doesnt always give optimal.', options: [{ code: '// Coin change: coins=[1,3,4], amount=6\n// Greedy: 4+1+1=3 coins\n// Optimal: 3+3=2 coins!', label: 'Coin change with special coins' }, { code: '// Activity selection', label: 'Greedy works here' }, { code: '// Making change with [1,5,10,25]', label: 'Standard coins work' }, { code: '// Huffman coding', label: 'Greedy optimal' }], correct: 0 },
        { type: 'fillgap', prompt: 'Greedy: fractional knapsack', codeParts: [{ text: '// Sort by value/weight ratio descending\n// Take items greedily\nfunction fractKnapsack(items, W) {\n    items.sort((a,b) => ', type: 'fixed' }, { text: 'b.val/b.wt - a.val/a.wt', type: 'gap', id: 'g1' }, { text: ');\n    // ... take as much as fits\n}', type: 'fixed' }], bank: ['b.val/b.wt - a.val/a.wt', 'a.val - b.val', 'a.wt - b.wt', 'b.wt/b.val - a.wt/a.val'], correctFill: { g1: 'b.val/b.wt - a.val/a.wt' } },
    ],
    42: [
        { type: 'realworld', prompt: 'Journey complete! Next step?', scenario: '🎓 You mastered: variables→loops→functions→DS→algorithms→DP→graphs!', options: [{ code: '// Build real projects!\n// Apply to apps, APIs, open source', label: 'Build projects! 🚀' }, { code: '// Review everything', label: 'Review' }, { code: '// Just read more', label: 'More books' }, { code: '// Stop forever', label: 'Never stop!' }], correct: 0 },
        { type: 'pair', prompt: 'Your journey recap', pairs: [{ id: 1, left: 'CH1-2', right: 'Variables & Flow' }, { id: 2, left: 'CH3-4', right: 'Loops & Functions' }, { id: 3, left: 'CH5-7', right: 'Data Structures' }, { id: 4, left: 'CH8-10', right: 'Algorithms & DP' }] },
        { type: 'trace', prompt: 'Final puzzle: what does this return?', code: [{ text: 'function mystery(n) {' }, { text: '    if (n === 0) return 1;' }, { text: '    return n * mystery(n - 1);' }, { text: '}' }, { text: 'console.log(mystery(5));', highlight: true }], options: ['5', '15', '120', '720'], correct: 2 },
        { type: 'scramble', prompt: 'Final: build memoized fibonacci', pieces: [{ id: 'a', text: 'function fib(n, memo = {}) {' }, { id: 'b', text: '    if (n in memo) return memo[n];' }, { id: 'c', text: '    if (n <= 1) return n;' }, { id: 'd', text: '    memo[n] = fib(n-1, memo) + fib(n-2, memo);' }, { id: 'e', text: '    return memo[n];' }, { id: 'f', text: '}' }], distractors: [{ id: 'g', text: '    return fib(n-1) + fib(n-2);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
    ],
}
