/* ══════════════════════════════════════════════════
   JAVASCRIPT EXERCISES — Journey Nodes
   ══════════════════════════════════════════════════ */
export const jsExercises = {
    // ═══ CH1: BASICS ═══
    1: [
        { type: 'trace', prompt: 'What is the value of `count`?', code: [{ text: 'let count = 0;' }, { text: 'for (let i = 0; i < 5; i++) {' }, { text: '    if (i % 2 === 0) {' }, { text: '        count++;' }, { text: '    }' }, { text: '}' }, { text: 'console.log(count);', highlight: true }], options: ['2', '3', '5', '4'], correct: 1 },
        { type: 'realworld', prompt: 'Which code counts total items in a cart?', scenario: '🛒 Cart: 3 apples, 2 oranges, 1 banana.', options: [{ code: 'const cart = [3, 2, 1];\nconst total = cart.reduce((a,b) => a+b, 0);', label: 'reduce()' }, { code: 'const cart = 3 + 2 + 1;\nconst total = cart.length;', label: '.length on number' }, { code: 'const cart = "3 2 1";\nconst total = cart.length;', label: 'String length' }, { code: 'const cart = new Set([3,2,1]);\nconst total = Math.max(...cart);', label: 'Max of set' }], correct: 0 },
        { type: 'pair', prompt: 'Match JavaScript concepts', pairs: [{ id: 1, left: 'let', right: 'Block-scoped variable' }, { id: 2, left: 'const', right: 'Immutable binding' }, { id: 3, left: 'typeof', right: 'Check data type' }, { id: 4, left: '===', right: 'Strict equality' }] },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'let x = 7;' }, { text: 'let y = 2;' }, { text: 'console.log(Math.floor(x/y), x%y);' }], terminalOutput: '3 1', options: ['3.5 1', '3 1', '3.5 0', '3 0'], correct: 1 },
        { type: 'fillgap', prompt: 'Complete: swap two variables with destructuring', codeParts: [{ text: 'let a = 5;\nlet b = 10;\n', type: 'fixed' }, { text: '[a, b] = [b, a];', type: 'gap', id: 'g1' }], bank: ['[a, b] = [b, a];', 'a = b; b = a;', 'swap(a, b);', 'a === b;'], correctFill: { g1: '[a, b] = [b, a];' } },
        { type: 'scramble', prompt: 'Build code to calculate BMI', pieces: [{ id: 'a', text: 'const weight = 70;' }, { id: 'b', text: 'const height = 1.75;' }, { id: 'c', text: 'const bmi = weight / (height ** 2);' }, { id: 'd', text: 'console.log(bmi.toFixed(1));' }], distractors: [{ id: 'e', text: 'const bmi = weight * height;' }], correctOrder: ['a', 'b', 'c', 'd'] },
    ],
    2: [
        { type: 'bug', prompt: 'Find the syntax error', code: [{ text: 'function greet(name) {', hasError: false }, { text: '    let msg = "Hello " + name;', hasError: false }, { text: '    console.log(msg', hasError: true }, { text: '    return msg;', hasError: false }], correctLine: 2 },
        { type: 'errordecode', prompt: 'Decode this error', errorText: 'Uncaught SyntaxError: Unexpected token }\n    at greet (main.js:4)\n    at main.js:6', question: 'What caused this?', options: ['Missing closing parenthesis', 'Undefined variable', 'Wrong indentation', 'Invalid string'], correct: 0 },
        { type: 'refactor', prompt: 'Which is the cleanest?', originalCode: 'let x = 10;\nlet r;\nif (x > 5) {\n    r = "big";\n} else {\n    r = "small";\n}\nconsole.log(r);', options: [{ code: 'const x = 10;\nconst r = x > 5 ? "big" : "small";\nconsole.log(r);', label: 'Ternary expression' }, { code: 'let x = 10;\nlet r = "";\nif (x > 5) r = "big";\nif (x <= 5) r = "small";', label: 'Two ifs' }, { code: 'x > 5 ? console.log("big") : console.log("small");', label: 'Console in ternary' }], correct: 0 },
        { type: 'bug', prompt: 'Why does this give wrong result?', code: [{ text: 'const age = prompt("Age: ");', hasError: false }, { text: 'if (age > 18) {', hasError: true }, { text: '    console.log("Adult");', hasError: false }], correctLine: 1 },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'let x = "5";' }, { text: 'let y = 3;' }, { text: 'console.log(x.repeat(y));' }], terminalOutput: '555', options: ['15', '555', '53', 'Error'], correct: 1 },
        { type: 'trace', prompt: 'What is typeof result?', code: [{ text: 'let a = 10;' }, { text: 'let b = 3;' }, { text: 'let result = a / b;' }, { text: 'console.log(typeof result);', highlight: true }], options: ['"integer"', '"number"', '"string"', '3.33'], correct: 1 },
    ],
    3: [
        { type: 'video', title: 'Variables & Data Types', description: 'let, const, var — JavaScript is dynamically typed. number, string, boolean, null, undefined, object are the core types.', duration: '2:45', thumbnail: '🎬' },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'const name = "Rheo";' }, { text: 'const age = 3;' }, { text: 'console.log(typeof age);' }], terminalOutput: 'number', options: ['"string"', '"number"', '3', '"integer"'], correct: 1 },
        { type: 'pair', prompt: 'Match JavaScript types', pairs: [{ id: 1, left: 'number', right: '42 or 3.14' }, { id: 2, left: 'string', right: '"hello"' }, { id: 3, left: 'boolean', right: 'true' }, { id: 4, left: 'undefined', right: 'Not assigned' }] },
    ],
    4: [
        { type: 'pair', prompt: 'Match operators', pairs: [{ id: 1, left: '===', right: 'Strict equals' }, { id: 2, left: '!==', right: 'Strict not equals' }, { id: 3, left: '**', right: 'Power' }, { id: 4, left: '??', right: 'Nullish coalescing' }] },
        { type: 'trace', prompt: 'What is the output?', code: [{ text: 'let x = 17;' }, { text: 'console.log(x % 5, Math.floor(x / 5));', highlight: true }], options: ['2 3', '3 2', '2 4', '17 5'], correct: 0 },
        { type: 'fillgap', prompt: 'Complete: convert Celsius to Fahrenheit', codeParts: [{ text: 'const celsius = 25;\n', type: 'fixed' }, { text: 'const fahrenheit = celsius * 9/5 + 32;', type: 'gap', id: 'g1' }, { text: '\nconsole.log(fahrenheit);', type: 'fixed' }], bank: ['celsius * 9/5 + 32;', 'celsius + 32;', 'celsius * 1.8;', 'celsius / 5 * 9;'], correctFill: { g1: 'celsius * 9/5 + 32;' } },
    ],
    // ═══ CH2: FLOW CONTROL ═══
    5: [
        { type: 'trace', prompt: 'What does this nested condition print?', code: [{ text: 'let x = 15;' }, { text: 'if (x > 20) {' }, { text: '    console.log("A");' }, { text: '} else if (x > 10) {' }, { text: '    if (x % 2 === 0) {' }, { text: '        console.log("B");' }, { text: '    } else {' }, { text: '        console.log("C");', highlight: true }, { text: '    }' }, { text: '}' }], options: ['A', 'B', 'C', 'undefined'], correct: 2 },
        { type: 'bug', prompt: 'Voting check bug — 18 year olds should vote!', code: [{ text: 'const age = 18;', hasError: false }, { text: 'if (age > 18) {', hasError: true }, { text: '    console.log("Can vote");', hasError: false }], correctLine: 1 },
        { type: 'output', prompt: 'Short-circuit: what prints?', code: [{ text: 'let a = 0;' }, { text: 'let b = 5;' }, { text: 'let result = a && b/a;' }, { text: 'console.log(result);' }], terminalOutput: '0', options: ['0', 'Error: Division by zero', '5', 'false'], correct: 0 },
        { type: 'realworld', prompt: 'Which handles login correctly?', scenario: '🔐 3 password attempts, then lock.', options: [{ code: 'let attempts = 0;\nwhile (attempts < 3) {\n    const pwd = prompt();\n    if (pwd === secret) break;\n    attempts++;\n}', label: 'Counter + break' }, { code: 'for (let i = 0; i < 3; i++) {\n    const pwd = prompt();\n    if (pwd !== secret) continue;\n}', label: 'Continue loop' }, { code: 'const pwd = prompt();\nif (pwd === secret) console.log("OK");', label: 'Single attempt' }, { code: 'while (true) {\n    const pwd = prompt();\n    break;\n}', label: 'Infinite + break' }], correct: 0 },
        { type: 'scramble', prompt: 'Build a grade calculator', pieces: [{ id: 'a', text: 'const score = 75;' }, { id: 'b', text: 'let grade;' }, { id: 'c', text: 'if (score >= 90) grade = "A";' }, { id: 'd', text: 'else if (score >= 80) grade = "B";' }, { id: 'e', text: 'else if (score >= 70) grade = "C";' }, { id: 'f', text: 'else grade = "F";' }, { id: 'g', text: 'console.log(grade);' }], distractors: [{ id: 'h', text: 'if (score == 90) grade = "A";' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'trace', prompt: 'Ternary chain result?', code: [{ text: 'const n = 0;' }, { text: 'const label = n > 0 ? "positive" : n < 0 ? "negative" : "zero";' }, { text: 'console.log(label);', highlight: true }], options: ['positive', 'negative', 'zero', 'Error'], correct: 2 },
    ],
    6: [
        { type: 'trace', prompt: 'Truthiness check — what prints?', code: [{ text: 'let x = [1, 2, 3];' }, { text: 'let y = [];' }, { text: 'console.log(!!x, !!y);', highlight: true }], options: ['true true', 'true false', 'false true', 'true true'], correct: 3 },
        { type: 'refactor', prompt: 'JS emptiness check?', originalCode: 'if (myArr.length > 0) {\n    doSomething();\n}', options: [{ code: 'if (myArr.length) {\n    doSomething();\n}', label: 'Truthy length' }, { code: 'if (myArr !== []) {\n    doSomething();\n}', label: 'Compare (wrong!)' }, { code: 'if (myArr != null) {\n    doSomething();\n}', label: 'Null check only' }], correct: 0 },
        { type: 'fillgap', prompt: 'Check if number is in range 1-100', codeParts: [{ text: 'function inRange(n) {\n    return ', type: 'fixed' }, { text: 'n >= 1 && n <= 100;', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['n >= 1 && n <= 100;', '1 <= n <= 100;', 'n in range(100);', 'n > 0 && n < 101;'], correctFill: { g1: 'n >= 1 && n <= 100;' } },
        { type: 'output', prompt: 'Falsy values in JS?', code: [{ text: 'const vals = [0, "", [], null, 1, "hi", [0]];' }, { text: 'const truthy = vals.filter(v => !!v);' }, { text: 'console.log(truthy.length);' }], terminalOutput: '4', options: ['2', '3', '4', '7'], correct: 2 },
        { type: 'pair', prompt: 'Match falsy values', pairs: [{ id: 1, left: '0', right: 'Falsy number' }, { id: 2, left: '""', right: 'Falsy string' }, { id: 3, left: 'null', right: 'Falsy null' }, { id: 4, left: 'undefined', right: 'Falsy undefined' }] },
    ],
    7: [
        { type: 'terminal', prompt: 'Create a variable and print it', expectedCommands: ['let name = "Otter";', 'console.log(name);'], hint: 'Use let to declare, console.log to print', terminalHistory: [{ type: 'system', text: '> Daily Challenge' }] },
        { type: 'trace', prompt: 'What is `result`?', code: [{ text: 'let result = "";' }, { text: 'for (const c of "hello") {' }, { text: '    result += c.toUpperCase();' }, { text: '}' }, { text: 'console.log(result);', highlight: true }], options: ['hello', 'HELLO', 'Hello', 'hELLO'], correct: 1 },
        { type: 'output', prompt: 'Template literal?', code: [{ text: 'const name = "Otter";' }, { text: 'const age = 5;' }, { text: 'console.log(`${name} is ${age*7} in human years`);' }], terminalOutput: 'Otter is 35 in human years', options: ['Otter is 35 in human years', 'Otter is 5 in human years', '${name} is ${age*7}', 'Error'], correct: 0 },
    ],
    8: [
        { type: 'video', title: 'Conditional Logic Deep Dive', description: 'if/else if/else chains, ternary, truthiness, short-circuit evaluation, switch statements.', duration: '3:00', thumbnail: '🎥' },
        { type: 'trace', prompt: 'Switch: what prints?', code: [{ text: 'const status = 404;' }, { text: 'let msg;' }, { text: 'switch (status) {' }, { text: '    case 200: msg = "OK"; break;' }, { text: '    case 404: msg = "Not Found"; break;' }, { text: '    default: msg = "Unknown";' }, { text: '}' }, { text: 'console.log(msg);', highlight: true }], options: ['OK', 'Not Found', 'Unknown', 'Error'], correct: 1 },
    ],
    // ═══ CH3: LOOPS ═══
    9: [
        { type: 'scramble', prompt: 'Print numbers 1-5', pieces: [{ id: 'a', text: 'for (let i = 1; i <= 5; i++) {' }, { id: 'b', text: '    console.log(i);' }, { id: 'c', text: '}' }], distractors: [{ id: 'd', text: '    console.log(i + 1);' }, { id: 'e', text: 'while (i < 5) {' }], correctOrder: ['a', 'b', 'c'] },
        { type: 'bug', prompt: 'Off-by-one: should print 1-10', code: [{ text: 'for (let i = 1; i < 10; i++) {', hasError: true }, { text: '    console.log(i);', hasError: false }, { text: '}', hasError: false }], correctLine: 0 },
        { type: 'trace', prompt: 'How many iterations?', code: [{ text: 'let n = 64;' }, { text: 'let count = 0;' }, { text: 'while (n > 1) {' }, { text: '    n = Math.floor(n / 2);' }, { text: '    count++;' }, { text: '}' }, { text: 'console.log(count);', highlight: true }], options: ['5', '6', '7', '32'], correct: 1 },
        { type: 'fillgap', prompt: 'Complete the sum loop', codeParts: [{ text: 'let total = 0;\nfor (const num of ', type: 'fixed' }, { text: '[1,2,3,4]', type: 'gap', id: 'g1' }, { text: ') {\n    total += num;\n}', type: 'fixed' }], bank: ['[1,2,3,4]', 'Array(4)', '{1:4}', '"1234"'], correctFill: { g1: '[1,2,3,4]' } },
        { type: 'realworld', prompt: 'Which finds the max in an array?', scenario: '📊 Find biggest number in [3, 7, 2, 9, 4]', options: [{ code: 'const nums = [3,7,2,9,4];\nlet best = nums[0];\nfor (const n of nums) {\n    if (n > best) best = n;\n}', label: 'Manual scan' }, { code: 'const best = Math.max(...nums);', label: 'Spread + Math.max' }, { code: 'const best = nums.sort()[0];', label: 'Sort first' }, { code: 'const best = nums.reduce((a,b)=>a+b);', label: 'Sum' }], correct: 0 },
        { type: 'output', prompt: 'What prints?', code: [{ text: 'for (let i = 0; i < 5; i++) {' }, { text: '    if (i === 3) break;' }, { text: '    process.stdout.write(i + " ");' }, { text: '}' }], terminalOutput: '0 1 2 ', options: ['0 1 2 ', '0 1 2 3', '0 1 2 3 4', '3'], correct: 0 },
    ],
    10: [
        { type: 'trace', prompt: 'How many times does console.log run?', code: [{ text: 'for (let i = 0; i < 3; i++) {' }, { text: '    for (let j = 0; j < 4; j++) {' }, { text: '        console.log(i, j);', highlight: true }, { text: '    }' }, { text: '}' }], options: ['7', '12', '9', '16'], correct: 1 },
        { type: 'output', prompt: 'What pattern prints?', code: [{ text: 'for (let i = 1; i <= 3; i++) {' }, { text: '    console.log("*".repeat(i));' }, { text: '}' }], terminalOutput: '*\n**\n***', options: ['***\n**\n*', '*\n**\n***', '***', '* * *'], correct: 1 },
        { type: 'realworld', prompt: 'Flatten a 2D array?', scenario: '📊 [[1,2],[3,4],[5,6]] → [1,2,3,4,5,6]', options: [{ code: 'const flat = arr.flat();', label: '.flat()' }, { code: 'const flat = arr.reduce((a,b) => a+b);', label: 'reduce (wrong)' }, { code: 'const flat = Array.from(arr);', label: 'Array.from' }, { code: 'const flat = [...arr];', label: 'Spread shallow' }], correct: 0 },
        { type: 'scramble', prompt: 'Build a multiplication table row', pieces: [{ id: 'a', text: 'const n = 5;' }, { id: 'b', text: 'for (let i = 1; i <= 10; i++) {' }, { id: 'c', text: '    console.log(`${n} x ${i} = ${n*i}`);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    console.log(n + i);' }], correctOrder: ['a', 'b', 'c', 'd'] },
        { type: 'trace', prompt: 'What does entries() give?', code: [{ text: 'const fruits = ["apple", "banana", "cherry"];' }, { text: 'for (const [i, f] of fruits.entries()) {' }, { text: '    console.log(i, f);', highlight: true }, { text: '}' }], options: ['0 apple\n1 banana\n2 cherry', 'apple 0\nbanana 1', '1 apple\n2 banana\n3 cherry', 'Error'], correct: 0 },
    ],
    11: [
        { type: 'scramble', prompt: 'Build a prime checker', pieces: [{ id: 'a', text: 'function isPrime(n) {' }, { id: 'b', text: '    if (n < 2) return false;' }, { id: 'c', text: '    for (let i = 2; i <= Math.sqrt(n); i++) {' }, { id: 'd', text: '        if (n % i === 0) return false;' }, { id: 'e', text: '    }' }, { id: 'f', text: '    return true;' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '    for (let i = 0; i < n; i++) {' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'trace', prompt: 'Array filter — what\'s the result?', code: [{ text: 'const nums = [1, 2, 3, 4, 5, 6];' }, { text: 'const evens = nums.filter(n => n % 2 === 0);' }, { text: 'console.log(evens);', highlight: true }], options: ['[2, 4, 6]', '[1, 3, 5]', '[1, 2, 3, 4, 5, 6]', '3'], correct: 0 },
        { type: 'fillgap', prompt: 'Complete: map to square numbers', codeParts: [{ text: 'const squares = ', type: 'fixed' }, { text: '[1,2,3,4,5].map(x => x**2);', type: 'gap', id: 'g1' }], bank: ['[1,2,3,4,5].map(x => x**2);', 'Array(5).map(x*x);', '[...range(5)]**2;', 'Math.pow([1,2,3,4,5]);'], correctFill: { g1: '[1,2,3,4,5].map(x => x**2);' } },
        { type: 'realworld', prompt: 'Which filters students who passed?', scenario: '📝 scores = [45, 78, 92, 33, 88]. Passing = 60+', options: [{ code: 'const passed = scores.filter(s => s >= 60);', label: '.filter() callback' }, { code: 'const passed = scores.find(60);', label: '.find()' }, { code: 'const passed = scores > 60;', label: 'Direct compare' }, { code: 'const passed = Math.max(...scores);', label: 'Max only' }], correct: 0 },
    ],
    12: [
        { type: 'pair', prompt: 'Match loop tools', pairs: [{ id: 1, left: 'break', right: 'Exit loop' }, { id: 2, left: 'continue', right: 'Skip iteration' }, { id: 3, left: '.entries()', right: 'Index + value' }, { id: 4, left: '.forEach()', right: 'Callback each item' }] },
        { type: 'trace', prompt: 'What does destructuring produce?', code: [{ text: 'const names = ["Ali", "Ece"];' }, { text: 'const ages = [20, 22];' }, { text: 'names.forEach((n, i) => {' }, { text: '    console.log(`${n}:${ages[i]}`);', highlight: true }, { text: '});' }], options: ['Ali:20\nEce:22', 'Ali Ece\n20 22', '[Ali,20]', 'Error'], correct: 0 },
        { type: 'output', prompt: 'What prints with continue?', code: [{ text: 'for (let i = 0; i < 5; i++) {' }, { text: '    if (i === 2) continue;' }, { text: '    process.stdout.write(i + " ");' }, { text: '}' }], terminalOutput: '0 1 3 4 ', options: ['0 1 3 4 ', '0 1 2 3 4', '2', '0 1'], correct: 0 },
    ],
    // ═══ CH4: FUNCTIONS ═══
    13: [
        { type: 'trace', prompt: 'Default params — what returns?', code: [{ text: 'function add(a, b = 10) {' }, { text: '    return a + b;' }, { text: '}' }, { text: 'console.log(add(3));', highlight: true }], options: ['3', '10', '13', 'NaN'], correct: 2 },
        { type: 'bug', prompt: 'Should return sum, not log it', code: [{ text: 'function add(a, b) {', hasError: false }, { text: '    const result = a + b;', hasError: false }, { text: '    console.log(result);', hasError: true }], correctLine: 2 },
        { type: 'refactor', prompt: 'Pick the cleanest', originalCode: 'function calc(a, b, op) {\n    if (op === "add") return a+b;\n    if (op === "sub") return a-b;\n    if (op === "mul") return a*b;\n}', options: [{ code: 'const ops = {\n    add: (a,b) => a+b,\n    sub: (a,b) => a-b,\n    mul: (a,b) => a*b\n};\nconst calc = (a,b,op) => ops[op](a,b);', label: 'Object dispatch' }, { code: 'const calc = (a,b,op) => eval(`${a}${op}${b}`);', label: 'eval()' }, { code: 'function calc(a,b,op) {\n    switch(op) { case "+": return a+b; }\n}', label: 'Switch' }], correct: 0 },
        { type: 'output', prompt: 'Rest params — what prints?', code: [{ text: 'function total(...nums) {' }, { text: '    return nums.reduce((a,b) => a+b, 0);' }, { text: '}' }, { text: 'console.log(total(1, 2, 3, 4));' }], terminalOutput: '10', options: ['[1,2,3,4]', '10', '4', 'Error'], correct: 1 },
        { type: 'scramble', prompt: 'Build a function with default + destructuring', pieces: [{ id: 'a', text: 'function greet(name, greeting = "Hello") {' }, { id: 'b', text: '    return `${greeting}, ${name}!`;' }, { id: 'c', text: '}' }, { id: 'd', text: 'console.log(greet("Furkan"));' }, { id: 'e', text: 'console.log(greet("Arda", "Hey"));' }], distractors: [{ id: 'f', text: '    return name + greeting;' }], correctOrder: ['a', 'b', 'c', 'd', 'e'] },
        { type: 'trace', prompt: 'Arrow + map — what returns?', code: [{ text: 'const double = x => x * 2;' }, { text: 'const nums = [1, 2, 3];' }, { text: 'const result = nums.map(double);' }, { text: 'console.log(result);', highlight: true }], options: ['[2, 4, 6]', '[1, 2, 3]', '6', 'Error'], correct: 0 },
    ],
    14: [
        { type: 'trace', prompt: 'Let scope — what prints?', code: [{ text: 'let x = "global";' }, { text: 'function f() {' }, { text: '    let x = "local";' }, { text: '    console.log(x);', highlight: true }, { text: '}' }, { text: 'f();' }], options: ['global', 'local', 'Error', 'undefined'], correct: 1 },
        { type: 'output', prompt: 'Closure counter', code: [{ text: 'function makeCounter() {' }, { text: '    let count = 0;' }, { text: '    return function() {' }, { text: '        count++;' }, { text: '        return count;' }, { text: '    };' }, { text: '}' }, { text: 'const c = makeCounter();' }, { text: 'console.log(c(), c(), c());' }], terminalOutput: '1 2 3', options: ['0 0 0', '1 1 1', '1 2 3', 'Error'], correct: 2 },
        { type: 'bug', prompt: 'Why does this fail?', code: [{ text: 'let total = 0;', hasError: false }, { text: 'function add(n) {', hasError: false }, { text: '    let total += n;', hasError: true }, { text: '}', hasError: false }], correctLine: 2 },
        { type: 'errordecode', prompt: 'Decode this scope error', errorText: "ReferenceError: total is not defined\n    at add (main.js:3)\n    at main.js:5", question: 'Fix?', options: ['Remove let — use outer total', 'Import total', 'Use var total', 'Delete total'], correct: 0 },
        { type: 'realworld', prompt: 'When to use closures?', scenario: '🧠 You need a function that remembers state between calls.', options: [{ code: 'function makeMultiplier(factor) {\n    return x => x * factor;\n}\nconst double = makeMultiplier(2);', label: 'Closure — captures factor' }, { code: 'let factor = 2;\nfunction multiply(x) {\n    return x * factor;\n}', label: 'Global variable' }, { code: 'class Mult {\n    constructor(f) { this.f = f; }\n}', label: 'Class (overkill)' }, { code: 'const multiply = x => x * 2;', label: 'Hardcoded arrow' }], correct: 0 },
    ],
    15: [
        { type: 'video', title: 'Functions Deep Dive', description: 'Parameters, defaults, rest/spread, closures, arrow functions, and higher-order functions.', duration: '3:30', thumbnail: '🎥' },
        { type: 'pair', prompt: 'Match function concepts', pairs: [{ id: 1, left: 'function', right: 'Declare function' }, { id: 2, left: 'return', right: 'Send value back' }, { id: 3, left: '...args', right: 'Rest parameters' }, { id: 4, left: '=>', right: 'Arrow function' }] },
        { type: 'trace', prompt: 'Higher-order function?', code: [{ text: 'function shout(fn) {' }, { text: '    return name => fn(name).toUpperCase();' }, { text: '}' }, { text: 'const greet = name => `hello ${name}`;' }, { text: 'const loudGreet = shout(greet);' }, { text: 'console.log(loudGreet("Otter"));', highlight: true }], options: ['hello Otter', 'HELLO OTTER', 'Hello Otter', 'Error'], correct: 1 },
    ],
    16: [
        { type: 'trace', prompt: 'What does fib(5) return?', code: [{ text: 'function fib(n) {' }, { text: '    if (n <= 1) return n;' }, { text: '    return fib(n-1) + fib(n-2);' }, { text: '}' }, { text: 'console.log(fib(5));', highlight: true }], options: ['3', '5', '8', '13'], correct: 1 },
        { type: 'algostep', prompt: 'fib(4) call tree', array: ['fib(4)', 'fib(3)+fib(2)', '(fib(2)+fib(1))+(fib(1)+fib(0))', '(1+1)+(1+0)=3'], step: 3, description: 'fib(4) = fib(3) + fib(2). Expanding...', question: 'What is fib(3)?', options: ['1', '2', '3', '5'], correct: 1 },
        { type: 'errordecode', prompt: 'Decode recursion error', errorText: 'RangeError: Maximum call stack size exceeded\n    at fib (main.js:2)', question: 'Cause?', options: ['Missing base case', 'Wrong return type', 'Too many params', 'Import error'], correct: 0 },
        { type: 'scramble', prompt: 'Build factorial', pieces: [{ id: 'a', text: 'function factorial(n) {' }, { id: 'b', text: '    if (n <= 1) return 1;' }, { id: 'c', text: '    return n * factorial(n - 1);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    return n + factorial(n);' }], correctOrder: ['a', 'b', 'c', 'd'] },
        { type: 'trace', prompt: 'What does sumDigits(123) return?', code: [{ text: 'function sumDigits(n) {' }, { text: '    if (n < 10) return n;' }, { text: '    return n % 10 + sumDigits(Math.floor(n / 10));' }, { text: '}' }, { text: 'console.log(sumDigits(123));', highlight: true }], options: ['6', '123', '3', '12'], correct: 0 },
        { type: 'realworld', prompt: 'Which is naturally recursive?', scenario: '🤔 Which breaks into same-type subproblems?', options: [{ code: '// File system: folders contain folders', label: 'Directory traversal ✓' }, { code: '// Read file line by line', label: 'File reading' }, { code: '// Print "Hello" 5 times', label: 'Simple loop' }, { code: '// Add two numbers', label: 'Addition' }], correct: 0 },
    ],
    // ═══ CH5-CH10: Use same conceptual exercises, shared with Python fallback ═══
    // Nodes 17-42 share language-agnostic exercises (pair, realworld, algostep)
    // and fall back to Python for code-heavy exercises via getExercisesForNode()
    17: [
        { type: 'trace', prompt: 'References! What prints?', code: [{ text: 'const a = [1, 2, 3];' }, { text: 'const b = a;' }, { text: 'b.push(4);' }, { text: 'console.log(a.length);', highlight: true }], options: ['3', '4', 'Error', '[1,2,3]'], correct: 1 },
        { type: 'output', prompt: 'Slicing result?', code: [{ text: 'const x = [10, 20, 30, 40, 50];' }, { text: 'console.log(x.slice(1, 4));' }], terminalOutput: '[20, 30, 40]', options: ['[10,20,30]', '[20,30,40]', '[20,30,40,50]', '[10,20,30,40]'], correct: 1 },
        { type: 'realworld', prompt: 'Copy without mutating?', scenario: '🔄 Original must stay unchanged', options: [{ code: 'const orig = [1,2,3];\nconst rev = [...orig].reverse();', label: 'Spread + reverse' }, { code: 'const orig = [1,2,3];\norig.reverse();', label: '.reverse() mutates!' }, { code: 'const rev = Array.from(orig);', label: 'Shallow only' }, { code: 'const rev = orig.slice().reverse();', label: 'slice + reverse' }], correct: 0 },
        { type: 'bug', prompt: 'Why does b change a?', code: [{ text: 'const a = [1, 2, 3];', hasError: false }, { text: 'const b = a;', hasError: true }, { text: 'b.push(4);', hasError: false }, { text: 'console.log(a); // [1,2,3,4] !', hasError: false }], correctLine: 1 },
        { type: 'refactor', prompt: 'How to properly copy an array?', originalCode: 'const original = [1, 2, 3];\nconst copy = original; // This is a reference!', options: [{ code: 'const copy = [...original];\n// or original.slice()\n// or Array.from(original)', label: 'Shallow copy ✓' }, { code: 'const copy = original;', label: 'Still a reference' }, { code: 'const copy = &original;', label: 'Not JS syntax' }], correct: 0 },
    ],
    18: [
        { type: 'trace', prompt: 'Frequency counter?', code: [{ text: 'const word = "banana";' }, { text: 'const freq = {};' }, { text: 'for (const c of word) {' }, { text: '    freq[c] = (freq[c] || 0) + 1;' }, { text: '}' }, { text: 'console.log(freq["a"]);', highlight: true }], options: ['1', '2', '3', 'undefined'], correct: 2 },
        { type: 'refactor', prompt: 'Cleanest char counting?', originalCode: 'const freq = {};\nfor (const c of word) {\n    if (freq[c]) freq[c]++;\n    else freq[c] = 1;\n}', options: [{ code: 'const freq = [...word].reduce((m,c) => {\n    m[c] = (m[c]||0)+1;\n    return m;\n}, {});', label: 'reduce() ✓' }, { code: 'const freq = {};\nword.split("").map(c => freq[c]++);', label: 'NaN issue' }, { code: 'const freq = Object.fromEntries(word);', label: 'fromEntries wrong' }], correct: 0 },
        { type: 'fillgap', prompt: 'Check anagram', codeParts: [{ text: 'function isAnagram(a, b) {\n    return ', type: 'fixed' }, { text: '[...a].sort().join("") === [...b].sort().join("");', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['[...a].sort().join("") === [...b].sort().join("");', 'a === b;', 'a.length === b.length;', 'new Set(a) === new Set(b);'], correctFill: { g1: '[...a].sort().join("") === [...b].sort().join("");' } },
        { type: 'output', prompt: 'Object comprehension-like?', code: [{ text: 'const obj = Object.fromEntries(' }, { text: '    [1,2,3,4].map(x => [x, x**2])' }, { text: ');' }, { text: 'console.log(obj);' }], terminalOutput: '{1:1, 2:4, 3:9, 4:16}', options: ['{1:1, 2:4, 3:9, 4:16}', '[1, 4, 9, 16]', 'Set{1,4,9,16}', 'Error'], correct: 0 },
        { type: 'pair', prompt: 'Match JS collection ops', pairs: [{ id: 1, left: '.map()', right: 'Transform each' }, { id: 2, left: '.filter()', right: 'Keep matching' }, { id: 3, left: '.reduce()', right: 'Accumulate' }, { id: 4, left: '.find()', right: 'First match' }] },
    ],
    19: [
        { type: 'scramble', prompt: 'Find duplicates in an array', pieces: [{ id: 'a', text: 'function findDupes(arr) {' }, { id: 'b', text: '    const seen = new Set();' }, { id: 'c', text: '    const dupes = new Set();' }, { id: 'd', text: '    for (const x of arr) {' }, { id: 'e', text: '        if (seen.has(x)) dupes.add(x);' }, { id: 'f', text: '        seen.add(x);' }, { id: 'g', text: '    }' }, { id: 'h', text: '    return [...dupes];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    return arr;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
        { type: 'trace', prompt: 'Set intersection?', code: [{ text: 'const a = new Set([1, 2, 3, 4]);' }, { text: 'const b = new Set([3, 4, 5, 6]);' }, { text: 'const inter = [...a].filter(x => b.has(x));' }, { text: 'console.log(inter);', highlight: true }], options: ['[3, 4]', '[1,2,3,4,5,6]', '[1,2]', '[5,6]'], correct: 0 },
        { type: 'output', prompt: 'Spread merge objects?', code: [{ text: 'const a = {x: 1, y: 2};' }, { text: 'const b = {y: 3, z: 4};' }, { text: 'const merged = {...a, ...b};' }, { text: 'console.log(merged.y);' }], terminalOutput: '3', options: ['2', '3', '[2,3]', 'Error'], correct: 1 },
    ],
    20: [
        { type: 'pair', prompt: 'Best use-case for each', pairs: [{ id: 1, left: 'Array', right: 'Ordered, index access' }, { id: 2, left: 'Set', right: 'Unique + fast lookup' }, { id: 3, left: 'Map', right: 'Key-value mapping' }, { id: 4, left: 'Object', right: 'Named properties' }] },
        { type: 'trace', prompt: 'Destructuring?', code: [{ text: 'const point = [3, 7];' }, { text: 'const [x, y] = point;' }, { text: 'console.log(x + y);', highlight: true }], options: ['[3,7]', '10', '37', 'Error'], correct: 1 },
        { type: 'realworld', prompt: 'Which data structure for a phone book?', scenario: '📱 Look up phone number by name.', options: [{ code: 'const phonebook = new Map();\nphonebook.set("Ali", "555-1234");', label: 'Map — O(1) lookup' }, { code: 'const pb = [["Ali","555-1234"]];', label: 'Array of arrays — O(n)' }, { code: 'const pb = new Set(["555-1234"]);', label: 'Set — no keys' }, { code: 'const pb = ["Ali", "555-1234"];', label: 'Flat array' }], correct: 0 },
    ],
}
