/* ══════════════════════════════════════════════════
   PYTHON EXERCISES — CH1-CH5 (nodes 1-20)
   ══════════════════════════════════════════════════ */
export const pyExercises = {
        1: [
            { type: 'trace', prompt: 'After the loop ends, what is in `count`?', code: [{ text: 'count = 0' }, { text: 'for i in range(5):' }, { text: '    if i % 2 == 0:' }, { text: '        count += 1' }, { text: 'print(count)', highlight: true }], options: ['2', '3', '5', '4'], correct: 1, explanation: 'range(5) hands out 0, 1, 2, 3, 4 — five values, and three of them are even (0, 2, 4). The usual slip is forgetting that 0 counts as even, which lands you on 2.', hint: 'Write down what i is on each pass, then tick the even ones.' },
            { type: 'realworld', prompt: 'Which snippet actually totals the items in the cart?', scenario: '🛒 3 apples, 2 oranges, 1 banana. You want 6, not 3.', options: [{ code: 'cart = [3, 2, 1]\ntotal = sum(cart)', label: 'Sum the list' }, { code: 'cart = [3, 2, 1]\ntotal = len(cart)', label: 'Length of the list' }, { code: 'cart = "3 2 1"\ntotal = len(cart)', label: 'Length of a string' }, { code: 'cart = {3, 2, 1}\ntotal = max(cart)', label: 'Biggest quantity' }], correct: 0, explanation: 'sum() adds the quantities and gives 6. len() gives 3 — the number of product kinds, not the number of items. Reaching for len() when you meant sum() is one of the most common bugs in real cart code, and nothing crashes to warn you.', hint: 'Two of these run fine and still give the wrong number. Which one answers "how many items", not "how many kinds"?' },
            { type: 'pair', prompt: 'Match each idea to what it means', pairs: [{ id: 1, left: 'Variable', right: 'Stores a value' }, { id: 2, left: 'String', right: 'Text data' }, { id: 3, left: 'Integer', right: 'Whole number' }, { id: 4, left: 'Boolean', right: 'True or False' }], explanation: 'A variable is a name pointing at a value; the other three are kinds of value it can point at. Almost everything you write early on is one of these four.' },
            { type: 'output', prompt: '`//` and `%` on the same numbers — what prints?', code: [{ text: 'x = 7' }, { text: 'y = 2' }, { text: 'print(x // y, x % y)' }], terminalOutput: '3 1', options: ['3.5 1', '3 1', '3.5 0', '3 0'], correct: 1, explanation: '// is floor division: 7 ÷ 2 is 3.5, and the remainder is thrown away, leaving 3. % keeps only what was thrown away — the 1. Plain / would have given 3.5, which is exactly what the other options are testing.', hint: 'One operator keeps the whole part and drops the rest. The other keeps only the rest.' },
            { type: 'fillgap', prompt: 'Swap two variables without a temporary', codeParts: [{ text: 'a = 5\nb = 10\n', type: 'fixed' }, { text: 'a, b = b, a', type: 'gap', id: 'g1' }], bank: ['a, b = b, a', 'a = b; b = a', 'swap(a, b)', 'a == b'], correctFill: { g1: 'a, b = b, a' }, explanation: 'Python evaluates the whole right side first, building the pair (10, 5), and only then unpacks it — so both original values still exist at the moment of assignment. a = b; b = a fails because after the first statement the old a is already gone and both end up 10.', hint: 'Step through a = b; b = a by hand and ask what a holds when the second statement runs.' },
            { type: 'scramble', prompt: 'Assemble a BMI calculation', pieces: [{ id: 'a', text: 'weight = 70' }, { id: 'b', text: 'height = 1.75' }, { id: 'c', text: 'bmi = weight / (height ** 2)' }, { id: 'd', text: 'print(round(bmi, 1))' }], distractors: [{ id: 'e', text: 'bmi = weight * height' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'Nothing can be used before it exists: both measurements have to be bound before the formula, and bmi before it is printed. The spare line multiplies instead of dividing by height squared — it runs perfectly and gives a meaningless number.', hint: 'Order the lines so no name is mentioned before the line that creates it.' },
        ],
        2: [
            { type: 'bug', prompt: 'One line stops this file from parsing — which?', code: [{ text: 'def greet(name):', hasError: false }, { text: '    msg = "Hello " + name', hasError: false }, { text: '    print(msg', hasError: true }, { text: '    return msg', hasError: false }], correctLine: 2, explanation: 'print(msg never closes its parenthesis, so Python keeps reading the next line hoping to find it. That is why the reported error often points one line lower than the real mistake — always check the line above the one Python blames.', hint: 'Count opening and closing brackets on each line.' },
            { type: 'bug', prompt: 'This security check never runs. Which line is dead?', scenario: '🔒 The same shape as Apple\'s "goto fail" SSL bug (2014).', code: [{ text: 'def is_authorized(user):', hasError: false }, { text: '    if not user.token:', hasError: false }, { text: '        return False', hasError: false }, { text: '        check_permissions(user)  # ?', hasError: true }], correctLine: 3, explanation: 'The permission check sits after a return, inside the same block, so it can never execute — anyone holding a token sails through. Apple\'s 2014 goto fail bug was exactly this shape: one stray line made SSL verification unreachable on millions of devices.', hint: 'Read top to bottom and ask, for each line, whether control can still reach it.' },
            { type: 'bug', prompt: 'Every caller ends up sharing one cart. Which line causes it?', scenario: '🛒 A Python gotcha that reaches production regularly.', code: [{ text: 'def add_to_cart(item, cart=[]):', hasError: true }, { text: '    cart.append(item)', hasError: false }, { text: '    return cart', hasError: false }], correctLine: 0, explanation: 'The default [] is built once, when the function is defined — not on each call. So every caller that omits cart mutates the same list, and one user sees another user\'s items. The fix is cart=None in the signature, then cart = cart or [] inside.', hint: 'Ask when that empty list is actually created: once, or once per call?' },
            { type: 'errordecode', prompt: 'What is this traceback really telling you?', errorText: 'Traceback (most recent call last):\n  File "main.py", line 3\n    print(message\n         ^\nSyntaxError: unexpected EOF while parsing', question: 'What caused this?', options: ['Missing closing parenthesis', 'Undefined variable', 'Wrong indentation', 'Invalid string'], correct: 0, explanation: 'EOF means end of file. Python reached the end while still waiting for something to be closed — here the parenthesis after print(message. The caret marks where Python gave up, not where you made the mistake.', hint: 'What was the parser still waiting for when it ran out of file?' },
            { type: 'refactor', prompt: 'Same behaviour, fewest moving parts — which?', originalCode: 'x = 10\nif x > 5:\n    r = "big"\nelse:\n    r = "small"\nprint(r)', options: [{ code: 'x = 10\nr = "big" if x > 5 else "small"\nprint(r)', label: 'Conditional expression' }, { code: 'x = 10\nresult = ""\nif x > 5: result = "big"\nif x <= 5: result = "small"', label: 'Two separate ifs' }, { code: 'print("big") if 10 > 5 else print("small")', label: 'Branch on the print' }], correct: 0, explanation: 'The conditional expression assigns once and cannot leave r unset. Two independent ifs re-test the same value and will silently disagree the day one condition is edited. The third hard-codes 10 and throws the value away instead of storing it.', hint: 'Which version still works if you later change what x is, and can never leave the variable empty?' },
            { type: 'bug', prompt: 'This crashes at runtime, not at parse time. Where?', code: [{ text: 'age = input("Age: ")', hasError: false }, { text: 'if age > 18:', hasError: true }, { text: '    print("Adult")', hasError: false }], correctLine: 1, explanation: 'input() always returns a str, whatever the user types, and Python 3 refuses to order a str against an int — TypeError. Python 2 allowed the comparison, which is why old tutorials still teach this broken pattern. Wrap it: int(input(...)).', hint: 'What type does input() hand back when the user types 25?' },
            { type: 'output', prompt: 'A string times a number — what prints?', code: [{ text: 'x = "5"' }, { text: 'y = 3' }, { text: 'print(x * y)' }], terminalOutput: '555', options: ['15', '555', '53', 'Error'], correct: 1, explanation: '* on a string repeats it, so "5" * 3 is "555". No error is raised, which is what makes it dangerous — you get plausible-looking output instead of a crash. For 15 you would need int(x) * y.', hint: 'Look at the quotes around the 5. Is it a number or text?' },
            { type: 'trace', prompt: 'What type does `/` produce here?', code: [{ text: 'a = 10' }, { text: 'b = 3' }, { text: 'result = a / b' }, { text: 'print(type(result))', highlight: true }], options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "3.33"], correct: 1, explanation: 'In Python 3, / always returns a float — even 10 / 2 gives 5.0, not 5. Use // when you want an int back. Note the question asks for the type, so the answer is a class, not the number 3.33.', hint: 'Two things to decide: what / returns, and what type() prints rather than the value.' },
        ],
        3: [
            { type: 'video', title: 'Variables & Data Types', description: 'Variables store data. Python is dynamically typed — no type declarations needed. int, float, str, bool are the basics.', duration: '2:45', thumbnail: '🎬' },
            { type: 'output', prompt: 'What does `type(age)` report?', code: [{ text: 'name = "Rheo"' }, { text: 'age = 3' }, { text: 'print(type(age))' }], terminalOutput: "<class 'int'>", options: ["<class 'str'>", "<class 'int'>", "3", "Error"], correct: 1, explanation: 'age was bound to 3 with no quotes, so it is an int. type() reports the type of the value, not the name — and it prints the class, not the value, which is why plain 3 is wrong.', hint: 'Check whether there are quotes around the 3, then check what type() actually prints.' },
            { type: 'pair', prompt: 'Match each type to a value of that type', pairs: [{ id: 1, left: 'int', right: '42' }, { id: 2, left: 'float', right: '3.14' }, { id: 3, left: 'str', right: '"hello"' }, { id: 4, left: 'bool', right: 'True' }], explanation: 'The literal tells you the type: no quotes and no dot means int, a dot means float, quotes mean str, and True/False are the only two bools. Python never asks you to declare any of it.' },
        ],
        4: [
            { type: 'pair', prompt: 'Match each operator to what it does', pairs: [{ id: 1, left: '==', right: 'Equals' }, { id: 2, left: '!=', right: 'Not equals' }, { id: 3, left: '**', right: 'Power' }, { id: 4, left: '//', right: 'Floor divide' }], explanation: 'Watch the doubles: = assigns while == compares, and / divides while // divides and drops the remainder. Writing = where you meant == is the single most common beginner typo.' },
            { type: 'trace', prompt: 'What do `%` and `//` give for 17 and 5?', code: [{ text: 'x = 17' }, { text: 'print(x % 5, x // 5)', highlight: true }], options: ['2 3', '3 2', '2 4', '17 5'], correct: 0, explanation: '17 = 5 × 3 + 2. So // gives 3 (how many whole 5s fit) and % gives 2 (what is left over). The order in the print matters: % comes first, so it is 2 then 3 — swapping them is exactly what the "3 2" option is checking.', hint: 'Work out 17 ÷ 5 as "whole part and remainder", then match them to the operators in the printed order.' },
            { type: 'fillgap', prompt: 'Complete the Celsius to Fahrenheit conversion', codeParts: [{ text: 'celsius = 25\n', type: 'fixed' }, { text: 'fahrenheit = celsius * 9/5 + 32', type: 'gap', id: 'g1' }, { text: '\nprint(fahrenheit)', type: 'fixed' }], bank: ['celsius * 9/5 + 32', 'celsius + 32', 'celsius * 1.8', 'celsius / 5 * 9'], correctFill: { g1: 'celsius * 9/5 + 32' }, explanation: 'Two things differ between the scales and you need both: degrees are a different size (× 9/5) and zero is in a different place (+ 32). celsius * 1.8 fixes only the size, celsius + 32 only the offset — each is right at exactly one temperature and wrong everywhere else.', hint: 'Check your candidate against a known pair: 0 °C is 32 °F and 100 °C is 212 °F. Only one option gets both.' },
        ],
        // ═══ CH2: FLOW CONTROL ⭐ ═══
        5: [
            { type: 'trace', prompt: 'x is 15. Which letter gets printed?', code: [{ text: 'x = 15' }, { text: 'if x > 20:' }, { text: '    print("A")' }, { text: 'elif x > 10:' }, { text: '    if x % 2 == 0:' }, { text: '        print("B")' }, { text: '    else:' }, { text: '        print("C")', highlight: true }], options: ['A', 'B', 'C', 'None'], correct: 2, explanation: 'Two decisions, not one. 15 > 20 is false so the elif takes over, and inside it 15 % 2 is 1, not 0 — so the inner else runs and prints C. "None" would need every branch to fail, which cannot happen once a chain ends in else.', hint: 'Pick the outer branch first, then work out which side of the inner if you land on.' },
            { type: 'bug', prompt: 'An 18-year-old is told they cannot vote. Which line is wrong?', code: [{ text: 'age = 18', hasError: false }, { text: 'if age > 18:', hasError: true }, { text: '    print("Can vote")', hasError: false }], correctLine: 1, explanation: 'The rule is "18 and over", but > 18 excludes exactly the boundary the rule is about. It needs >=. Off-by-one on a boundary is the most common logic bug there is, and it stays invisible until someone tests the boundary value itself.', hint: 'Substitute 18 into the comparison and read it out loud.' },
            { type: 'output', prompt: 'a is 0 — does this crash, and what prints?', code: [{ text: 'a = 0' }, { text: 'b = 5' }, { text: 'result = a and b/a' }, { text: 'print(result)' }], terminalOutput: '0', options: ['0', 'Error: ZeroDivision', '5', 'False'], correct: 0, explanation: 'Two things save it. `and` stops as soon as it finds a falsy operand, so b/a never runs — no division by zero. And `and` returns the operand itself, not a boolean, so you get 0 rather than False. This is why `x and x.method()` is a safe guard in Python.', hint: 'Ask separately: does the right-hand side ever run, and what does `and` actually hand back?' },
            { type: 'realworld', prompt: 'Which one locks the user out after three wrong passwords?', scenario: '🔐 Three attempts, then stop asking.', options: [{ code: 'attempts = 0\nwhile attempts < 3:\n    pwd = input()\n    if pwd == secret: break\n    attempts += 1', label: 'while with a counter' }, { code: 'for i in range(3):\n    pwd = input()\n    if pwd != secret: continue', label: 'for with continue' }, { code: 'attempts = 0\nwhile attempts < 3:\n    pwd = input()\n    if pwd == secret: break', label: 'while, break on success' }, { code: 'while True:\n    pwd = input()\n    if pwd == secret: break', label: 'loop until correct' }], correct: 0, explanation: 'Only the first one both stops early on success and counts failures, so it ends after three wrong tries. The third looks almost identical but never increments attempts — the condition stays true forever and it asks endlessly. The last has no limit at all, and the `continue` version does nothing on a wrong password since continue simply goes to the next iteration.', hint: 'For each one, ask what makes the loop stop when the password is always wrong.' },
            { type: 'scramble', prompt: 'Assemble a grade calculator', pieces: [{ id: 'a', text: 'score = 75' }, { id: 'b', text: 'if score >= 90: grade = "A"' }, { id: 'c', text: 'elif score >= 80: grade = "B"' }, { id: 'd', text: 'elif score >= 70: grade = "C"' }, { id: 'e', text: 'else: grade = "F"' }, { id: 'f', text: 'print(grade)' }], distractors: [{ id: 'g', text: 'if score == 90: grade = "A"' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'], explanation: 'The order of the elif tests IS the logic: each one only runs when everything above it failed. Put >= 70 before >= 80 and a score of 95 comes out as a C, because the first test it reaches already passes. The spare line uses == 90, which would match only the single value 90.', hint: 'The thresholds have to descend. Ask what a 95 would score if you got the order backwards.' },
            { type: 'trace', prompt: 'n is 0. What ends up in `label`?', code: [{ text: 'n = 0' }, { text: 'label = "positive" if n > 0 else "negative" if n < 0 else "zero"' }, { text: 'print(label)', highlight: true }], options: ['positive', 'negative', 'zero', 'Error'], correct: 2, explanation: 'Read it left to right: n > 0 fails, so the else half is evaluated — and that half is itself another conditional expression. n < 0 also fails, leaving "zero". There is no special chaining syntax here, just one conditional nested inside another.', hint: 'Rewrite it as a nested if/else on paper, then follow n = 0 down.' },
        ],
        6: [
            { type: 'trace', prompt: 'What do these two lists evaluate to as booleans?', code: [{ text: 'x = [1, 2, 3]' }, { text: 'y = []' }, { text: 'print(bool(x), bool(y))', highlight: true }], options: ['True True', 'True False', 'False True', 'False False'], correct: 1, explanation: 'A container is truthy when it holds anything and falsy when empty — what it holds is irrelevant. So the filled list is True and the empty one False. Worth noting [0] would also be True: it has one item, and that is all that counts.', hint: 'For a container only the item count matters, not the values inside.' },
            { type: 'refactor', prompt: 'Which is the idiomatic way to ask "is this list non-empty?"', originalCode: 'if len(my_list) > 0:\n    do_something()', options: [{ code: 'if my_list:\n    do_something()', label: 'Rely on truthiness' }, { code: 'if my_list != []:\n    do_something()', label: 'Compare against []' }, { code: 'if my_list is not None:\n    do_something()', label: 'Compare against None' }], correct: 0, explanation: 'if my_list: reads as the question being asked and works for any container. Comparing against [] builds a throwaway list every time and only works for lists. The None check answers a completely different question — an empty list is not None, so that version happily runs the body on an empty list.', hint: 'One of these three is testing something other than emptiness. Find it first.' },
            { type: 'fillgap', prompt: 'Return True when n is between 1 and 100, ends included', codeParts: [{ text: 'def in_range(n):\n    return ', type: 'fixed' }, { text: '1 <= n <= 100', type: 'gap', id: 'g1' }], bank: ['1 <= n <= 100', '1 <= n or n <= 100', 'n in range(100)', '1 < n < 100'], correctFill: { g1: '1 <= n <= 100' }, explanation: 'Chained comparison reads exactly like the maths and includes both ends. Swapping `and` for `or` — as the second option effectively does — is always true for every number, so it silently accepts everything. range(100) stops at 99 and only accepts integers. And 1 < n < 100 excludes 1 and 100, the two values the question is specifically about.', hint: 'Test each candidate at n = 1 and n = 100. The ends are exactly where they disagree.' },
            { type: 'output', prompt: 'How many of these seven values survive the filter?', code: [{ text: 'values = [0, "", [], None, 1, "hi", [0]]' }, { text: 'truthy = [v for v in values if v]' }, { text: 'print(len(truthy))' }], terminalOutput: '3', options: ['2', '3', '4', '7'], correct: 1, explanation: '0, "", [] and None are all falsy, leaving 1, "hi" and [0] — three. The last one is the trap: the list contains a falsy value, but the list itself is not empty, so it passes. Answering 2 usually means discarding [0] along with the 0 inside it.', hint: 'Count the falsy ones and subtract. Look hard at the last item.' },
            { type: 'pair', prompt: 'Match each falsy value to what makes it falsy', pairs: [{ id: 1, left: '0', right: 'Zero number' }, { id: 2, left: '""', right: 'Empty string' }, { id: 3, left: '[]', right: 'Empty container' }, { id: 4, left: 'None', right: 'Absence of a value' }], explanation: 'Python\'s rule is "empty or zero is false": 0, 0.0, "", [], {}, set() and None. Everything else is true unless a class overrides __bool__ or __len__ to say otherwise.' },
        ],
        7: [
            { type: 'terminal', prompt: 'Store a name in a variable, then print it', expectedCommands: ['name = "Otter"', 'print(name)'], hint: 'Two lines: bind the value first, then hand the variable to print.', terminalHistory: [{ type: 'system', text: '>>> Daily Challenge' }] },
            { type: 'trace', prompt: 'What does `result` hold after the loop?', code: [{ text: 'result = ""' }, { text: 'for c in "hello":' }, { text: '    result += c.upper()' }, { text: 'print(result)', highlight: true }], options: ['hello', 'HELLO', 'Hello', 'hELLO'], correct: 1, explanation: 'The loop walks the string one character at a time and appends each one uppercased, so all five end up uppercase. "Hello" would require uppercasing only the first pass, and "hELLO" only the passes after the first — neither matches a rule applied identically every iteration.', hint: 'Write down result after each of the five passes.' },
            { type: 'output', prompt: 'The braces hold an expression — what prints?', code: [{ text: 'name = "Otter"' }, { text: 'age = 5' }, { text: 'print(f"{name} is {age*7} in human years")' }], terminalOutput: 'Otter is 35 in human years', options: ['Otter is 35 in human years', 'Otter is 5 in human years', '{name} is {age*7}', 'Error'], correct: 0, explanation: 'An f-string evaluates whatever sits inside the braces, so {age*7} becomes 35 — not just the variable, the whole expression. Drop the f prefix and you get the third option: the braces print literally, with no error to warn you.', hint: 'Two questions: does the f do anything, and is {age*7} a name or a calculation?' },
        ],
        8: [
            { type: 'video', title: 'Conditional Logic Deep Dive', description: 'if/elif/else chains, ternary, truthiness, short-circuit evaluation, match-case (3.10+).', duration: '3:00', thumbnail: '🎥' },
            { type: 'trace', prompt: 'status is 404. What does match print?', code: [{ text: 'status = 404' }, { text: 'match status:' }, { text: '    case 200: msg = "OK"' }, { text: '    case 404: msg = "Not Found"' }, { text: '    case _: msg = "Unknown"' }, { text: 'print(msg)', highlight: true }], options: ['OK', 'Not Found', 'Unknown', 'Error'], correct: 1, explanation: 'match checks the cases top to bottom and stops at the first that matches, so 404 wins and the catch-all `case _` is never reached — it only fires when nothing above it did. The Error option is a fair worry: match-case needs Python 3.10 or newer and really is a SyntaxError on 3.9.', hint: 'Read the cases in order and stop at the first hit. Then ask when `case _` would ever run.' },
        ],
        // ═══ CH3: LOOPS ⭐⭐ ═══
        9: [
            { type: 'scramble', prompt: 'Print the numbers 1 to 5, one per line', pieces: [{ id: 'a', text: 'for i in range(1, 6):' }, { id: 'b', text: '    print(i)' }], distractors: [{ id: 'c', text: '    print(i + 1)' }, { id: 'd', text: 'while i < 5:' }], correctOrder: ['a', 'b'], explanation: 'range(1, 6) starts at 1 and stops BEFORE 6, so it yields 1,2,3,4,5 — exactly five numbers. The spare while line would need i to already exist and to be incremented inside, or it loops forever; and printing i + 1 would give 2 to 6.', hint: 'Work out which numbers range(1, 6) actually hands you before choosing what to print.' },
            { type: 'bug', prompt: 'This should print 1 through 10 but stops at 9. Which line?', code: [{ text: 'for i in range(1, 10):', hasError: true }, { text: '    print(i)', hasError: false }], correctLine: 0, explanation: 'The second argument to range is exclusive — it is where the loop stops, not the last value produced. range(1, 10) ends at 9, so reaching 10 needs range(1, 11). This one rule causes more off-by-one bugs than anything else in Python.', hint: 'Count how many numbers range(1, 10) actually produces, then compare with what was asked for.' },
            { type: 'trace', prompt: 'How many times does the loop body run?', code: [{ text: 'n = 64' }, { text: 'count = 0' }, { text: 'while n > 1:' }, { text: '    n = n // 2' }, { text: '    count += 1' }, { text: 'print(count)', highlight: true }], options: ['5', '6', '7', '32'], correct: 1, explanation: 'n halves each pass: 64→32→16→8→4→2→1, which is six steps. Since 64 is 2⁶, the answer is log₂(64) = 6 — this is exactly the shape that makes binary search O(log n). Answering 7 usually means counting the starting value as a step; 32 is one halving, not the whole loop.', hint: 'Write the sequence of values n takes and count the arrows, not the numbers.' },
            { type: 'fillgap', prompt: 'Make total end up as 10 — the sum of 1 through 4', codeParts: [{ text: 'total = 0\nfor num in ', type: 'fixed' }, { text: '[1,2,3,4]', type: 'gap', id: 'g1' }, { text: ':\n    total += num', type: 'fixed' }], bank: ['[1,2,3,4]', 'range(4)', '(1,2,3)', '{1:4}'], correctFill: { g1: '[1,2,3,4]' }, explanation: 'Every option here is iterable and none of them crash — they just add up to the wrong number. range(4) gives 0,1,2,3 and totals 6; the tuple (1,2,3) totals 6 as well; and iterating a dict walks its KEYS, so {1:4} adds only 1. Only the explicit list reaches 10.', hint: 'They all run. Add each one up by hand and see which lands on 10.' },
            { type: 'realworld', prompt: 'Which one actually leaves the largest value in `best`?', scenario: '📊 nums = [3, 7, 2, 9, 4] — you want 9.', options: [{ code: 'best = nums[0]\nfor n in nums:\n    if n > best: best = n', label: 'Scan and keep the winner' }, { code: 'best = nums[-1]', label: 'Take the last item' }, { code: 'nums.sort()\nbest = nums[0]', label: 'Sort, then take the first' }, { code: 'best = sum(nums) / len(nums)', label: 'Take the average' }], correct: 0, explanation: 'The scan seeds best with a real element and replaces it whenever it sees something bigger — the standard maximum pattern. Taking the last item only works if the list happens to end on its largest. Sorting then taking index 0 gives the SMALLEST, since sort ascends; you would need nums[-1]. The average is a different statistic entirely.', hint: 'Run each one on [3, 7, 2, 9, 4] and see which produces 9. One of them is off by exactly a reversed sort.' },
            { type: 'output', prompt: 'What does break leave printed?', code: [{ text: 'for i in range(5):' }, { text: '    if i == 3: break' }, { text: '    print(i, end=" ")' }], terminalOutput: '0 1 2 ', options: ['0 1 2 ', '0 1 2 3', '0 1 2 3 4', '3'], correct: 0, explanation: 'break leaves the loop immediately, so when i reaches 3 the print below it never runs — 3 is never shown. Move the print above the if and you would get "0 1 2 3". Compare this with continue, which skips only the rest of that one pass and keeps looping.', hint: 'The order of the two lines inside the loop is the whole answer.' },
        ],
        10: [
            { type: 'trace', prompt: 'How many lines does this nested loop print?', code: [{ text: 'for i in range(3):' }, { text: '    for j in range(4):' }, { text: '        print(i, j)', highlight: true }], options: ['7', '12', '9', '16'], correct: 1, explanation: 'The inner loop runs fully for every single pass of the outer one, so it is 3 × 4 = 12 — a product, not a sum. Answering 7 is adding them; 9 and 16 are squaring one of them. This is also why nested loops over the same collection are O(n²).', hint: 'For each value of i, how many times does j run? Then combine.' },
            { type: 'output', prompt: 'Which shape does this print?', code: [{ text: 'for i in range(1, 4):' }, { text: '    print("*" * i)' }], terminalOutput: '*\n**\n***', options: ['***\n**\n*', '*\n**\n***', '***', '* * *'], correct: 1, explanation: 'i goes 1, 2, 3 and "*" * i repeats the string that many times, so the rows grow. The reversed triangle would need range(3, 0, -1). Note that * on a string repeats rather than multiplies — the same operator doing a different job depending on the type.', hint: 'Write down what i is on each pass, then what "*" * i produces for it.' },
            { type: 'realworld', prompt: 'Which one flattens the matrix into a single list?', scenario: '📊 [[1,2],[3,4],[5,6]] → [1,2,3,4,5,6]', options: [{ code: 'flat = [x for row in m for x in row]', label: 'Nested comprehension' }, { code: 'flat = sum(m)', label: 'sum() over the rows' }, { code: 'flat = m.flatten()', label: '.flatten() method' }, { code: 'flat = list(m)', label: 'list() around it' }], correct: 0, explanation: 'The two for clauses read in the same order you would write them as nested loops: outer first, then inner. sum(m) raises TypeError because it starts from 0 and cannot add a list to an int — sum(m, []) would actually work. .flatten() belongs to NumPy arrays, not lists. And list(m) just copies the outer list, leaving the rows intact.', hint: 'Two of these fail loudly, one succeeds but changes nothing. Find the one that changes the shape.' },
            { type: 'scramble', prompt: 'Assemble one row of a multiplication table', pieces: [{ id: 'a', text: 'n = 5' }, { id: 'b', text: 'for i in range(1, 11):' }, { id: 'c', text: '    print(f"{n} x {i} = {n*i}")' }], distractors: [{ id: 'd', text: '    print(n + i)' }], correctOrder: ['a', 'b', 'c'], explanation: 'n has to exist before the loop that uses it, and the print has to be indented inside the loop or it runs only once, after the loop finishes. range(1, 11) gives 1 through 10 — the exclusive end again. The spare line adds instead of multiplying.', hint: 'One line sets up, one repeats, one does the work. Which has to be inside which?' },
            { type: 'trace', prompt: 'What does enumerate hand to each iteration?', code: [{ text: 'fruits = ["apple", "banana", "cherry"]' }, { text: 'for i, f in enumerate(fruits):' }, { text: '    print(i, f)', highlight: true }], options: ['0 apple\n1 banana\n2 cherry', 'apple 0\nbanana 1', '1 apple\n2 banana\n3 cherry', 'Error'], correct: 0, explanation: 'enumerate yields (index, value) pairs in that order, counting from 0. If you want it to count from 1 — for a numbered list shown to a user — pass enumerate(fruits, start=1), which is what the third option shows. The order of the pair matters: swapping i and f in the for line silently gives you the value in i.', hint: 'Two questions: which of the pair comes first, and what number does counting start at?' },
        ],
        11: [
            { type: 'scramble', prompt: 'Assemble a primality test', pieces: [{ id: 'a', text: 'def is_prime(n):' }, { id: 'b', text: '    if n < 2: return False' }, { id: 'c', text: '    for i in range(2, int(n**0.5)+1):' }, { id: 'd', text: '        if n % i == 0: return False' }, { id: 'e', text: '    return True' }], distractors: [{ id: 'f', text: '    for i in range(n):' }], correctOrder: ['a', 'b', 'c', 'd', 'e'], explanation: 'The guard for n < 2 has to come first, because 0 and 1 are not prime and would otherwise fall through to the final return True. Testing only up to √n is the real trick: any factor above the square root has a matching partner below it, so if none was found by then there is none at all. The spare line starts at 0 — and n % 0 raises ZeroDivisionError immediately.', hint: 'Why is √n enough? Think about what pairs up with a factor larger than it.' },
            { type: 'trace', prompt: 'What does the comprehension filter down to?', code: [{ text: 'nums = [1, 2, 3, 4, 5, 6]' }, { text: 'evens = [n for n in nums if n % 2 == 0]' }, { text: 'print(evens)', highlight: true }], options: ['[2, 4, 6]', '[1, 3, 5]', '[1, 2, 3, 4, 5, 6]', '3'], correct: 0, explanation: 'The if at the end keeps only the items it accepts, and n % 2 == 0 is true for even numbers. Reading it as "n % 2" alone would keep the odd ones instead — that is the [1, 3, 5] option. The result is a list, not a count, so 3 answers a different question.', hint: 'Read the trailing if as a filter, then check which numbers it lets through.' },
            { type: 'fillgap', prompt: 'Build [1, 4, 9, 16, 25] — the squares of 1 through 5', codeParts: [{ text: 'squares = ', type: 'fixed' }, { text: '[x**2 for x in range(1,6)]', type: 'gap', id: 'g1' }], bank: ['[x**2 for x in range(1,6)]', 'map(x**2, range(5))', '[x*x in range(5)]', 'range(1,6)**2'], correctFill: { g1: '[x**2 for x in range(1,6)]' }, explanation: 'range(1,6) gives 1 to 5 and ** squares each one. The map version fails twice over — x does not exist outside a comprehension, and map wants a function, not an expression. [x*x in range(5)] has no `for`, so it is not a comprehension at all: it is a membership test wrapped in brackets, giving a one-element list like [True]. And a range object cannot be raised to a power.', hint: 'Only one of these builds a list of five numbers. Start by ruling out the ones that cannot.' },
            { type: 'realworld', prompt: 'Which one collects the scores of 60 and above?', scenario: '📝 scores = [45, 78, 92, 33, 88], passing mark 60.', options: [{ code: 'passed = [s for s in scores if s >= 60]', label: 'Comprehension with a filter' }, { code: 'passed = scores.filter(60)', label: 'Call .filter() on the list' }, { code: 'passed = scores > 60', label: 'Compare the list directly' }, { code: 'passed = [s for s in scores if s > 60]', label: 'Comprehension, strictly above' }], correct: 0, explanation: 'The passing mark is 60, so the test has to include it — >= 60, not > 60. On this data both happen to give the same three scores, which is exactly what makes the bug so easy to ship: it only shows up the day someone scores exactly 60. Lists have no .filter() method (that is JavaScript), and comparing a list to an int raises TypeError.', hint: 'Two of these produce identical output on this data. Ask which one would disagree on a score of exactly 60.' },
        ],
        12: [
            { type: 'pair', prompt: 'Match each loop tool to what it does', pairs: [{ id: 1, left: 'break', right: 'Leave the loop now' }, { id: 2, left: 'continue', right: 'Skip to the next pass' }, { id: 3, left: 'enumerate()', right: 'Index alongside value' }, { id: 4, left: 'zip()', right: 'Walk two sequences together' }], explanation: 'break and continue are often confused: break abandons the whole loop, continue abandons only the current pass. enumerate and zip both exist so you never have to loop over indices manually — reaching for range(len(x)) is usually a sign one of these two is what you actually wanted.' },
            { type: 'trace', prompt: 'What does zip pair up here?', code: [{ text: 'names = ["Ali", "Ece"]' }, { text: 'ages = [20, 22]' }, { text: 'for n, a in zip(names, ages):' }, { text: '    print(f"{n}:{a}")', highlight: true }], options: ['Ali:20\nEce:22', 'Ali Ece\n20 22', '(Ali,20)', 'Error'], correct: 0, explanation: 'zip takes one item from each sequence per pass and hands them over as a pair, which the for line unpacks into n and a. Worth knowing the failure mode: zip stops at the SHORTER sequence and drops the rest silently — pass a 2-item and a 5-item list and you get 2 pairs with no warning.', hint: 'One item from each list, per pass. Then ask what happens if the lists were different lengths.' },
            { type: 'output', prompt: 'What does continue leave printed?', code: [{ text: 'for i in range(5):' }, { text: '    if i == 2: continue' }, { text: '    print(i, end=" ")' }], terminalOutput: '0 1 3 4 ', options: ['0 1 3 4 ', '0 1 2 3 4', '2', '0 1'], correct: 0, explanation: 'continue skips the rest of this one pass and moves to the next, so only 2 is missing — the loop keeps going. "0 1" would be the answer if this were break, which is the distinction the question is really testing.', hint: 'Does the loop end at i = 2, or just skip that one pass?' },
        ],
        // ═══ CH4: FUNCTIONS ⭐⭐ ═══
        13: [
            { type: 'trace', prompt: 'Only one argument is passed — what comes back?', code: [{ text: 'def add(a, b=10):' }, { text: '    return a + b' }, { text: 'print(add(3))', highlight: true }], options: ['3', '10', '13', 'Error'], correct: 2, explanation: 'b has a default, so leaving it out is allowed and it takes the value 10 — giving 3 + 10 = 13. A parameter with a default is optional; one without is not, which is why defaults must always come last in the signature.', hint: 'Write down what a and b each hold at the moment the body runs.' },
            { type: 'bug', prompt: 'The caller gets None instead of the sum. Which line?', code: [{ text: 'def add(a, b):', hasError: false }, { text: '    result = a + b', hasError: false }, { text: '    print(result)', hasError: true }], correctLine: 2, explanation: 'Printing shows a value on screen; returning hands it back to the caller. With no return the function yields None, so total = add(2, 3) silently stores None and the failure surfaces somewhere else entirely. Confusing these two is the most common beginner bug in any language.', hint: 'Ask what `x = add(2, 3)` would put in x.' },
            { type: 'refactor', prompt: 'Which version stays correct as more operations are added?', originalCode: 'def calc(a, b, op):\n    if op == "add": return a+b\n    if op == "sub": return a-b\n    if op == "mul": return a*b', options: [{ code: 'ops = {"add": lambda a,b: a+b,\n       "sub": lambda a,b: a-b,\n       "mul": lambda a,b: a*b}\ndef calc(a,b,op): return ops[op](a,b)', label: 'Look the operation up in a dict' }, { code: 'def calc(a,b,op): return eval(f"{a}{op}{b}")', label: 'Build a string and eval it' }, { code: 'def calc(a,b,op):\n    match op:\n        case "+": return a+b', label: 'match on the operator' }], correct: 0, explanation: 'The dict turns "add another operation" into "add another entry" — no control flow to edit, and the table can be extended at runtime. eval executes whatever string it is given, so any caller-supplied op becomes arbitrary code execution; it is a genuine security hole, not just untidy. The match version handles only "+" and silently returns None for everything else.', hint: 'Imagine adding division tomorrow. Which one do you edit, and which one can a hostile caller abuse?' },
            { type: 'output', prompt: 'Four arguments, one parameter — what prints?', code: [{ text: 'def total(*nums):' }, { text: '    return sum(nums)' }, { text: 'print(total(1, 2, 3, 4))' }], terminalOutput: '10', options: ['(1,2,3,4)', '10', '4', 'Error'], correct: 1, explanation: '*nums collects every positional argument into a tuple, so inside the function nums is (1,2,3,4) and sum gives 10. The tuple itself is what the first option shows — that would be the answer if the function returned nums rather than summing it. 4 would be len(nums).', hint: 'Two steps: what does nums hold inside the function, and what does sum do to it?' },
            { type: 'scramble', prompt: 'Assemble a greeter with an optional greeting', pieces: [{ id: 'a', text: 'def greet(name, greeting="Hello"):' }, { id: 'b', text: '    return f"{greeting}, {name}!"' }, { id: 'c', text: 'print(greet("Furkan"))' }, { id: 'd', text: 'print(greet("Arda", greeting="Hey"))' }], distractors: [{ id: 'e', text: '    return name + greeting' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'The function has to be defined before either call, and the body has to be indented under it. The two calls show why defaults are useful: the first accepts "Hello", the second overrides it by name. The spare line concatenates in the wrong order and without punctuation.', hint: 'Definition before use, body indented inside. Then the two calls in the order that shows the default first.' },
            { type: 'trace', prompt: 'What does map produce here?', code: [{ text: 'double = lambda x: x * 2' }, { text: 'nums = [1, 2, 3]' }, { text: 'result = list(map(double, nums))' }, { text: 'print(result)', highlight: true }], options: ['[2, 4, 6]', '[1, 2, 3]', '6', 'Error'], correct: 0, explanation: 'map applies double to each item, and list() forces the result out — without it you would print a map object rather than the numbers, because map is lazy in Python 3. A lambda is just a function with no name; def double(x): return x * 2 would behave identically.', hint: 'Two things to track: what map does to each item, and why list() is wrapped around it.' },
        ],
        14: [
            { type: 'trace', prompt: 'Same name inside and outside — which one prints?', code: [{ text: 'x = "global"' }, { text: 'def f():' }, { text: '    x = "local"' }, { text: '    print(x)', highlight: true }, { text: 'f()' }], options: ['global', 'local', 'Error', 'None'], correct: 1, explanation: 'Assigning to x inside the function creates a brand new local name that shadows the outer one for the whole function. The global x is untouched — print it after f() and it still says "global". Reading a name you never assign to would find the outer one instead.', hint: 'Does the function assign to x, or only read it? That single fact decides the answer.' },
            { type: 'output', prompt: 'The counter is called three times — what prints?', code: [{ text: 'def make_counter():' }, { text: '    count = 0' }, { text: '    def inc():' }, { text: '        nonlocal count' }, { text: '        count += 1' }, { text: '        return count' }, { text: '    return inc' }, { text: 'c = make_counter()' }, { text: 'print(c(), c(), c())' }], terminalOutput: '1 2 3', options: ['0 0 0', '1 1 1', '1 2 3', 'Error'], correct: 2, explanation: 'inc closes over count, so the variable outlives make_counter and keeps its value between calls — that is what a closure is. nonlocal is what makes it work: without it, count += 1 would try to create a local and raise UnboundLocalError, which is the "Error" option. "1 1 1" would happen if each call started fresh.', hint: 'Where does count live after make_counter has returned, and what does nonlocal change?' },
            { type: 'bug', prompt: 'This raises UnboundLocalError. Which line triggers it?', code: [{ text: 'total = 0', hasError: false }, { text: 'def add(n):', hasError: false }, { text: '    total += n', hasError: true }, { text: 'add(5)', hasError: false }], correctLine: 2, explanation: 'total += n is an assignment, so Python marks total as local for the whole function — then tries to read it before anything has been stored, and fails. The decision is made when the function is compiled, not when it runs, which is why the error appears even though a global total clearly exists. Declaring `global total` fixes it.', hint: 'Python decides local-or-global by looking for assignments. Which line assigns?' },
            { type: 'errordecode', prompt: 'What does this scope error actually want you to change?', errorText: "UnboundLocalError: cannot access local variable 'total' where it is not associated with a value", question: 'Fix?', options: ['Add "global total" or "nonlocal total"', 'Use total = 0 inside function', 'Import total', 'Delete total'], correct: 0, explanation: 'The declaration tells Python that total refers to the outer variable, so the assignment updates it instead of creating a local. Initialising total = 0 inside the function also stops the error, but it makes a fresh counter every call — the error goes away and the behaviour is still wrong, which is the more dangerous outcome.', hint: 'Two of these silence the error. Only one keeps the accumulated value.' },
            { type: 'realworld', prompt: 'Which one lets you build several multipliers, each with its own factor?', scenario: '🧠 You want double(x) and triple(x) from the same code.', options: [{ code: 'def make_multiplier(factor):\n    def multiply(x):\n        return x * factor\n    return multiply\ndouble = make_multiplier(2)\ntriple = make_multiplier(3)', label: 'Return an inner function' }, { code: 'factor = 2\ndef multiply(x):\n    return x * factor', label: 'Read a module-level factor' }, { code: 'def multiply(x, factor):\n    return x * factor', label: 'Take the factor each call' }, { code: 'double = lambda x: x * 2', label: 'Write one lambda per factor' }], correct: 0, explanation: 'Each call to make_multiplier creates a separate closure holding its own factor, so double and triple coexist. The module-level version has exactly one factor for the whole program — change it and every caller changes. Passing the factor every call works but is not the same thing: you cannot hand a one-argument function to something like map. And writing a lambda per factor does not scale past the ones you thought of.', hint: 'You need double AND triple alive at once. Which options can produce two independent functions?' },
        ],
        15: [
            { type: 'video', title: 'Functions Deep Dive', description: 'Parameters, defaults, *args, **kwargs, closures, decorators, and first-class functions.', duration: '3:30', thumbnail: '🎥' },
            { type: 'pair', prompt: 'Match each piece of function syntax to its job', pairs: [{ id: 1, left: 'def', right: 'Declare a function' }, { id: 2, left: 'return', right: 'Hand a value back' }, { id: 3, left: '*args', right: 'Collect extra positional args' }, { id: 4, left: '**kwargs', right: 'Collect extra keyword args' }], explanation: 'The single star packs loose positional arguments into a tuple; the double star packs named ones into a dict. They must appear in that order in a signature, after the ordinary parameters. And a function with no return still returns something — None.' },
            { type: 'trace', prompt: 'The decorator wraps greet — what prints?', code: [{ text: 'def shout(func):' }, { text: '    def wrapper(name):' }, { text: '        return func(name).upper()' }, { text: '    return wrapper' }, { text: '@shout' }, { text: 'def greet(name):' }, { text: '    return f"hello {name}"' }, { text: 'print(greet("Otter"))', highlight: true }], options: ['hello Otter', 'HELLO OTTER', 'Hello Otter', 'Error'], correct: 1, explanation: '@shout is shorthand for greet = shout(greet), so the name greet now points at wrapper. Calling it runs the original, then uppercases the whole result — including the "hello", which is why the answer is not "Hello Otter". Decorators are ordinary functions that take a function and return a replacement.', hint: 'Rewrite @shout as an assignment. What is the name greet actually bound to by the time it is called?' },
        ],
        16: [
            { type: 'trace', prompt: 'What does fib(5) return?', code: [{ text: 'def fib(n):' }, { text: '    if n <= 1: return n' }, { text: '    return fib(n-1) + fib(n-2)' }, { text: 'print(fib(5))', highlight: true }], options: ['3', '5', '8', '13'], correct: 1, explanation: 'The sequence from this definition is 0,1,1,2,3,5 — so fib(5) is 5. It is easy to be one place out: fib(4) is 3 and fib(6) is 8, which is what the neighbouring options are. Work upward from the base case rather than expanding the tree downward.', hint: 'List fib(0) through fib(5) in order, each one the sum of the two before it.' },
            { type: 'algostep', prompt: 'Expanding the fib(4) call tree', array: ['fib(4)', 'fib(3)+fib(2)', '(fib(2)+fib(1))+(fib(1)+fib(0))', '(1+1)+(1+0)=3'], step: 3, description: 'fib(4) = fib(3) + fib(2). Expanding...', question: 'What is fib(3)?', options: ['1', '2', '3', '5'], correct: 1, explanation: 'fib(3) = fib(2) + fib(1) = 1 + 1 = 2. Notice fib(1) gets computed twice even in this tiny tree — that duplication is what makes naive recursion exponential, and exactly what memoisation removes.', hint: 'Expand fib(3) one level and add the two base cases underneath.' },
            { type: 'errordecode', prompt: 'What is missing when recursion hits this error?', errorText: 'RecursionError: maximum recursion depth exceeded', question: 'Cause?', options: ['Missing base case', 'Wrong return type', 'Too many params', 'Import error'], correct: 0, explanation: 'Every recursive function needs a case that returns without recursing, and each call must move towards it. Miss either and the stack grows until Python stops you at roughly 1000 frames. Note the limit is Python protecting itself — the logic error is yours, and raising the limit only postpones the crash.', hint: 'What has to be true for the calls to eventually stop?' },
            { type: 'scramble', prompt: 'Assemble a recursive factorial', pieces: [{ id: 'a', text: 'def factorial(n):' }, { id: 'b', text: '    if n <= 1: return 1' }, { id: 'c', text: '    return n * factorial(n-1)' }], distractors: [{ id: 'd', text: '    return n + factorial(n)' }], correctOrder: ['a', 'b', 'c'], explanation: 'The base case has to come before the recursive call, or nothing ever stops it. The spare line breaks both halves at once: it adds where it should multiply, and calls factorial(n) rather than factorial(n-1) — so it never moves towards the base case and recurses forever.', hint: 'Two things every recursion needs: somewhere to stop, and a step that gets closer to it.' },
            { type: 'trace', prompt: 'What does sum_digits(123) return?', code: [{ text: 'def sum_digits(n):' }, { text: '    if n < 10: return n' }, { text: '    return n % 10 + sum_digits(n // 10)' }, { text: 'print(sum_digits(123))', highlight: true }], options: ['6', '123', '3', '12'], correct: 0, explanation: '% 10 peels off the last digit and // 10 removes it, so the calls are 3 + (2 + (1)) = 6. The pair of operators is the whole trick: one takes the digit, the other shrinks the number towards the base case. 3 would be the digit count, not the sum.', hint: 'Work out what n % 10 and n // 10 give for 123, then follow one level down.' },
            { type: 'realworld', prompt: 'Which of these problems contains a smaller copy of itself?', scenario: '🤔 Recursion fits when a problem breaks into the same problem, smaller.', options: [{ code: '# A folder contains files and more folders', label: 'Walking a directory tree' }, { code: '# Read a file one line at a time until EOF', label: 'Reading lines sequentially' }, { code: '# Print "Hello" five times', label: 'Repeating a fixed number of times' }, { code: '# Add two numbers together', label: 'A single arithmetic step' }], correct: 0, explanation: 'A folder contains folders, each handled by exactly the same procedure — the structure is self-similar, so the code can be too. The others are all flat: reading lines and counting to five are plain iteration, and adding two numbers has no subproblem at all. Recursion is not "a fancier loop", it is for structures that nest.', hint: 'For each one, ask whether solving it requires solving a smaller version of the identical problem.' },
        ],
        // ═══ CH5: DATA STRUCTURES I ⭐⭐ ═══
        17: [
            { type: 'trace', prompt: 'b was appended to — what is len(a)?', code: [{ text: 'a = [1, 2, 3]' }, { text: 'b = a' }, { text: 'b.append(4)' }, { text: 'print(len(a))', highlight: true }], options: ['3', '4', 'Error', '[1,2,3]'], correct: 1, explanation: 'b = a does not copy anything — it gives the same list a second name, so appending through either name changes the one object both point at. This is the single most consequential thing to understand about mutable values: pass a list to a function and the function can change it under you.', hint: 'Ask how many list objects exist after line 2. One, or two?' },
            { type: 'output', prompt: 'Which items does x[1:4] include?', code: [{ text: 'x = [10, 20, 30, 40, 50]' }, { text: 'print(x[1:4])' }], terminalOutput: '[20, 30, 40]', options: ['[10, 20, 30]', '[20, 30, 40]', '[20, 30, 40, 50]', '[10, 20, 30, 40]'], correct: 1, explanation: 'A slice starts at the first index and stops BEFORE the second — indices 1, 2, 3, which are 20, 30 and 40. Same exclusive-end rule as range. The count is easy to get right: 4 - 1 = 3 items, always.', hint: 'Count from 0, then remember which end the slice leaves out.' },
            { type: 'realworld', prompt: 'Which leaves a reversed list in rev AND original untouched?', scenario: '🔄 Both names must be usable as lists afterwards.', options: [{ code: 'rev = original[::-1]', label: 'Slice with a negative step' }, { code: 'original.reverse()', label: 'Call .reverse() on it' }, { code: 'rev = reversed(original)', label: 'Call reversed()' }, { code: 'rev = original.sort(reverse=True)', label: 'Sort in reverse' }], correct: 0, explanation: 'A slice always builds a new list, so original survives. .reverse() flips the list in place and returns None — original is destroyed and rev would be None. reversed() leaves original alone but hands back a lazy iterator, not a list: print it and you get <list_reverseiterator object>, and it can only be consumed once. .sort() also mutates in place and returns None, so rev ends up None again.', hint: 'Two of these return None. Of the remaining two, which gives you something you can print and index?' },
            { type: 'bug', prompt: 'Appending to b changed a. Which line is responsible?', code: [{ text: 'a = [1, 2, 3]', hasError: false }, { text: 'b = a', hasError: true }, { text: 'b.append(4)', hasError: false }, { text: 'print(a)', hasError: false }], correctLine: 1, explanation: 'The append is doing exactly what it says; the problem is one line earlier, where b was made another name for the same list rather than a copy. Writing b = a[:] or b = a.copy() there fixes it. Blaming the line where the symptom appears rather than the line that set it up is a habit worth breaking early.', hint: 'The line that misbehaves is not always the line that is wrong. Which line decided there would be only one list?' },
            { type: 'refactor', prompt: 'Which one gives you a list you can change independently?', originalCode: 'original = [1, 2, 3]\ncopy = original', options: [{ code: 'copy = original[:]', label: 'Slice the whole thing' }, { code: 'copy = original', label: 'Assign it across' }, { code: 'copy = list(original)[0:0]', label: 'Empty slice of a new list' }], correct: 0, explanation: 'A full slice builds a new list holding the same items — list(original) and original.copy() do the same. Plain assignment shares the object, which is the bug being fixed. The third does make a new list but slices nothing out of it, leaving you an empty one. Note all of these are SHALLOW: copy a list of lists and the inner lists are still shared, which is what copy.deepcopy is for.', hint: 'Two of these produce a separate object. Only one of those still has the items in it.' },
            { type: 'complexity', prompt: 'Which finds a duplicate faster in a huge list?', scenario: '🔍 nums has 1,000,000 items.', options: [{ code: 'for i in range(len(nums)):\n  for j in range(i+1, len(nums)):\n    if nums[i] == nums[j]:\n      return True', label: 'Nested loops', complexity: 'O(n²)' }, { code: 'seen = set()\nfor x in nums:\n  if x in seen:\n    return True\n  seen.add(x)', label: 'Hash set', complexity: 'O(n)' }], correct: 1, explanation: 'The set scans once and checks membership in O(1) → O(n). Nested loops compare every pair → O(n²): ~500 billion operations for 1M items.' },
            { type: 'complexity', prompt: 'Repeatedly checking if a value exists — which scales?', scenario: '🔁 The check runs thousands of times.', options: [{ code: 'if target in my_list:\n  ...', label: 'list membership', complexity: 'O(n)' }, { code: 'lookup = set(my_list)\nif target in lookup:\n  ...', label: 'set membership', complexity: 'O(1)' }], correct: 1, explanation: 'Building the set is a one-time O(n), but each lookup is O(1) vs O(n) for a list. For many repeated checks the set wins by a huge margin.' },
        ],
        18: [
            { type: 'trace', prompt: 'How many times does "a" appear in banana?', code: [{ text: 'word = "banana"' }, { text: 'freq = {}' }, { text: 'for c in word:' }, { text: '    freq[c] = freq.get(c, 0) + 1' }, { text: 'print(freq["a"])', highlight: true }], options: ['1', '2', '3', 'Error'], correct: 2, explanation: 'b-a-n-a-n-a has three a\'s. The real lesson is .get(c, 0): it returns the default when the key is absent, so the first sighting of a letter starts at 0 + 1 rather than raising KeyError. Plain freq[c] + 1 on a fresh dict is what the Error option is about.', hint: 'Spell banana out letter by letter. Then ask what .get does the very first time it sees each one.' },
            { type: 'refactor', prompt: 'Which one counts correctly without rescanning the string?', originalCode: 'freq = {}\nfor c in word:\n    if c in freq: freq[c] += 1\n    else: freq[c] = 1', options: [{ code: 'from collections import Counter\nfreq = Counter(word)', label: 'Use Counter' }, { code: 'freq = {c: word.count(c) for c in word}', label: 'Comprehension calling count()' }, { code: 'freq = dict.fromkeys(word, 0)', label: 'Build with fromkeys' }], correct: 0, explanation: 'Counter walks the string once and is written for exactly this. The comprehension gives the right numbers but calls count() for every character, and count() itself scans the whole string — so it is quadratic, fine for a word and painful for a file. fromkeys sets every letter to 0 and never counts anything, so the answer is simply wrong.', hint: 'Two of these produce correct counts. Work out how many times each one walks the string.' },
            { type: 'fillgap', prompt: 'Return True only when the two words use the same letters, same counts', codeParts: [{ text: 'def is_anagram(a, b):\n    return ', type: 'fixed' }, { text: 'sorted(a) == sorted(b)', type: 'gap', id: 'g1' }, { text: '\n\nis_anagram("listen", "silent")   # True\nis_anagram("aab", "abb")         # must be False', type: 'fixed' }], bank: ['sorted(a) == sorted(b)', 'a == b', 'len(a) == len(b)', 'set(a) == set(b)'], correctFill: { g1: 'sorted(a) == sorted(b)' }, explanation: 'Sorting puts both words in the same canonical order, so it compares letters AND how many of each. The other three all say True for "aab" and "abb": set() throws the counts away, len() only compares length, and == is just equality. The second example in the code is there precisely to separate them.', hint: 'Every option returns True for listen/silent. Test each one against aab/abb instead.' },
            { type: 'output', prompt: 'What kind of thing does this build?', code: [{ text: 'squares = {x: x**2 for x in range(1,5)}' }, { text: 'print(squares)' }], terminalOutput: '{1: 1, 2: 4, 3: 9, 4: 16}', options: ['{1:1, 2:4, 3:9, 4:16}', '[1, 4, 9, 16]', '{1,4,9,16}', 'Error'], correct: 0, explanation: 'The colon inside the braces is what makes it a dict comprehension rather than a set one — key on the left, value on the right. Drop the x: and you would get the set {1,4,9,16}; use square brackets and you would get the list. Same syntax family, three different containers, distinguished by punctuation alone.', hint: 'Braces alone are not enough to tell you the type. Look for the colon.' },
            { type: 'realworld', prompt: 'Which one reports that "the" appears most often?', scenario: '📝 words = ["the", "cat", "the", "dog", "the"]', options: [{ code: 'most = Counter(words).most_common(1)', label: 'Counter, then most_common' }, { code: 'most = max(words)', label: 'max() over the list' }, { code: 'most = max(words, key=words.count)', label: 'max() keyed by count' }, { code: 'most = words[0]', label: 'The first element' }], correct: 0, explanation: 'most_common(1) returns [("the", 3)] — the word and its count, which is what was asked for. max(words) compares the strings themselves and returns "the" alphabetically, right for the wrong reason and wrong the moment a word like "zebra" appears. max keyed by count does find the right word but gives no count and rescans the list for every element. words[0] just happens to be "the" here.', hint: 'Three of these return "the" on this data. Which one would still be right if the list started with "zebra"?' },
            { type: 'pair', prompt: 'Match each set operator to what it returns', pairs: [{ id: 1, left: 'a | b', right: 'In either one' }, { id: 2, left: 'a & b', right: 'In both' }, { id: 3, left: 'a - b', right: 'In a but not b' }, { id: 4, left: 'a ^ b', right: 'In exactly one' }], explanation: 'These are the same symbols as the bitwise operators, doing the analogous job on membership. The one people forget is ^ — everything that is in one set or the other but not both, which is union minus intersection. Note - is the only one that is not symmetric: a - b and b - a differ.' },
        ],
        19: [
            { type: 'scramble', prompt: 'Assemble a duplicate finder', pieces: [{ id: 'a', text: 'def find_dupes(lst):' }, { id: 'b', text: '    seen = set()' }, { id: 'c', text: '    dupes = set()' }, { id: 'd', text: '    for x in lst:' }, { id: 'e', text: '        if x in seen: dupes.add(x)' }, { id: 'f', text: '        seen.add(x)' }, { id: 'g', text: '    return list(dupes)' }], distractors: [{ id: 'h', text: '    return lst' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The order of the two lines inside the loop is the whole algorithm: check membership BEFORE adding, or every item looks like a duplicate of itself. Both sets have to exist before the loop. dupes is a set rather than a list so an item appearing three times is still reported once.', hint: 'If you add x to seen first, what does the very next line say about x?' },
            { type: 'trace', prompt: 'What does a & b give for these two sets?', code: [{ text: 'a = {1, 2, 3, 4}' }, { text: 'b = {3, 4, 5, 6}' }, { text: 'print(a & b)', highlight: true }], options: ['{3, 4}', '{1,2,3,4,5,6}', '{1,2}', '{5,6}'], correct: 0, explanation: '& keeps only what appears in both, which is 3 and 4. The other options are the neighbouring operators: | would give everything, a - b gives {1,2}, and b - a gives {5,6} — worth knowing all four are on the same keyboard row of this exercise.', hint: 'Which numbers appear in both lines above?' },
            { type: 'realworld', prompt: 'Which one removes duplicates AND keeps the original order?', scenario: '📋 [3, 1, 4, 1, 5, 9, 2, 6, 5] → [3, 1, 4, 5, 9, 2, 6]', options: [{ code: 'seen = set()\nresult = []\nfor x in lst:\n    if x not in seen:\n        seen.add(x)\n        result.append(x)', label: 'Track seen, append the rest' }, { code: 'result = list(set(lst))', label: 'Round-trip through a set' }, { code: 'result = sorted(set(lst))', label: 'Sort a set' }, { code: 'result = list(dict.fromkeys(lst))', label: 'Round-trip through dict keys' }], correct: 0, explanation: 'The explicit loop is the version that states its intent and works on any Python. Going through a set drops the order — sets have none. Sorting gives a defined order, just not the original one. The dict trick does actually work and preserves order, but only because dicts have kept insertion order since 3.7; it is a clever idiom rather than something a reader can see the correctness of at a glance.', hint: 'Three of these give the right SET of numbers. Only some of them give the right sequence — and one is right by an accident of language history.' },
            { type: 'output', prompt: 'Both dicts have a "y" — which value survives?', code: [{ text: 'a = {"x": 1, "y": 2}' }, { text: 'b = {"y": 3, "z": 4}' }, { text: 'merged = {**a, **b}' }, { text: 'print(merged["y"])' }], terminalOutput: '3', options: ['2', '3', '[2,3]', 'Error'], correct: 1, explanation: 'Unpacking happens left to right, so b is applied second and its y overwrites a\'s. Swap the order and you get 2. Nothing is combined and nothing errors — a key can only hold one value, so a silent overwrite is the whole behaviour. This is why merge order matters when layering config over defaults.', hint: 'Which dict is written into the new one last?' },
        ],
        20: [
            { type: 'pair', prompt: 'Match each container to what it is for', pairs: [{ id: 1, left: 'List', right: 'Ordered, reachable by index' }, { id: 2, left: 'Set', right: 'No duplicates, fast membership' }, { id: 3, left: 'Dict', right: 'Look a value up by key' }, { id: 4, left: 'Tuple', right: 'A fixed group that cannot change' }], explanation: 'Picking the right one is mostly about the question you will ask most often. "Is x in here?" is O(n) on a list and O(1) on a set or dict — the single biggest easy win in most beginner code. Tuples being immutable is also why they can be dict keys and lists cannot.' },
            { type: 'trace', prompt: 'After unpacking, what does x + y give?', code: [{ text: 'point = (3, 7)' }, { text: 'x, y = point' }, { text: 'print(x + y)', highlight: true }], options: ['(3,7)', '10', '37', 'Error'], correct: 1, explanation: 'Unpacking binds x to 3 and y to 7, so + adds two ints and gives 10. "37" would be the answer if they were strings, where + concatenates — the operator does completely different jobs depending on type, and nothing warns you. Unpacking requires the counts to match: x, y, z = point would raise ValueError.', hint: 'What type are x and y after line 2? That decides what + does.' },
            { type: 'realworld', prompt: 'You will look up a number by name thousands of times. Which shape?', scenario: '📱 Given "Ali", return "555-1234".', options: [{ code: 'phonebook = {"Ali": "555-1234", "Ece": "555-5678"}', label: 'Dict keyed by name' }, { code: 'phonebook = [("Ali","555-1234"), ("Ece","555-5678")]', label: 'List of name/number pairs' }, { code: 'phonebook = {"555-1234", "555-5678"}', label: 'Set of numbers' }, { code: 'phonebook = ["Ali", "555-1234", "Ece", "555-5678"]', label: 'Flat alternating list' }], correct: 0, explanation: 'A dict hashes the name straight to the number, so lookup cost does not grow with the phone book. The list of pairs holds the same information but has to be scanned, which is fine for ten contacts and hopeless for ten thousand. The set has no names at all to look up by. The flat list technically encodes it, but every read means index arithmetic and one insertion in the wrong place corrupts every pair after it.', hint: 'Two of these contain all the information. Ask what each one costs per lookup, and what happens as the book grows.' },
        ],
}
