/* ══════════════════════════════════════════════════
   JAVA EXERCISES — Journey Nodes CH1-CH5
   ══════════════════════════════════════════════════ */
export const javaExercises = {
    // ═══ CH1: BASICS ═══
    1: [
        { type: 'trace', prompt: 'What is the value of `count`?', code: [{ text: 'int count = 0;' }, { text: 'for (int i = 0; i < 5; i++) {' }, { text: '    if (i % 2 == 0) {' }, { text: '        count++;' }, { text: '    }' }, { text: '}' }, { text: 'System.out.println(count);', highlight: true }], options: ['2', '3', '5', '4'], correct: 1, explanation: 'Five values of i (0..4), three even (0, 2, 4) — the usual slip is forgetting 0 counts as even. Note count++ is the idiomatic Java increment; count += 1 is identical in effect.', hint: 'Write down what i is on each pass, then tick the even ones.' },
        { type: 'realworld', prompt: 'Which code counts total items in a cart?', scenario: '🛒 Cart: 3 apples, 2 oranges, 1 banana.', options: [{ code: 'int[] cart = {3, 2, 1};\nint total = Arrays.stream(cart).sum();', label: 'Stream sum' }, { code: 'int cart = 3 + 2 + 1;\nint total = String.valueOf(cart).length();', label: 'length on string' }, { code: 'String cart = "3 2 1";\nint total = cart.length();', label: 'String length' }, { code: 'Set<Integer> cart = Set.of(3,2,1);\nint total = Collections.max(cart);', label: 'Max of set' }], correct: 0, explanation: 'Arrays.stream(cart).sum() adds the quantities: 6. The length-based options count characters or elements — kinds, not items. All compile; only one answers the question, and nothing crashes to warn you.', hint: 'Two of these run fine and still give the wrong number. Which answers "how many items"?' },
        { type: 'pair', prompt: 'Match Java concepts', pairs: [{ id: 1, left: 'int', right: 'Whole number' }, { id: 2, left: 'String', right: 'Text data' }, { id: 3, left: 'boolean', right: 'true or false' }, { id: 4, left: 'double', right: 'Decimal number' }], explanation: 'Java declares types up front — static typing, and it is why the compiler catches whole bug classes at build time that Python and JS discover at runtime. boolean is its own type: no truthiness, an if takes a boolean and nothing else.' },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'int x = 7;' }, { text: 'int y = 2;' }, { text: 'System.out.println(x / y + " " + x % y);' }], terminalOutput: '3 1', options: ['3.5 1', '3 1', '3.5 0', '3 0'], correct: 1, explanation: 'int / int is integer division in Java: 7/2 is 3, no floor call needed — the fraction is simply discarded. That silent truncation is a feature here and a bug in average calculations, where one operand must be cast to double first.', hint: 'Both operands are int. What does / do with the fraction, and is that automatic?' },
        { type: 'fillgap', prompt: 'Complete: swap two variables', codeParts: [{ text: 'int a = 5;\nint b = 10;\n', type: 'fixed' }, { text: 'int temp = a; a = b; b = temp;', type: 'gap', id: 'g1' }], bank: ['int temp = a; a = b; b = temp;', 'a = b; b = a;', 'swap(a, b);', 'a == b;'], correctFill: { g1: 'int temp = a; a = b; b = temp;' }, explanation: 'Java has no tuple swap, so the temp variable is the idiom: save one value before the overwrite destroys it. a = b; b = a fails because the first assignment already lost the old a — after it, both variables hold b\'s value.', hint: 'Step through a = b; b = a by hand. What does a hold when the second statement runs?' },
        { type: 'scramble', prompt: 'Build code to calculate BMI', pieces: [{ id: 'a', text: 'double weight = 70;' }, { id: 'b', text: 'double height = 1.75;' }, { id: 'c', text: 'double bmi = weight / (height * height);' }, { id: 'd', text: 'System.out.printf("%.1f%n", bmi);' }], distractors: [{ id: 'e', text: 'double bmi = weight * height;' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'Declarations before use, and the formula divides by height squared — height * height, since ** does not exist in Java; Math.pow works too but returns double anyway. printf\'s %.1f rounds for display without changing the stored value.', hint: 'Order the lines so no name is used before its declaration. What does Java lack that Python has for powers?' },
    ],
    2: [
        { type: 'bug', prompt: 'Find the syntax error', code: [{ text: 'public static String greet(String name) {', hasError: false }, { text: '    String msg = "Hello " + name;', hasError: false }, { text: '    System.out.println(msg', hasError: true }, { text: '    return msg;', hasError: false }], correctLine: 2, explanation: 'println(msg never closes its parenthesis, and javac reports "\')\' expected" — often on the NEXT line, where it finally gave up waiting. The semicolon is missing too; fixing the parenthesis surfaces that second error, a common cascade.', hint: 'Count opening and closing brackets on each line.' },
        { type: 'errordecode', prompt: 'Decode this error', errorText: 'Main.java:3: error: \')\' expected\n    System.out.println(msg\n                         ^\n1 error', question: 'What caused this?', options: ['Missing closing parenthesis and semicolon', 'Undefined variable', 'Wrong indentation', 'Invalid string'], correct: 0, explanation: '"\')\' expected" with the caret under the gap says the parser wanted a closing parenthesis before the line ended. javac errors name the missing TOKEN, which is more helpful than it looks: the fix is literally to supply what it asked for, at or before the caret.', hint: 'What token does the message name, and where does the caret point?' },
        { type: 'refactor', prompt: 'Which is the cleanest?', originalCode: 'int x = 10;\nString r;\nif (x > 5) {\n    r = "big";\n} else {\n    r = "small";\n}\nSystem.out.println(r);', options: [{ code: 'int x = 10;\nString r = x > 5 ? "big" : "small";\nSystem.out.println(r);', label: 'Ternary expression' }, { code: 'int x = 10;\nString r = "";\nif (x > 5) r = "big";\nif (x <= 5) r = "small";', label: 'Two ifs' }, { code: 'System.out.println(10>5 ? "big":"small");', label: 'Inline ternary' }], correct: 0, explanation: 'The ternary assigns once and the variable can never be left unset — which in Java is not just style: the compiler REJECTS reading a possibly-unassigned local. Two ifs re-test the same value; the inline version throws the result away.', hint: 'Which version can never leave r unassigned — and why does Java care at compile time?' },
        { type: 'bug', prompt: 'Why does this give wrong comparison?', code: [{ text: 'String a = new String("hello");', hasError: false }, { text: 'String b = new String("hello");', hasError: false }, { text: 'if (a == b) {', hasError: true }, { text: '    System.out.println("Equal");', hasError: false }], correctLine: 2, explanation: '== on objects compares references, and two new String(...) calls build two distinct objects — so == is false even though the text matches. equals() compares contents. With LITERALS the string pool would make == true, which is why this bug appears and disappears confusingly.', hint: 'Are there one or two String objects here? What does == check for objects?' },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'String x = "5";' }, { text: 'int y = 3;' }, { text: 'System.out.println(x.repeat(y));' }], terminalOutput: '555', options: ['15', '555', '53', 'Error'], correct: 1, explanation: 'repeat(3) copies the string: "555" (Java 11+). x * y would not compile at all — Java refuses arithmetic on String, where JS coerces and Python repeats. Three languages, three answers to the same expression: this is the strictest.', hint: 'Is x text or a number? What would the compiler say about x * y?' },
        { type: 'trace', prompt: 'What is the type of result?', code: [{ text: 'int a = 10;' }, { text: 'int b = 3;' }, { text: 'double result = (double) a / b;' }, { text: 'System.out.println(result);', highlight: true }], options: ['3', '3.3333...', 'int', 'Error'], correct: 1, explanation: '(double) a / b casts BEFORE dividing, so the division is floating-point: 3.333… Cast placement is everything — (double)(a / b) divides as ints FIRST, giving 3.0. The parentheses decide which operation the cast touches.', hint: 'Does the cast apply to a, or to the whole division? Move the parentheses mentally.' },
    ],
    3: [
        { type: 'concept', chapter: 1 },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'String name = "Rheo";' }, { text: 'int age = 3;' }, { text: 'System.out.println(((Object)age).getClass().getSimpleName());' }], terminalOutput: 'Integer', options: ['"String"', '"Integer"', '3', '"int"'], correct: 1, explanation: 'getClass().getSimpleName() on a boxed int says Integer — the wrapper class, capital I. Primitives box into wrappers when treated as objects; int and Integer are genuinely different types, and that gap (autoboxing) is where subtle Java bugs live.', hint: 'What happens to a primitive int when you call a method on it?' },
        { type: 'pair', prompt: 'Match Java types', pairs: [{ id: 1, left: 'int', right: '42' }, { id: 2, left: 'double', right: '3.14' }, { id: 3, left: 'String', right: '"hello"' }, { id: 4, left: 'boolean', right: 'true' }], explanation: 'The literal tells the type: bare digits int, a decimal point double, quotes String, true/false boolean. Unlike Python and JS, these are declared and checked at compile time — mismatches never reach runtime.' },
    ],
    4: [
        { type: 'pair', prompt: 'Match operators', pairs: [{ id: 1, left: '==', right: 'Value equality (primitives)' }, { id: 2, left: '.equals()', right: 'Object equality' }, { id: 3, left: 'Math.pow()', right: 'Power' }, { id: 4, left: '/', right: 'Integer division (int/int)' }], explanation: '== is safe on primitives and treacherous on objects — that split is THE Java equality lesson: .equals for content, == for identity or primitives. Math.pow covers exponentiation (no ** operator), and int/int division truncates by design.' },
        { type: 'trace', prompt: 'What is the output?', code: [{ text: 'int x = 17;' }, { text: 'System.out.println(x % 5 + " " + x / 5);', highlight: true }], options: ['2 3', '3 2', '2 4', '17 5'], correct: 0, explanation: '17 = 5 × 3 + 2, so % gives 2 and / gives 3 — integer division, no floor needed. The print order is % first; swapping them is what the "3 2" option checks.', hint: 'Work out 17 ÷ 5 as whole part and remainder, then match them to the printed order.' },
        { type: 'fillgap', prompt: 'Complete: convert Celsius to Fahrenheit', codeParts: [{ text: 'double celsius = 25;\ndouble fahrenheit = ', type: 'fixed' }, { text: 'celsius * 9.0/5 + 32;', type: 'gap', id: 'g1' }, { text: '\nSystem.out.println(fahrenheit);', type: 'fixed' }], bank: ['celsius * 9.0/5 + 32;', 'celsius + 32;', 'celsius * 1.8;', 'celsius / 5 * 9;'], correctFill: { g1: 'celsius * 9.0/5 + 32;' }, explanation: 'The 9.0 matters as much as the formula: with all ints, 9/5 would truncate to 1 before multiplying. Writing 9.0 forces double arithmetic. Both scale (× 9/5) and offset (+ 32) are needed; each distractor fixes only one.', hint: 'Check candidates at 0°C and 100°C. And ask why the 9 is written 9.0.' },
    ],
    // ═══ CH2: FLOW CONTROL ═══
    5: [
        { type: 'trace', prompt: 'x is 15. Which letter gets printed?', code: [{ text: 'int x = 15;' }, { text: 'if (x > 20) {' }, { text: '    System.out.println("A");' }, { text: '} else if (x > 10) {' }, { text: '    if (x % 2 == 0) {' }, { text: '        System.out.println("B");' }, { text: '    } else {' }, { text: '        System.out.println("C");', highlight: true }, { text: '    }' }, { text: '}' }], options: ['A', 'B', 'C', 'Nothing'], correct: 2, explanation: 'Two decisions, not one. 15 > 20 is false so the else-if takes over, and inside it 15 % 2 is 1, not 0 — so the inner else runs and prints C. "Nothing" would need every branch to fail, which cannot happen once a chain ends in else.', hint: 'Pick the outer branch first, then work out which side of the inner if you land on.' },
        { type: 'bug', prompt: 'An 18-year-old is told they cannot vote. Which line is wrong?', code: [{ text: 'int age = 18;', hasError: false }, { text: 'if (age > 18) {', hasError: true }, { text: '    System.out.println("Can vote");', hasError: false }], correctLine: 1, explanation: 'The rule is "18 and over", but > 18 excludes exactly the boundary the rule is about. It needs >=. Off-by-one on a boundary is the most common logic bug there is, and it stays invisible until someone tests the boundary value itself.', hint: 'Substitute 18 into the comparison and read it out loud.' },
        { type: 'output', prompt: 'a is 0. Does the division ever happen?', code: [{ text: 'int a = 0;' }, { text: 'int b = 5;' }, { text: 'boolean result = (a != 0) && (b/a > 1);' }, { text: 'System.out.println(result);' }], terminalOutput: 'false', options: ['false', 'ArithmeticException', 'true', '0'], correct: 0, explanation: '&& short-circuits: (a != 0) is false, so the right-hand side never runs and b/a is never evaluated. That matters here because integer division by zero in Java really does throw ArithmeticException — the guard is the only thing preventing it. Swap && for & and you lose the short-circuit and get the exception. Also note Java\'s && returns a boolean, so the answer is false, not 0.', hint: 'Two questions: does the right side run at all, and what would happen if it did?' },
        { type: 'scramble', prompt: 'Assemble a grade calculator', pieces: [{ id: 'a', text: 'int score = 75;' }, { id: 'b', text: 'String grade;' }, { id: 'c', text: 'if (score >= 90) grade = "A";' }, { id: 'd', text: 'else if (score >= 80) grade = "B";' }, { id: 'e', text: 'else if (score >= 70) grade = "C";' }, { id: 'f', text: 'else grade = "F";' }, { id: 'g', text: 'System.out.println(grade);' }], distractors: [{ id: 'h', text: 'if (score == 90) grade = "A";' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The order of the else-if tests IS the logic: each only runs when everything above it failed. Put >= 70 before >= 80 and a score of 95 comes out as a C. The final else is not optional in Java either — without it the compiler rejects the println, because grade might not have been initialised on every path. The spare line uses == 90, matching only that single value.', hint: 'The thresholds have to descend. Then ask why Java insists on the else being there at all.' },
        { type: 'trace', prompt: 'n is 0. What ends up in `label`?', code: [{ text: 'int n = 0;' }, { text: 'String label = n > 0 ? "positive" : n < 0 ? "negative" : "zero";' }, { text: 'System.out.println(label);', highlight: true }], options: ['positive', 'negative', 'zero', 'Error'], correct: 2, explanation: 'Read it left to right: n > 0 fails, so the colon half is evaluated — and that half is itself another ternary. n < 0 also fails, leaving "zero". There is no special chaining syntax, just one ternary nested inside another.', hint: 'Rewrite it as a nested if/else on paper, then follow n = 0 down.' },
        { type: 'realworld', prompt: 'Which one locks the user out after three wrong passwords?', scenario: '🔐 Three attempts, then stop asking.', options: [{ code: 'int attempts = 0;\nwhile (attempts < 3) {\n    String pwd = scanner.nextLine();\n    if (pwd.equals(secret)) break;\n    attempts++;\n}', label: 'while with a counter' }, { code: 'for (int i=0; i<3; i++) {\n    String pwd = scanner.nextLine();\n    if (!pwd.equals(secret)) continue;\n}', label: 'for with continue' }, { code: 'int attempts = 0;\nwhile (attempts < 3) {\n    String pwd = scanner.nextLine();\n    if (pwd.equals(secret)) break;\n}', label: 'while, break on success' }, { code: 'while (true) {\n    String pwd = scanner.nextLine();\n    if (pwd.equals(secret)) break;\n}', label: 'loop until correct' }], correct: 0, explanation: 'Only the first both stops early on success and counts failures, so it ends after three wrong tries. The third looks almost identical but never runs attempts++ — the condition stays true forever and it asks endlessly. The last has no limit at all, and the continue version does nothing on a wrong password since continue just moves to the next iteration.', hint: 'For each one, ask what makes the loop stop when the password is always wrong.' },
    ],
    6: [
        { type: 'trace', prompt: 'Same text, two objects — what do == and equals say?', code: [{ text: 'String a = "hello";' }, { text: 'String b = new String("hello");' }, { text: 'System.out.println(a == b);', highlight: true }, { text: 'System.out.println(a.equals(b));' }], options: ['true true', 'false true', 'true false', 'false false'], correct: 1, explanation: '== compares references — is this the same object? — while equals compares contents. The literal "hello" lives in the string pool, but new String() deliberately builds a separate object, so == is false and equals is true. Had b also been the literal "hello", both would be true because the pool hands back the same object. This is why you never compare strings with == in Java.', hint: 'One operator asks "same object?", the other asks "same characters?". Which is which?' },
        { type: 'refactor', prompt: 'Which rewrite is still safe when str is null?', originalCode: 'if (str != null && str.length() > 0) {\n    doSomething();\n}', options: [{ code: 'if (str != null && !str.isEmpty()) {\n    doSomething();\n}', label: 'null check then isEmpty()' }, { code: 'if (str != "") {\n    doSomething();\n}', label: 'compare against ""' }, { code: 'if (str.length() > 0) {\n    doSomething();\n}', label: 'length() alone' }], correct: 0, explanation: 'The first keeps the null guard and && short-circuits, so isEmpty() is only called on a real string. The second compares references rather than contents, so it is true even for a string that reads "" if it was built at runtime — and it does not guard null either. The third drops the guard entirely and throws NullPointerException the moment str is null, which is exactly the case the original was protecting against.', hint: 'Feed null into all three and see which one survives.' },
        { type: 'fillgap', prompt: 'Return true when n is between 1 and 100, ends included', codeParts: [{ text: 'static boolean inRange(int n) {\n    return ', type: 'fixed' }, { text: 'n >= 1 && n <= 100;', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['n >= 1 && n <= 100;', '1 <= n <= 100;', 'n >= 1 || n <= 100;', 'Range.of(1, 100).contains(n);'], correctFill: { g1: 'n >= 1 && n <= 100;' }, explanation: 'Java has no chained comparison: `1 <= n <= 100` would try to compare a boolean with an int, so it does not even compile — the compiler catches it, unlike JavaScript where the same line silently evaluates to true. Swapping && for || is always true for every number. And Range.of is not in the JDK at all; that is a Guava-flavoured invention.', hint: 'One of these fails at compile time, one is always true, one does not exist. Sort them out.' },
        { type: 'pair', prompt: 'Match each type to the value a field gets before you assign one', pairs: [{ id: 1, left: 'int', right: '0' }, { id: 2, left: 'boolean', right: 'false' }, { id: 3, left: 'String', right: 'null' }, { id: 4, left: 'double', right: '0.0' }], explanation: 'Primitives default to a zero-like value; reference types default to null. This applies to fields and array slots, not local variables — a local you read before assigning is a compile error, which is Java catching the mistake for you.' },
        { type: 'output', prompt: 'Optional wrapping a null — what comes out?', code: [{ text: 'Optional<String> opt = Optional.ofNullable(null);' }, { text: 'String val = opt.orElse("default");' }, { text: 'System.out.println(val);' }], terminalOutput: 'default', options: ['null', 'default', 'Error', 'Optional.empty'], correct: 1, explanation: 'ofNullable accepts null and produces an empty Optional, so orElse supplies the fallback and you get "default". Note the difference from Optional.of(null), which throws NullPointerException immediately — that is the "Error" option, and it is the right answer to a slightly different question.', hint: 'Two steps: what does ofNullable make from null, and what does orElse do with that?' },
    ],
    7: [
        { type: 'terminal', prompt: 'Store a name in a variable, then print it', expectedCommands: ['String name = "Otter";', 'System.out.println(name);'], hint: 'Two lines: Java needs the type on the declaration, then hand the variable to println.', terminalHistory: [{ type: 'system', text: '> Daily Challenge' }] },
        { type: 'trace', prompt: 'What does `result` hold after the loop?', code: [{ text: 'String result = "";' }, { text: 'for (char c : "hello".toCharArray()) {' }, { text: '    result += Character.toUpperCase(c);' }, { text: '}' }, { text: 'System.out.println(result);', highlight: true }], options: ['hello', 'HELLO', 'Hello', 'hELLO'], correct: 1, explanation: 'The enhanced for walks each character and appends it uppercased, so all five end up uppercase. Worth knowing what this costs: strings are immutable, so += builds a brand new String every iteration. For five characters nobody cares; in a loop over a large input you want StringBuilder.', hint: 'Write down result after each of the five passes.' },
        { type: 'output', prompt: 'printf with two placeholders — what prints?', code: [{ text: 'String name = "Otter";' }, { text: 'int age = 5;' }, { text: 'System.out.printf("%s is %d in human years%n", name, age*7);' }], terminalOutput: 'Otter is 35 in human years', options: ['Otter is 35 in human years', 'Otter is 5 in human years', '%s is %d', 'Error'], correct: 0, explanation: 'The arguments are evaluated before printf sees them, so age*7 arrives as 35 and %d prints it. %s takes the string, %d an integer — pass age*7 to a %s and you would get a mismatch exception. %n is the platform newline, which is why there is no \\n in the text.', hint: 'The arguments are evaluated first. What is age*7 by the time printf runs?' },
    ],
    8: [
        { type: 'concept', chapter: 2 },
        { type: 'trace', prompt: 'status is 404. What does this switch expression return?', code: [{ text: 'int status = 404;' }, { text: 'String msg = switch (status) {' }, { text: '    case 200 -> "OK";' }, { text: '    case 404 -> "Not Found";' }, { text: '    default -> "Unknown";' }, { text: '};' }, { text: 'System.out.println(msg);', highlight: true }], options: ['OK', 'Not Found', 'Unknown', 'Error'], correct: 1, explanation: 'This is a switch expression, not a statement: it evaluates to a value that gets assigned to msg. The arrow form has no fallthrough, so no break is needed and only the matching arm runs. It also requires default to be exhaustive — drop it and the code will not compile, which is a real improvement on the old colon form.', hint: 'Find the matching arm. Then ask why there is no break anywhere and why the semicolon after } is needed.' },
    ],
    // ═══ CH3: LOOPS ═══
    9: [
        { type: 'scramble', prompt: 'Print the numbers 1 to 5, one per line', pieces: [{ id: 'a', text: 'for (int i = 1; i <= 5; i++) {' }, { id: 'b', text: '    System.out.println(i);' }, { id: 'c', text: '}' }], distractors: [{ id: 'd', text: '    System.out.println(i + 1);' }, { id: 'e', text: 'while (i < 5) {' }], correctOrder: ['a', 'b', 'c'], explanation: 'The three parts of a for header do the whole job: start at 1, keep going while i <= 5, add one each pass. The spare while line would not even compile — i is declared inside the for header, so it does not exist outside it. Printing i + 1 would give 2 to 6.', hint: 'Work out which numbers the header actually produces before choosing what to print.' },
        { type: 'bug', prompt: 'This should print 1 through 10 but stops at 9. Which line?', code: [{ text: 'for (int i = 1; i < 10; i++) {', hasError: true }, { text: '    System.out.println(i);', hasError: false }, { text: '}', hasError: false }], correctLine: 0, explanation: 'The condition is checked before each pass, so with i < 10 the loop quits the moment i reaches 10 — the last value that runs is 9. Reaching 10 needs i <= 10. Choosing between < and <= in a loop header is where most off-by-one bugs come from.', hint: 'Ask what i is on the pass that does NOT run, then whether that value should have printed.' },
        { type: 'trace', prompt: 'How many times does the loop body run?', code: [{ text: 'int n = 64;' }, { text: 'int count = 0;' }, { text: 'while (n > 1) {' }, { text: '    n = n / 2;' }, { text: '    count++;' }, { text: '}' }, { text: 'System.out.println(count);', highlight: true }], options: ['5', '6', '7', '32'], correct: 1, explanation: 'n halves each pass: 64→32→16→8→4→2→1, six steps. Since 64 is 2⁶ the answer is log₂(64) = 6 — the same shape that makes binary search O(log n). Note n / 2 on two ints is integer division and truncates, which is exactly what makes the sequence terminate at 1.', hint: 'Write the sequence of values n takes and count the arrows, not the numbers.' },
        { type: 'fillgap', prompt: 'Make total end up as 10 — the sum of 1 through 4', codeParts: [{ text: 'int total = 0;\nint[] nums = ', type: 'fixed' }, { text: '{1, 2, 3, 4}', type: 'gap', id: 'g1' }, { text: ';\nfor (int num : nums) {\n    total += num;\n}', type: 'fixed' }], bank: ['{1, 2, 3, 4}', 'new int[4]', 'Arrays.asList(1,2,3,4)', '"1234"'], correctFill: { g1: '{1, 2, 3, 4}' }, explanation: 'The brace form is the array initialiser shorthand, valid exactly here on a declaration. new int[4] compiles too — but Java zero-fills it, so the loop runs four times and total stays 0, which is the dangerous one because nothing complains. The other two do not compile at all: List<Integer> is not int[], and neither is a String.', hint: 'Two of these will not compile. Of the two that do, which actually holds the numbers 1 to 4?' },
        { type: 'output', prompt: 'What does break leave printed?', code: [{ text: 'for (int i = 0; i < 5; i++) {' }, { text: '    if (i == 3) break;' }, { text: '    System.out.print(i + " ");' }, { text: '}' }], terminalOutput: '0 1 2 ', options: ['0 1 2 ', '0 1 2 3', '0 1 2 3 4', '3'], correct: 0, explanation: 'break leaves the loop immediately, so when i reaches 3 the print below it never runs — 3 is never shown. Move the print above the if and you would get "0 1 2 3". Compare with continue, which abandons only that one pass and keeps looping.', hint: 'The order of the two statements inside the loop is the whole answer.' },
        { type: 'realworld', prompt: 'Which one actually leaves 9 in `best`?', scenario: '📊 int[] nums = {3, 7, 2, 9, 4} — you want the largest.', options: [{ code: 'int best = Arrays.stream(nums).max().getAsInt();', label: 'Stream max()' }, { code: 'int best = nums[0];\nfor (int n : nums) {\n    if (n < best) best = n;\n}', label: 'Scan, keeping the smaller' }, { code: 'Arrays.sort(nums);\nint best = nums[0];', label: 'Sort, take the first' }, { code: 'int best = nums.length;', label: 'Array length' }], correct: 0, explanation: 'max() on an IntStream returns an OptionalInt because the array might be empty; getAsInt unwraps it. The scan looks right at a glance but compares with < , so it finds the minimum — reading the direction of a comparison is the whole skill here. Sorting then taking index 0 also gives the smallest, and worse, Arrays.sort mutates the caller\'s array in place. The length is 5, not a value from the array at all.', hint: 'Three of these produce a number. Only one of them is the largest — check each comparison direction carefully.' },
    ],
    10: [
        { type: 'trace', prompt: 'How many lines does this nested loop print?', code: [{ text: 'for (int i = 0; i < 3; i++) {' }, { text: '    for (int j = 0; j < 4; j++) {' }, { text: '        System.out.println(i + " " + j);', highlight: true }, { text: '    }' }, { text: '}' }], options: ['7', '12', '9', '16'], correct: 1, explanation: 'The inner loop runs fully for every single pass of the outer one, so it is 3 × 4 = 12 — a product, not a sum. Answering 7 is adding them; 9 and 16 are squaring one of them. This is also why nested loops over the same collection are O(n²).', hint: 'For each value of i, how many times does j run? Then combine.' },
        { type: 'output', prompt: 'Which shape does this print?', code: [{ text: 'for (int i = 1; i <= 3; i++) {' }, { text: '    System.out.println("*".repeat(i));' }, { text: '}' }], terminalOutput: '*\n**\n***', options: ['***\n**\n*', '*\n**\n***', '***', '* * *'], correct: 1, explanation: 'i goes 1, 2, 3 and repeat(i) grows the row each pass. The reversed triangle would need the loop to count down. Note String.repeat arrived in Java 11 — before that you would build it with a StringBuilder or a nested loop.', hint: 'Write down what i is on each pass, then what repeat(i) produces for it.' },
        { type: 'scramble', prompt: 'Assemble one row of a multiplication table', pieces: [{ id: 'a', text: 'int n = 5;' }, { id: 'b', text: 'for (int i = 1; i <= 10; i++) {' }, { id: 'c', text: '    System.out.printf("%d x %d = %d%n", n, i, n*i);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    System.out.println(n + i);' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'n has to exist before the loop that uses it, and the printf has to sit inside the braces or it runs once after the loop instead of ten times within it. The three %d placeholders line up with the three arguments in order. The spare line adds where it should multiply.', hint: 'One line sets up, one repeats, one does the work. Which has to be inside which?' },
    ],
    11: [
        { type: 'scramble', prompt: 'Assemble a primality test', pieces: [{ id: 'a', text: 'static boolean isPrime(int n) {' }, { id: 'b', text: '    if (n < 2) return false;' }, { id: 'c', text: '    for (int i = 2; i <= Math.sqrt(n); i++) {' }, { id: 'd', text: '        if (n % i == 0) return false;' }, { id: 'e', text: '    }' }, { id: 'f', text: '    return true;' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '    for (int i = 0; i < n; i++) {' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The guard for n < 2 has to come first, because 0 and 1 are not prime and would otherwise reach the final return true. Testing only up to √n is the real trick: any factor above the square root has a matching partner below it, so if none turned up by then there is none at all. The spare line starts at 0, and integer n % 0 throws ArithmeticException on the very first pass.', hint: 'Why is √n enough? Think about what pairs up with a factor larger than it.' },
        { type: 'trace', prompt: 'What does the stream filter leave behind?', code: [{ text: 'int[] nums = {1, 2, 3, 4, 5, 6};' }, { text: 'int[] evens = Arrays.stream(nums)' }, { text: '    .filter(n -> n % 2 == 0).toArray();' }, { text: 'System.out.println(Arrays.toString(evens));', highlight: true }], options: ['[2, 4, 6]', '[1, 3, 5]', '[1, 2, 3, 4, 5, 6]', '3'], correct: 0, explanation: 'filter keeps every element the predicate returns true for, and n % 2 == 0 is true for even numbers. Note Arrays.toString is what makes it print readably — println on the array itself would give you something like [I@1b6d3586, the type and hash code, which trips up nearly everyone once.', hint: 'Read the lambda as a keep-or-drop test, then check which numbers it keeps.' },
        { type: 'fillgap', prompt: 'Build {1, 4, 9, 16, 25} from a stream over 1 to 5', codeParts: [{ text: 'int[] squares = ', type: 'fixed' }, { text: 'IntStream.rangeClosed(1,5).map(x -> x*x).toArray();', type: 'gap', id: 'g1' }], bank: ['IntStream.rangeClosed(1,5).map(x -> x*x).toArray();', 'IntStream.range(1,5).map(x -> x*x).toArray();', 'Arrays.stream(5).map(x*x);', 'Math.pow(range(5));'], correctFill: { g1: 'IntStream.rangeClosed(1,5).map(x -> x*x).toArray();' }, explanation: 'rangeClosed includes both ends, so 1 to 5 — five values. range excludes the upper end and would give 1 to 4, producing only four squares and silently dropping the 25. That pair of method names is the whole lesson. The other two do not compile: Arrays.stream needs an array not an int, and there is no range() in Java.', hint: 'Two of these are real IntStream methods that differ by one element. Which end does each include?' },
    ],
    12: [
        { type: 'pair', prompt: 'Match each loop tool to what it does', pairs: [{ id: 1, left: 'break', right: 'Leave the loop now' }, { id: 2, left: 'continue', right: 'Skip to the next pass' }, { id: 3, left: 'for-each', right: 'Walk a collection' }, { id: 4, left: 'Iterator', right: 'Traverse and remove safely' }], explanation: 'break and continue are often confused: break abandons the whole loop, continue abandons only the current pass. The for-each is the one to reach for by default, but it cannot remove items — do that and you get ConcurrentModificationException. That is exactly what an explicit Iterator with its remove() is for.' },
        { type: 'output', prompt: 'What does continue leave printed?', code: [{ text: 'for (int i = 0; i < 5; i++) {' }, { text: '    if (i == 2) continue;' }, { text: '    System.out.print(i + " ");' }, { text: '}' }], terminalOutput: '0 1 3 4 ', options: ['0 1 3 4 ', '0 1 2 3 4', '2', '0 1'], correct: 0, explanation: 'continue skips the rest of this one pass and moves to the next, so only 2 is missing — the loop keeps going. "0 1" would be the answer if this were break, which is the distinction the question is really testing. Note continue still runs i++, so it cannot cause an infinite loop here the way it can in a while loop.', hint: 'Does the loop end at i = 2, or just skip that one pass?' },
    ],
    // ═══ CH4: FUNCTIONS ═══
    13: [
        { type: 'trace', prompt: 'Two methods share a name — which one runs?', code: [{ text: 'static int add(int a) { return a + 10; }' }, { text: 'static int add(int a, int b) { return a + b; }' }, { text: 'System.out.println(add(3));', highlight: true }], options: ['3', '10', '13', 'Error'], correct: 2, explanation: 'Java picks the overload by the argument list, and one int matches the first method — giving 3 + 10 = 13. Java has no default parameters, so overloading is how you get the same effect. The compiler decides this, not the runtime, which is why an ambiguous overload is a compile error rather than a surprise later.', hint: 'Count the arguments at the call site, then find the method whose signature matches.' },
        { type: 'bug', prompt: 'The caller never receives the sum. Which line?', code: [{ text: 'static int add(int a, int b) {', hasError: false }, { text: '    int result = a + b;', hasError: false }, { text: '    System.out.println(result);', hasError: true }], correctLine: 2, explanation: 'Printing shows a value on screen; returning hands it back to the caller. Java is stricter than most here — a method declared int that can finish without returning will not even compile, so this one is caught before it runs. In Python or JavaScript the same mistake compiles fine and silently yields None or undefined.', hint: 'Ask what `int x = add(2, 3);` would put in x — then whether javac would even allow it.' },
        { type: 'output', prompt: 'Four arguments, one parameter — what prints?', code: [{ text: 'static int total(int... nums) {' }, { text: '    return Arrays.stream(nums).sum();' }, { text: '}' }, { text: 'System.out.println(total(1, 2, 3, 4));' }], terminalOutput: '10', options: ['[1,2,3,4]', '10', '4', 'Error'], correct: 1, explanation: 'int... collects the arguments into a real int[], so nums is {1,2,3,4} and the stream sums it to 10. Varargs must be the last parameter and there can only be one — otherwise the compiler could not tell where the list ends. 4 would be nums.length.', hint: 'Two steps: what type is nums inside the method, and what does .sum() do to it?' },
        { type: 'scramble', prompt: 'Assemble two overloads of greet', pieces: [{ id: 'a', text: 'static String greet(String name) {' }, { id: 'b', text: '    return "Hello, " + name + "!";' }, { id: 'c', text: '}' }, { id: 'd', text: 'static String greet(String name, String greeting) {' }, { id: 'e', text: '    return greeting + ", " + name + "!";' }, { id: 'f', text: '}' }], distractors: [{ id: 'g', text: '    return name + greeting;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'], explanation: 'Each method must be fully closed before the next begins — Java has no nested method definitions. The two overloads differ by parameter count, which is what makes them legal siblings; changing only the return type would not be enough and the compiler would reject it. The spare line concatenates without punctuation and in the wrong order.', hint: 'Close each method before starting the next. What exactly makes two same-named methods legal?' },
        { type: 'trace', prompt: 'What does the stream pipeline produce?', code: [{ text: 'List<Integer> nums = List.of(1, 2, 3);' }, { text: 'List<Integer> result = nums.stream()' }, { text: '    .map(x -> x * 2).collect(Collectors.toList());' }, { text: 'System.out.println(result);', highlight: true }], options: ['[2, 4, 6]', '[1, 2, 3]', '6', 'Error'], correct: 0, explanation: 'map transforms each element and collect gathers the results into a new list — nums itself is untouched, and List.of makes it immutable anyway, so it could not be modified in place even by accident. Without the terminal collect nothing would run at all: streams are lazy and do no work until a terminal operation asks for it.', hint: 'Does the pipeline change nums or build something new? And what makes it actually execute?' },
    ],
    14: [
        { type: 'trace', prompt: 'A field and a local share a name — which prints?', code: [{ text: 'String x = "global";' }, { text: 'void f() {' }, { text: '    String x = "local";' }, { text: '    System.out.println(x);', highlight: true }, { text: '}' }], options: ['global', 'local', 'Error', 'null'], correct: 1, explanation: 'The local declaration shadows the field for the rest of the method, so the nearer binding wins. The field is untouched — reach it explicitly with this.x, which is exactly why constructors are full of this.name = name.', hint: 'Which declaration is closer to the print? And how would you name the other one on purpose?' },
        { type: 'bug', prompt: 'javac rejects this. Which line does it point at?', code: [{ text: 'int total = 0;', hasError: false }, { text: 'static void add(int n) {', hasError: false }, { text: '    total += n;', hasError: true }, { text: '}', hasError: false }], correctLine: 2, explanation: 'total is an instance field — it exists once per object — but add is static, so it runs with no object at all and has nothing to add to. The error lands on the line that does the referencing, not on either declaration. Making total static, or making add non-static, both resolve it, but they mean different things: one counter for the class versus one per instance.', hint: 'Which of the two lives on an instance, and which one runs without any instance existing?' },
        { type: 'errordecode', prompt: 'What does "static context" mean in this error?', errorText: "error: non-static variable total cannot be\nreferenced from a static context\n    total += n;\n    ^", question: 'Fix?', options: ['Make total static too', 'Make it a local variable', 'Import total', 'Delete total'], correct: 0, explanation: 'A static method belongs to the class, so it runs without an instance — and an instance field needs one. Marking total static gives it a single home on the class, which both the field and the method then share. A local variable also compiles, but it is created fresh on every call and discarded on return, so the total never accumulates: the error goes and the behaviour is still wrong.', hint: 'Two of these compile. Only one still adds up across calls.' },
        { type: 'realworld', prompt: 'Which one can be passed around as a value?', scenario: '🧠 You want to hand "multiply by 2" to another method.', options: [{ code: 'interface Multiplier {\n    int multiply(int x);\n}\nMultiplier doubler = x -> x * 2;\nMultiplier tripler = x -> x * 3;', label: 'Functional interface plus lambda' }, { code: 'int factor = 2;\nint multiply(int x) {\n    return x * factor;\n}', label: 'A method reading a field' }, { code: 'class Mult {\n    int f;\n    Mult(int f) { this.f = f; }\n}', label: 'A class with no method' }, { code: 'final int mult = 2;', label: 'A constant' }], correct: 0, explanation: 'An interface with a single abstract method can be implemented by a lambda, so doubler and tripler are ordinary values you can store, pass and return — the closest Java gets to a first-class function. A plain method cannot be passed by itself (only via a method reference, which still needs a matching interface). The class holds a factor but has no operation to call, and a constant is just a number.', hint: 'The requirement is to HAND it to another method. Which of these is a value rather than a declaration?' },
    ],
    15: [
        { type: 'concept', chapter: 4 },
        { type: 'pair', prompt: 'Match each keyword to what it does', pairs: [{ id: 1, left: 'static', right: 'Belongs to the class' }, { id: 2, left: 'return', right: 'Hands a value back' }, { id: 3, left: 'int...', right: 'Accepts any number of ints' }, { id: 4, left: '->', right: 'Introduces a lambda' }], explanation: 'static is the one that trips people up: a static member exists once for the whole class, so it cannot touch instance fields — that is the single most common compile error in a first Java course. Varargs must be the last parameter, and a lambda only works where a functional interface (exactly one abstract method) is expected.' },
    ],
    16: [
        { type: 'trace', prompt: 'What does fib(5) return?', code: [{ text: 'static int fib(int n) {' }, { text: '    if (n <= 1) return n;' }, { text: '    return fib(n-1) + fib(n-2);' }, { text: '}' }, { text: 'System.out.println(fib(5));', highlight: true }], options: ['3', '5', '8', '13'], correct: 1, explanation: 'The sequence from this definition is 0,1,1,2,3,5 — so fib(5) is 5. It is easy to be one place out: fib(4) is 3 and fib(6) is 8, which is what the neighbouring options are. Work upward from the base case rather than expanding the tree downward.', hint: 'List fib(0) through fib(5) in order, each one the sum of the two before it.' },
        { type: 'errordecode', prompt: 'What is missing when recursion hits this error?', errorText: 'Exception in thread "main"\njava.lang.StackOverflowError\n    at Main.fib(Main.java:2)', question: 'Cause?', options: ['Missing base case', 'Wrong return type', 'Too many params', 'Import error'], correct: 0, explanation: 'Every recursive method needs a case that returns without recursing, and each call must move towards it. Miss either and the JVM stack fills up. Note StackOverflowError is an Error, not an Exception — it signals a broken program rather than a condition you are meant to catch and recover from.', hint: 'What has to be true for the calls to eventually stop?' },
        { type: 'scramble', prompt: 'Assemble a recursive factorial', pieces: [{ id: 'a', text: 'static int factorial(int n) {' }, { id: 'b', text: '    if (n <= 1) return 1;' }, { id: 'c', text: '    return n * factorial(n - 1);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    return n + factorial(n);' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'The base case has to come before the recursive call, or nothing ever stops it. The spare line breaks both halves at once — it adds where it should multiply, and calls factorial(n) rather than factorial(n - 1), so it never approaches the base case. Worth knowing the limit of the correct version too: int overflows silently past 13!, giving a negative answer with no warning.', hint: 'Two things every recursion needs: somewhere to stop, and a step that gets closer to it.' },
        { type: 'trace', prompt: 'What does sumDigits(123) return?', code: [{ text: 'static int sumDigits(int n) {' }, { text: '    if (n < 10) return n;' }, { text: '    return n % 10 + sumDigits(n / 10);' }, { text: '}' }, { text: 'System.out.println(sumDigits(123));', highlight: true }], options: ['6', '123', '3', '12'], correct: 0, explanation: '% 10 peels off the last digit and / 10 removes it, so the calls are 3 + (2 + (1)) = 6. Integer division is what makes this work without any rounding call — 123 / 10 is 12, not 12.3. In JavaScript the same line would need Math.floor. 3 would be the digit count, not the sum.', hint: 'Work out what n % 10 and n / 10 give for 123, then follow one level down.' },
        { type: 'realworld', prompt: 'Which of these problems contains a smaller copy of itself?', scenario: '🤔 Recursion fits when a problem breaks into the same problem, smaller.', options: [{ code: '// A folder contains files and more folders', label: 'Walking a directory tree' }, { code: '// Read a file one line at a time until EOF', label: 'Reading lines sequentially' }, { code: '// Print "Hello" five times', label: 'Repeating a fixed number of times' }, { code: '// Add two numbers together', label: 'A single arithmetic step' }], correct: 0, explanation: 'A folder contains folders, each handled by exactly the same procedure — the structure is self-similar, so the code can be too. The others are flat: reading lines and counting to five are plain iteration, and adding two numbers has no subproblem at all. Recursion is not "a fancier loop", it is for structures that nest.', hint: 'For each one, ask whether solving it requires solving a smaller version of the identical problem.' },
    ],
    // ═══ CH5+ shares conceptual exercises, falls back to Python ═══
    17: [
        { type: 'trace', prompt: 'b[0] was assigned — what is a[0]?', code: [{ text: 'int[] a = {1, 2, 3};' }, { text: 'int[] b = a;' }, { text: 'b[0] = 99;' }, { text: 'System.out.println(a[0]);', highlight: true }], options: ['1', '99', 'Error', '[1,2,3]'], correct: 1, explanation: 'An array variable holds a reference, so int[] b = a copies the reference, not the array — both names point at one object. Note the contrast with primitives one line up: int y = x really does copy the value. Arrays and objects behave differently from int and double, and that difference is the whole lesson.', hint: 'Does the assignment copy the array, or just the arrow pointing at it?' },
        { type: 'output', prompt: 'Which items does copyOfRange(x, 1, 4) take?', code: [{ text: 'int[] x = {10, 20, 30, 40, 50};' }, { text: 'int[] sub = Arrays.copyOfRange(x, 1, 4);' }, { text: 'System.out.println(Arrays.toString(sub));' }], terminalOutput: '[20, 30, 40]', options: ['[10,20,30]', '[20,30,40]', '[20,30,40,50]', '[10,20,30,40]'], correct: 1, explanation: 'The from index is inclusive and the to index exclusive — the same convention as substring, List.subList and every range API in the JDK. So indices 1, 2, 3, and the length is always to minus from. It returns a new array, so x is untouched.', hint: 'Count from 0, then decide which end the range leaves out.' },
        { type: 'bug', prompt: 'Writing to b changed a. Which line is responsible?', code: [{ text: 'int[] a = {1, 2, 3};', hasError: false }, { text: 'int[] b = a;', hasError: true }, { text: 'b[0] = 99;', hasError: false }, { text: 'System.out.println(Arrays.toString(a));', hasError: false }], correctLine: 1, explanation: 'The write does exactly what it says; the problem is one line earlier, where b became a second reference to the same array rather than a copy. int[] b = a.clone() there fixes it. Blaming the line where the symptom appears rather than the line that set it up is a habit worth breaking early.', hint: 'The line that misbehaves is not always the line that is wrong. Which line decided there would be only one array?' },
        { type: 'refactor', prompt: 'Which one gives you an array you can change independently?', originalCode: 'int[] original = {1, 2, 3};\nint[] copy = original;', options: [{ code: 'int[] copy = original.clone();', label: 'Call clone()' }, { code: 'int[] copy = original;', label: 'Assign it across' }, { code: 'int[] copy = new int[original.length];', label: 'Allocate the same size' }], correct: 0, explanation: 'clone() allocates a new array and copies the elements across — Arrays.copyOf does the same. Plain assignment shares the object, which is the bug being fixed. Allocating a same-sized array gives you a separate object but it is zero-filled, so the values are gone. Worth being precise: clone() on an array is SHALLOW. For int[] that is indistinguishable from deep, but clone a String[][] and the inner arrays are still shared.', hint: 'Two of these produce a second array. Only one of them has the numbers in it.' },
    ],
    18: [
        { type: 'trace', prompt: 'How many times does \'a\' appear in banana?', code: [{ text: 'String word = "banana";' }, { text: 'Map<Character,Integer> freq = new HashMap<>();' }, { text: 'for (char c : word.toCharArray()) {' }, { text: '    freq.merge(c, 1, Integer::sum);' }, { text: '}' }, { text: 'System.out.println(freq.get(\'a\'));', highlight: true }], options: ['1', '2', '3', 'null'], correct: 2, explanation: 'b-a-n-a-n-a has three a\'s. merge is what makes this one line: absent key, store 1; present key, combine old and new with Integer::sum. Without it you would need a get, a null check and a put — and freq.get(c) + 1 on a missing key throws NullPointerException, because the Integer unboxes from null. That is the "null" option.', hint: 'Spell banana out. Then ask what merge does the very first time it sees a letter.' },
        { type: 'fillgap', prompt: 'Return true only when both words use the same letters, same counts', codeParts: [{ text: 'static boolean isAnagram(String a, String b) {\n    char[] ca = a.toCharArray(), cb = b.toCharArray();\n    ', type: 'fixed' }, { text: 'Arrays.sort(ca); Arrays.sort(cb);\n    return Arrays.equals(ca, cb);', type: 'gap', id: 'g1' }, { text: '\n}\n\n// isAnagram("listen", "silent") -> true\n// isAnagram("aab", "abb")       -> must be false', type: 'fixed' }], bank: ['Arrays.sort(ca); Arrays.sort(cb);\n    return Arrays.equals(ca, cb);', 'return a.equals(b);', 'return a.length() == b.length();', 'return new HashSet<>(a).equals(new HashSet<>(b));'], correctFill: { g1: 'Arrays.sort(ca); Arrays.sort(cb);\n    return Arrays.equals(ca, cb);' }, explanation: 'Sorting both char arrays into a canonical order compares letters AND their counts. Note Arrays.equals, not == — comparing two arrays with == asks whether they are the same object, which they never are. equals() is plain string equality, length only compares length, and the HashSet line does not even compile: a String is not a Collection, so there is no such constructor.', hint: 'One option will not compile at all. Of the rest, test each against aab/abb.' },
        { type: 'pair', prompt: 'Match each collection to what it is built on', pairs: [{ id: 1, left: 'ArrayList', right: 'A resizing array' }, { id: 2, left: 'HashMap', right: 'A hash table of key-value pairs' }, { id: 3, left: 'HashSet', right: 'A HashMap with the values ignored' }, { id: 4, left: 'LinkedList', right: 'Nodes linked in both directions' }], explanation: 'The implementation tells you the costs. ArrayList indexes in O(1) but shifts everything on an insert near the front; LinkedList is the reverse. HashSet is literally a HashMap underneath, which is why both give O(1) membership and neither promises any order — for that you want LinkedHashSet or TreeSet.' },
    ],
    19: [
        { type: 'scramble', prompt: 'Assemble a duplicate finder', pieces: [{ id: 'a', text: 'static List<Integer> findDupes(int[] arr) {' }, { id: 'b', text: '    Set<Integer> seen = new HashSet<>();' }, { id: 'c', text: '    Set<Integer> dupes = new HashSet<>();' }, { id: 'd', text: '    for (int x : arr) {' }, { id: 'e', text: '        if (!seen.add(x)) dupes.add(x);' }, { id: 'f', text: '    }' }, { id: 'g', text: '    return new ArrayList<>(dupes);' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '    return Arrays.asList(arr);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], explanation: 'The neat part is that Set.add returns false when the element was already there, so one call both records and detects — no separate contains() needed. Both sets must exist before the loop. The spare line is a classic trap: Arrays.asList on an int[] gives a List<int[]> with one element, not a list of Integers, because generics do not accept primitives.', hint: 'What does Set.add return, and what does the ! in front of it therefore mean?' },
        { type: 'trace', prompt: 'What is left in a after retainAll?', code: [{ text: 'Set<Integer> a = new HashSet<>(Set.of(1,2,3,4));' }, { text: 'Set<Integer> b = Set.of(3,4,5,6);' }, { text: 'a.retainAll(b);' }, { text: 'System.out.println(a);', highlight: true }], options: ['[3, 4]', '[1,2,3,4,5,6]', '[1,2]', '[5,6]'], correct: 0, explanation: 'retainAll keeps only what also appears in b — the intersection. Note it MUTATES a rather than returning a new set, which is why a had to be wrapped in new HashSet<>() first: Set.of produces an immutable set and calling retainAll on that throws UnsupportedOperationException. The sibling methods are addAll (union) and removeAll (difference), both equally in-place.', hint: 'Which numbers are in both? Then ask where the result is stored — a new set, or one of the two?' },
    ],
    20: [
        { type: 'pair', prompt: 'Match each container to what it is for', pairs: [{ id: 1, left: 'ArrayList', right: 'Ordered, reachable by index' }, { id: 2, left: 'HashSet', right: 'No duplicates, fast membership' }, { id: 3, left: 'HashMap', right: 'Look a value up by key' }, { id: 4, left: 'int[]', right: 'Fixed size, no boxing' }], explanation: 'Picking the right one is mostly about the question you will ask most often — "is x in here?" is O(n) on a list and O(1) on a set or map. int[] is the one with a performance argument rather than a shape argument: List<Integer> boxes every value into an object, which costs both memory and a pointer hop.' },
        { type: 'realworld', prompt: 'You will look up a number by name thousands of times. Which shape?', scenario: '📱 Given "Ali", return "555-1234".', options: [{ code: 'Map<String,String> pb = new HashMap<>();\npb.put("Ali", "555-1234");', label: 'HashMap keyed by name' }, { code: 'List<String[]> pb = new ArrayList<>();\npb.add(new String[]{"Ali", "555-1234"});', label: 'List of name/number pairs' }, { code: 'Set<String> pb = new HashSet<>();\npb.add("555-1234");', label: 'Set of numbers' }, { code: 'String[] pb = {"Ali", "555-1234", "Ece", "555-5678"};', label: 'Flat alternating array' }], correct: 0, explanation: 'A HashMap hashes the name straight to the number, so lookup cost does not grow with the phone book. The list of pairs holds the same information but must be scanned. The set has no names to look up by. The flat array encodes it, but every read means index arithmetic and one insertion in the wrong place corrupts every pair after it.', hint: 'Two of these contain all the information. Ask what each costs per lookup as the book grows.' },
    ],
}
