/* ══════════════════════════════════════════════════
   JAVA EXERCISES — Journey Nodes CH1-CH5
   ══════════════════════════════════════════════════ */
export const javaExercises = {
    // ═══ CH1: BASICS ═══
    1: [
        { type: 'trace', prompt: 'What is the value of `count`?', code: [{ text: 'int count = 0;' }, { text: 'for (int i = 0; i < 5; i++) {' }, { text: '    if (i % 2 == 0) {' }, { text: '        count++;' }, { text: '    }' }, { text: '}' }, { text: 'System.out.println(count);', highlight: true }], options: ['2', '3', '5', '4'], correct: 1 },
        { type: 'realworld', prompt: 'Which code counts total items in a cart?', scenario: '🛒 Cart: 3 apples, 2 oranges, 1 banana.', options: [{ code: 'int[] cart = {3, 2, 1};\nint total = Arrays.stream(cart).sum();', label: 'Stream sum' }, { code: 'int cart = 3 + 2 + 1;\nint total = String.valueOf(cart).length();', label: 'length on string' }, { code: 'String cart = "3 2 1";\nint total = cart.length();', label: 'String length' }, { code: 'Set<Integer> cart = Set.of(3,2,1);\nint total = Collections.max(cart);', label: 'Max of set' }], correct: 0 },
        { type: 'pair', prompt: 'Match Java concepts', pairs: [{ id: 1, left: 'int', right: 'Whole number' }, { id: 2, left: 'String', right: 'Text data' }, { id: 3, left: 'boolean', right: 'true or false' }, { id: 4, left: 'double', right: 'Decimal number' }] },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'int x = 7;' }, { text: 'int y = 2;' }, { text: 'System.out.println(x / y + " " + x % y);' }], terminalOutput: '3 1', options: ['3.5 1', '3 1', '3.5 0', '3 0'], correct: 1 },
        { type: 'fillgap', prompt: 'Complete: swap two variables', codeParts: [{ text: 'int a = 5;\nint b = 10;\n', type: 'fixed' }, { text: 'int temp = a; a = b; b = temp;', type: 'gap', id: 'g1' }], bank: ['int temp = a; a = b; b = temp;', 'a = b; b = a;', 'swap(a, b);', 'a == b;'], correctFill: { g1: 'int temp = a; a = b; b = temp;' } },
        { type: 'scramble', prompt: 'Build code to calculate BMI', pieces: [{ id: 'a', text: 'double weight = 70;' }, { id: 'b', text: 'double height = 1.75;' }, { id: 'c', text: 'double bmi = weight / (height * height);' }, { id: 'd', text: 'System.out.printf("%.1f%n", bmi);' }], distractors: [{ id: 'e', text: 'double bmi = weight * height;' }], correctOrder: ['a', 'b', 'c', 'd'] },
    ],
    2: [
        { type: 'bug', prompt: 'Find the syntax error', code: [{ text: 'public static String greet(String name) {', hasError: false }, { text: '    String msg = "Hello " + name;', hasError: false }, { text: '    System.out.println(msg', hasError: true }, { text: '    return msg;', hasError: false }], correctLine: 2 },
        { type: 'errordecode', prompt: 'Decode this error', errorText: 'Main.java:3: error: \')\' expected\n    System.out.println(msg\n                         ^\n1 error', question: 'What caused this?', options: ['Missing closing parenthesis and semicolon', 'Undefined variable', 'Wrong indentation', 'Invalid string'], correct: 0 },
        { type: 'refactor', prompt: 'Which is the cleanest?', originalCode: 'int x = 10;\nString r;\nif (x > 5) {\n    r = "big";\n} else {\n    r = "small";\n}\nSystem.out.println(r);', options: [{ code: 'int x = 10;\nString r = x > 5 ? "big" : "small";\nSystem.out.println(r);', label: 'Ternary expression' }, { code: 'int x = 10;\nString r = "";\nif (x > 5) r = "big";\nif (x <= 5) r = "small";', label: 'Two ifs' }, { code: 'System.out.println(10>5 ? "big":"small");', label: 'Inline ternary' }], correct: 0 },
        { type: 'bug', prompt: 'Why does this give wrong comparison?', code: [{ text: 'String a = new String("hello");', hasError: false }, { text: 'String b = new String("hello");', hasError: false }, { text: 'if (a == b) {', hasError: true }, { text: '    System.out.println("Equal");', hasError: false }], correctLine: 2 },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'String x = "5";' }, { text: 'int y = 3;' }, { text: 'System.out.println(x.repeat(y));' }], terminalOutput: '555', options: ['15', '555', '53', 'Error'], correct: 1 },
        { type: 'trace', prompt: 'What is the type of result?', code: [{ text: 'int a = 10;' }, { text: 'int b = 3;' }, { text: 'double result = (double) a / b;' }, { text: 'System.out.println(result);', highlight: true }], options: ['3', '3.3333...', 'int', 'Error'], correct: 1 },
    ],
    3: [
        { type: 'video', title: 'Variables & Data Types', description: 'Java is statically typed — type declarations required. int, double, String, boolean, char are the basics. Primitive vs Reference types.', duration: '2:45', thumbnail: '🎬' },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'String name = "Rheo";' }, { text: 'int age = 3;' }, { text: 'System.out.println(((Object)age).getClass().getSimpleName());' }], terminalOutput: 'Integer', options: ['"String"', '"Integer"', '3', '"int"'], correct: 1 },
        { type: 'pair', prompt: 'Match Java types', pairs: [{ id: 1, left: 'int', right: '42' }, { id: 2, left: 'double', right: '3.14' }, { id: 3, left: 'String', right: '"hello"' }, { id: 4, left: 'boolean', right: 'true' }] },
    ],
    4: [
        { type: 'pair', prompt: 'Match operators', pairs: [{ id: 1, left: '==', right: 'Value equality (primitives)' }, { id: 2, left: '.equals()', right: 'Object equality' }, { id: 3, left: 'Math.pow()', right: 'Power' }, { id: 4, left: '/', right: 'Integer division (int/int)' }] },
        { type: 'trace', prompt: 'What is the output?', code: [{ text: 'int x = 17;' }, { text: 'System.out.println(x % 5 + " " + x / 5);', highlight: true }], options: ['2 3', '3 2', '2 4', '17 5'], correct: 0 },
        { type: 'fillgap', prompt: 'Complete: convert Celsius to Fahrenheit', codeParts: [{ text: 'double celsius = 25;\n', type: 'fixed' }, { text: 'double fahrenheit = celsius * 9.0/5 + 32;', type: 'gap', id: 'g1' }, { text: '\nSystem.out.println(fahrenheit);', type: 'fixed' }], bank: ['celsius * 9.0/5 + 32;', 'celsius + 32;', 'celsius * 1.8;', 'celsius / 5 * 9;'], correctFill: { g1: 'celsius * 9.0/5 + 32;' } },
    ],
    // ═══ CH2: FLOW CONTROL ═══
    5: [
        { type: 'trace', prompt: 'What does this nested condition print?', code: [{ text: 'int x = 15;' }, { text: 'if (x > 20) {' }, { text: '    System.out.println("A");' }, { text: '} else if (x > 10) {' }, { text: '    if (x % 2 == 0) {' }, { text: '        System.out.println("B");' }, { text: '    } else {' }, { text: '        System.out.println("C");', highlight: true }, { text: '    }' }, { text: '}' }], options: ['A', 'B', 'C', 'Nothing'], correct: 2 },
        { type: 'bug', prompt: 'Voting check bug — 18 year olds should vote!', code: [{ text: 'int age = 18;', hasError: false }, { text: 'if (age > 18) {', hasError: true }, { text: '    System.out.println("Can vote");', hasError: false }], correctLine: 1 },
        { type: 'output', prompt: 'Short-circuit: what prints?', code: [{ text: 'int a = 0;' }, { text: 'int b = 5;' }, { text: 'boolean result = (a != 0) && (b/a > 1);' }, { text: 'System.out.println(result);' }], terminalOutput: 'false', options: ['false', 'ArithmeticException', 'true', '0'], correct: 0 },
        { type: 'scramble', prompt: 'Build a grade calculator', pieces: [{ id: 'a', text: 'int score = 75;' }, { id: 'b', text: 'String grade;' }, { id: 'c', text: 'if (score >= 90) grade = "A";' }, { id: 'd', text: 'else if (score >= 80) grade = "B";' }, { id: 'e', text: 'else if (score >= 70) grade = "C";' }, { id: 'f', text: 'else grade = "F";' }, { id: 'g', text: 'System.out.println(grade);' }], distractors: [{ id: 'h', text: 'if (score == 90) grade = "A";' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'trace', prompt: 'Ternary chain result?', code: [{ text: 'int n = 0;' }, { text: 'String label = n > 0 ? "positive" : n < 0 ? "negative" : "zero";' }, { text: 'System.out.println(label);', highlight: true }], options: ['positive', 'negative', 'zero', 'Error'], correct: 2 },
        { type: 'realworld', prompt: 'Which handles login correctly?', scenario: '🔐 3 password attempts, then lock.', options: [{ code: 'int attempts = 0;\nwhile (attempts < 3) {\n    String pwd = scanner.nextLine();\n    if (pwd.equals(secret)) break;\n    attempts++;\n}', label: 'Counter + break' }, { code: 'for (int i=0; i<3; i++) {\n    String pwd = scanner.nextLine();\n    if (!pwd.equals(secret)) continue;\n}', label: 'Continue loop' }, { code: 'String pwd = scanner.nextLine();\nif (pwd.equals(secret))\n    System.out.println("OK");', label: 'Single attempt' }, { code: 'while (true) {\n    scanner.nextLine();\n    break;\n}', label: 'Infinite + break' }], correct: 0 },
    ],
    6: [
        { type: 'trace', prompt: 'String comparison — what prints?', code: [{ text: 'String a = "hello";' }, { text: 'String b = new String("hello");' }, { text: 'System.out.println(a == b);', highlight: true }, { text: 'System.out.println(a.equals(b));' }], options: ['true true', 'false true', 'true false', 'false false'], correct: 1 },
        { type: 'refactor', prompt: 'Java null-safe check?', originalCode: 'if (str != null && str.length() > 0) {\n    doSomething();\n}', options: [{ code: 'if (str != null && !str.isEmpty()) {\n    doSomething();\n}', label: '.isEmpty() check' }, { code: 'if (str != "") {\n    doSomething();\n}', label: 'Wrong! Reference compare' }, { code: 'if (str.length() > 0) {\n    doSomething();\n}', label: 'NPE if null!' }], correct: 0 },
        { type: 'fillgap', prompt: 'Check if number is in range 1-100', codeParts: [{ text: 'static boolean inRange(int n) {\n    return ', type: 'fixed' }, { text: 'n >= 1 && n <= 100;', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['n >= 1 && n <= 100;', '1 <= n <= 100;', 'Range.of(1,100).contains(n);', 'n > 0 && n < 101;'], correctFill: { g1: 'n >= 1 && n <= 100;' } },
        { type: 'pair', prompt: 'Match Java null/default values', pairs: [{ id: 1, left: 'int', right: '0' }, { id: 2, left: 'boolean', right: 'false' }, { id: 3, left: 'String', right: 'null' }, { id: 4, left: 'double', right: '0.0' }] },
        { type: 'output', prompt: 'What does Optional do?', code: [{ text: 'Optional<String> opt = Optional.ofNullable(null);' }, { text: 'String val = opt.orElse("default");' }, { text: 'System.out.println(val);' }], terminalOutput: 'default', options: ['null', 'default', 'Error', 'Optional.empty'], correct: 1 },
    ],
    7: [
        { type: 'terminal', prompt: 'Create a variable and print it', expectedCommands: ['String name = "Otter";', 'System.out.println(name);'], hint: 'Declare type, use System.out.println', terminalHistory: [{ type: 'system', text: '> Daily Challenge' }] },
        { type: 'trace', prompt: 'What is `result`?', code: [{ text: 'String result = "";' }, { text: 'for (char c : "hello".toCharArray()) {' }, { text: '    result += Character.toUpperCase(c);' }, { text: '}' }, { text: 'System.out.println(result);', highlight: true }], options: ['hello', 'HELLO', 'Hello', 'hELLO'], correct: 1 },
        { type: 'output', prompt: 'String.format?', code: [{ text: 'String name = "Otter";' }, { text: 'int age = 5;' }, { text: 'System.out.printf("%s is %d in human years%n", name, age*7);' }], terminalOutput: 'Otter is 35 in human years', options: ['Otter is 35 in human years', 'Otter is 5 in human years', '%s is %d', 'Error'], correct: 0 },
    ],
    8: [
        { type: 'video', title: 'Conditional Logic Deep Dive', description: 'if/else if/else chains, ternary, switch expressions (Java 14+), pattern matching.', duration: '3:00', thumbnail: '🎥' },
        { type: 'trace', prompt: 'Switch: what prints?', code: [{ text: 'int status = 404;' }, { text: 'String msg = switch (status) {' }, { text: '    case 200 -> "OK";' }, { text: '    case 404 -> "Not Found";' }, { text: '    default -> "Unknown";' }, { text: '};' }, { text: 'System.out.println(msg);', highlight: true }], options: ['OK', 'Not Found', 'Unknown', 'Error'], correct: 1 },
    ],
    // ═══ CH3: LOOPS ═══
    9: [
        { type: 'scramble', prompt: 'Print numbers 1-5', pieces: [{ id: 'a', text: 'for (int i = 1; i <= 5; i++) {' }, { id: 'b', text: '    System.out.println(i);' }, { id: 'c', text: '}' }], distractors: [{ id: 'd', text: '    System.out.println(i + 1);' }, { id: 'e', text: 'while (i < 5) {' }], correctOrder: ['a', 'b', 'c'] },
        { type: 'bug', prompt: 'Off-by-one: should print 1-10', code: [{ text: 'for (int i = 1; i < 10; i++) {', hasError: true }, { text: '    System.out.println(i);', hasError: false }, { text: '}', hasError: false }], correctLine: 0 },
        { type: 'trace', prompt: 'How many iterations?', code: [{ text: 'int n = 64;' }, { text: 'int count = 0;' }, { text: 'while (n > 1) {' }, { text: '    n = n / 2;' }, { text: '    count++;' }, { text: '}' }, { text: 'System.out.println(count);', highlight: true }], options: ['5', '6', '7', '32'], correct: 1 },
        { type: 'fillgap', prompt: 'Complete the sum loop', codeParts: [{ text: 'int total = 0;\nint[] nums = ', type: 'fixed' }, { text: '{1, 2, 3, 4}', type: 'gap', id: 'g1' }, { text: ';\nfor (int num : nums) {\n    total += num;\n}', type: 'fixed' }], bank: ['{1, 2, 3, 4}', 'new int[4]', 'Arrays.asList(1,2,3,4)', '"1234"'], correctFill: { g1: '{1, 2, 3, 4}' } },
        { type: 'output', prompt: 'What prints?', code: [{ text: 'for (int i = 0; i < 5; i++) {' }, { text: '    if (i == 3) break;' }, { text: '    System.out.print(i + " ");' }, { text: '}' }], terminalOutput: '0 1 2 ', options: ['0 1 2 ', '0 1 2 3', '0 1 2 3 4', '3'], correct: 0 },
        { type: 'realworld', prompt: 'Which finds the max?', scenario: '📊 Find biggest in {3, 7, 2, 9, 4}', options: [{ code: 'int[] nums = {3,7,2,9,4};\nint best = nums[0];\nfor (int n : nums) {\n    if (n > best) best = n;\n}', label: 'Enhanced for loop' }, { code: 'int best = Arrays.stream(nums).max().getAsInt();', label: 'Stream max' }, { code: 'Arrays.sort(nums); // mutates!', label: 'Sort first' }, { code: 'int best = nums.length;', label: 'Length' }], correct: 0 },
    ],
    10: [
        { type: 'trace', prompt: 'How many times does println run?', code: [{ text: 'for (int i = 0; i < 3; i++) {' }, { text: '    for (int j = 0; j < 4; j++) {' }, { text: '        System.out.println(i + " " + j);', highlight: true }, { text: '    }' }, { text: '}' }], options: ['7', '12', '9', '16'], correct: 1 },
        { type: 'output', prompt: 'What pattern prints?', code: [{ text: 'for (int i = 1; i <= 3; i++) {' }, { text: '    System.out.println("*".repeat(i));' }, { text: '}' }], terminalOutput: '*\n**\n***', options: ['***\n**\n*', '*\n**\n***', '***', '* * *'], correct: 1 },
        { type: 'scramble', prompt: 'Build a multiplication table row', pieces: [{ id: 'a', text: 'int n = 5;' }, { id: 'b', text: 'for (int i = 1; i <= 10; i++) {' }, { id: 'c', text: '    System.out.printf("%d x %d = %d%n", n, i, n*i);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    System.out.println(n + i);' }], correctOrder: ['a', 'b', 'c', 'd'] },
    ],
    11: [
        { type: 'scramble', prompt: 'Build a prime checker', pieces: [{ id: 'a', text: 'static boolean isPrime(int n) {' }, { id: 'b', text: '    if (n < 2) return false;' }, { id: 'c', text: '    for (int i = 2; i <= Math.sqrt(n); i++) {' }, { id: 'd', text: '        if (n % i == 0) return false;' }, { id: 'e', text: '    }' }, { id: 'f', text: '    return true;' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '    for (int i = 0; i < n; i++) {' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'trace', prompt: 'Stream filter — what prints?', code: [{ text: 'int[] nums = {1, 2, 3, 4, 5, 6};' }, { text: 'int[] evens = Arrays.stream(nums)' }, { text: '    .filter(n -> n % 2 == 0).toArray();' }, { text: 'System.out.println(Arrays.toString(evens));', highlight: true }], options: ['[2, 4, 6]', '[1, 3, 5]', '[1, 2, 3, 4, 5, 6]', '3'], correct: 0 },
        { type: 'fillgap', prompt: 'Complete: stream to square numbers', codeParts: [{ text: 'int[] squares = ', type: 'fixed' }, { text: 'IntStream.rangeClosed(1,5).map(x -> x*x).toArray();', type: 'gap', id: 'g1' }], bank: ['IntStream.rangeClosed(1,5).map(x -> x*x).toArray();', 'new int[]{1,4,9,16,25};', 'Arrays.stream(5).map(x*x);', 'Math.pow(range(5));'], correctFill: { g1: 'IntStream.rangeClosed(1,5).map(x -> x*x).toArray();' } },
    ],
    12: [
        { type: 'pair', prompt: 'Match loop tools', pairs: [{ id: 1, left: 'break', right: 'Exit loop' }, { id: 2, left: 'continue', right: 'Skip iteration' }, { id: 3, left: 'for-each', right: 'Iterate collection' }, { id: 4, left: 'Iterator', right: 'Manual traversal' }] },
        { type: 'output', prompt: 'What prints with continue?', code: [{ text: 'for (int i = 0; i < 5; i++) {' }, { text: '    if (i == 2) continue;' }, { text: '    System.out.print(i + " ");' }, { text: '}' }], terminalOutput: '0 1 3 4 ', options: ['0 1 3 4 ', '0 1 2 3 4', '2', '0 1'], correct: 0 },
    ],
    // ═══ CH4: FUNCTIONS ═══
    13: [
        { type: 'trace', prompt: 'Overloaded method — what prints?', code: [{ text: 'static int add(int a) { return a + 10; }' }, { text: 'static int add(int a, int b) { return a + b; }' }, { text: 'System.out.println(add(3));', highlight: true }], options: ['3', '10', '13', 'Error'], correct: 2 },
        { type: 'bug', prompt: 'Should return sum, not print it', code: [{ text: 'static int add(int a, int b) {', hasError: false }, { text: '    int result = a + b;', hasError: false }, { text: '    System.out.println(result);', hasError: true }], correctLine: 2 },
        { type: 'output', prompt: 'Varargs — what prints?', code: [{ text: 'static int total(int... nums) {' }, { text: '    return Arrays.stream(nums).sum();' }, { text: '}' }, { text: 'System.out.println(total(1, 2, 3, 4));' }], terminalOutput: '10', options: ['[1,2,3,4]', '10', '4', 'Error'], correct: 1 },
        { type: 'scramble', prompt: 'Build an overloaded greet method', pieces: [{ id: 'a', text: 'static String greet(String name) {' }, { id: 'b', text: '    return "Hello, " + name + "!";' }, { id: 'c', text: '}' }, { id: 'd', text: 'static String greet(String name, String greeting) {' }, { id: 'e', text: '    return greeting + ", " + name + "!";' }, { id: 'f', text: '}' }], distractors: [{ id: 'g', text: '    return name + greeting;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        { type: 'trace', prompt: 'Lambda + map — what returns?', code: [{ text: 'List<Integer> nums = List.of(1, 2, 3);' }, { text: 'List<Integer> result = nums.stream()' }, { text: '    .map(x -> x * 2).collect(Collectors.toList());' }, { text: 'System.out.println(result);', highlight: true }], options: ['[2, 4, 6]', '[1, 2, 3]', '6', 'Error'], correct: 0 },
    ],
    14: [
        { type: 'trace', prompt: 'Local vs field — what prints?', code: [{ text: 'String x = "global";' }, { text: 'void f() {' }, { text: '    String x = "local";' }, { text: '    System.out.println(x);', highlight: true }, { text: '}' }], options: ['global', 'local', 'Error', 'null'], correct: 1 },
        { type: 'bug', prompt: 'Why does this cause a compile error?', code: [{ text: 'int total = 0;', hasError: false }, { text: 'static void add(int n) {', hasError: false }, { text: '    total += n;', hasError: true }, { text: '}', hasError: false }], correctLine: 2 },
        { type: 'errordecode', prompt: 'Decode this scope error', errorText: "error: non-static variable total cannot be\nreferenced from a static context\n    total += n;\n    ^", question: 'Fix?', options: ['Make total static', 'Use local variable', 'Import total', 'Delete total'], correct: 0 },
        { type: 'realworld', prompt: 'When to use interfaces?', scenario: '🧠 Multiple implementations of same contract.', options: [{ code: 'interface Multiplier {\n    int multiply(int x);\n}\nMultiplier doubler = x -> x * 2;', label: 'Functional interface + lambda' }, { code: 'int factor = 2;\nint multiply(int x) {\n    return x * factor;\n}', label: 'Static method' }, { code: 'class Mult {\n    int f;\n    Mult(int f) { this.f = f; }\n}', label: 'Full class' }, { code: 'final int mult = 2;', label: 'Constant' }], correct: 0 },
    ],
    15: [
        { type: 'video', title: 'Methods Deep Dive', description: 'Parameters, overloading, varargs, static vs instance, lambdas, functional interfaces, and method references.', duration: '3:30', thumbnail: '🎥' },
        { type: 'pair', prompt: 'Match method concepts', pairs: [{ id: 1, left: 'static', right: 'Class-level method' }, { id: 2, left: 'return', right: 'Send value back' }, { id: 3, left: 'int...', right: 'Varargs' }, { id: 4, left: '->', right: 'Lambda expression' }] },
    ],
    16: [
        { type: 'trace', prompt: 'What does fib(5) return?', code: [{ text: 'static int fib(int n) {' }, { text: '    if (n <= 1) return n;' }, { text: '    return fib(n-1) + fib(n-2);' }, { text: '}' }, { text: 'System.out.println(fib(5));', highlight: true }], options: ['3', '5', '8', '13'], correct: 1 },
        { type: 'errordecode', prompt: 'Decode recursion error', errorText: 'Exception in thread "main"\njava.lang.StackOverflowError\n    at Main.fib(Main.java:2)', question: 'Cause?', options: ['Missing base case', 'Wrong return type', 'Too many params', 'Import error'], correct: 0 },
        { type: 'scramble', prompt: 'Build factorial', pieces: [{ id: 'a', text: 'static int factorial(int n) {' }, { id: 'b', text: '    if (n <= 1) return 1;' }, { id: 'c', text: '    return n * factorial(n - 1);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    return n + factorial(n);' }], correctOrder: ['a', 'b', 'c', 'd'] },
        { type: 'trace', prompt: 'What does sumDigits(123) return?', code: [{ text: 'static int sumDigits(int n) {' }, { text: '    if (n < 10) return n;' }, { text: '    return n % 10 + sumDigits(n / 10);' }, { text: '}' }, { text: 'System.out.println(sumDigits(123));', highlight: true }], options: ['6', '123', '3', '12'], correct: 0 },
        { type: 'realworld', prompt: 'Which is naturally recursive?', scenario: '🤔 Which breaks into same-type subproblems?', options: [{ code: '// File system: folders contain folders', label: 'Directory traversal ✓' }, { code: '// Read file line by line', label: 'File reading' }, { code: '// Print "Hello" 5 times', label: 'Simple loop' }, { code: '// Add two numbers', label: 'Addition' }], correct: 0 },
    ],
    // ═══ CH5+ shares conceptual exercises, falls back to Python ═══
    17: [
        { type: 'trace', prompt: 'References! What prints?', code: [{ text: 'int[] a = {1, 2, 3};' }, { text: 'int[] b = a;' }, { text: 'b[0] = 99;' }, { text: 'System.out.println(a[0]);', highlight: true }], options: ['1', '99', 'Error', '[1,2,3]'], correct: 1 },
        { type: 'output', prompt: 'Arrays.copyOfRange?', code: [{ text: 'int[] x = {10, 20, 30, 40, 50};' }, { text: 'int[] sub = Arrays.copyOfRange(x, 1, 4);' }, { text: 'System.out.println(Arrays.toString(sub));' }], terminalOutput: '[20, 30, 40]', options: ['[10,20,30]', '[20,30,40]', '[20,30,40,50]', '[10,20,30,40]'], correct: 1 },
        { type: 'bug', prompt: 'Why does b change a?', code: [{ text: 'int[] a = {1, 2, 3};', hasError: false }, { text: 'int[] b = a;', hasError: true }, { text: 'b[0] = 99;', hasError: false }, { text: 'System.out.println(Arrays.toString(a));', hasError: false }], correctLine: 1 },
        { type: 'refactor', prompt: 'Copy an array properly?', originalCode: 'int[] original = {1, 2, 3};\nint[] copy = original; // Reference!', options: [{ code: 'int[] copy = original.clone();\n// or Arrays.copyOf(original, original.length)', label: 'Deep copy ✓' }, { code: 'int[] copy = original;', label: 'Still reference' }, { code: 'int[] copy = new int[original];', label: 'Compile error' }], correct: 0 },
    ],
    18: [
        { type: 'trace', prompt: 'Frequency counter?', code: [{ text: 'String word = "banana";' }, { text: 'Map<Character,Integer> freq = new HashMap<>();' }, { text: 'for (char c : word.toCharArray()) {' }, { text: '    freq.merge(c, 1, Integer::sum);' }, { text: '}' }, { text: 'System.out.println(freq.get(\'a\'));', highlight: true }], options: ['1', '2', '3', 'null'], correct: 2 },
        { type: 'fillgap', prompt: 'Check anagram', codeParts: [{ text: 'static boolean isAnagram(String a, String b) {\n    char[] ca = a.toCharArray(), cb = b.toCharArray();\n    ', type: 'fixed' }, { text: 'Arrays.sort(ca); Arrays.sort(cb);\n    return Arrays.equals(ca, cb);', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['Arrays.sort(ca); Arrays.sort(cb);\n    return Arrays.equals(ca, cb);', 'return a.equals(b);', 'return a.length() == b.length();', 'return new HashSet<>(a).equals(new HashSet<>(b));'], correctFill: { g1: 'Arrays.sort(ca); Arrays.sort(cb);\n    return Arrays.equals(ca, cb);' } },
        { type: 'pair', prompt: 'Match Java collections', pairs: [{ id: 1, left: 'ArrayList', right: 'Dynamic array' }, { id: 2, left: 'HashMap', right: 'Key-value O(1)' }, { id: 3, left: 'HashSet', right: 'Unique elements' }, { id: 4, left: 'LinkedList', right: 'Doubly-linked' }] },
    ],
    19: [
        { type: 'scramble', prompt: 'Find duplicates', pieces: [{ id: 'a', text: 'static List<Integer> findDupes(int[] arr) {' }, { id: 'b', text: '    Set<Integer> seen = new HashSet<>();' }, { id: 'c', text: '    Set<Integer> dupes = new HashSet<>();' }, { id: 'd', text: '    for (int x : arr) {' }, { id: 'e', text: '        if (!seen.add(x)) dupes.add(x);' }, { id: 'f', text: '    }' }, { id: 'g', text: '    return new ArrayList<>(dupes);' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '    return Arrays.asList(arr);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
        { type: 'trace', prompt: 'Set retain (intersection)?', code: [{ text: 'Set<Integer> a = new HashSet<>(Set.of(1,2,3,4));' }, { text: 'Set<Integer> b = Set.of(3,4,5,6);' }, { text: 'a.retainAll(b);' }, { text: 'System.out.println(a);', highlight: true }], options: ['[3, 4]', '[1,2,3,4,5,6]', '[1,2]', '[5,6]'], correct: 0 },
    ],
    20: [
        { type: 'pair', prompt: 'Best use-case for each', pairs: [{ id: 1, left: 'ArrayList', right: 'Ordered, index access' }, { id: 2, left: 'HashSet', right: 'Unique + fast lookup' }, { id: 3, left: 'HashMap', right: 'Key-value mapping' }, { id: 4, left: 'int[]', right: 'Fixed-size primitives' }] },
        { type: 'realworld', prompt: 'Which data structure for a phone book?', scenario: '📱 Look up phone number by name.', options: [{ code: 'Map<String,String> pb = new HashMap<>();\npb.put("Ali", "555-1234");', label: 'HashMap — O(1) lookup' }, { code: 'List<String[]> pb = new ArrayList<>();', label: 'List — O(n)' }, { code: 'Set<String> pb = new HashSet<>();', label: 'Set — no values' }, { code: 'String[] pb = {"Ali","555-1234"};', label: 'Flat array' }], correct: 0 },
    ],
}
