/* ══════════════════════════════════════════════════
   PYTHON EXERCISES — CH6-CH10 (nodes 21-42)
   ══════════════════════════════════════════════════ */
export const pyExercisesCh6to10 = {
        21: [
            { type: 'algostep', prompt: 'Selection sort begins on [64,25,12,22,11]', array: [64, 25, 12, 22, 11], step: 1, description: 'Pass 1 scans the whole array for the smallest value.', question: 'What does pass 1 do?', options: ['11→index 0', '12→index 0', '22→index 1', '25→index 0'], correct: 0, explanation: 'Selection sort scans for the minimum of the unsorted part and swaps it to the front — pass 1 finds 11 and puts it at index 0. Each pass fixes exactly one position for good, which is why it always takes n-1 passes no matter how sorted the input already is.', hint: 'Scan the whole array once. What is the smallest value, and where does this algorithm put it?' },
            { type: 'trace', prompt: 'After ONE bubble pass, what is guaranteed?', code: [{ text: '# Compare adjacent, swap if needed' }, { text: '[5,1]→swap [1,5,4,2,8]' }, { text: '[5,4]→swap [1,4,5,2,8]' }, { text: '[5,2]→swap [1,4,2,5,8]' }, { text: '[5,8]→ok   [1,4,2,5,8]', highlight: true }], options: ['Largest at end', 'Array sorted', 'Smallest at start', 'Nothing guaranteed'], correct: 0, explanation: 'Watch what travels: the 5 gets carried rightward by every swap until something bigger stops it — so after one pass the largest element has bubbled all the way to the end, and only that much is promised. The rest is still scrambled ([1,4,2,5,8] is not sorted). That one-guarantee-per-pass is why bubble sort needs up to n-1 passes.', hint: 'Follow the 5 through the swaps. Where does the biggest value always end up, and what happens to everything else?' },
            { type: 'realworld', prompt: 'The array is already 95% sorted. Which sort exploits that?', scenario: '📊 Two elements misplaced, the rest in order.', options: [{ code: 'insertion_sort(arr)', label: 'Insertion sort' }, { code: 'merge_sort(arr)', label: 'Merge sort' }, { code: 'quick_sort(arr)', label: 'Quick sort' }, { code: 'selection_sort(arr)', label: 'Selection sort' }], correct: 0, explanation: 'Insertion sort does almost no work on sorted input: each element compares once against its neighbour and stays put, so a nearly-sorted array finishes in about O(n). Merge sort does its full O(n log n) regardless — it never notices the input is easy. Selection sort scans the whole remainder every pass no matter what. And quicksort with a naive pivot is at its WORST on sorted data. This adaptivity is exactly why Timsort (Python\'s sorted) is built on insertion sort for small runs.', hint: 'Which algorithm gets to stop early when nothing needs moving? Walk one element of sorted input through each.' },
            { type: 'pair', prompt: 'Match each sort to its cost', pairs: [{ id: 1, left: 'Bubble, worst case', right: 'O(n²)' }, { id: 2, left: 'Merge, always', right: 'O(n log n)' }, { id: 3, left: 'Insertion, best case', right: 'O(n)' }, { id: 4, left: 'Python sorted()', right: 'Timsort' }], explanation: 'The qualifier matters as much as the number: merge sort is O(n log n) in EVERY case, insertion sort ranges from O(n) on sorted input to O(n²) on reversed input. Timsort — what sorted() and .sort() actually run — merges the two ideas: insertion sort on small runs, merge sort to combine them, so it inherits the O(n) best case AND the O(n log n) guarantee.' },
            { type: 'scramble', prompt: 'Assemble insertion sort', pieces: [{ id: 'a', text: 'def insertion_sort(arr):' }, { id: 'b', text: '    for i in range(1, len(arr)):' }, { id: 'c', text: '        key = arr[i]' }, { id: 'd', text: '        j = i - 1' }, { id: 'e', text: '        while j >= 0 and arr[j] > key:' }, { id: 'f', text: '            arr[j+1] = arr[j]; j -= 1' }, { id: 'g', text: '        arr[j+1] = key' }], distractors: [{ id: 'h', text: '        arr[j] = key' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'key has to be saved BEFORE the shifting starts, because the shift overwrites arr[i]. The while walks left moving bigger elements one slot right, and when it stops, j+1 is the hole where key belongs. The spare line writes to arr[j] instead of arr[j+1] — off by one slot, which quietly overwrites an element instead of filling the hole.', hint: 'When the while loop stops, where exactly is the empty slot — at j, or at j+1?' },
        ],
        22: [
            { type: 'algostep', prompt: 'Binary search for 7 in [1,3,5,7,9,11,13]', array: [1, 3, 5, 7, 9, 11, 13], step: 1, description: 'lo=0, hi=6, so mid=3 — and arr[3] is checked first.', question: 'How many comparisons does finding 7 take?', options: ['1', '2', '3', '7'], correct: 0, explanation: 'The first midpoint of a 7-element array is index 3, and arr[3] happens to BE the 7 — one comparison, done. That is luck, not the general cost: the guarantee is at most log₂(n)+1 comparisons, so ⌈log₂(7)⌉ ≈ 3 in the worst case. 7 comparisons is what linear search would need if the target were last.', hint: 'Work out which index gets checked first. What value lives there?' },
            { type: 'trace', prompt: '6 is not in the array. What does the search do?', code: [{ text: 'def bsearch(arr, t):' }, { text: '    lo, hi = 0, len(arr)-1' }, { text: '    while lo <= hi:' }, { text: '        mid = (lo+hi)//2' }, { text: '        if arr[mid]==t: return mid' }, { text: '        elif arr[mid]<t: lo=mid+1' }, { text: '        else: hi=mid-1' }, { text: '    return -1', highlight: true }], options: ['Returns 2', 'Returns 3', 'Returns -1', 'Infinite loop'], correct: 2, explanation: 'Trace it: mid=2 → arr[2]=5 < 6 so lo=3; mid=3 → arr[3]=7 > 6 so hi=2. Now lo > hi, the while condition fails, and -1 comes back. The termination is no accident: every pass moves lo up or hi down, so the window must eventually close. An infinite loop is what you get if you write lo=mid instead of lo=mid+1.', hint: 'Run two iterations by hand. What are lo and hi after each, and when does the while stop?' },
            { type: 'errordecode', prompt: 'What is wrong with this midpoint line?', errorText: 'mid = (lo + hi) / 2  # TypeError when used as index:\narr[mid]  # list indices must be integers, not float', question: 'Safe midpoint?', options: ['lo + (hi-lo)//2', '(lo+hi) % 2', 'hi - lo', 'lo * hi'], correct: 0, explanation: 'In Python 3, / always produces a float, and a float cannot index a list — so the fix must use //. The lo + (hi-lo)//2 form is preferred over (lo+hi)//2 for a second reason that Python does not have but Java and C do: lo+hi can overflow a fixed-width int, and this famous bug sat in the JDK\'s own binary search for nine years. % 2 gives 0 or 1, and the other two are not midpoints at all.', hint: 'Two separate issues: what type does / return here, and what could lo+hi do in a fixed-width language?' },
            { type: 'realworld', prompt: 'What must be true of the array before binary search works?', scenario: '⚠️ Break the precondition and the search silently misses values that ARE there.', options: [{ code: 'arr = sorted(data)', label: 'It is sorted' }, { code: 'len(set(arr)) == len(arr)', label: 'All elements unique' }, { code: 'len(arr) < 1000', label: 'It is small' }, { code: 'isinstance(arr, list)', label: 'It is a list' }], correct: 0, explanation: 'Halving only works because comparing against the middle tells you WHICH half the target must be in — and that inference is only valid on sorted data. On unsorted data the search returns wrong answers silently, no error. Duplicates are fine (you just get one of the positions), size is irrelevant, and any indexable sequence works.', hint: 'The algorithm throws half the array away after one comparison. What justifies that?' },
            { type: 'fillgap', prompt: 'On a hit, keep searching left — find the FIRST occurrence', codeParts: [{ text: 'def first_occur(arr, t):\n    lo, hi, result = 0, len(arr)-1, -1\n    while lo <= hi:\n        mid = (lo+hi)//2\n        if arr[mid] == t:\n            ', type: 'fixed' }, { text: 'result = mid; hi = mid - 1', type: 'gap', id: 'g1' }, { text: '\n        elif arr[mid] < t: lo = mid+1\n        else: hi = mid-1\n    return result', type: 'fixed' }], bank: ['result = mid; hi = mid - 1', 'return mid', 'lo = mid + 1', 'break'], correctFill: { g1: 'result = mid; hi = mid - 1' }, explanation: 'A hit might not be the FIRST hit — there could be equal values further left. So the trick is to record the match and keep narrowing leftward; the last recorded mid is the leftmost occurrence. return mid and break both stop at whatever occurrence the search happened to land on, and lo = mid + 1 searches the wrong side, finding the LAST occurrence instead.', hint: 'On [5,7,7,7,9] searching 7, the first probe lands on the middle 7. What must happen next for the answer to be index 1?' },
        ],
        23: [
            { type: 'trace', prompt: 'How does the work grow when n doubles?', code: [{ text: 'for i in range(n):' }, { text: '    for j in range(n):' }, { text: '        print(i, j)' }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'], correct: 1, explanation: 'The inner loop runs n times for each of the n outer passes — n × n = n². The practical meaning: double n and the work quadruples. O(n log n) would need the inner range to shrink or halve; O(2ⁿ) is a different universe, where adding ONE to n doubles the work.', hint: 'Count total prints for n=10, then for n=20. What is the ratio?' },
            { type: 'realworld', prompt: 'Binary search over a million sorted items — how many probes?', scenario: '🔍 1,000,000 sorted integers, one lookup.', options: [{ code: '~20', label: 'About twenty' }, { code: '~1,000,000', label: 'About a million' }, { code: '~500,000', label: 'About half a million' }, { code: '~1,000', label: 'About a thousand' }], correct: 0, explanation: 'Each probe halves the search space, and 2²⁰ ≈ 1,048,576 — so twenty halvings pin down one item among a million. That is the visceral meaning of O(log n): a thousand times more data costs only ten more probes. Half a million is the average for LINEAR search, and a thousand would be √n, which is no standard algorithm here.', hint: 'How many times can you halve 1,000,000 before reaching 1? Count powers of 2.' },
            { type: 'pair', prompt: 'Match each algorithm to its complexity', pairs: [{ id: 1, left: 'Binary Search', right: 'O(log n)' }, { id: 2, left: 'Bubble Sort', right: 'O(n²)' }, { id: 3, left: 'Merge Sort', right: 'O(n log n)' }, { id: 4, left: 'Hash Lookup', right: 'O(1) average' }], explanation: 'A useful reading: log n means "halves the problem each step", n² means "compares pairs", n log n means "divides, then touches everything per level", and O(1) average carries the word average for a reason — a pathological set of colliding keys degrades a hash table to O(n).' },
            { type: 'trace', prompt: 'i is halved each pass. What is the complexity?', code: [{ text: 'i = n' }, { text: 'while i > 0:' }, { text: '    print(i)' }, { text: '    i = i // 2', highlight: true }], options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1, explanation: 'The loop variable is divided, not decremented — that single character difference is the whole answer. From n it takes log₂(n) halvings to reach 0, so the loop body runs O(log n) times. Change the line to i -= 2 and it becomes O(n). Spotting divide-versus-subtract in the update is the fastest complexity tell there is.', hint: 'Look only at the highlighted line. Is i shrinking by a constant amount, or by a constant factor?' },
            { type: 'refactor', prompt: 'The membership check runs thousands of times. Which rewrite pays off?', originalCode: '# Runs in a hot loop:\nif x in my_list:\n    ...', options: [{ code: 'lookup = set(my_list)   # once\nif x in lookup:\n    ...', label: 'Build a set, check the set' }, { code: 'my_list.sort()          # once\ni = bisect.bisect_left(my_list, x)\nif i < len(my_list) and my_list[i] == x:\n    ...', label: 'Sort once, bisect each time' }, { code: 'found = False\nfor item in my_list:\n    if item == x:\n        found = True\n        break', label: 'Loop with early exit' }], correct: 0, explanation: 'The set costs O(n) once, then every check is O(1) — thousands of checks amortise the build immediately. The bisect version genuinely works too, but each check is O(log n) and sorting may destroy an order you needed; it earns its place only when you also need range queries. The manual loop is exactly what `in` already does — same O(n), more code.', hint: 'Separate the one-time cost from the per-check cost. Which option has the cheapest per-check?' },
        ],
        24: [
            { type: 'trace', prompt: 'Which pair does the brute force return first?', code: [{ text: 'def two_sum(nums, t):' }, { text: '    for i in range(len(nums)):' }, { text: '        for j in range(i+1, len(nums)):' }, { text: '            if nums[i]+nums[j]==t:' }, { text: '                return [i,j]' }, { text: 'print(two_sum([2,7,11,15], 9))', highlight: true }], options: ['[0, 1]', '[1, 2]', '[0, 3]', 'None'], correct: 0, explanation: 'The very first pair tried is i=0, j=1: nums[0]+nums[1] = 2+7 = 9 — immediate hit, and the function returns INDICES, not the values themselves. Note j starts at i+1, which is what prevents both using the same element twice and checking each pair twice. None only happens if every pair misses.', hint: 'What is the first (i, j) the loops generate, and what do those two values sum to?' },
            { type: 'refactor', prompt: 'Which rewrite makes two-sum a single pass AND keeps the indices right?', originalCode: 'for i in range(len(nums)):\n    for j in range(i+1, len(nums)):\n        if nums[i]+nums[j]==target: return [i,j]', options: [{ code: 'seen = {}\nfor i, n in enumerate(nums):\n    comp = target - n\n    if comp in seen: return [seen[comp], i]\n    seen[n] = i', label: 'Dict of value→index' }, { code: 'nums.sort()\nlo, hi = 0, len(nums)-1\n# then walk pointers inward', label: 'Sort, then two pointers' }, { code: 'for n in nums:\n    if target - n in nums:\n        return [nums.index(n), nums.index(target-n)]', label: 'Check complement with in' }], correct: 0, explanation: 'The dict answers "have I already seen my complement?" in O(1), one pass total. The two-pointer version is genuinely O(n log n) and elegant — but sort() destroys the original indices, which the problem asks for; you would need to sort (value, index) pairs. The `in` version looks linear but both `in nums` and .index are themselves O(n) scans, so it is still quadratic — and it also breaks when n is its own complement, returning the same index twice.', hint: 'Two of these are faster than the original. Which one still returns the ORIGINAL indices without extra bookkeeping?' },
            { type: 'scramble', prompt: 'Assemble the one-pass two-sum', pieces: [{ id: 'a', text: 'def two_sum(nums, target):' }, { id: 'b', text: '    seen = {}' }, { id: 'c', text: '    for i, n in enumerate(nums):' }, { id: 'd', text: '        comp = target - n' }, { id: 'e', text: '        if comp in seen:' }, { id: 'f', text: '            return [seen[comp], i]' }, { id: 'g', text: '        seen[n] = i' }], distractors: [{ id: 'h', text: '        seen[i] = n' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The check must come BEFORE the insert: check-then-add is what stops an element pairing with itself when target is 2n. The dict maps value→index, so seen[comp] retrieves where the complement was. The spare line maps index→value — backwards, so `comp in seen` would be asking whether the complement is an INDEX, silently wrong on most inputs.', hint: 'The dict is asked "where did I see this VALUE?". Which way round must the keys go for that question to work?' },
            { type: 'output', prompt: 'n iterations, each doing an O(1) lookup — total?', code: [{ text: '# The hash-map two_sum:' }, { text: '#   the loop body runs n times' }, { text: '#   each body does one dict lookup + one insert' }, { text: '# Total = iterations x cost per iteration = ?', highlight: true }], terminalOutput: 'O(n)', options: ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'], correct: 1, explanation: 'n iterations × O(1) each = O(n). The mistake this question exists to catch is multiplying the loop by the SIZE of the dict instead of the COST of the lookup — the dict grows to n entries, but each lookup stays O(1) regardless, because that is the entire point of hashing. O(1) total would mean the loop itself vanished.', hint: 'Multiply the number of iterations by the cost of one iteration — not by the size of anything.' },
        ],
        // ═══ CH7: DATA STRUCTURES II ⭐⭐⭐ ═══
        25: [
            { type: 'trace', prompt: 'Push 1, 2, 3, then pop twice. What remains?', code: [{ text: 'stack = []' }, { text: 'stack.append(1); stack.append(2); stack.append(3)' }, { text: 'stack.pop(); stack.pop()' }, { text: 'print(stack)', highlight: true }], options: ['[1]', '[3]', '[1,2]', '[]'], correct: 0, explanation: 'pop() removes from the END — last in, first out. The two pops take 3 then 2, leaving [1]. Answering [3] means thinking of a queue, where the earliest items leave first; that is exactly the distinction this question tests. In Python a plain list IS the stack idiom: append and pop both work at the tail in O(1).', hint: 'Which end does pop() take from? Remove twice from that end.' },
            { type: 'realworld', prompt: 'Which structure checks "({[]})" correctly?', scenario: '🔍 "({[]})" is balanced; "([)]" is not — same counts, wrong ORDER.', options: [{ code: 'stack: push opener, on closer pop and compare', label: 'Stack' }, { code: 'queue: enqueue opener, on closer dequeue and compare', label: 'Queue' }, { code: 'count = openers - closers; balanced if 0', label: 'Counter' }, { code: 'balanced if set(openers) == set(matching closers)', label: 'Set' }], correct: 0, explanation: 'The most recently opened bracket must close first — that is literally LIFO, so a stack mirrors the structure. The counter is the instructive failure: "([)]" has matching counts and still is not balanced, because nesting is about order, not quantity. A queue checks the OLDEST opener first, backwards. Sets ignore both order and count.', hint: 'Test each candidate on "([)]" — counts match, order does not. Which structure notices?' },
            { type: 'pair', prompt: 'Match each structure to its discipline', pairs: [{ id: 1, left: 'Stack', right: 'Last in, first out' }, { id: 2, left: 'Queue', right: 'First in, first out' }, { id: 3, left: 'Deque', right: 'Both ends open' }, { id: 4, left: 'Priority Queue', right: 'Best out first' }], explanation: 'The discipline — who leaves first — is the entire difference; the storage underneath can be identical. A priority queue is the odd one out: departure order depends on a comparison, not on arrival time, which is why it is backed by a heap rather than a list. Python note: use collections.deque for queues, because list.pop(0) shifts every element.' },
            { type: 'scramble', prompt: 'Assemble the balanced-brackets checker', pieces: [{ id: 'a', text: 'def is_valid(s):' }, { id: 'b', text: '    stack = []' }, { id: 'c', text: '    pairs = {")":"(", "]":"[", "}":"{"}' }, { id: 'd', text: '    for c in s:' }, { id: 'e', text: '        if c in "([{": stack.append(c)' }, { id: 'f', text: '        elif not stack or stack.pop() != pairs[c]:' }, { id: 'g', text: '            return False' }, { id: 'h', text: '    return len(stack) == 0' }], distractors: [{ id: 'i', text: '    return True' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], explanation: 'Two subtleties carry the algorithm. `not stack` must be checked before popping — a closer with nothing open (")(" ) would otherwise crash. And the final line must verify the stack is EMPTY: plain return True passes "(((", where openers never closed. The three ways to fail are wrong pair, early closer, unclosed opener — one line each.', hint: 'Three ways to be unbalanced: wrong match, closer-first, opener never closed. Find the line that catches each.' },
            { type: 'trace', prompt: 'Enqueue A, B, C — which two leave first?', code: [{ text: 'from collections import deque' }, { text: 'q = deque()' }, { text: 'q.append("A"); q.append("B"); q.append("C")' }, { text: 'print(q.popleft(), q.popleft())', highlight: true }], options: ['A B', 'C B', 'A C', 'B C'], correct: 0, explanation: 'popleft takes from the FRONT, so departures follow arrivals: A then B. "C B" is stack thinking. deque exists precisely because list.pop(0) must shift every remaining element — O(n) per dequeue — while popleft is O(1) at both ends.', hint: 'append adds at the right, popleft removes at the left. Who has been waiting longest?' },
        ],
        26: [
            { type: 'trace', prompt: 'What is a.next.val in this chain?', code: [{ text: 'class Node:' }, { text: '    def __init__(self, val): self.val=val; self.next=None' }, { text: 'a=Node(1); b=Node(2); c=Node(3)' }, { text: 'a.next=b; b.next=c' }, { text: 'print(a.next.val)', highlight: true }], options: ['1', '2', '3', 'None'], correct: 1, explanation: 'a.next points at b, and b.val is 2. Reading a chain of dots left to right — a, then .next (b), then .val — is the core skill for every linked-structure problem. a.next.next.val would be 3, and c.next is None, which is how the end of a list announces itself.', hint: 'Resolve one dot at a time: what object is a.next? Then take its val.' },
            { type: 'scramble', prompt: 'Assemble the list traversal', pieces: [{ id: 'a', text: 'def traverse(head):' }, { id: 'b', text: '    curr = head' }, { id: 'c', text: '    while curr:' }, { id: 'd', text: '        print(curr.val)' }, { id: 'e', text: '        curr = curr.next' }], distractors: [{ id: 'f', text: '        curr = curr.prev' }], correctOrder: ['a', 'b', 'c', 'd', 'e'], explanation: 'The loop condition is `while curr`, not `while curr.next` — the latter stops one node early and never prints the last value, the most common traversal off-by-one. Advancing via a separate curr keeps head intact for whoever still needs the list. The spare line needs .prev, which singly-linked nodes do not have.', hint: 'When should the loop stop: at the last node, or after it? Check which condition prints the final value.' },
            { type: 'realworld', prompt: 'Where does a linked list actually beat an array?', scenario: '🤔 Same data, different dominant operation.', options: [{ code: 'insert/remove at the FRONT, constantly', label: 'Heavy work at the head' }, { code: 'data[i] for random i, constantly', label: 'Random access by index' }, { code: 'sort the data repeatedly', label: 'Frequent sorting' }, { code: 'binary search over sorted data', label: 'Binary search' }], correct: 0, explanation: 'Inserting at a list head is relinking two pointers — O(1) — where an array must shift everything. Everything else favours the array: indexing a linked list walks i nodes, sorting wants cheap swaps and locality, and binary search NEEDS O(1) indexing to jump to mid, so it degrades to useless on a linked list. One honest niche, not a general upgrade.', hint: 'Three of these need to jump to arbitrary positions. Which one only ever touches the front?' },
            { type: 'trace', prompt: 'What does this pointer dance accomplish?', code: [{ text: 'prev = None; curr = head' }, { text: 'while curr:' }, { text: '    nxt = curr.next' }, { text: '    curr.next = prev' }, { text: '    prev = curr' }, { text: '    curr = nxt' }, { text: '# when the loop ends, what is prev?', highlight: true }], options: ['The reversed list\'s head, in O(n)', 'The unchanged head', 'None — the list was lost', 'The reversed head, in O(n²)'], correct: 0, explanation: 'Each pass flips one arrow: nxt saves the rest of the list BEFORE curr.next is overwritten — skip that save and the list really is lost, which is the third option. One walk, constant work per node, so O(n) with O(1) extra space. When curr runs off the end, prev holds the last node: the new head.', hint: 'Why is nxt saved first? Delete that line mentally and see what curr = nxt would do.' },
        ],
        27: [
            { type: 'trace', prompt: 'In-order traversal of this BST prints what?', code: [{ text: '#       4' }, { text: '#      / \\' }, { text: '#     2   6' }, { text: '#    / \\' }, { text: '#   1   3' }, { text: '# in-order: visit left subtree, node, right subtree', highlight: true }], options: ['4 2 1 3 6', '1 2 3 4 6', '1 3 2 6 4', '4 2 6 1 3'], correct: 1, explanation: 'In-order goes fully left first: 1, back to 2, then 3, up to 4, then 6 — ascending order. That is not luck: BST invariant (left < node < right) plus in-order = sorted output, always. The first option is pre-order, the third post-order, the last level-order; recognising all four from output is worth drilling.', hint: 'Fully left before every node, right after. Start at the deepest left leaf.' },
            { type: 'pair', prompt: 'Match each traversal to its visiting order', pairs: [{ id: 1, left: 'In-order', right: 'Left, root, right' }, { id: 2, left: 'Pre-order', right: 'Root, left, right' }, { id: 3, left: 'Post-order', right: 'Left, right, root' }, { id: 4, left: 'Level-order', right: 'Layer by layer (BFS)' }], explanation: 'The name says where the ROOT goes: pre (first), in (middle), post (last). Each has a job — pre-order copies a tree, post-order deletes one safely (children before parent), and level-order is the odd one out: it needs a queue, not recursion, because it crosses branches.' },
            { type: 'realworld', prompt: 'What falls out of in-order on a Binary SEARCH Tree?', scenario: '🌳 Not just any binary tree — one with the BST ordering invariant.', options: [{ code: 'the values, in ascending order, O(n)', label: 'Sorted output' }, { code: 'the values, largest first', label: 'Reverse sorted' }, { code: 'insertion order', label: 'Insertion order' }, { code: 'root first, then by depth', label: 'By depth' }], correct: 0, explanation: 'The invariant (left < node < right) applied recursively means "everything printed before a node is smaller" — so in-order streams the whole tree in ascending order in one O(n) pass. Reverse sorted is one edit away: traverse right first. Insertion order is gone forever; the tree reorganised it. This property is why databases love B-trees for range queries.', hint: 'Combine two facts: what in-order visits first, and what the BST promises lives on the left.' },
            { type: 'trace', prompt: 'Searching this BST for 3 — how many nodes are visited?', code: [{ text: '#       4        3 < 4 → go left' }, { text: '#      / \\' }, { text: '#     2   6      3 > 2 → go right' }, { text: '#    / \\' }, { text: '#   1   3        found', highlight: true }], options: ['3', '2', '4', '5'], correct: 0, explanation: 'The path is 4 → 2 → 3: three nodes, one comparison each. That path length is the depth of the target, and in a balanced tree depth is about log₂(n) — the entire reason BSTs exist. Skew the same values into a chain (1→2→3→4→6) and the same search visits nearly every node: O(log n) is a promise about SHAPE, not about trees in general.', hint: 'Count every node the search touches, including the one where it stops.' },
        ],
        28: [
            { type: 'video', title: 'Data Structures Visualized', description: 'Stacks, queues, linked lists, trees — when to use each, trade-offs, and real-world applications.', duration: '4:00', thumbnail: '🎥' },
            { type: 'pair', prompt: 'Match each operation to its cost', pairs: [{ id: 1, left: 'array[i]', right: 'O(1)' }, { id: 2, left: 'Linked list: insert at head', right: 'O(1), two pointers move' }, { id: 3, left: 'BST search, balanced', right: 'O(log n)' }, { id: 4, left: 'Array: insert at front', right: 'O(n), everything shifts' }], explanation: 'Each structure buys one cheap operation by making another expensive: the array\'s O(1) indexing costs it O(n) front-insertion, and the linked list makes the opposite trade. The BST\'s log n carries a hidden condition — "balanced" — which is why self-balancing variants (AVL, red-black) exist at all.' },
        ],
        // ═══ CH8: ALGORITHMS II ⭐⭐⭐⭐ ═══
        29: [
            { type: 'trace', prompt: 'Tower of Hanoi: 3 disks = ? moves', code: [{ text: 'def hanoi(n):' }, { text: '    if n == 1: return 1' }, { text: '    return 2 * hanoi(n-1) + 1' }, { text: 'print(hanoi(3))', highlight: true }], options: ['3', '5', '7', '8'], correct: 2 },
            { type: 'realworld', prompt: 'Which is naturally recursive?', scenario: '🤔 Same-type subproblems?', options: [{ code: '# Directory tree: folders in folders', label: 'File system' }, { code: '# Read file line by line', label: 'Sequential' }, { code: '# Print "Hi" 5 times', label: 'Loop' }, { code: '# Add two nums', label: 'Simple op' }], correct: 0 },
            { type: 'trace', prompt: 'sum_digits(1234)?', code: [{ text: 'def sum_digits(n):' }, { text: '    if n < 10: return n' }, { text: '    return n%10 + sum_digits(n//10)' }, { text: 'print(sum_digits(1234))', highlight: true }], options: ['10', '1234', '4', '24'], correct: 0 },
            { type: 'output', prompt: 'Recursive power complexity?', code: [{ text: 'def power(b, e):' }, { text: '    if e == 0: return 1' }, { text: '    if e % 2 == 0:' }, { text: '        h = power(b, e//2)' }, { text: '        return h * h' }, { text: '    return b * power(b, e-1)' }, { text: '# Halves each time!', highlight: true }], terminalOutput: 'O(log n)', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
            { type: 'scramble', prompt: 'Build binary search recursively', pieces: [{ id: 'a', text: 'def bsearch(arr, t, lo, hi):' }, { id: 'b', text: '    if lo > hi: return -1' }, { id: 'c', text: '    mid = (lo+hi)//2' }, { id: 'd', text: '    if arr[mid] == t: return mid' }, { id: 'e', text: '    elif arr[mid] < t: return bsearch(arr,t,mid+1,hi)' }, { id: 'f', text: '    else: return bsearch(arr,t,lo,mid-1)' }], distractors: [{ id: 'g', text: '    return bsearch(arr,t,lo,hi)' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        ],
        30: [
            { type: 'algostep', prompt: 'Merge [1,3,5] and [2,4,6]', array: [1, 3, 5, 2, 4, 6], step: 1, description: 'Compare: 1<2, take 1. Left:[3,5] Right:[2,4,6]', question: 'Next comparison?', options: ['3 vs 2', '1 vs 2', '5 vs 6', '3 vs 4'], correct: 0 },
            { type: 'trace', prompt: 'Merge sort time complexity?', code: [{ text: '# Divide in half: log₂(n) levels' }, { text: '# Merge: O(n) per level' }, { text: '# Total = levels × work per level = ?', highlight: true }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'], correct: 2 },
            { type: 'scramble', prompt: 'Build merge function', pieces: [{ id: 'a', text: 'def merge(left, right):' }, { id: 'b', text: '    result = []; i = j = 0' }, { id: 'c', text: '    while i<len(left) and j<len(right):' }, { id: 'd', text: '        if left[i]<=right[j]: result.append(left[i]); i+=1' }, { id: 'e', text: '        else: result.append(right[j]); j+=1' }, { id: 'f', text: '    result += left[i:] + right[j:]' }, { id: 'g', text: '    return result' }], distractors: [{ id: 'h', text: '    return left + right' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
            { type: 'pair', prompt: 'Divide & Conquer examples', pairs: [{ id: 1, left: 'Merge Sort', right: 'Split array, sort halves' }, { id: 2, left: 'Quick Sort', right: 'Partition around pivot' }, { id: 3, left: 'Binary Search', right: 'Halve search space' }, { id: 4, left: 'Strassen', right: 'Matrix multiply' }] },
        ],
        31: [
            { type: 'trace', prompt: 'fib(5) calls WITHOUT memo?', code: [{ text: 'def fib(n):' }, { text: '    if n<=1: return n' }, { text: '    return fib(n-1)+fib(n-2)' }, { text: '# How many times is fib() entered for fib(5)?', highlight: true }], options: ['5', '9', '15', '25'], correct: 2 },
            { type: 'refactor', prompt: 'O(2ⁿ) fib → O(n)?', originalCode: 'def fib(n):\n    if n<=1: return n\n    return fib(n-1)+fib(n-2)', options: [{ code: 'memo = {}\ndef fib(n):\n    if n in memo: return memo[n]\n    if n<=1: return n\n    memo[n] = fib(n-1)+fib(n-2)\n    return memo[n]', label: 'Memoization — O(n)' }, { code: 'def fib(n):\n    return n if n<=1 else fib(n-1)+fib(n-2)', label: 'Still O(2ⁿ)' }, { code: 'import math\ndef fib(n): return math.factorial(n)', label: 'Wrong formula' }], correct: 0 },
            { type: 'realworld', prompt: 'What is the fewest coins that make 6 from [1, 3, 4]?', scenario: '💰 Coins: [1, 3, 4]. Target: 6. Take the biggest coin first and see where it lands you.', options: [{ code: '3 + 3 = 6', label: '2 coins' }, { code: '4 + 1 + 1 = 6', label: '3 coins' }, { code: '4 + 3 = 7', label: '2 coins, overshoots' }, { code: '1 * 6 = 6', label: '6 coins' }], correct: 0, explanation: 'Taking the largest coin first (greedy) grabs 4, then can only finish with 1+1 — three coins. Skipping the 4 entirely gives 3+3, two coins. This is exactly why coin change needs DP: the locally best choice is not globally best. Greedy only happens to work on "canonical" systems like [1,5,10,25].', hint: 'Try it once starting from the 4, and once ignoring the 4.' },
            { type: 'fillgap', prompt: 'Complete: climbing stairs DP', codeParts: [{ text: 'def climb(n):\n    if n<=2: return n\n    dp = [0]*(n+1)\n    dp[1], dp[2] = 1, 2\n    for i in range(3, n+1):\n        ', type: 'fixed' }, { text: 'dp[i] = dp[i-1] + dp[i-2]', type: 'gap', id: 'g1' }, { text: '\n    return dp[n]', type: 'fixed' }], bank: ['dp[i] = dp[i-1] + dp[i-2]', 'dp[i] = dp[i-1] * 2', 'dp[i] = i', 'dp[i] = dp[i-1]'], correctFill: { g1: 'dp[i] = dp[i-1] + dp[i-2]' } },
            { type: 'trace', prompt: 'Climbing stairs n=5?', code: [{ text: '# dp[1]=1, dp[2]=2' }, { text: '# dp[3]=3, dp[4]=5' }, { text: '# dp[5] = dp[4]+dp[3] = ?', highlight: true }], options: ['5', '7', '8', '13'], correct: 2 },
        ],
        32: [
            { type: 'trace', prompt: 'Fast power: power(2,10)?', code: [{ text: 'def power(b, e):' }, { text: '    if e==0: return 1' }, { text: '    if e%2==0: h=power(b,e//2); return h*h' }, { text: '    return b*power(b,e-1)' }, { text: 'print(power(2, 10))', highlight: true }], options: ['20', '100', '512', '1024'], correct: 3 },
            { type: 'output', prompt: 'Its complexity?', code: [{ text: '# power(2,10)→power(2,5)→power(2,4)' }, { text: '# →power(2,2)→power(2,1)→power(2,0)', highlight: true }], terminalOutput: 'O(log n)', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
            { type: 'scramble', prompt: 'Build memoized fibonacci', pieces: [{ id: 'a', text: 'memo = {}' }, { id: 'b', text: 'def fib(n):' }, { id: 'c', text: '    if n in memo: return memo[n]' }, { id: 'd', text: '    if n <= 1: return n' }, { id: 'e', text: '    memo[n] = fib(n-1) + fib(n-2)' }, { id: 'f', text: '    return memo[n]' }], distractors: [{ id: 'g', text: '    return fib(n)' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
            { type: 'realworld', prompt: 'When does DP help?', scenario: '🧠 DP works when problem has...', options: [{ code: '# 1. Overlapping subproblems\n# 2. Optimal substructure', label: 'Both conditions' }, { code: '# Only overlapping subproblems', label: 'One condition' }, { code: '# Any recursive problem', label: 'Not always' }, { code: '# Only sorting problems', label: 'Sorting only' }], correct: 0 },
        ],
        // ═══ CH9: ADVANCED ⭐⭐⭐⭐ ═══
        33: [
            { type: 'pair', prompt: 'Match graph terms', pairs: [{ id: 1, left: 'Adjacency List', right: 'Dict of neighbors' }, { id: 2, left: 'Adjacency Matrix', right: '2D array' }, { id: 3, left: 'Directed', right: 'One-way edges' }, { id: 4, left: 'Undirected', right: 'Two-way edges' }] },
            { type: 'realworld', prompt: 'Best graph application?', scenario: '🌍 Real-world graph.', options: [{ code: '# Social network: users=nodes, friends=edges', label: 'Social network' }, { code: '# To-do list', label: 'List' }, { code: '# Calculator', label: 'Calculator' }, { code: '# Timer', label: 'Counter' }], correct: 0 },
            { type: 'output', prompt: 'Adjacency list for A→B, A→C, B→C?', code: [{ text: 'graph = {' }, { text: '    "A": ["B", "C"],' }, { text: '    "B": ["C"],' }, { text: '    "C": []' }, { text: '}' }, { text: 'print(len(graph["A"]))' }], terminalOutput: '2', options: ['1', '2', '3', '0'], correct: 1 },
            { type: 'trace', prompt: 'How many edges in this undirected graph?', code: [{ text: '# A--B, A--C, B--C (triangle)' }, { text: '# Each edge stored twice in adj list' }, { text: '# Total entries in adj lists: 6' }, { text: '# Actual edges:', highlight: true }], options: ['3', '6', '2', '9'], correct: 0 },
        ],
        34: [
            { type: 'trace', prompt: 'BFS from A. Visit order?', code: [{ text: '# A→[B,C], B→[D], C→[D], D→[]' }, { text: 'def bfs(start, graph):' }, { text: '    q = deque([start]); seen = {start}' }, { text: '    while q:' }, { text: '        node = q.popleft(); print(node)' }, { text: '        for n in graph[node]:' }, { text: '            if n not in seen:' }, { text: '                seen.add(n); q.append(n)', highlight: true }], options: ['A B C D', 'A B D C', 'A C B D', 'D B C A'], correct: 0 },
            { type: 'refactor', prompt: 'Cycle detection in directed graph?', originalCode: '# Naive: just "visited" set\n# Cannot distinguish exploring vs explored', options: [{ code: '# 3-color: WHITE→GRAY→BLACK\n# Cycle = visiting GRAY node', label: 'Three-color' }, { code: '# Simple visited set', label: 'Incomplete' }, { code: '# Count edges vs nodes', label: 'Wrong' }], correct: 0 },
            { type: 'realworld', prompt: 'BFS vs DFS — when use BFS?', scenario: '🗺️ Finding shortest path in unweighted graph.', options: [{ code: '# BFS: guarantees shortest path\n# Explores level by level', label: 'BFS — shortest path' }, { code: '# DFS: goes deep first', label: 'DFS — no shortest guarantee' }, { code: '# Both give same path', label: 'Same result' }, { code: '# Neither works', label: 'Neither' }], correct: 0 },
            { type: 'pair', prompt: 'BFS vs DFS', pairs: [{ id: 1, left: 'BFS', right: 'Queue (FIFO)' }, { id: 2, left: 'DFS', right: 'Stack (LIFO)' }, { id: 3, left: 'BFS use', right: 'Shortest path' }, { id: 4, left: 'DFS use', right: 'Cycle detection' }] },
        ],
        35: [
            { type: 'trace', prompt: 'Two-pointer: pair summing to 6 in [1,2,3,4,6]?', code: [{ text: 'lo, hi = 0, 4  # 1+6=7>6' }, { text: 'hi -= 1        # 1+4=5<6' }, { text: 'lo += 1        # 2+4=6 ✓', highlight: true }], options: ['indices [1,5]', 'indices [0,4]', 'indices [1,3]', 'indices [2,3]'], correct: 2 },
            { type: 'refactor', prompt: 'O(n²) duplicates → O(n)?', originalCode: 'for i in range(len(arr)):\n    for j in range(i+1, len(arr)):\n        if arr[i]==arr[j]: return True', options: [{ code: 'return len(arr) != len(set(arr))', label: 'Set — O(n)' }, { code: 'arr.sort()\nfor i in range(len(arr)-1):\n    if arr[i]==arr[i+1]: return True', label: 'Sort — O(n log n)' }, { code: 'from collections import Counter\nreturn max(Counter(arr).values())>1', label: 'Counter — O(n)' }], correct: 0 },
            { type: 'fillgap', prompt: 'Sliding window: max sum of k consecutive', codeParts: [{ text: 'def max_sum(arr, k):\n    window = sum(arr[:k])\n    best = window\n    for i in range(k, len(arr)):\n        ', type: 'fixed' }, { text: 'window += arr[i] - arr[i-k]', type: 'gap', id: 'g1' }, { text: '\n        best = max(best, window)\n    return best', type: 'fixed' }], bank: ['window += arr[i] - arr[i-k]', 'window = sum(arr[i-k:i])', 'window += arr[i]', 'window = arr[i]'], correctFill: { g1: 'window += arr[i] - arr[i-k]' } },
            { type: 'realworld', prompt: 'Sliding window complexity?', scenario: '📊 Instead of recalculating sum each time...', options: [{ code: '# Slide: add new, remove old = O(n)\n# vs recalculate: O(n*k)', label: 'O(n) — add/remove trick' }, { code: '# O(n*k) — recompute each time', label: 'O(n*k)' }, { code: '# O(n²)', label: 'O(n²)' }, { code: '# O(1)', label: 'O(1)' }], correct: 0 },
            { type: 'trace', prompt: 'Remove duplicates in-place from sorted?', code: [{ text: 'arr = [1,1,2,2,3]' }, { text: 'w = 1  # write pointer' }, { text: 'for r in range(1, len(arr)):' }, { text: '    if arr[r] != arr[r-1]:' }, { text: '        arr[w] = arr[r]; w += 1' }, { text: 'print(arr[:w])', highlight: true }], options: ['[1,2,3]', '[1,1,2]', '[2,3]', '[1,2,2,3]'], correct: 0 },
        ],
        36: [
            { type: 'scramble', prompt: 'Build BFS', pieces: [{ id: 'a', text: 'from collections import deque' }, { id: 'b', text: 'def bfs(graph, start):' }, { id: 'c', text: '    q = deque([start])' }, { id: 'd', text: '    visited = {start}' }, { id: 'e', text: '    while q:' }, { id: 'f', text: '        node = q.popleft()' }, { id: 'g', text: '        for nb in graph[node]:' }, { id: 'h', text: '            if nb not in visited:' }, { id: 'i', text: '                visited.add(nb); q.append(nb)' }], distractors: [{ id: 'j', text: '        q.append(node)' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
            { type: 'trace', prompt: 'DFS from A?', code: [{ text: '# A→[B,C], B→[D], C→[], D→[]' }, { text: 'def dfs(node, graph, seen=set()):' }, { text: '    if node in seen: return' }, { text: '    seen.add(node); print(node)' }, { text: '    for n in graph[node]: dfs(n, graph, seen)', highlight: true }], options: ['A B D C', 'A B C D', 'A C B D', 'D B C A'], correct: 0 },
            { type: 'realworld', prompt: 'Graph for GPS navigation?', scenario: '🗺️ Find shortest route between cities.', options: [{ code: '# Weighted graph + Dijkstra\n# Nodes=cities, edges=roads with distance', label: 'Weighted graph' }, { code: '# Simple array of cities', label: 'Array' }, { code: '# Unweighted BFS', label: 'Missing distances' }, { code: '# Binary tree', label: 'Not a tree' }], correct: 0 },
        ],
        // ═══ CH10: MASTERY ⭐⭐⭐⭐ ═══
        37: [
            { type: 'trace', prompt: 'Climbing stairs n=4?', code: [{ text: '# dp[0]=1, dp[1]=1' }, { text: '# dp[2] = dp[1]+dp[0] = 2' }, { text: '# dp[3] = dp[2]+dp[1] = 3' }, { text: '# dp[4] = dp[3]+dp[2] = ?', highlight: true }], options: ['4', '5', '6', '8'], correct: 1 },
            { type: 'realworld', prompt: 'Which is a DP problem?', scenario: '🧠 Overlapping subproblems + optimal substructure?', options: [{ code: '# Longest Common Subsequence\n# LCS("ABCDE","ACE")="ACE"', label: 'LCS — classic DP' }, { code: '# Find max in array', label: 'Simple scan' }, { code: '# Print all elements', label: 'Traverse' }, { code: '# Swap variables', label: 'Basic op' }], correct: 0 },
            { type: 'pair', prompt: 'Match DP patterns', pairs: [{ id: 1, left: 'Fibonacci', right: 'dp[i]=dp[i-1]+dp[i-2]' }, { id: 2, left: 'Knapsack', right: 'Include or exclude item' }, { id: 3, left: 'LCS', right: 'Match or skip chars' }, { id: 4, left: 'Coin Change', right: 'min(dp[amt-coin]+1)' }] },
            { type: 'fillgap', prompt: 'Complete: 0/1 Knapsack', codeParts: [{ text: 'def knapsack(W, wt, val, n):\n    dp = [[0]*(W+1) for _ in range(n+1)]\n    for i in range(1, n+1):\n        for w in range(1, W+1):\n            if wt[i-1] <= w:\n                ', type: 'fixed' }, { text: 'dp[i][w] = max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w])', type: 'gap', id: 'g1' }, { text: '\n            else:\n                dp[i][w] = dp[i-1][w]\n    return dp[n][W]', type: 'fixed' }], bank: ['dp[i][w] = max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w])', 'dp[i][w] = val[i-1]', 'dp[i][w] = dp[i-1][w] + 1', 'dp[i][w] = w'], correctFill: { g1: 'dp[i][w] = max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w])' } },
        ],
        38: [
            { type: 'refactor', prompt: 'Primes up to n — best approach?', originalCode: '# Brute: O(n√n)\nfor i in range(2, n+1):\n    if is_prime(i): result.append(i)', options: [{ code: '# Sieve of Eratosthenes: O(n log log n)\nsieve = [True]*(n+1)\nfor i in range(2, int(n**0.5)+1):\n    if sieve[i]:\n        for j in range(i*i, n+1, i):\n            sieve[j] = False', label: 'Sieve — much faster' }, { code: '# Check all divisors', label: 'Still brute' }, { code: '# Random testing', label: 'Probabilistic' }], correct: 0 },
            { type: 'pair', prompt: 'Match pattern to problem', pairs: [{ id: 1, left: 'Sliding window', right: 'Max subarray of size k' }, { id: 2, left: 'Two pointer', right: 'Pair sum sorted' }, { id: 3, left: 'BFS', right: 'Shortest path unweighted' }, { id: 4, left: 'DP', right: 'Min coins for amount' }] },
            { type: 'realworld', prompt: 'Problem-solving strategy?', scenario: '🎯 You get a hard problem in an interview.', options: [{ code: '# 1. Brute force first\n# 2. Identify pattern\n# 3. Optimize with right DS\n# 4. Code + test edge cases', label: 'Structured approach' }, { code: '# Jump to optimal solution', label: 'Risky' }, { code: '# Give up', label: 'Never!' }, { code: '# Memorize solutions', label: 'Not scalable' }], correct: 0 },
            { type: 'scramble', prompt: 'Build Sieve of Eratosthenes', pieces: [{ id: 'a', text: 'def sieve(n):' }, { id: 'b', text: '    is_prime = [True] * (n+1)' }, { id: 'c', text: '    is_prime[0] = is_prime[1] = False' }, { id: 'd', text: '    for i in range(2, int(n**0.5)+1):' }, { id: 'e', text: '        if is_prime[i]:' }, { id: 'f', text: '            for j in range(i*i, n+1, i):' }, { id: 'g', text: '                is_prime[j] = False' }, { id: 'h', text: '    return [i for i in range(n+1) if is_prime[i]]' }], distractors: [{ id: 'i', text: '            is_prime[i] = False' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
        ],
        39: [
            { type: 'fillgap', prompt: 'Reverse string in-place', codeParts: [{ text: 'def reverse(s):\n    lo, hi = 0, len(s)-1\n    while lo < hi:\n        ', type: 'fixed' }, { text: 's[lo], s[hi] = s[hi], s[lo]', type: 'gap', id: 'g1' }, { text: '\n        lo += 1; hi -= 1', type: 'fixed' }], bank: ['s[lo], s[hi] = s[hi], s[lo]', 's.reverse()', 'lo, hi = hi, lo', 's[lo] = s[hi]'], correctFill: { g1: 's[lo], s[hi] = s[hi], s[lo]' } },
            { type: 'terminal', prompt: 'FizzBuzz 1-15', expectedCommands: ['for i in range(1, 16):', '    if i%15==0: print("FizzBuzz")', '    elif i%3==0: print("Fizz")', '    elif i%5==0: print("Buzz")', '    else: print(i)'], hint: 'Check 15 first!', terminalHistory: [{ type: 'system', text: '>>> Interview: FizzBuzz' }] },
            { type: 'trace', prompt: 'Valid palindrome check?', code: [{ text: 'def is_palindrome(s):' }, { text: '    s = s.lower()' }, { text: '    s = "".join(c for c in s if c.isalnum())' }, { text: '    return s == s[::-1]' }, { text: 'print(is_palindrome("A man, a plan, a canal: Panama"))', highlight: true }], options: ['True', 'False', 'Error', 'None'], correct: 0 },
            { type: 'scramble', prompt: 'Build valid anagram checker', pieces: [{ id: 'a', text: 'def is_anagram(s, t):' }, { id: 'b', text: '    if len(s) != len(t): return False' }, { id: 'c', text: '    from collections import Counter' }, { id: 'd', text: '    return Counter(s) == Counter(t)' }], distractors: [{ id: 'e', text: '    return s == t' }], correctOrder: ['a', 'b', 'c', 'd'] },
            { type: 'realworld', prompt: 'Most asked interview pattern?', scenario: '💼 Top coding interview topics.', options: [{ code: '# Arrays + Hash Maps: ~40% of problems\n# Two pointer, sliding window, sorting', label: 'Arrays + Hashing' }, { code: '# Graph algorithms only', label: 'Graphs (~15%)' }, { code: '# Dynamic Programming only', label: 'DP (~20%)' }, { code: '# Linked lists only', label: 'LL (~10%)' }], correct: 0 },
        ],
        40: [
            { type: 'trace', prompt: 'Matrix search (sorted rows+cols)?', code: [{ text: 'def search(m, t):' }, { text: '    r, c = 0, len(m[0])-1' }, { text: '    while r<len(m) and c>=0:' }, { text: '        if m[r][c]==t: return True' }, { text: '        elif m[r][c]>t: c-=1' }, { text: '        else: r+=1' }, { text: '    return False' }, { text: 'print(search([[1,4,7],[2,5,8],[3,6,9]], 5))', highlight: true }], options: ['True', 'False', 'Error', '[1,1]'], correct: 0 },
            { type: 'output', prompt: 'Its complexity?', code: [{ text: '# Start top-right' }, { text: '# Each step: eliminate row or col' }, { text: '# At most m+n steps', highlight: true }], terminalOutput: 'O(m+n)', options: ['O(m×n)', 'O(m+n)', 'O(log(mn))', 'O(1)'], correct: 1 },
            { type: 'refactor', prompt: 'Max subarray — which algo?', originalCode: '# Brute: O(n²)\nfor i in range(n):\n    curr = 0\n    for j in range(i, n):\n        curr += arr[j]\n        best = max(best, curr)', options: [{ code: "# Kadane's: O(n)\ncurr = best = arr[0]\nfor x in arr[1:]:\n    curr = max(x, curr+x)\n    best = max(best, curr)", label: "Kadane's — O(n)" }, { code: '# Sort + take last k', label: 'Sorting' }, { code: '# Recursion no memo', label: 'O(2ⁿ)' }], correct: 0 },
            { type: 'trace', prompt: "Kadane's on [-2,1,-3,4,-1,2,1,-5,4]?", code: [{ text: '# curr: -2→1→-2→4→3→5→6→1→5' }, { text: '# best: -2→1→ 1→4→4→5→6→6→6' }, { text: 'print(best)', highlight: true }], options: ['4', '6', '7', '5'], correct: 1 },
            { type: 'scramble', prompt: "Build Kadane's algorithm", pieces: [{ id: 'a', text: 'def max_subarray(nums):' }, { id: 'b', text: '    curr = best = nums[0]' }, { id: 'c', text: '    for x in nums[1:]:' }, { id: 'd', text: '        curr = max(x, curr + x)' }, { id: 'e', text: '        best = max(best, curr)' }, { id: 'f', text: '    return best' }], distractors: [{ id: 'g', text: '        curr += x' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        ],
        41: [
            { type: 'pair', prompt: 'Advanced concepts', pairs: [{ id: 1, left: 'Amortized O(1)', right: 'Avg cost over many ops' }, { id: 2, left: 'NP-Complete', right: 'No known fast solution' }, { id: 3, left: 'Space-Time Tradeoff', right: 'Memory saves time' }, { id: 4, left: 'Greedy', right: 'Local optimal choices' }] },
            { type: 'trace', prompt: 'Greedy: activity selection?', code: [{ text: '# Activities: (start, end)' }, { text: '# [(1,4),(3,5),(0,6),(5,7),(8,9),(5,9)]' }, { text: '# Sort by end time, pick non-overlapping' }, { text: '# Pick: (1,4),(5,7),(8,9)', highlight: true }], options: ['3 activities', '2 activities', '4 activities', '6 activities'], correct: 0 },
            { type: 'realworld', prompt: 'When does greedy FAIL?', scenario: '⚠️ Greedy doesnt always give optimal.', options: [{ code: '# Coin change: coins=[1,3,4], amount=6\n# Greedy: 4+1+1=3 coins\n# Optimal: 3+3=2 coins!', label: 'Coin change with special coins' }, { code: '# Activity selection', label: 'Greedy works here' }, { code: '# Making change with [1,5,10,25]', label: 'Standard coins work' }, { code: '# Huffman coding', label: 'Greedy optimal' }], correct: 0 },
        ],
        42: [
            { type: 'realworld', prompt: 'Journey complete! Next step?', scenario: '🎓 You mastered: variables→loops→functions→DS→algorithms→DP→graphs!', options: [{ code: '# Build real projects!\n# Apply to apps, APIs, open source', label: 'Build projects! 🚀' }, { code: '# Review everything', label: 'Review' }, { code: '# Just read more', label: 'More books' }, { code: '# Stop forever', label: 'Never stop!' }], correct: 0 },
            { type: 'pair', prompt: 'Your journey recap', pairs: [{ id: 1, left: 'CH1-2', right: 'Variables & Flow' }, { id: 2, left: 'CH3-4', right: 'Loops & Functions' }, { id: 3, left: 'CH5-7', right: 'Data Structures' }, { id: 4, left: 'CH8-10', right: 'Algorithms & DP' }] },
            { type: 'trace', prompt: 'Final puzzle: what does this return?', code: [{ text: 'def mystery(n):' }, { text: '    if n == 0: return 1' }, { text: '    return n * mystery(n-1)' }, { text: 'print(mystery(5))', highlight: true }], options: ['5', '15', '120', '720'], correct: 2 },
        ],
}
