/* ══════════════════════════════════════════════════
   JAVA EXERCISES — CH6-CH10 (nodes 21-42)
   Expanded: 4-5 exercises per node, diverse types
   University-aligned: MIT 6.031, Princeton COS226
   ══════════════════════════════════════════════════ */
export const javaExercisesCh6to10 = {
    // ═══ CH6: ALGORITHMS I ═══
    21: [
        { type: 'algostep', prompt: 'Selection sort: find min in [64,25,12,22,11]', array: [64, 25, 12, 22, 11], step: 1, description: 'Scanning for minimum...', question: 'After pass 1?', options: ['[11,25,12,22,64]', '[11,64,25,22,12]', '[12,25,64,22,11]', '[11,25,64,22,12]'], correct: 0 },
        { type: 'pair', prompt: 'Match sort to complexity', pairs: [{ id: 1, left: 'Arrays.sort(int[])', right: 'Dual-Pivot Quicksort O(n log n)' }, { id: 2, left: 'Collections.sort()', right: 'TimSort O(n log n)' }, { id: 3, left: 'Insertion sort (best)', right: 'O(n) already sorted' }, { id: 4, left: 'Bubble sort', right: 'O(n²) worst/avg' }] },
        { type: 'trace', prompt: 'Insertion sort: after inserting 3 into [1,2,5,7]?', code: [{ text: '// key = 3, shift 5→, 7 already shifted' }, { text: '// [1,2,_,5,7] → insert 3' }, { text: '// Result: [1,2,3,5,7]', highlight: true }], options: ['[1,2,3,5,7]', '[3,1,2,5,7]', '[1,2,5,3,7]', '[1,3,2,5,7]'], correct: 0 },
        { type: 'bug', prompt: 'Sort comparison bug?', code: [{ text: 'Integer[] arr = {10, 9, 1, 2, 100};', hasError: false }, { text: 'Arrays.sort(arr, (a,b) -> a - b);', hasError: true }, { text: '// Works for small numbers but...', hasError: false }, { text: '// Integer.MIN_VALUE - 1 = overflow!', hasError: false }], correctLine: 1 },
        { type: 'realworld', prompt: 'Which sort is stable?', scenario: '⚖️ Stability: equal elements keep original order', options: [{ code: '// Merge sort, TimSort, Insertion sort', label: 'Merge, Tim, Insertion ✓' }, { code: '// Quick sort', label: 'Quicksort is NOT stable' }, { code: '// All sorts are stable', label: 'Not true' }, { code: '// Heap sort', label: 'Heapsort is NOT stable' }], correct: 0 },
    ],
    22: [
        { type: 'algostep', prompt: 'Binary search for 7 in [1,3,5,7,9,11,13]', array: [1, 3, 5, 7, 9, 11, 13], step: 1, description: 'lo=0 hi=6 mid=3 arr[3]=7=target!', question: 'Comparisons?', options: ['1', '2', '3', '7'], correct: 0 },
        { type: 'trace', prompt: 'Search for 6 in {1,3,5,7,9}?', code: [{ text: 'int lo=0, hi=4;' }, { text: 'while (lo <= hi) {' }, { text: '    int mid = lo + (hi-lo)/2;' }, { text: '    if (arr[mid]==6) return mid;' }, { text: '    else if (arr[mid]<6) lo=mid+1;' }, { text: '    else hi=mid-1;' }, { text: '}' }, { text: 'return -1;', highlight: true }], options: ['Returns 2', 'Returns 3', 'Returns -1', 'Infinite loop'], correct: 2 },
        { type: 'errordecode', prompt: 'Classic binary search overflow', errorText: 'int mid = (lo + hi) / 2;\n// If lo=1500000000, hi=2000000000\n// lo+hi overflows int!', question: 'Safe formula?', options: ['lo + (hi - lo) / 2', '(lo + hi) % 2', 'hi - lo', 'lo >>> 1'], correct: 0 },
        { type: 'scramble', prompt: 'Binary search iterative', pieces: [{ id: 'a', text: 'static int bsearch(int[] arr, int t) {' }, { id: 'b', text: '    int lo = 0, hi = arr.length - 1;' }, { id: 'c', text: '    while (lo <= hi) {' }, { id: 'd', text: '        int mid = lo + (hi - lo) / 2;' }, { id: 'e', text: '        if (arr[mid] == t) return mid;' }, { id: 'f', text: '        else if (arr[mid] < t) lo = mid + 1;' }, { id: 'g', text: '        else hi = mid - 1;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return -1;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        lo = mid;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
    ],
    23: [
        { type: 'trace', prompt: 'Nested loop complexity?', code: [{ text: 'for (int i=0; i<n; i++)' }, { text: '    for (int j=0; j<n; j++)' }, { text: '        System.out.println(i+","+j);' }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'], correct: 1 },
        { type: 'pair', prompt: 'Java collections complexity', pairs: [{ id: 1, left: 'HashMap.get()', right: 'O(1) amortized' }, { id: 2, left: 'TreeMap.get()', right: 'O(log n)' }, { id: 3, left: 'ArrayList.get(i)', right: 'O(1)' }, { id: 4, left: 'LinkedList.get(i)', right: 'O(n)' }] },
        { type: 'trace', prompt: 'Log complexity loop?', code: [{ text: 'int i = n;' }, { text: 'while (i > 0) {' }, { text: '    System.out.println(i);' }, { text: '    i = i / 2;', highlight: true }, { text: '}' }], options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
        { type: 'refactor', prompt: 'O(n) lookup with HashSet', originalCode: '// O(n) check\nfor (int x : arr)\n    if (x == target) return true;', options: [{ code: 'Set<Integer> set = new HashSet<>(Arrays.asList(arr));\nreturn set.contains(target); // O(1)', label: 'HashSet — O(1) lookup' }, { code: 'Arrays.sort(arr);\n// binary search', label: 'Sort + search O(n log n)' }, { code: 'return Arrays.asList(arr).indexOf(target) >= 0;', label: 'Still O(n)' }], correct: 0 },
    ],
    24: [
        { type: 'trace', prompt: 'Two-sum brute force result?', code: [{ text: 'int[] nums = {2,7,11,15};' }, { text: 'int target = 9;' }, { text: 'for (int i=0; i<nums.length; i++)' }, { text: '    for (int j=i+1; j<nums.length; j++)' }, { text: '        if (nums[i]+nums[j]==target)' }, { text: '            return new int[]{i,j};', highlight: true }], options: ['[0,1]', '[1,2]', '[0,3]', 'null'], correct: 0 },
        { type: 'refactor', prompt: 'O(n) two-sum with HashMap', originalCode: '// O(n²) brute force', options: [{ code: 'Map<Integer,Integer> map = new HashMap<>();\nfor (int i=0; i<nums.length; i++) {\n    int comp = target - nums[i];\n    if (map.containsKey(comp)) return new int[]{map.get(comp),i};\n    map.put(nums[i], i);\n}', label: 'HashMap — O(n)' }, { code: 'Arrays.sort(nums); // loses indices', label: 'Sort loses indices' }, { code: 'Set<Integer> set = new HashSet<>();', label: 'Set — no indices' }], correct: 0 },
        { type: 'scramble', prompt: 'Build HashMap two-sum', pieces: [{ id: 'a', text: 'Map<Integer,Integer> map = new HashMap<>();' }, { id: 'b', text: 'for (int i = 0; i < nums.length; i++) {' }, { id: 'c', text: '    int complement = target - nums[i];' }, { id: 'd', text: '    if (map.containsKey(complement)) {' }, { id: 'e', text: '        return new int[]{map.get(complement), i};' }, { id: 'f', text: '    }' }, { id: 'g', text: '    map.put(nums[i], i);' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '    map.put(i, nums[i]);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
        { type: 'realworld', prompt: 'When HashMap fails?', scenario: '⚠️ HashMap vs TreeMap trade-offs', options: [{ code: '// HashMap: O(1) avg but O(n) worst (hash collisions)\n// TreeMap: O(log n) guaranteed', label: 'Collision degrades HashMap' }, { code: '// HashMap always O(1)', label: 'Not guaranteed' }, { code: '// TreeMap is always faster', label: 'Usually slower' }, { code: '// They are the same', label: 'Different implementations' }], correct: 0 },
    ],
    // ═══ CH7: DATA STRUCTURES II ═══
    25: [
        { type: 'trace', prompt: 'Stack push 1,2,3 then pop twice?', code: [{ text: 'Deque<Integer> stack = new ArrayDeque<>();' }, { text: 'stack.push(1); stack.push(2); stack.push(3);' }, { text: 'stack.pop(); stack.pop();' }, { text: 'System.out.println(stack.peek());', highlight: true }], options: ['1', '2', '3', 'null'], correct: 0 },
        { type: 'pair', prompt: 'Java Stack implementations', pairs: [{ id: 1, left: 'ArrayDeque', right: 'Preferred stack impl' }, { id: 2, left: 'Stack class', right: 'Legacy (synchronized)' }, { id: 3, left: 'LinkedList', right: 'As Deque/Queue' }, { id: 4, left: 'PriorityQueue', right: 'Heap-based min PQ' }] },
        { type: 'scramble', prompt: 'Check balanced brackets', pieces: [{ id: 'a', text: 'boolean isValid(String s) {' }, { id: 'b', text: '    Deque<Character> stack = new ArrayDeque<>();' }, { id: 'c', text: '    Map<Character,Character> pairs = Map.of(\\\')\\\',\\\'(\\\', \\\']\\\',\\\'[\\\', \\\'}\\\',\\\'{\\\');' }, { id: 'd', text: '    for (char c : s.toCharArray()) {' }, { id: 'e', text: '        if ("([{".indexOf(c) >= 0) stack.push(c);' }, { id: 'f', text: '        else if (stack.isEmpty() || stack.pop() != pairs.get(c))' }, { id: 'g', text: '            return false;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return stack.isEmpty();' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '    return true;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'bug', prompt: 'Why not use Stack class?', code: [{ text: 'Stack<Integer> s = new Stack<>();', hasError: true }, { text: '// Stack extends Vector (synchronized)', hasError: false }, { text: '// Use Deque<Integer> instead', hasError: false }], correctLine: 0 },
    ],
    26: [
        { type: 'trace', prompt: 'head.next.val?', code: [{ text: 'class Node { int val; Node next; }' }, { text: 'Node a=new Node(1), b=new Node(2), c=new Node(3);' }, { text: 'a.next=b; b.next=c;' }, { text: 'System.out.println(a.next.val);', highlight: true }], options: ['1', '2', '3', 'NPE'], correct: 1 },
        { type: 'scramble', prompt: 'Reverse linked list', pieces: [{ id: 'a', text: 'Node reverse(Node head) {' }, { id: 'b', text: '    Node prev = null, curr = head;' }, { id: 'c', text: '    while (curr != null) {' }, { id: 'd', text: '        Node next = curr.next;' }, { id: 'e', text: '        curr.next = prev;' }, { id: 'f', text: '        prev = curr;' }, { id: 'g', text: '        curr = next;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return prev;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        curr.next = next;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'realworld', prompt: 'LinkedList vs ArrayList?', scenario: '🤔 Java collections trade-offs', options: [{ code: '// LinkedList: O(1) insert/delete at head\n// ArrayList: O(1) random access\n// ArrayList usually wins (cache locality)', label: 'ArrayList usually faster ✓' }, { code: '// LinkedList always faster', label: 'Rarely true' }, { code: '// Same performance', label: 'Very different' }, { code: '// Use arrays instead', label: 'Collections are better' }], correct: 0 },
        { type: 'bug', prompt: 'NPE in linked list traversal?', code: [{ text: 'Node curr = head;', hasError: false }, { text: 'while (curr.next != null) {', hasError: true }, { text: '    curr = curr.next;', hasError: false }, { text: '}', hasError: false }], correctLine: 1 },
    ],
    27: [
        { type: 'trace', prompt: 'In-order BST traversal?', code: [{ text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '//    / \\' }, { text: '//   1   3' }, { text: '// In-order: L→Root→R', highlight: true }], options: ['4 2 1 3 6', '1 2 3 4 6', '1 3 2 6 4', '4 2 6 1 3'], correct: 1 },
        { type: 'pair', prompt: 'Java tree implementations', pairs: [{ id: 1, left: 'TreeMap', right: 'Red-Black BST' }, { id: 2, left: 'PriorityQueue', right: 'Binary Heap' }, { id: 3, left: 'TreeSet', right: 'Sorted unique set' }, { id: 4, left: 'HashMap', right: 'Hash table (not tree)' }] },
        { type: 'fillgap', prompt: 'BST search recursive', codeParts: [{ text: 'Node search(Node root, int val) {\n    if (root == null || root.val == val) return root;\n    return val < root.val\n        ? ', type: 'fixed' }, { text: 'search(root.left, val)', type: 'gap', id: 'g1' }, { text: '\n        : search(root.right, val);\n}', type: 'fixed' }], bank: ['search(root.left, val)', 'search(root.right, val)', 'search(root, val-1)', 'root.left'], correctFill: { g1: 'search(root.left, val)' } },
        { type: 'realworld', prompt: 'When to use TreeMap over HashMap?', scenario: '🌳 Ordered operations needed', options: [{ code: '// TreeMap: sorted keys, range queries\n// .firstKey(), .lastKey(), .subMap()', label: 'Need sorted order/ranges ✓' }, { code: '// Always use HashMap', label: 'HashMap has no order' }, { code: '// TreeMap is always faster', label: 'HashMap is faster for lookup' }, { code: '// Use both', label: 'Pick one based on need' }], correct: 0 },
    ],
    28: [
        { type: 'video', title: 'Data Structures Visualized', description: 'Stacks (ArrayDeque), Queues (PriorityQueue), LinkedList, Trees (TreeMap) — Java implementations, trade-offs.', duration: '4:00', thumbnail: '🎥' },
        { type: 'pair', prompt: 'Operation complexities', pairs: [{ id: 1, left: 'ArrayList.get(i)', right: 'O(1)' }, { id: 2, left: 'LinkedList.add(0,x)', right: 'O(1)' }, { id: 3, left: 'TreeMap.get(key)', right: 'O(log n)' }, { id: 4, left: 'ArrayList.add(0,x)', right: 'O(n)' }] },
        { type: 'trace', prompt: 'PriorityQueue order?', code: [{ text: 'PriorityQueue<Integer> pq = new PriorityQueue<>();' }, { text: 'pq.add(5); pq.add(1); pq.add(3);' }, { text: 'System.out.println(pq.poll());', highlight: true }], options: ['5', '1', '3', 'Error'], correct: 1 },
        { type: 'realworld', prompt: 'Queue in Java — which impl?', scenario: '📋 Need FIFO queue for BFS', options: [{ code: 'Deque<Integer> queue = new ArrayDeque<>()', label: 'ArrayDeque ✓ (fastest)' }, { code: 'Queue<Integer> q = new LinkedList<>()', label: 'Works but slower' }, { code: 'Stack<Integer> s = new Stack<>()', label: 'LIFO not FIFO' }, { code: 'List<Integer> q = new ArrayList<>()', label: 'No queue ops' }], correct: 0 },
    ],
    // ═══ CH8: ALGORITHMS II ═══
    29: [
        { type: 'trace', prompt: 'Tower of Hanoi: 3 disks = ? moves', code: [{ text: 'int hanoi(int n) {' }, { text: '    if (n == 1) return 1;' }, { text: '    return 2 * hanoi(n-1) + 1;' }, { text: '}' }, { text: 'System.out.println(hanoi(3));', highlight: true }], options: ['3', '5', '7', '8'], correct: 2 },
        { type: 'fillgap', prompt: 'Recursive sum of digits', codeParts: [{ text: 'int sumDigits(int n) {\n    if (n < 10) return n;\n    return ', type: 'fixed' }, { text: 'n % 10 + sumDigits(n / 10);', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['n % 10 + sumDigits(n / 10);', 'n + sumDigits(n - 1);', 'sumDigits(n % 10);', 'n / 10 + n % 10;'], correctFill: { g1: 'n % 10 + sumDigits(n / 10);' } },
        { type: 'errordecode', prompt: 'StackOverflowError cause?', errorText: 'Exception in thread "main" java.lang.StackOverflowError\n    at Recursion.factorial(Recursion.java:3)', question: 'Root cause?', options: ['Missing base case or recursion too deep', 'Array too large', 'Null pointer', 'Syntax error'], correct: 0 },
        { type: 'bug', prompt: 'Factorial bug — which line?', code: [{ text: 'int factorial(int n) {', hasError: false }, { text: '    return n * factorial(n - 1);', hasError: true }, { text: '}', hasError: false }], correctLine: 1 },
    ],
    30: [
        { type: 'algostep', prompt: 'Merge [1,3,5] and [2,4,6]', array: [1, 3, 5, 2, 4, 6], step: 1, description: 'Compare 1 vs 2, take 1.', question: 'Next?', options: ['3 vs 2', '1 vs 2', '5 vs 6', '3 vs 4'], correct: 0 },
        { type: 'pair', prompt: 'Divide & Conquer', pairs: [{ id: 1, left: 'Merge Sort', right: 'O(n log n) stable' }, { id: 2, left: 'Quick Sort', right: 'O(n log n) avg, unstable' }, { id: 3, left: 'Binary Search', right: 'O(log n)' }, { id: 4, left: 'Karatsuba', right: 'Fast multiplication' }] },
        { type: 'trace', prompt: 'Merge sort space complexity?', code: [{ text: '// Creates new arrays at each level' }, { text: '// Total extra space ≈ O(n)', highlight: true }], options: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'], correct: 1 },
        { type: 'scramble', prompt: 'Build merge function', pieces: [{ id: 'a', text: 'void merge(int[] arr, int l, int m, int r) {' }, { id: 'b', text: '    int[] left = Arrays.copyOfRange(arr, l, m+1);' }, { id: 'c', text: '    int[] right = Arrays.copyOfRange(arr, m+1, r+1);' }, { id: 'd', text: '    int i=0, j=0, k=l;' }, { id: 'e', text: '    while (i<left.length && j<right.length)' }, { id: 'f', text: '        arr[k++] = left[i]<=right[j] ? left[i++] : right[j++];' }, { id: 'g', text: '    while (i<left.length) arr[k++] = left[i++];' }, { id: 'h', text: '    while (j<right.length) arr[k++] = right[j++];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    Arrays.sort(arr, l, r+1);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
    ],
    31: [
        { type: 'refactor', prompt: 'O(2ⁿ) fib → O(n) with memo', originalCode: 'int fib(int n) {\n    if (n<=1) return n;\n    return fib(n-1)+fib(n-2);\n}', options: [{ code: 'Map<Integer,Integer> memo = new HashMap<>();\nint fib(int n) {\n    if (memo.containsKey(n)) return memo.get(n);\n    if (n<=1) return n;\n    int val = fib(n-1)+fib(n-2);\n    memo.put(n, val);\n    return val;\n}', label: 'Memoization ✓' }, { code: 'Same recursive code', label: 'Still O(2ⁿ)' }, { code: 'int fib = Math.factorial(n);', label: 'Wrong' }], correct: 0 },
        { type: 'fillgap', prompt: 'Tabulation — bottom-up DP', codeParts: [{ text: 'int fib(int n) {\n    if (n <= 1) return n;\n    int[] dp = new int[n+1];\n    dp[0]=0; dp[1]=1;\n    for (int i=2; i<=n; i++)\n        ', type: 'fixed' }, { text: 'dp[i] = dp[i-1] + dp[i-2];', type: 'gap', id: 'g1' }, { text: '\n    return dp[n];\n}', type: 'fixed' }], bank: ['dp[i] = dp[i-1] + dp[i-2];', 'dp[i] = dp[i-1] * 2;', 'dp[i] = i;', 'dp[i] = dp[i-1];'], correctFill: { g1: 'dp[i] = dp[i-1] + dp[i-2];' } },
        { type: 'realworld', prompt: 'Memoization vs Tabulation?', scenario: '🧠 Two DP approaches in Java', options: [{ code: '// Memo: HashMap + recursion (top-down)\n// Tab: array + iteration (bottom-up)\n// Tab avoids StackOverflow!', label: 'Top-down vs bottom-up ✓' }, { code: '// Same thing', label: 'Different approaches' }, { code: '// Always use memo', label: 'Tab better for large n' }, { code: '// Always use tab', label: 'Depends on problem' }], correct: 0 },
        { type: 'trace', prompt: 'Climbing stairs dp[4]?', code: [{ text: '// dp[1]=1, dp[2]=2' }, { text: '// dp[3]=dp[2]+dp[1]=3' }, { text: '// dp[4]=dp[3]+dp[2]=?', highlight: true }], options: ['4', '5', '6', '8'], correct: 1 },
    ],
    32: [
        { type: 'trace', prompt: 'Fast exponentiation: power(2,10)?', code: [{ text: 'long power(long b, int e) {' }, { text: '    if (e==0) return 1;' }, { text: '    if (e%2==0) { long h=power(b,e/2); return h*h; }' }, { text: '    return b*power(b,e-1);' }, { text: '}' }, { text: '// power(2,10) = ?', highlight: true }], options: ['20', '100', '512', '1024'], correct: 3 },
        { type: 'scramble', prompt: 'Build coin change DP', pieces: [{ id: 'a', text: 'int coinChange(int[] coins, int amount) {' }, { id: 'b', text: '    int[] dp = new int[amount+1];' }, { id: 'c', text: '    Arrays.fill(dp, amount+1);' }, { id: 'd', text: '    dp[0] = 0;' }, { id: 'e', text: '    for (int i=1; i<=amount; i++)' }, { id: 'f', text: '        for (int c : coins)' }, { id: 'g', text: '            if (c<=i) dp[i] = Math.min(dp[i], dp[i-c]+1);' }, { id: 'h', text: '    return dp[amount]>amount ? -1 : dp[amount];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    dp[0] = 1;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
        { type: 'realworld', prompt: 'When does DP help?', scenario: '🧠 DP requires...', options: [{ code: '// 1. Overlapping subproblems\n// 2. Optimal substructure', label: 'Both conditions ✓' }, { code: '// Any recursive problem', label: 'Not always' }, { code: '// Sorting only', label: 'Much broader' }, { code: '// Only Fibonacci', label: 'Many applications' }], correct: 0 },
    ],
    // ═══ CH9: ADVANCED ═══
    33: [
        { type: 'pair', prompt: 'Graph representations', pairs: [{ id: 1, left: 'Adjacency List', right: 'List<List<Integer>>' }, { id: 2, left: 'Adjacency Matrix', right: 'int[][]' }, { id: 3, left: 'Edge List', right: 'List<int[]>' }, { id: 4, left: 'Space: List vs Matrix', right: 'O(V+E) vs O(V²)' }] },
        { type: 'fillgap', prompt: 'Build adjacency list', codeParts: [{ text: 'List<List<Integer>> buildGraph(int n, int[][] edges) {\n    List<List<Integer>> g = new ArrayList<>();\n    for (int i=0; i<n; i++) g.add(new ArrayList<>());\n    for (int[] e : edges) {\n        ', type: 'fixed' }, { text: 'g.get(e[0]).add(e[1]);', type: 'gap', id: 'g1' }, { text: '\n    }\n    return g;\n}', type: 'fixed' }], bank: ['g.get(e[0]).add(e[1]);', 'g.add(e[0]);', 'g[e[0]] = e[1];', 'g.set(e[0], e[1]);'], correctFill: { g1: 'g.get(e[0]).add(e[1]);' } },
        { type: 'realworld', prompt: 'Adjacency list vs matrix?', scenario: '🤔 When which?', options: [{ code: '// List: sparse graphs (V+E << V²)\n// Matrix: dense graphs, fast edge lookup', label: 'Sparse→List, Dense→Matrix ✓' }, { code: '// Always use list', label: 'Matrix better for dense' }, { code: '// Always use matrix', label: 'Wastes space for sparse' }, { code: '// Use edge list', label: 'Slowest lookups' }], correct: 0 },
        { type: 'output', prompt: 'Graph neighbors?', code: [{ text: 'Map<String,List<String>> g = Map.of(' }, { text: '    "A", List.of("B","C"),' }, { text: '    "B", List.of("C"),' }, { text: '    "C", List.of()' }, { text: ');' }, { text: 'System.out.println(g.get("A").size());' }], terminalOutput: '2', options: ['1', '2', '3', '0'], correct: 1 },
    ],
    34: [
        { type: 'trace', prompt: 'BFS from A: visit order?', code: [{ text: '// A→[B,C], B→[D], C→[D], D→[]' }, { text: 'Queue<String> q = new LinkedList<>();' }, { text: 'q.add("A"); Set<String> seen = new HashSet<>();' }, { text: 'seen.add("A");' }, { text: '// Process: A→enqueue B,C → B→enqueue D → C→D already seen', highlight: true }], options: ['A B C D', 'A B D C', 'A C B D', 'D B C A'], correct: 0 },
        { type: 'pair', prompt: 'BFS vs DFS in Java', pairs: [{ id: 1, left: 'BFS', right: 'Queue (ArrayDeque)' }, { id: 2, left: 'DFS iterative', right: 'Stack (ArrayDeque)' }, { id: 3, left: 'DFS recursive', right: 'Call stack' }, { id: 4, left: 'BFS finds', right: 'Shortest path unweighted' }] },
        { type: 'scramble', prompt: 'BFS with Java Queue', pieces: [{ id: 'a', text: 'void bfs(Map<String,List<String>> g, String start) {' }, { id: 'b', text: '    Queue<String> q = new ArrayDeque<>();' }, { id: 'c', text: '    Set<String> visited = new HashSet<>();' }, { id: 'd', text: '    q.add(start); visited.add(start);' }, { id: 'e', text: '    while (!q.isEmpty()) {' }, { id: 'f', text: '        String node = q.poll();' }, { id: 'g', text: '        for (String nb : g.get(node)) {' }, { id: 'h', text: '            if (!visited.contains(nb)) {' }, { id: 'i', text: '                visited.add(nb); q.add(nb);' }, { id: 'j', text: '            }' }, { id: 'k', text: '        }' }, { id: 'l', text: '    }' }, { id: 'm', text: '}' }], distractors: [{ id: 'n', text: '        String node = q.peek();' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'] },
        { type: 'bug', prompt: 'ConcurrentModificationException risk?', code: [{ text: 'for (String node : graph.keySet()) {', hasError: true }, { text: '    if (condition) graph.remove(node);', hasError: false }], correctLine: 0 },
    ],
    35: [
        { type: 'trace', prompt: 'Two-pointer: pair=6 in [1,2,3,4,6]?', code: [{ text: 'int lo=0, hi=4; // 1+6=7>6' }, { text: 'hi--;           // 1+4=5<6' }, { text: 'lo++;           // 2+4=6 ✓', highlight: true }], options: ['[1,5]', '[0,4]', '[1,3]', '[2,3]'], correct: 2 },
        { type: 'fillgap', prompt: 'Sliding window max sum', codeParts: [{ text: 'int maxSum(int[] arr, int k) {\n    int window = 0;\n    for (int i=0; i<k; i++) window += arr[i];\n    int best = window;\n    for (int i=k; i<arr.length; i++) {\n        ', type: 'fixed' }, { text: 'window += arr[i] - arr[i-k];', type: 'gap', id: 'g1' }, { text: '\n        best = Math.max(best, window);\n    }\n    return best;\n}', type: 'fixed' }], bank: ['window += arr[i] - arr[i-k];', 'window = arr[i];', 'window += arr[i];', 'window -= arr[i-k];'], correctFill: { g1: 'window += arr[i] - arr[i-k];' } },
        { type: 'refactor', prompt: 'Contains duplicate — O(n)?', originalCode: '// O(n²)\nfor (int i=0; i<n; i++)\n    for (int j=i+1; j<n; j++)\n        if (arr[i]==arr[j]) return true;', options: [{ code: 'Set<Integer> seen = new HashSet<>();\nfor (int x : arr)\n    if (!seen.add(x)) return true;', label: 'HashSet.add returns false if exists ✓' }, { code: 'Arrays.sort(arr);\n// check adjacent', label: 'O(n log n)' }, { code: 'return new HashSet<>(Arrays.asList(arr)).size() != arr.length;', label: 'Also O(n) but autoboxes' }], correct: 0 },
        { type: 'realworld', prompt: 'Two-pointer vs HashMap?', scenario: '🤔 Which approach when?', options: [{ code: '// Two-pointer: sorted input\n// HashMap: unsorted, need O(1) lookup', label: 'Sorted→pointers, Unsorted→map ✓' }, { code: '// Always use HashMap', label: 'Two-pointer saves space' }, { code: '// Always use two-pointer', label: 'Needs sorted input' }, { code: '// Same thing', label: 'Different approaches' }], correct: 0 },
    ],
    36: [
        { type: 'scramble', prompt: 'DFS recursive', pieces: [{ id: 'a', text: 'void dfs(int node, List<List<Integer>> g, boolean[] vis) {' }, { id: 'b', text: '    vis[node] = true;' }, { id: 'c', text: '    System.out.println(node);' }, { id: 'd', text: '    for (int nb : g.get(node)) {' }, { id: 'e', text: '        if (!vis[nb]) dfs(nb, g, vis);' }, { id: 'f', text: '    }' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '        dfs(nb, g, vis);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'pair', prompt: 'Graph algorithm applications', pairs: [{ id: 1, left: 'BFS', right: 'Shortest unweighted path' }, { id: 2, left: 'DFS', right: 'Topological sort (COS226)' }, { id: 3, left: 'Dijkstra', right: 'Shortest weighted path' }, { id: 4, left: 'Union-Find', right: 'Connected components' }] },
        { type: 'trace', prompt: 'DFS from 0: visit order?', code: [{ text: '// 0→[1,2], 1→[3], 2→[], 3→[]' }, { text: '// DFS: 0 → 1 → 3 → backtrack → 2', highlight: true }], options: ['0 1 3 2', '0 1 2 3', '0 2 1 3', '3 1 2 0'], correct: 0 },
        { type: 'errordecode', prompt: 'Graph cycle → infinite recursion', errorText: 'StackOverflowError at dfs(Graph.java:5)', question: 'Fix?', options: ['Add visited[] check before recursing', 'Increase stack size', 'Use BFS instead', 'Remove edges'], correct: 0 },
    ],
    // ═══ CH10: MASTERY ═══
    37: [
        { type: 'pair', prompt: 'DP patterns (MIT 6.006)', pairs: [{ id: 1, left: 'Fibonacci', right: 'dp[i]=dp[i-1]+dp[i-2]' }, { id: 2, left: '0-1 Knapsack', right: 'Include or exclude' }, { id: 3, left: 'LCS', right: 'Match chars or skip' }, { id: 4, left: 'Coin Change', right: 'min(dp[amt-c]+1)' }] },
        { type: 'fillgap', prompt: 'LCS in Java', codeParts: [{ text: 'int lcs(String a, String b) {\n    int[][] dp = new int[a.length()+1][b.length()+1];\n    for (int i=1; i<=a.length(); i++)\n        for (int j=1; j<=b.length(); j++)\n            dp[i][j] = a.charAt(i-1)==b.charAt(j-1)\n                ? ', type: 'fixed' }, { text: 'dp[i-1][j-1] + 1', type: 'gap', id: 'g1' }, { text: '\n                : Math.max(dp[i-1][j], dp[i][j-1]);\n    return dp[a.length()][b.length()];\n}', type: 'fixed' }], bank: ['dp[i-1][j-1] + 1', 'dp[i][j] + 1', 'dp[i-1][j-1]', 'i + j'], correctFill: { g1: 'dp[i-1][j-1] + 1' } },
        { type: 'trace', prompt: 'LCS of "ABCBDAB" and "BDCAB"?', code: [{ text: '// LCS = "BCAB" or "BDAB" → length 4', highlight: true }], options: ['3', '4', '5', '7'], correct: 1 },
        { type: 'realworld', prompt: 'DP in production?', scenario: '🏭 Real DP applications', options: [{ code: '// Git diff: longest common subsequence\n// Spell check: edit distance\n// Knapsack: resource allocation', label: 'Diff, spell check, allocation ✓' }, { code: '// Only academic', label: 'Very practical!' }, { code: '// Only Fibonacci', label: 'Many applications' }, { code: '// Only in Java', label: 'Language-agnostic' }], correct: 0 },
    ],
    38: [
        { type: 'pair', prompt: 'Pattern → problem', pairs: [{ id: 1, left: 'Sliding window', right: 'Max subarray size k' }, { id: 2, left: 'Two pointer', right: 'Pair sum sorted' }, { id: 3, left: 'BFS', right: 'Shortest unweighted' }, { id: 4, left: 'DP', right: 'Min coins' }] },
        { type: 'realworld', prompt: 'Interview strategy?', scenario: '🎯 Hard problem approach', options: [{ code: '// 1. Brute force\n// 2. Find pattern\n// 3. Optimize DS\n// 4. Code + edge cases', label: 'Structured ✓' }, { code: '// Jump to optimal', label: 'Risky' }, { code: '// Give up', label: 'Never!' }, { code: '// Memorize', label: 'Not scalable' }], correct: 0 },
        { type: 'trace', prompt: 'Kadane max subarray [-2,1,-3,4,-1,2,1,-5,4]?', code: [{ text: '// curr max at each step:' }, { text: '// -2,1,-2,4,3,5,6,1,5' }, { text: '// global max = 6', highlight: true }], options: ['6', '5', '4', '7'], correct: 0 },
        { type: 'scramble', prompt: 'Kadane algorithm', pieces: [{ id: 'a', text: 'int maxSubArray(int[] nums) {' }, { id: 'b', text: '    int curr = nums[0], best = nums[0];' }, { id: 'c', text: '    for (int i = 1; i < nums.length; i++) {' }, { id: 'd', text: '        curr = Math.max(nums[i], curr + nums[i]);' }, { id: 'e', text: '        best = Math.max(best, curr);' }, { id: 'f', text: '    }' }, { id: 'g', text: '    return best;' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '        curr += nums[i];' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
    ],
    39: [
        { type: 'fillgap', prompt: 'Reverse array in-place', codeParts: [{ text: 'void reverse(int[] arr) {\n    int lo = 0, hi = arr.length - 1;\n    while (lo < hi) {\n        ', type: 'fixed' }, { text: 'int tmp = arr[lo]; arr[lo] = arr[hi]; arr[hi] = tmp;', type: 'gap', id: 'g1' }, { text: '\n        lo++; hi--;\n    }\n}', type: 'fixed' }], bank: ['int tmp = arr[lo]; arr[lo] = arr[hi]; arr[hi] = tmp;', 'arr[lo] = arr[hi];', 'swap(lo, hi);', 'Collections.swap(arr, lo, hi);'], correctFill: { g1: 'int tmp = arr[lo]; arr[lo] = arr[hi]; arr[hi] = tmp;' } },
        { type: 'trace', prompt: 'Palindrome check?', code: [{ text: 'boolean isPalindrome(String s) {' }, { text: '    s = s.toLowerCase().replaceAll("[^a-z0-9]","");' }, { text: '    return new StringBuilder(s).reverse().toString().equals(s);' }, { text: '}' }, { text: '// isPalindrome("A man, a plan, a canal: Panama")', highlight: true }], options: ['true', 'false', 'Error', 'null'], correct: 0 },
        { type: 'scramble', prompt: 'Valid anagram', pieces: [{ id: 'a', text: 'boolean isAnagram(String s, String t) {' }, { id: 'b', text: '    if (s.length() != t.length()) return false;' }, { id: 'c', text: '    char[] a = s.toCharArray(), b = t.toCharArray();' }, { id: 'd', text: '    Arrays.sort(a); Arrays.sort(b);' }, { id: 'e', text: '    return Arrays.equals(a, b);' }, { id: 'f', text: '}' }], distractors: [{ id: 'g', text: '    return s.equals(t);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        { type: 'bug', prompt: 'Contains duplicate — why slow?', code: [{ text: 'for (int i=0; i<n; i++)', hasError: false }, { text: '    for (int j=i+1; j<n; j++)', hasError: true }, { text: '        if (arr[i]==arr[j]) return true;', hasError: false }], correctLine: 1 },
    ],
    40: [
        { type: 'trace', prompt: 'Matrix search O(m+n)?', code: [{ text: '// Start top-right corner' }, { text: '// > target: go left' }, { text: '// < target: go down', highlight: true }], options: ['O(m+n)', 'O(m*n)', 'O(log(mn))', 'O(1)'], correct: 0 },
        { type: 'scramble', prompt: 'Binary search iterative', pieces: [{ id: 'a', text: 'int search(int[] nums, int target) {' }, { id: 'b', text: '    int lo = 0, hi = nums.length - 1;' }, { id: 'c', text: '    while (lo <= hi) {' }, { id: 'd', text: '        int mid = lo + (hi - lo) / 2;' }, { id: 'e', text: '        if (nums[mid] == target) return mid;' }, { id: 'f', text: '        else if (nums[mid] < target) lo = mid + 1;' }, { id: 'g', text: '        else hi = mid - 1;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return -1;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        lo = mid;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'realworld', prompt: 'Final boss tip?', scenario: '🏆 What makes a great solution?', options: [{ code: '// Correct + readable + optimal\n// Handle edge cases\n// Explain time/space complexity', label: 'All three matter ✓' }, { code: '// Just make it work', label: 'Correctness alone insufficient' }, { code: '// Fastest possible', label: 'Readability matters too' }, { code: '// Shortest code', label: 'Code golf ≠ production' }], correct: 0 },
        { type: 'errordecode', prompt: 'ArrayIndexOutOfBoundsException', errorText: 'java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5', question: 'Cause?', options: ['Array indices are 0 to length-1, not 1 to length', 'Array too small', 'Null array', 'Wrong type'], correct: 0 },
    ],
    41: [
        { type: 'pair', prompt: 'Advanced CS concepts', pairs: [{ id: 1, left: 'Amortized O(1)', right: 'ArrayList.add avg' }, { id: 2, left: 'NP-Complete', right: 'TSP, SAT, Clique' }, { id: 3, left: 'Space-Time', right: 'HashMap caches results' }, { id: 4, left: 'Greedy', right: 'Local optimal choices' }] },
        { type: 'trace', prompt: 'Greedy activity selection?', code: [{ text: '// Sort by end time' }, { text: '// [(1,4),(3,5),(0,6),(5,7),(8,9)]' }, { text: '// Pick: (1,4),(5,7),(8,9)', highlight: true }], options: ['3', '2', '4', '5'], correct: 0 },
        { type: 'realworld', prompt: 'When greedy fails?', scenario: '⚠️ Greedy ≠ optimal always', options: [{ code: '// Coin change: coins=[1,3,4], amt=6\n// Greedy: 4+1+1=3 coins\n// DP: 3+3=2 coins!', label: 'Special coin denominations' }, { code: '// Activity selection', label: 'Greedy works' }, { code: '// Standard coins [1,5,10,25]', label: 'Greedy works' }, { code: '// Huffman', label: 'Greedy optimal' }], correct: 0 },
    ],
    42: [
        { type: 'realworld', prompt: 'Journey complete! Next step?', scenario: '🎓 Mastered: variables→loops→functions→DS→algorithms→DP→graphs!', options: [{ code: '// Build real projects!\n// Contribute to open source\n// Apply concepts to real applications', label: 'Build projects! 🚀' }, { code: '// Review everything', label: 'Review' }, { code: '// Just read more', label: 'More books' }, { code: '// Stop forever', label: 'Never stop!' }], correct: 0 },
        { type: 'pair', prompt: 'Journey recap', pairs: [{ id: 1, left: 'CH1-2', right: 'Variables & Flow' }, { id: 2, left: 'CH3-4', right: 'Loops & Functions' }, { id: 3, left: 'CH5-7', right: 'Data Structures' }, { id: 4, left: 'CH8-10', right: 'Algorithms & DP' }] },
        { type: 'trace', prompt: 'Final puzzle: mystery(5)?', code: [{ text: 'static int mystery(int n) {' }, { text: '    if (n == 0) return 1;' }, { text: '    return n * mystery(n - 1);' }, { text: '}' }, { text: 'System.out.println(mystery(5));', highlight: true }], options: ['5', '15', '120', '720'], correct: 2 },
        { type: 'scramble', prompt: 'Final: memoized fibonacci', pieces: [{ id: 'a', text: 'static Map<Integer,Integer> memo = new HashMap<>();' }, { id: 'b', text: 'static int fib(int n) {' }, { id: 'c', text: '    if (memo.containsKey(n)) return memo.get(n);' }, { id: 'd', text: '    if (n <= 1) return n;' }, { id: 'e', text: '    int val = fib(n-1) + fib(n-2);' }, { id: 'f', text: '    memo.put(n, val);' }, { id: 'g', text: '    return val;' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '    return fib(n-1) + fib(n-2);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
    ],
}
