/* ══════════════════════════════════════════════════
   JAVASCRIPT EXERCISES — Journey Nodes
   ══════════════════════════════════════════════════ */
export const jsExercises = {
    // ═══ CH1: BASICS ═══
    1: [
        { type: 'trace', prompt: 'What is the value of `count`?', code: [{ text: 'let count = 0;' }, { text: 'for (let i = 0; i < 5; i++) {' }, { text: '    if (i % 2 === 0) {' }, { text: '        count++;' }, { text: '    }' }, { text: '}' }, { text: 'console.log(count);', highlight: true }], options: ['2', '3', '5', '4'], correct: 1, explanation: 'let count survives the loop because let is block-scoped to the for, not recreated per pass. Five values of i (0..4), three even (0, 2, 4) — the usual slip is forgetting 0 counts as even, which lands you on 2.', hint: 'Write down what i is on each pass, then tick the even ones.' },
        { type: 'realworld', prompt: 'Which code counts total items in a cart?', scenario: '🛒 Cart: 3 apples, 2 oranges, 1 banana.', options: [{ code: 'const cart = [3, 2, 1];\nconst total = cart.reduce((a,b) => a+b, 0);', label: 'reduce()' }, { code: 'const cart = 3 + 2 + 1;\nconst total = cart.length;', label: '.length on number' }, { code: 'const cart = "3 2 1";\nconst total = cart.length;', label: 'String length' }, { code: 'const cart = new Set([3,2,1]);\nconst total = Math.max(...cart);', label: 'Max of set' }], correct: 0, explanation: 'reduce with a 0 seed adds the quantities: 6. .length on the array would give 3 — the number of product KINDS — and on a number it is undefined, not an error. Silent wrong answers are the theme: nothing here crashes.', hint: 'Two of these run fine and still give the wrong number. Which answers "how many items", not "how many kinds"?' },
        { type: 'pair', prompt: 'Match JavaScript concepts', pairs: [{ id: 1, left: 'let', right: 'Block-scoped variable' }, { id: 2, left: 'const', right: 'Immutable binding' }, { id: 3, left: 'typeof', right: 'Check data type' }, { id: 4, left: '===', right: 'Strict equality' }], explanation: 'let re-assigns, const does not — but const only freezes the BINDING, not the contents of an object it points to. typeof asks the type at runtime, and === is the equality to default to: == coerces types first, which is where the famous JS surprises live.' },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'let x = 7;' }, { text: 'let y = 2;' }, { text: 'console.log(Math.floor(x/y), x%y);' }], terminalOutput: '3 1', options: ['3.5 1', '3 1', '3.5 0', '3 0'], correct: 1, explanation: 'Math.floor(7/2) is 3 — JS has no integer division, / always produces 3.5 and the floor must be explicit. % gives the remainder 1.', hint: 'One operator needs help to drop the fraction in JS. Which one, and what provides it?' },
        { type: 'fillgap', prompt: 'Complete: swap two variables with destructuring', codeParts: [{ text: 'let a = 5;\nlet b = 10;\n', type: 'fixed' }, { text: '[a, b] = [b, a];', type: 'gap', id: 'g1' }], bank: ['[a, b] = [b, a];', 'a = b; b = a;', 'swap(a, b);', 'a === b;'], correctFill: { g1: '[a, b] = [b, a];' }, explanation: 'The right side [b, a] is built completely before the destructuring assigns, so both old values still exist at the critical moment — same principle as Python\'s tuple swap. a = b; b = a fails because the first statement already destroyed the old a.', hint: 'Step through a = b; b = a by hand. What does a hold when the second statement runs?' },
        { type: 'scramble', prompt: 'Build code to calculate BMI', pieces: [{ id: 'a', text: 'const weight = 70;' }, { id: 'b', text: 'const height = 1.75;' }, { id: 'c', text: 'const bmi = weight / (height ** 2);' }, { id: 'd', text: 'console.log(bmi.toFixed(1));' }], distractors: [{ id: 'e', text: 'const bmi = weight * height;' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'No name can be used before the line that creates it: both measurements before the formula, bmi before the log. toFixed(1) returns a STRING with one decimal — fine for display, a trap if you calculate with it afterwards. The spare line multiplies instead of dividing: runs clean, means nothing.', hint: 'Order the lines so no name is mentioned before the line that creates it.' },
    ],
    2: [
        { type: 'bug', prompt: 'Find the syntax error', code: [{ text: 'function greet(name) {', hasError: false }, { text: '    let msg = "Hello " + name;', hasError: false }, { text: '    console.log(msg', hasError: true }, { text: '    return msg;', hasError: false }], correctLine: 2, explanation: 'console.log(msg never closes its parenthesis, so the parser keeps consuming the next line looking for it — which is why reported positions often sit one line below the real mistake. Always check the line above the one blamed.', hint: 'Count opening and closing brackets on each line.' },
        { type: 'errordecode', prompt: 'Decode this error', errorText: 'Uncaught SyntaxError: Unexpected token }\n    at greet (main.js:4)\n    at main.js:6', question: 'What caused this?', options: ['Missing closing parenthesis', 'Undefined variable', 'Wrong indentation', 'Invalid string'], correct: 0, explanation: 'The parser hit } while still waiting for the ) that print(msg never closed — the token is unexpected because something else was due first. Syntax errors report where parsing FAILED, not where the mistake was made; hunt upward from the reported line.', hint: 'What was the parser still waiting for when it met the } ?' },
        { type: 'refactor', prompt: 'Which is the cleanest?', originalCode: 'let x = 10;\nlet r;\nif (x > 5) {\n    r = "big";\n} else {\n    r = "small";\n}\nconsole.log(r);', options: [{ code: 'const x = 10;\nconst r = x > 5 ? "big" : "small";\nconsole.log(r);', label: 'Ternary expression' }, { code: 'let x = 10;\nlet r = "";\nif (x > 5) r = "big";\nif (x <= 5) r = "small";', label: 'Two ifs' }, { code: 'x > 5 ? console.log("big") : console.log("small");', label: 'Console in ternary' }], correct: 0, explanation: 'The ternary assigns once into a const — r can never be left undefined. Two independent ifs re-test the same value and will silently disagree the day one is edited. The third hard-codes the 10 and throws the value away instead of storing it.', hint: 'Which version still works if x changes, and can never leave r empty?' },
        { type: 'bug', prompt: 'Why does this give wrong result?', code: [{ text: 'const age = prompt("Age: ");', hasError: false }, { text: 'if (age > 18) {', hasError: true }, { text: '    console.log("Adult");', hasError: false }], correctLine: 1, explanation: 'prompt() returns a STRING, and "9" > 18 coerces the string to a number — works for 9, but "abc" becomes NaN and every comparison with NaN is false. Worse: with two strings, > compares alphabetically. Number(age) first, then compare.', hint: 'What type does prompt() hand back, and what does > do when one side is a string?' },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'let x = "5";' }, { text: 'let y = 3;' }, { text: 'console.log(x.repeat(y));' }], terminalOutput: '555', options: ['15', '555', '53', 'Error'], correct: 1, explanation: 'repeat(3) copies the string three times: "555". Note JS needs the explicit method — unlike Python, "5" * 3 would COERCE and give 15, arguably the bigger trap: the two languages disagree on what string-times-number means.', hint: 'Is x text or a number? And what does .repeat do that * would not?' },
        { type: 'trace', prompt: 'What is typeof result?', code: [{ text: 'let a = 10;' }, { text: 'let b = 3;' }, { text: 'let result = a / b;' }, { text: 'console.log(typeof result);', highlight: true }], options: ['"integer"', '"number"', '"string"', '3.33'], correct: 1, explanation: 'typeof says "number" — JS has exactly one number type for integers and floats alike. There is no "integer" in typeof\'s vocabulary, which is why that option cannot be right no matter what the division produced.', hint: 'How many numeric types does JavaScript\'s typeof distinguish?' },
    ],
    3: [
        { type: 'concept', chapter: 1 },
        { type: 'output', prompt: 'What does this print?', code: [{ text: 'const name = "Rheo";' }, { text: 'const age = 3;' }, { text: 'console.log(typeof age);' }], terminalOutput: 'number', options: ['"string"', '"number"', '3', '"integer"'], correct: 1, explanation: 'age was bound to 3 with no quotes, so typeof says "number" — JS\'s single numeric type. typeof returns a STRING naming the type, which is why the options are quoted.', hint: 'Check whether there are quotes around the 3, then check what typeof actually returns.' },
        { type: 'pair', prompt: 'Match JavaScript types', pairs: [{ id: 1, left: 'number', right: '42 or 3.14' }, { id: 2, left: 'string', right: '"hello"' }, { id: 3, left: 'boolean', right: 'true' }, { id: 4, left: 'undefined', right: 'Not assigned' }], explanation: 'The literal tells the type: bare digits are number (int or float, same type), quotes are string, true/false are boolean, and undefined means "never assigned" — distinct from null, which means "deliberately empty". That pair is unique to JS and a favourite interview question.' },
    ],
    4: [
        { type: 'pair', prompt: 'Match operators', pairs: [{ id: 1, left: '===', right: 'Strict equals' }, { id: 2, left: '!==', right: 'Strict not equals' }, { id: 3, left: '**', right: 'Power' }, { id: 4, left: '??', right: 'Nullish coalescing' }], explanation: '=== and !== compare without coercion — the safe defaults. ** is exponentiation. ?? returns the right side only for null/undefined, unlike || which also swallows 0 and "" — choosing between them is a real bug class.' },
        { type: 'trace', prompt: 'What is the output?', code: [{ text: 'let x = 17;' }, { text: 'console.log(x % 5, Math.floor(x / 5));', highlight: true }], options: ['2 3', '3 2', '2 4', '17 5'], correct: 0, explanation: '17 = 5 × 3 + 2, so % gives 2 and the floored division gives 3. The print order is % first — swapping them is exactly what the "3 2" option checks.', hint: 'Work out 17 ÷ 5 as whole part and remainder, then match them to the printed order.' },
        { type: 'fillgap', prompt: 'Complete: convert Celsius to Fahrenheit', codeParts: [{ text: 'const celsius = 25;\nconst fahrenheit = ', type: 'fixed' }, { text: 'celsius * 9/5 + 32;', type: 'gap', id: 'g1' }, { text: '\nconsole.log(fahrenheit);', type: 'fixed' }], bank: ['celsius * 9/5 + 32;', 'celsius + 32;', 'celsius * 1.8;', 'celsius / 5 * 9;'], correctFill: { g1: 'celsius * 9/5 + 32;' }, explanation: 'Both differences between the scales are needed: degree size (× 9/5) and zero point (+ 32). celsius * 1.8 fixes only the size, + 32 only the offset — each is right at exactly one temperature and wrong everywhere else.', hint: 'Check candidates against a known pair: 0°C = 32°F and 100°C = 212°F. Only one option gets both.' },
    ],
    // ═══ CH2: FLOW CONTROL ═══
    5: [
        { type: 'trace', prompt: 'x is 15. Which letter gets printed?', code: [{ text: 'let x = 15;' }, { text: 'if (x > 20) {' }, { text: '    console.log("A");' }, { text: '} else if (x > 10) {' }, { text: '    if (x % 2 === 0) {' }, { text: '        console.log("B");' }, { text: '    } else {' }, { text: '        console.log("C");', highlight: true }, { text: '    }' }, { text: '}' }], options: ['A', 'B', 'C', 'undefined'], correct: 2, explanation: 'Two decisions, not one. 15 > 20 is false so the else-if takes over, and inside it 15 % 2 is 1, not 0 — so the inner else runs and prints C. "undefined" would need every branch to fail, which cannot happen once a chain ends in else.', hint: 'Pick the outer branch first, then work out which side of the inner if you land on.' },
        { type: 'bug', prompt: 'An 18-year-old is told they cannot vote. Which line is wrong?', code: [{ text: 'const age = 18;', hasError: false }, { text: 'if (age > 18) {', hasError: true }, { text: '    console.log("Can vote");', hasError: false }], correctLine: 1, explanation: 'The rule is "18 and over", but > 18 excludes exactly the boundary the rule is about. It needs >=. Off-by-one on a boundary is the most common logic bug there is, and it stays invisible until someone tests the boundary value itself.', hint: 'Substitute 18 into the comparison and read it out loud.' },
        { type: 'output', prompt: 'a is 0 — does this crash, and what prints?', code: [{ text: 'let a = 0;' }, { text: 'let b = 5;' }, { text: 'let result = a && b/a;' }, { text: 'console.log(result);' }], terminalOutput: '0', options: ['0', 'Error: Division by zero', '5', 'false'], correct: 0, explanation: '&& stops as soon as it finds a falsy operand, so b/a never runs — and it returns the operand itself, not a boolean, so you get 0 rather than false. Note that JavaScript would not have thrown anyway: 5/0 is Infinity, not an error. That is a real difference from most languages.', hint: 'Ask separately: does the right-hand side ever run, and what does && actually hand back?' },
        { type: 'realworld', prompt: 'Which one locks the user out after three wrong passwords?', scenario: '🔐 Three attempts, then stop asking.', options: [{ code: 'let attempts = 0;\nwhile (attempts < 3) {\n    const pwd = prompt();\n    if (pwd === secret) break;\n    attempts++;\n}', label: 'while with a counter' }, { code: 'for (let i = 0; i < 3; i++) {\n    const pwd = prompt();\n    if (pwd !== secret) continue;\n}', label: 'for with continue' }, { code: 'let attempts = 0;\nwhile (attempts < 3) {\n    const pwd = prompt();\n    if (pwd === secret) break;\n}', label: 'while, break on success' }, { code: 'while (true) {\n    const pwd = prompt();\n    if (pwd === secret) break;\n}', label: 'loop until correct' }], correct: 0, explanation: 'Only the first both stops early on success and counts failures, so it ends after three wrong tries. The third looks almost identical but never runs attempts++ — the condition stays true forever and it asks endlessly. The last has no limit at all, and the continue version does nothing on a wrong password since continue just moves to the next iteration.', hint: 'For each one, ask what makes the loop stop when the password is always wrong.' },
        { type: 'scramble', prompt: 'Assemble a grade calculator', pieces: [{ id: 'a', text: 'const score = 75;' }, { id: 'b', text: 'let grade;' }, { id: 'c', text: 'if (score >= 90) grade = "A";' }, { id: 'd', text: 'else if (score >= 80) grade = "B";' }, { id: 'e', text: 'else if (score >= 70) grade = "C";' }, { id: 'f', text: 'else grade = "F";' }, { id: 'g', text: 'console.log(grade);' }], distractors: [{ id: 'h', text: 'if (score == 90) grade = "A";' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The order of the else-if tests IS the logic: each one only runs when everything above it failed. Put >= 70 before >= 80 and a score of 95 comes out as a C. Note `let grade;` has to come before the chain — assigning to an undeclared name is a ReferenceError under strict mode. The spare line uses == 90, matching only that single value.', hint: 'The thresholds have to descend. Also ask which line has to exist before any branch can assign.' },
        { type: 'trace', prompt: 'n is 0. What ends up in `label`?', code: [{ text: 'const n = 0;' }, { text: 'const label = n > 0 ? "positive" : n < 0 ? "negative" : "zero";' }, { text: 'console.log(label);', highlight: true }], options: ['positive', 'negative', 'zero', 'Error'], correct: 2, explanation: 'Read it left to right: n > 0 fails, so the colon half is evaluated — and that half is itself another ternary. n < 0 also fails, leaving "zero". There is no special chaining syntax, just one ternary nested inside another.', hint: 'Rewrite it as a nested if/else on paper, then follow n = 0 down.' },
    ],
    6: [
        { type: 'trace', prompt: 'An empty array — truthy or falsy in JavaScript?', code: [{ text: 'let x = [1, 2, 3];' }, { text: 'let y = [];' }, { text: 'console.log(!!x, !!y);', highlight: true }], options: ['true true', 'true false', 'false true', 'false false'], correct: 0, explanation: 'Both are true. In JavaScript every object is truthy, and an array IS an object — so [] is truthy even though it is empty. So is {}, and even new Boolean(false). This is the opposite of Python, where [] is falsy, and it is why you check myArr.length rather than myArr itself.', hint: 'The answer is not what it would be in Python. Ask what JavaScript considers falsy — the list is short.' },
        { type: 'refactor', prompt: 'Which check actually fires only when the array has items?', originalCode: 'if (myArr.length > 0) {\n    doSomething();\n}', options: [{ code: 'if (myArr.length) {\n    doSomething();\n}', label: 'Truthy length' }, { code: 'if (myArr !== []) {\n    doSomething();\n}', label: 'Compare against []' }, { code: 'if (myArr != null) {\n    doSomething();\n}', label: 'Compare against null' }], correct: 0, explanation: 'A length of 0 is falsy and anything above it is truthy, so if (myArr.length) says exactly what is meant. Comparing against [] is always true — you are comparing a reference to a brand new array, and two arrays are never the same object. The null check is a different question: an empty array is not null, so that version runs the body on an empty array.', hint: 'One of these three is true no matter what myArr contains. Work out which, and why.' },
        { type: 'fillgap', prompt: 'Return true when n is between 1 and 100, ends included', codeParts: [{ text: 'function inRange(n) {\n    return ', type: 'fixed' }, { text: 'n >= 1 && n <= 100;', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['n >= 1 && n <= 100;', '1 <= n <= 100;', 'n >= 1 || n <= 100;', 'n in [1, 100];'], correctFill: { g1: 'n >= 1 && n <= 100;' }, explanation: 'JavaScript has no chained comparison. `1 <= n <= 100` parses as `(1 <= n) <= 100`, which compares a boolean to 100 — true becomes 1, and 1 <= 100 is always true. It never throws, so it silently accepts everything. Swapping && for || is also always true. And `in` checks object keys, not membership in a range.', hint: 'Test every candidate at n = 500. Two of them still say true.' },
        { type: 'output', prompt: 'How many of these seven values survive the filter?', code: [{ text: 'const vals = [0, "", [], null, 1, "hi", [0]];' }, { text: 'const truthy = vals.filter(v => !!v);' }, { text: 'console.log(truthy.length);' }], terminalOutput: '4', options: ['2', '3', '4', '7'], correct: 2, explanation: 'Only 0, "" and null are falsy here, so four survive: [], 1, "hi" and [0]. The empty array is the one that catches people — it is an object, so it passes. Answering 3 is the Python answer, where [] would be dropped.', hint: 'Count the falsy ones. In JavaScript that list is shorter than you expect.' },
        { type: 'pair', prompt: 'Match each falsy value to what makes it falsy', pairs: [{ id: 1, left: '0', right: 'Zero number' }, { id: 2, left: '""', right: 'Empty string' }, { id: 3, left: 'null', right: 'Explicit no value' }, { id: 4, left: 'undefined', right: 'Never assigned' }], explanation: 'JavaScript has exactly seven falsy values: false, 0, -0, 0n, "", null, undefined and NaN. Everything else — including [], {} and "0" — is truthy. null means "deliberately empty"; undefined means "never given a value".' },
    ],
    7: [
        { type: 'terminal', prompt: 'Store a name in a variable, then print it', expectedCommands: ['let name = "Otter";', 'console.log(name);'], hint: 'Two lines: declare with let, then hand the variable to console.log.', terminalHistory: [{ type: 'system', text: '> Daily Challenge' }] },
        { type: 'trace', prompt: 'What does `result` hold after the loop?', code: [{ text: 'let result = "";' }, { text: 'for (const c of "hello") {' }, { text: '    result += c.toUpperCase();' }, { text: '}' }, { text: 'console.log(result);', highlight: true }], options: ['hello', 'HELLO', 'Hello', 'hELLO'], correct: 1, explanation: 'for...of walks the characters of the string and appends each one uppercased, so all five end up uppercase. "Hello" would require uppercasing only the first pass, "hELLO" only the passes after it — neither matches a rule applied identically every iteration. Note for...in would give you indices instead, a common mix-up.', hint: 'Write down result after each of the five passes.' },
        { type: 'output', prompt: 'The braces hold an expression — what prints?', code: [{ text: 'const name = "Otter";' }, { text: 'const age = 5;' }, { text: 'console.log(`${name} is ${age*7} in human years`);' }], terminalOutput: 'Otter is 35 in human years', options: ['Otter is 35 in human years', 'Otter is 5 in human years', '${name} is ${age*7}', 'Error'], correct: 0, explanation: '${...} evaluates whatever is inside it, so ${age*7} becomes 35 — not just the variable, the whole expression. Swap the backticks for quotes and you get the third option: the placeholders print literally, with no error to warn you.', hint: 'Two questions: do the backticks matter, and is ${age*7} a name or a calculation?' },
    ],
    8: [
        { type: 'concept', chapter: 2 },
        { type: 'trace', prompt: 'status is 404. What does the switch print?', code: [{ text: 'const status = 404;' }, { text: 'let msg;' }, { text: 'switch (status) {' }, { text: '    case 200: msg = "OK"; break;' }, { text: '    case 404: msg = "Not Found"; break;' }, { text: '    default: msg = "Unknown";' }, { text: '}' }, { text: 'console.log(msg);', highlight: true }], options: ['OK', 'Not Found', 'Unknown', 'Error'], correct: 1, explanation: 'switch jumps to the matching case, so 404 wins, and its break stops execution before default is reached. Drop that break and you get "Unknown" instead — execution falls straight through into the next case. That fallthrough is why every case needs a break unless you want it. Also note switch compares with ===, so the string "404" would not match.', hint: 'Find the matching case, then ask what the break does. Then ask what happens if you delete it.' },
    ],
    // ═══ CH3: LOOPS ═══
    9: [
        { type: 'scramble', prompt: 'Print the numbers 1 to 5, one per line', pieces: [{ id: 'a', text: 'for (let i = 1; i <= 5; i++) {' }, { id: 'b', text: '    console.log(i);' }, { id: 'c', text: '}' }], distractors: [{ id: 'd', text: '    console.log(i + 1);' }, { id: 'e', text: 'while (i < 5) {' }], correctOrder: ['a', 'b', 'c'], explanation: 'The three parts of a for header do the whole job: start at 1, keep going while i <= 5, add one each pass. The spare while line would need i declared beforehand and incremented inside, or it never stops; and printing i + 1 would give 2 to 6.', hint: 'Work out which numbers the header actually produces before choosing what to print.' },
        { type: 'bug', prompt: 'This should print 1 through 10 but stops at 9. Which line?', code: [{ text: 'for (let i = 1; i < 10; i++) {', hasError: true }, { text: '    console.log(i);', hasError: false }, { text: '}', hasError: false }], correctLine: 0, explanation: 'The condition is checked before each pass, so with i < 10 the loop quits the moment i reaches 10 — the last value that runs is 9. Reaching 10 needs i <= 10. Choosing between < and <= in a loop header is where most off-by-one bugs come from.', hint: 'Ask what i is on the pass that does NOT run, then whether that value should have printed.' },
        { type: 'trace', prompt: 'How many times does the loop body run?', code: [{ text: 'let n = 64;' }, { text: 'let count = 0;' }, { text: 'while (n > 1) {' }, { text: '    n = Math.floor(n / 2);' }, { text: '    count++;' }, { text: '}' }, { text: 'console.log(count);', highlight: true }], options: ['5', '6', '7', '32'], correct: 1, explanation: 'n halves each pass: 64→32→16→8→4→2→1, six steps. Since 64 is 2⁶ the answer is log₂(64) = 6 — the same shape that makes binary search O(log n). Note Math.floor matters: without it JavaScript would keep producing fractions and the loop would run far longer.', hint: 'Write the sequence of values n takes and count the arrows, not the numbers.' },
        { type: 'fillgap', prompt: 'Make total end up as 10 — the sum of 1 through 4', codeParts: [{ text: 'let total = 0;\nfor (const num of ', type: 'fixed' }, { text: '[1,2,3,4]', type: 'gap', id: 'g1' }, { text: ') {\n    total += num;\n}', type: 'fixed' }], bank: ['[1,2,3,4]', 'Array(4)', '{1:4}', '"1234"'], correctFill: { g1: '[1,2,3,4]' }, explanation: 'Each wrong option fails in its own way. "1234" iterates characters, and += on a string concatenates rather than adds — total ends up as the string "01234". Array(4) has four empty slots that for...of yields as undefined, so total becomes NaN. And a plain object is not iterable at all: for...of on {1:4} throws TypeError.', hint: 'Only one of these is a list of numbers. Predict what each of the others does to total before choosing.' },
        { type: 'realworld', prompt: 'Which one actually evaluates to 9?', scenario: '📊 nums = [3, 7, 2, 9, 4] — you want the largest.', options: [{ code: 'const best = Math.max(...nums);', label: 'Math.max with spread' }, { code: 'const best = Math.max(nums);', label: 'Math.max on the array' }, { code: 'const best = nums.sort()[0];', label: 'Sort, take the first' }, { code: 'const best = nums.reduce((a,b) => a+b);', label: 'reduce with +' }], correct: 0, explanation: 'Math.max takes separate arguments, so the array has to be spread — hand it the array itself and it tries to convert it to a number, giving NaN. Sorting then taking index 0 gives the smallest, and there is a second trap: sort() with no comparator sorts LEXICOGRAPHICALLY, so [10, 9, 1] becomes [1, 10, 9]. The reduce adds instead, giving 25.', hint: 'One fails on the arguments, one takes the wrong end, one adds. Only one asks for a maximum correctly.' },
        { type: 'output', prompt: 'What does break leave printed?', code: [{ text: 'for (let i = 0; i < 5; i++) {' }, { text: '    if (i === 3) break;' }, { text: '    process.stdout.write(i + " ");' }, { text: '}' }], terminalOutput: '0 1 2 ', options: ['0 1 2 ', '0 1 2 3', '0 1 2 3 4', '3'], correct: 0, explanation: 'break leaves the loop immediately, so when i reaches 3 the write below it never runs — 3 is never shown. Move the write above the if and you would get "0 1 2 3". Compare with continue, which abandons only that one pass and keeps looping.', hint: 'The order of the two statements inside the loop is the whole answer.' },
    ],
    10: [
        { type: 'trace', prompt: 'How many lines does this nested loop print?', code: [{ text: 'for (let i = 0; i < 3; i++) {' }, { text: '    for (let j = 0; j < 4; j++) {' }, { text: '        console.log(i, j);', highlight: true }, { text: '    }' }, { text: '}' }], options: ['7', '12', '9', '16'], correct: 1, explanation: 'The inner loop runs fully for every single pass of the outer one, so it is 3 × 4 = 12 — a product, not a sum. Answering 7 is adding them; 9 and 16 are squaring one of them. This is also why nested loops over the same collection are O(n²).', hint: 'For each value of i, how many times does j run? Then combine.' },
        { type: 'output', prompt: 'Which shape does this print?', code: [{ text: 'for (let i = 1; i <= 3; i++) {' }, { text: '    console.log("*".repeat(i));' }, { text: '}' }], terminalOutput: '*\n**\n***', options: ['***\n**\n*', '*\n**\n***', '***', '* * *'], correct: 1, explanation: 'i goes 1, 2, 3 and repeat(i) grows the row each pass. The reversed triangle would need the loop to count down. Note JavaScript needs the explicit .repeat() method here — unlike Python, "*" * 3 would give NaN.', hint: 'Write down what i is on each pass, then what repeat(i) produces for it.' },
        { type: 'realworld', prompt: 'Which one flattens the array into a single level?', scenario: '📊 [[1,2],[3,4],[5,6]] → [1,2,3,4,5,6]', options: [{ code: 'const flat = arr.flat();', label: '.flat()' }, { code: 'const flat = arr.reduce((a,b) => a+b);', label: 'reduce with +' }, { code: 'const flat = Array.from(arr);', label: 'Array.from()' }, { code: 'const flat = [...arr];', label: 'Spread into a new array' }], correct: 0, explanation: 'flat() is built for exactly this. The reduce is the nasty one: + on two arrays converts both to strings, so you silently get "1,23,45,6" — a string, not an array, and no error. Array.from and the spread both copy the outer array only, leaving the inner arrays untouched, so the shape never changes.', hint: 'Two of these give you an array that looks identical to the input. One gives something that is not an array at all.' },
        { type: 'scramble', prompt: 'Assemble one row of a multiplication table', pieces: [{ id: 'a', text: 'const n = 5;' }, { id: 'b', text: 'for (let i = 1; i <= 10; i++) {' }, { id: 'c', text: '    console.log(`${n} x ${i} = ${n*i}`);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    console.log(n + i);' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'n has to exist before the loop that uses it, and the log has to sit inside the braces or it runs once after the loop instead of ten times within it. The spare line adds where it should multiply — and with a string it would concatenate rather than either.', hint: 'One line sets up, one repeats, one does the work. Which has to be inside which?' },
        { type: 'trace', prompt: 'What does entries() hand to each iteration?', code: [{ text: 'const fruits = ["apple", "banana", "cherry"];' }, { text: 'for (const [i, f] of fruits.entries()) {' }, { text: '    console.log(i, f);', highlight: true }, { text: '}' }], options: ['0 apple\n1 banana\n2 cherry', 'apple 0\nbanana 1', '1 apple\n2 banana\n3 cherry', 'Error'], correct: 0, explanation: 'entries() yields [index, value] pairs counting from 0, and the [i, f] in the for line destructures them. Note the contrast with for...in, which gives you keys as STRINGS ("0", "1", "2") and is the usual source of confusion here.', hint: 'Two questions: which of the pair comes first, and what number does counting start at?' },
    ],
    11: [
        { type: 'scramble', prompt: 'Assemble a primality test', pieces: [{ id: 'a', text: 'function isPrime(n) {' }, { id: 'b', text: '    if (n < 2) return false;' }, { id: 'c', text: '    for (let i = 2; i <= Math.sqrt(n); i++) {' }, { id: 'd', text: '        if (n % i === 0) return false;' }, { id: 'e', text: '    }' }, { id: 'f', text: '    return true;' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '    for (let i = 0; i < n; i++) {' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'], explanation: 'The guard for n < 2 has to come first, because 0 and 1 are not prime and would otherwise reach the final return true. Testing only up to √n is the real trick: any factor above the square root has a matching partner below it, so if none turned up by then there is none at all. The spare line starts at 0, and n % 0 is NaN — which is never === 0, so every number would look prime.', hint: 'Why is √n enough? Think about what pairs up with a factor larger than it.' },
        { type: 'trace', prompt: 'What does the filter leave behind?', code: [{ text: 'const nums = [1, 2, 3, 4, 5, 6];' }, { text: 'const evens = nums.filter(n => n % 2 === 0);' }, { text: 'console.log(evens);', highlight: true }], options: ['[2, 4, 6]', '[1, 3, 5]', '[1, 2, 3, 4, 5, 6]', '3'], correct: 0, explanation: 'filter keeps every item the callback returns true for, and n % 2 === 0 is true for even numbers. Drop the === 0 and you would keep the odd ones instead, since 1 is truthy and 0 is falsy — that is the [1, 3, 5] option. filter returns a new array, so 3 answers a different question.', hint: 'Read the callback as a keep-or-drop test, then check which numbers it keeps.' },
        { type: 'fillgap', prompt: 'Build [1, 4, 9, 16, 25] — the squares of 1 through 5', codeParts: [{ text: 'const squares = ', type: 'fixed' }, { text: '[1,2,3,4,5].map(x => x**2);', type: 'gap', id: 'g1' }], bank: ['[1,2,3,4,5].map(x => x**2);', 'Array(5).map(x*x);', '[...range(5)]**2;', 'Math.pow([1,2,3,4,5]);'], correctFill: { g1: '[1,2,3,4,5].map(x => x**2);' }, explanation: 'map applies the callback to each item and returns a new array. Array(5).map fails twice — x is not defined, and map skips empty slots entirely, so even a valid callback would return five holes. There is no range() in JavaScript. And Math.pow takes two numbers, not an array.', hint: 'Only one of these produces a list of five numbers. Rule out the ones that cannot.' },
        { type: 'realworld', prompt: 'Which one collects the scores of 60 and above?', scenario: '📝 scores = [45, 78, 92, 33, 88], passing mark 60.', options: [{ code: 'const passed = scores.filter(s => s >= 60);', label: 'filter, 60 included' }, { code: 'const passed = scores.filter(s => s > 60);', label: 'filter, strictly above' }, { code: 'const passed = scores.find(s => s >= 60);', label: 'find instead of filter' }, { code: 'const passed = scores > 60;', label: 'Compare the array directly' }], correct: 0, explanation: 'The passing mark is 60, so the test must include it. On this data >= and > give the identical three scores, which is precisely what makes the bug so easy to ship — it only surfaces the day someone scores exactly 60. find returns the FIRST match rather than all of them, so you would get 78 instead of an array. And comparing an array to a number stringifies it, quietly giving false.', hint: 'Two of these produce identical output here. Ask which would disagree on a score of exactly 60.' },
    ],
    12: [
        { type: 'pair', prompt: 'Match each loop tool to what it does', pairs: [{ id: 1, left: 'break', right: 'Leave the loop now' }, { id: 2, left: 'continue', right: 'Skip to the next pass' }, { id: 3, left: '.entries()', right: 'Index alongside value' }, { id: 4, left: '.forEach()', right: 'Run a callback per item' }], explanation: 'break and continue are often confused: break abandons the whole loop, continue abandons only the current pass. One catch worth knowing — neither works inside forEach, because the callback is a function: return skips one item, and there is no way to stop early. Reach for a real for...of loop when you need to break out.' },
        { type: 'trace', prompt: 'forEach gives the callback an index — what prints?', code: [{ text: 'const names = ["Ali", "Ece"];' }, { text: 'const ages = [20, 22];' }, { text: 'names.forEach((n, i) => {' }, { text: '    console.log(`${n}:${ages[i]}`);', highlight: true }, { text: '});' }], options: ['Ali:20\nEce:22', 'Ali Ece\n20 22', '[Ali,20]', 'Error'], correct: 0, explanation: 'forEach passes the value first and the index second, so i lines the two arrays up by position. This works only while the arrays stay the same length — if ages were shorter, ages[i] would be undefined and print silently rather than throwing.', hint: 'Which of the two callback parameters is the index? Then use it to look into the second array.' },
        { type: 'output', prompt: 'What does continue leave printed?', code: [{ text: 'for (let i = 0; i < 5; i++) {' }, { text: '    if (i === 2) continue;' }, { text: '    process.stdout.write(i + " ");' }, { text: '}' }], terminalOutput: '0 1 3 4 ', options: ['0 1 3 4 ', '0 1 2 3 4', '2', '0 1'], correct: 0, explanation: 'continue skips the rest of this one pass and moves to the next, so only 2 is missing — the loop keeps going. "0 1" would be the answer if this were break, which is the distinction the question is really testing.', hint: 'Does the loop end at i = 2, or just skip that one pass?' },
    ],
    // ═══ CH4: FUNCTIONS ═══
    13: [
        { type: 'trace', prompt: 'Only one argument is passed — what comes back?', code: [{ text: 'function add(a, b = 10) {' }, { text: '    return a + b;' }, { text: '}' }, { text: 'console.log(add(3));', highlight: true }], options: ['3', '10', '13', 'NaN'], correct: 2, explanation: 'b has a default, so omitting it is allowed and it takes 10 — giving 13. Without the default b would be undefined and 3 + undefined is NaN, which is the fourth option and what JavaScript does instead of complaining about a missing argument.', hint: 'Write down what a and b each hold at the moment the body runs.' },
        { type: 'bug', prompt: 'The caller gets undefined instead of the sum. Which line?', code: [{ text: 'function add(a, b) {', hasError: false }, { text: '    const result = a + b;', hasError: false }, { text: '    console.log(result);', hasError: true }], correctLine: 2, explanation: 'Logging shows a value in the console; returning hands it back to the caller. With no return the function yields undefined, so const total = add(2, 3) silently stores undefined and the failure surfaces somewhere else entirely. Confusing these two is the most common beginner bug in any language.', hint: 'Ask what `const x = add(2, 3)` would put in x.' },
        { type: 'refactor', prompt: 'Which version stays correct as more operations are added?', originalCode: 'function calc(a, b, op) {\n    if (op === "add") return a+b;\n    if (op === "sub") return a-b;\n    if (op === "mul") return a*b;\n}', options: [{ code: 'const ops = {\n    add: (a,b) => a+b,\n    sub: (a,b) => a-b,\n    mul: (a,b) => a*b\n};\nconst calc = (a,b,op) => ops[op](a,b);', label: 'Look the operation up in an object' }, { code: 'const calc = (a,b,op) => eval(`${a}${op}${b}`);', label: 'Build a string and eval it' }, { code: 'function calc(a,b,op) {\n    switch(op) { case "+": return a+b; }\n}', label: 'switch on the operator' }], correct: 0, explanation: 'The object turns "add another operation" into "add another entry" — no control flow to edit. eval executes whatever string it is handed, so a caller-supplied op becomes arbitrary code execution; that is a genuine security hole, not just untidy. The switch handles only "+" and falls out returning undefined for everything else.', hint: 'Imagine adding division tomorrow. Which one do you edit, and which one can a hostile caller abuse?' },
        { type: 'output', prompt: 'Four arguments, one parameter — what prints?', code: [{ text: 'function total(...nums) {' }, { text: '    return nums.reduce((a,b) => a+b, 0);' }, { text: '}' }, { text: 'console.log(total(1, 2, 3, 4));' }], terminalOutput: '10', options: ['[1,2,3,4]', '10', '4', 'Error'], correct: 1, explanation: '...nums collects every argument into a real array, so reduce can walk it and produce 10. The 0 passed to reduce is the starting value — leave it out and an empty call would throw instead of returning 0. The array itself is the first option; 4 would be nums.length.', hint: 'Two steps: what does nums hold inside the function, and what does reduce do to it?' },
        { type: 'scramble', prompt: 'Assemble a greeter with an optional greeting', pieces: [{ id: 'a', text: 'function greet(name, greeting = "Hello") {' }, { id: 'b', text: '    return `${greeting}, ${name}!`;' }, { id: 'c', text: '}' }, { id: 'd', text: 'console.log(greet("Furkan"));' }, { id: 'e', text: 'console.log(greet("Arda", "Hey"));' }], distractors: [{ id: 'f', text: '    return name + greeting;' }], correctOrder: ['a', 'b', 'c', 'd', 'e'], explanation: 'The body has to be closed before the calls, and the two calls show why defaults are useful: the first accepts "Hello", the second overrides it positionally. The spare line concatenates in the wrong order and without punctuation. Note function declarations are hoisted, so the calls would actually work above the definition — but nobody reads code that way.', hint: 'Definition, closing brace, then the two calls in the order that shows the default first.' },
        { type: 'trace', prompt: 'What does map produce here?', code: [{ text: 'const double = x => x * 2;' }, { text: 'const nums = [1, 2, 3];' }, { text: 'const result = nums.map(double);' }, { text: 'console.log(result);', highlight: true }], options: ['[2, 4, 6]', '[1, 2, 3]', '6', 'Error'], correct: 0, explanation: 'map applies double to each item and returns a new array — the original nums is untouched, which is the difference between map and a loop that mutates. Note double is passed by name, not called: writing nums.map(double(x)) would be an error.', hint: 'Does map change nums, or build something new? And is double called or handed over?' },
    ],
    14: [
        { type: 'trace', prompt: 'Same name inside and outside — which one prints?', code: [{ text: 'let x = "global";' }, { text: 'function f() {' }, { text: '    let x = "local";' }, { text: '    console.log(x);', highlight: true }, { text: '}' }, { text: 'f();' }], options: ['global', 'local', 'Error', 'undefined'], correct: 1, explanation: 'The inner let creates a separate binding that shadows the outer one for the whole function body. The outer x is untouched — log it after f() and it still says "global". Remove the inner let and the function would read and write the outer variable instead.', hint: 'Does the function declare its own x, or only use the outer one?' },
        { type: 'output', prompt: 'The counter is called three times — what prints?', code: [{ text: 'function makeCounter() {' }, { text: '    let count = 0;' }, { text: '    return function() {' }, { text: '        count++;' }, { text: '        return count;' }, { text: '    };' }, { text: '}' }, { text: 'const c = makeCounter();' }, { text: 'console.log(c(), c(), c());' }], terminalOutput: '1 2 3', options: ['0 0 0', '1 1 1', '1 2 3', 'Error'], correct: 2, explanation: 'The returned function closes over count, so the variable outlives makeCounter and keeps its value between calls — that is what a closure is. "1 1 1" would happen if each call started fresh; calling makeCounter() twice really does give two independent counters.', hint: 'Where does count live after makeCounter has already returned?' },
        { type: 'bug', prompt: 'This throws before it ever assigns. Which line causes it?', code: [{ text: 'let total = 0;', hasError: false }, { text: 'function add(n) {', hasError: false }, { text: '    console.log(total);', hasError: false }, { text: '    let total = n;', hasError: true }, { text: '}', hasError: false }], correctLine: 3, explanation: 'The inner `let total` applies to the entire function body, not just from its own line down — so the log above it refers to the inner binding, which has not been initialised yet. That gap is the temporal dead zone, and it throws. Delete the inner let and the function would read and update the outer total quite happily, because JavaScript has no equivalent of Python\'s UnboundLocalError.', hint: 'Which binding does the log actually refer to? The declaration is not where the variable starts existing.' },
        { type: 'errordecode', prompt: 'What is this error telling you about where the variable lives?', errorText: "ReferenceError: Cannot access 'total' before initialization\n    at add (main.js:3)\n    at main.js:6", question: 'Fix?', options: ['Remove the inner let — use the outer total', 'Move the log below the let', 'Switch let to var', 'Delete the outer total'], correct: 0, explanation: 'Removing the inner declaration makes the function read and write the outer variable, which is what the code was trying to do. Moving the log below the let also stops the error, but the function then reports its own fresh copy and the outer total never changes — error gone, behaviour still wrong. var would hoist to undefined and log that instead of throwing: quieter, and worse.', hint: 'Three of these make the error disappear. Only one keeps the outer variable in play.' },
        { type: 'realworld', prompt: 'Which one lets you build several multipliers, each with its own factor?', scenario: '🧠 You want double(x) and triple(x) from the same code.', options: [{ code: 'function makeMultiplier(factor) {\n    return x => x * factor;\n}\nconst double = makeMultiplier(2);\nconst triple = makeMultiplier(3);', label: 'Return an inner function' }, { code: 'let factor = 2;\nfunction multiply(x) {\n    return x * factor;\n}', label: 'Read a module-level factor' }, { code: 'function multiply(x, factor) {\n    return x * factor;\n}', label: 'Take the factor each call' }, { code: 'const double = x => x * 2;', label: 'Write one arrow per factor' }], correct: 0, explanation: 'Each call to makeMultiplier creates a separate closure holding its own factor, so double and triple coexist. The module-level version has exactly one factor for the whole program — change it and every caller changes. Passing the factor every call works but is not the same thing: you cannot hand a two-argument function straight to map. And writing an arrow per factor does not scale past the ones you thought of.', hint: 'You need double AND triple alive at once. Which options can produce two independent functions?' },
    ],
    15: [
        { type: 'concept', chapter: 4 },
        { type: 'pair', prompt: 'Match each piece of function syntax to its job', pairs: [{ id: 1, left: 'function', right: 'Declare a function' }, { id: 2, left: 'return', right: 'Hand a value back' }, { id: 3, left: '...args', right: 'Collect the extra arguments' }, { id: 4, left: '=>', right: 'Arrow function shorthand' }], explanation: 'Rest params collect leftover arguments into a real array — unlike the old `arguments` object, which looks like an array but has none of the methods. Arrow functions are not just shorter: they take `this` from the surrounding scope rather than from how they are called, which is why they are the safe choice inside callbacks.' },
        { type: 'trace', prompt: 'shout wraps greet — what prints?', code: [{ text: 'function shout(fn) {' }, { text: '    return name => fn(name).toUpperCase();' }, { text: '}' }, { text: 'const greet = name => `hello ${name}`;' }, { text: 'const loudGreet = shout(greet);' }, { text: 'console.log(loudGreet("Otter"));', highlight: true }], options: ['hello Otter', 'HELLO OTTER', 'Hello Otter', 'Error'], correct: 1, explanation: 'shout takes a function and returns a new one that calls it and uppercases the whole result — including the "hello", which is why it is not "Hello Otter". Functions being values you can pass around and return is what "higher-order" means, and it is the same machinery a decorator uses.', hint: 'Follow what loudGreet actually is, then what it does to the string it gets back.' },
    ],
    16: [
        { type: 'trace', prompt: 'What does fib(5) return?', code: [{ text: 'function fib(n) {' }, { text: '    if (n <= 1) return n;' }, { text: '    return fib(n-1) + fib(n-2);' }, { text: '}' }, { text: 'console.log(fib(5));', highlight: true }], options: ['3', '5', '8', '13'], correct: 1, explanation: 'The sequence from this definition is 0,1,1,2,3,5 — so fib(5) is 5. It is easy to be one place out: fib(4) is 3 and fib(6) is 8, which is what the neighbouring options are. Work upward from the base case rather than expanding the tree downward.', hint: 'List fib(0) through fib(5) in order, each one the sum of the two before it.' },
        { type: 'algostep', prompt: 'Expanding the fib(4) call tree', array: ['fib(4)', 'fib(3)+fib(2)', '(fib(2)+fib(1))+(fib(1)+fib(0))', '(1+1)+(1+0)=3'], step: 3, description: 'fib(4) = fib(3) + fib(2). Expanding...', question: 'What is fib(3)?', options: ['1', '2', '3', '5'], correct: 1, explanation: 'fib(3) = fib(2) + fib(1) = 1 + 1 = 2. Notice fib(1) gets computed twice even in this tiny tree — that duplication is what makes naive recursion exponential, and exactly what memoisation removes.', hint: 'Expand fib(3) one level and add the two base cases underneath.' },
        { type: 'errordecode', prompt: 'What is missing when recursion hits this error?', errorText: 'RangeError: Maximum call stack size exceeded\n    at fib (main.js:2)', question: 'Cause?', options: ['Missing base case', 'Wrong return type', 'Too many params', 'Import error'], correct: 0, explanation: 'Every recursive function needs a case that returns without recursing, and each call must move towards it. Miss either and the call stack grows until the engine gives up. Note JavaScript has no tail-call optimisation in practice, so even correct deep recursion can hit this — which is why loops are often preferred here.', hint: 'What has to be true for the calls to eventually stop?' },
        { type: 'scramble', prompt: 'Assemble a recursive factorial', pieces: [{ id: 'a', text: 'function factorial(n) {' }, { id: 'b', text: '    if (n <= 1) return 1;' }, { id: 'c', text: '    return n * factorial(n - 1);' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    return n + factorial(n);' }], correctOrder: ['a', 'b', 'c', 'd'], explanation: 'The base case has to come before the recursive call, or nothing ever stops it. The spare line breaks both halves at once: it adds where it should multiply, and calls factorial(n) rather than factorial(n - 1) — so it never moves towards the base case and recurses until the stack dies.', hint: 'Two things every recursion needs: somewhere to stop, and a step that gets closer to it.' },
        { type: 'trace', prompt: 'What does sumDigits(123) return?', code: [{ text: 'function sumDigits(n) {' }, { text: '    if (n < 10) return n;' }, { text: '    return n % 10 + sumDigits(Math.floor(n / 10));' }, { text: '}' }, { text: 'console.log(sumDigits(123));', highlight: true }], options: ['6', '123', '3', '12'], correct: 0, explanation: '% 10 peels off the last digit and Math.floor(n / 10) removes it, so the calls are 3 + (2 + (1)) = 6. The floor is essential here — JavaScript division produces 12.3, and without flooring the recursion would never reach a clean single digit. 3 would be the digit count, not the sum.', hint: 'Work out what n % 10 and Math.floor(n / 10) give for 123, then follow one level down.' },
        { type: 'realworld', prompt: 'Which of these problems contains a smaller copy of itself?', scenario: '🤔 Recursion fits when a problem breaks into the same problem, smaller.', options: [{ code: '// A folder contains files and more folders', label: 'Walking a directory tree' }, { code: '// Read a file one line at a time until EOF', label: 'Reading lines sequentially' }, { code: '// Print "Hello" five times', label: 'Repeating a fixed number of times' }, { code: '// Add two numbers together', label: 'A single arithmetic step' }], correct: 0, explanation: 'A folder contains folders, each handled by exactly the same procedure — the structure is self-similar, so the code can be too. The others are flat: reading lines and counting to five are plain iteration, and adding two numbers has no subproblem at all. Recursion is not "a fancier loop", it is for structures that nest.', hint: 'For each one, ask whether solving it requires solving a smaller version of the identical problem.' },
    ],
    // ═══ CH5-CH10: Use same conceptual exercises, shared with Python fallback ═══
    // Nodes 17-42 share language-agnostic exercises (pair, realworld, algostep)
    // and fall back to Python for code-heavy exercises via getExercisesForNode()
    17: [
        { type: 'trace', prompt: 'b was pushed to — what is a.length?', code: [{ text: 'const a = [1, 2, 3];' }, { text: 'const b = a;' }, { text: 'b.push(4);' }, { text: 'console.log(a.length);', highlight: true }], options: ['3', '4', 'Error', '[1,2,3]'], correct: 1, explanation: 'const b = a does not copy anything — it gives the same array a second name, so pushing through either changes the one object both point at. Note const only stops REASSIGNING b; it does nothing to protect the contents, which is why push is allowed here at all.', hint: 'How many arrays exist after line 2? And what exactly does const freeze — the name or the contents?' },
        { type: 'output', prompt: 'Which items does slice(1, 4) include?', code: [{ text: 'const x = [10, 20, 30, 40, 50];' }, { text: 'console.log(x.slice(1, 4));' }], terminalOutput: '[20, 30, 40]', options: ['[10,20,30]', '[20,30,40]', '[20,30,40,50]', '[10,20,30,40]'], correct: 1, explanation: 'slice starts at the first index and stops BEFORE the second — indices 1, 2, 3. The count is always end minus start, here 3. Do not confuse it with splice, which takes a start and a LENGTH and mutates the original array rather than returning a copy.', hint: 'Count from 0, then remember which end slice leaves out.' },
        { type: 'realworld', prompt: 'Which leaves rev reversed AND orig untouched?', scenario: '🔄 Both must still be usable afterwards.', options: [{ code: 'const rev = [...orig].reverse();', label: 'Spread into a new array, then reverse' }, { code: 'const rev = orig.reverse();', label: 'Reverse it directly' }, { code: 'const rev = Array.from(orig);', label: 'Array.from' }, { code: 'const rev = orig.reverse().slice();', label: 'Reverse, then copy' }], correct: 0, explanation: 'Spreading builds a new array first, so reverse flips the copy and orig survives. Calling reverse directly mutates in place and returns the SAME array, so rev and orig end up being one reversed array. Array.from copies but never reverses. The last one reverses orig before copying — the copy is right and the original is already destroyed, which is the subtlest of the three failures.', hint: 'reverse() always mutates whatever it is called on. So the only question is: what is it called on?' },
        { type: 'bug', prompt: 'Pushing to b changed a. Which line is responsible?', code: [{ text: 'const a = [1, 2, 3];', hasError: false }, { text: 'const b = a;', hasError: true }, { text: 'b.push(4);', hasError: false }, { text: 'console.log(a);', hasError: false }], correctLine: 1, explanation: 'The push does exactly what it says; the problem is one line earlier, where b became another name for the same array rather than a copy. Writing const b = [...a] there fixes it. Blaming the line where the symptom appears rather than the line that set it up is a habit worth breaking early.', hint: 'The line that misbehaves is not always the line that is wrong. Which line decided there would be only one array?' },
        { type: 'refactor', prompt: 'Which one gives you an array you can change independently?', originalCode: 'const original = [1, 2, 3];\nconst copy = original;', options: [{ code: 'const copy = [...original];', label: 'Spread into a new array' }, { code: 'const copy = original;', label: 'Assign it across' }, { code: 'const copy = Object.freeze(original);', label: 'Freeze it' }], correct: 0, explanation: 'Spreading builds a new array holding the same items — slice() and Array.from do the same. Plain assignment shares the object, which is the bug being fixed. Object.freeze does not copy at all: it returns the SAME array and merely blocks changes to it, so now neither name can be modified. All of these are shallow — copy an array of objects and the inner objects are still shared, which is what structuredClone is for.', hint: 'Two of these leave you with one array, not two. Which one actually allocates a second?' },
    ],
    18: [
        { type: 'trace', prompt: 'How many times does "a" appear in banana?', code: [{ text: 'const word = "banana";' }, { text: 'const freq = {};' }, { text: 'for (const c of word) {' }, { text: '    freq[c] = (freq[c] || 0) + 1;' }, { text: '}' }, { text: 'console.log(freq["a"]);', highlight: true }], options: ['1', '2', '3', 'undefined'], correct: 2, explanation: 'b-a-n-a-n-a has three a\'s. The real lesson is (freq[c] || 0): a missing key gives undefined, and undefined + 1 is NaN — so the fallback is what stops every count becoming NaN on the first sighting. That silent NaN, rather than an error, is the JavaScript trap here.', hint: 'Spell banana out letter by letter. Then ask what freq[c] is the very first time each letter is seen.' },
        { type: 'refactor', prompt: 'Which one actually produces the counts?', originalCode: 'const freq = {};\nfor (const c of word) {\n    if (freq[c]) freq[c]++;\n    else freq[c] = 1;\n}', options: [{ code: 'const freq = [...word].reduce((m,c) => {\n    m[c] = (m[c]||0)+1;\n    return m;\n}, {});', label: 'reduce into an object' }, { code: 'const freq = {};\nword.split("").map(c => freq[c]++);', label: 'map with ++' }, { code: 'const freq = Object.fromEntries(word);', label: 'Object.fromEntries on the string' }], correct: 0, explanation: 'The reduce threads the accumulator through and returns it each pass — forget that return and you get undefined on the second iteration. The map version increments undefined, so every value becomes NaN, and it also misuses map for a side effect where forEach was meant. fromEntries expects pairs; handed single characters it throws.', hint: 'One silently fills the object with NaN. Work out what undefined++ evaluates to.' },
        { type: 'fillgap', prompt: 'Return true only when both words use the same letters, same counts', codeParts: [{ text: 'function isAnagram(a, b) {\n    return ', type: 'fixed' }, { text: '[...a].sort().join("") === [...b].sort().join("");', type: 'gap', id: 'g1' }, { text: '\n}\n\nisAnagram("listen", "silent")  // true\nisAnagram("aab", "abb")        // must be false', type: 'fixed' }], bank: ['[...a].sort().join("") === [...b].sort().join("");', 'a === b;', 'a.length === b.length;', 'new Set(a) === new Set(b);'], correctFill: { g1: '[...a].sort().join("") === [...b].sort().join("");' }, explanation: 'Sorting both into a canonical string compares letters AND their counts. Comparing lengths passes aab/abb. And comparing two Sets with === is always false — even new Set("a") === new Set("a") — because === on objects compares references, so that option never returns true for anything.', hint: 'One option is false for every possible input. Find that one first, then test the rest against aab/abb.' },
        { type: 'output', prompt: 'What shape does fromEntries build here?', code: [{ text: 'const obj = Object.fromEntries(' }, { text: '    [1,2,3,4].map(x => [x, x**2])' }, { text: ');' }, { text: 'console.log(obj);' }], terminalOutput: '{1:1, 2:4, 3:9, 4:16}', options: ['{1:1, 2:4, 3:9, 4:16}', '[1, 4, 9, 16]', 'Set{1,4,9,16}', 'Error'], correct: 0, explanation: 'map produces [key, value] pairs and fromEntries folds them into an object — JavaScript has no dict comprehension, so this is the idiom. One detail worth noticing: object keys are always strings, so the numeric 1 becomes "1". Object.entries is the inverse, turning an object back into pairs.', hint: 'What is the shape of each item map returns? That is what fromEntries consumes.' },
        { type: 'pair', prompt: 'Match each array method to what it returns', pairs: [{ id: 1, left: '.map()', right: 'A new array, same length' }, { id: 2, left: '.filter()', right: 'A new array, same or fewer' }, { id: 3, left: '.reduce()', right: 'One accumulated value' }, { id: 4, left: '.find()', right: 'The first matching item' }], explanation: 'The useful distinction is what comes back. map and filter both return arrays; find returns a single element (or undefined); reduce returns whatever you accumulated, which can be any type at all. None of the four mutates the original — that is what separates them from sort, reverse and splice.' },
    ],
    19: [
        { type: 'scramble', prompt: 'Assemble a duplicate finder', pieces: [{ id: 'a', text: 'function findDupes(arr) {' }, { id: 'b', text: '    const seen = new Set();' }, { id: 'c', text: '    const dupes = new Set();' }, { id: 'd', text: '    for (const x of arr) {' }, { id: 'e', text: '        if (seen.has(x)) dupes.add(x);' }, { id: 'f', text: '        seen.add(x);' }, { id: 'g', text: '    }' }, { id: 'h', text: '    return [...dupes];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    return arr;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], explanation: 'The order of the two lines inside the loop is the whole algorithm: check membership BEFORE adding, or every item looks like a duplicate of itself. dupes is a Set so an item appearing three times is still reported once, and the spread at the end converts it back to the array the signature promises.', hint: 'If you add x to seen first, what does the very next line say about x?' },
        { type: 'trace', prompt: 'What does this intersection produce?', code: [{ text: 'const a = new Set([1, 2, 3, 4]);' }, { text: 'const b = new Set([3, 4, 5, 6]);' }, { text: 'const inter = [...a].filter(x => b.has(x));' }, { text: 'console.log(inter);', highlight: true }], options: ['[3, 4]', '[1,2,3,4,5,6]', '[1,2]', '[5,6]'], correct: 0, explanation: 'Spreading a into an array makes filter available, and b.has keeps only what is in both — 3 and 4. Note the result is an array, not a Set, which is why it prints with square brackets. Flip the filter to !b.has(x) and you get the difference [1,2] instead.', hint: 'Which numbers appear in both lines? Then check what type the result actually is.' },
        { type: 'output', prompt: 'Both objects have a y — which value survives?', code: [{ text: 'const a = {x: 1, y: 2};' }, { text: 'const b = {y: 3, z: 4};' }, { text: 'const merged = {...a, ...b};' }, { text: 'console.log(merged.y);' }], terminalOutput: '3', options: ['2', '3', '[2,3]', 'Error'], correct: 1, explanation: 'Spreading happens left to right, so b is applied second and its y overwrites a\'s. Swap the order and you get 2. Nothing is combined and nothing errors — a key holds one value, so a silent overwrite is the whole behaviour. This is exactly why {...defaults, ...userConfig} is the standard ordering.', hint: 'Which object is written into the new one last?' },
    ],
    20: [
        { type: 'pair', prompt: 'Match each container to what it is for', pairs: [{ id: 1, left: 'Array', right: 'Ordered, reachable by index' }, { id: 2, left: 'Set', right: 'No duplicates, fast membership' }, { id: 3, left: 'Map', right: 'Any key type, remembers order' }, { id: 4, left: 'Object', right: 'String-keyed named fields' }], explanation: 'Map versus Object is the one worth internalising: an Object only takes string and symbol keys, inherits from the prototype chain, and has no reliable size. A Map takes any value as a key — including objects and numbers that stay numbers — reports .size directly, and iterates in insertion order. Reach for Map when the keys are data rather than field names.' },
        { type: 'trace', prompt: 'After destructuring, what does x + y give?', code: [{ text: 'const point = [3, 7];' }, { text: 'const [x, y] = point;' }, { text: 'console.log(x + y);', highlight: true }], options: ['[3,7]', '10', '37', 'Error'], correct: 1, explanation: 'Destructuring binds x to 3 and y to 7, so + adds two numbers and gives 10. "37" would be the answer if they were strings, where + concatenates — and JavaScript will happily do that without warning if the array held ["3", "7"]. Unlike Python, a count mismatch is not an error here: const [x, y, z] = point simply leaves z undefined.', hint: 'What type are x and y after line 2? That decides what + does.' },
        { type: 'realworld', prompt: 'You will look up a number by name thousands of times. Which shape?', scenario: '📱 Given "Ali", return "555-1234".', options: [{ code: 'const pb = new Map();\npb.set("Ali", "555-1234");', label: 'Map keyed by name' }, { code: 'const pb = [["Ali", "555-1234"], ["Ece", "555-5678"]];', label: 'Array of name/number pairs' }, { code: 'const pb = new Set(["555-1234", "555-5678"]);', label: 'Set of numbers' }, { code: 'const pb = ["Ali", "555-1234", "Ece", "555-5678"];', label: 'Flat alternating array' }], correct: 0, explanation: 'A Map hashes the name straight to the number, so lookup cost does not grow with the phone book. The array of pairs holds the same information but must be scanned. The Set has no names to look up by. The flat array encodes it but every read means index arithmetic, and one insertion in the wrong place corrupts every pair after it. A plain object would also work here — Map wins when keys are not strings or when insertion order and size matter.', hint: 'Two of these contain all the information. Ask what each costs per lookup as the book grows.' },
    ],
}
