/* ══════════════════════════════════════════════════
   JAVASCRIPT EXERCISES — CH6-CH10 (nodes 21-42)
   Expanded: 4-5 exercises per node, diverse types
   University-aligned: MIT 6.006, Stanford CS106B, Princeton COS226
   ══════════════════════════════════════════════════ */
export const jsExercisesCh6to10 = {
    // ═══ CH6: ALGORITHMS I ═══
    21: [
        { type: 'algostep', prompt: 'Selection sort: find min in [64,25,12,22,11]', array: [64, 25, 12, 22, 11], step: 1, description: 'Scanning for minimum...', question: 'Min goes where?', options: ['11→index 0', '12→index 0', '22→index 1', '25→index 0'], correct: 0 },
        { type: 'trace', prompt: 'After ONE bubble sort pass on [5,1,4,2,8]?', code: [{ text: '// Compare adjacent, swap if needed' }, { text: '[5,1]→swap [1,5,4,2,8]' }, { text: '[5,4]→swap [1,4,5,2,8]' }, { text: '[5,2]→swap [1,4,2,5,8]' }, { text: '[5,8]→ok   [1,4,2,5,8]', highlight: true }], options: ['Largest at end', 'Array sorted', 'Smallest at start', 'Nothing guaranteed'], correct: 0 },
        { type: 'pair', prompt: 'Match sort to worst case', pairs: [{ id: 1, left: 'Bubble', right: 'O(n²)' }, { id: 2, left: 'Merge', right: 'O(n log n)' }, { id: 3, left: 'Insertion (best)', right: 'O(n)' }, { id: 4, left: 'Array.sort()', right: 'Timsort O(n log n)' }] },
        { type: 'scramble', prompt: 'Build insertion sort', pieces: [{ id: 'a', text: 'function insertionSort(arr) {' }, { id: 'b', text: '    for (let i = 1; i < arr.length; i++) {' }, { id: 'c', text: '        let key = arr[i];' }, { id: 'd', text: '        let j = i - 1;' }, { id: 'e', text: '        while (j >= 0 && arr[j] > key) {' }, { id: 'f', text: '            arr[j+1] = arr[j]; j--;' }, { id: 'g', text: '        }' }, { id: 'h', text: '        arr[j+1] = key;' }, { id: 'i', text: '    }' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        arr[j] = key;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'bug', prompt: 'Why does this sort fail for some inputs?', code: [{ text: 'function sort(arr) {', hasError: false }, { text: '    return arr.sort();', hasError: true }, { text: '}', hasError: false }, { text: 'sort([10,9,1,2,100]); // [1,10,100,2,9]', hasError: false }], correctLine: 1 },
    ],
    22: [
        { type: 'algostep', prompt: 'Binary search for 7 in [1,3,5,7,9,11,13]', array: [1, 3, 5, 7, 9, 11, 13], step: 1, description: 'lo=0 hi=6 mid=3 arr[3]=7=target!', question: 'Comparisons needed?', options: ['1', '2', '3', '7'], correct: 0 },
        { type: 'trace', prompt: 'Search for 6 in [1,3,5,7,9]?', code: [{ text: 'function bsearch(arr, t) {' }, { text: '    let lo = 0, hi = arr.length - 1;' }, { text: '    while (lo <= hi) {' }, { text: '        const mid = Math.floor((lo+hi)/2);' }, { text: '        if (arr[mid] === t) return mid;' }, { text: '        else if (arr[mid] < t) lo = mid+1;' }, { text: '        else hi = mid-1;' }, { text: '    }' }, { text: '    return -1;', highlight: true }, { text: '}' }], options: ['Returns 2', 'Returns 3', 'Returns -1', 'Infinite loop'], correct: 2 },
        { type: 'errordecode', prompt: 'Why can binary search have issues?', errorText: 'const mid = (lo + hi) / 2; // float!\n// In large arrays: lo+hi can exceed Number.MAX_SAFE_INTEGER', question: 'Safe mid calc?', options: ['lo + Math.floor((hi-lo)/2)', '(lo+hi) % 2', 'hi - lo', 'lo * hi'], correct: 0 },
        { type: 'realworld', prompt: 'Binary search requires what?', scenario: '⚠️ Precondition for binary search to work.', options: [{ code: '// Array MUST be sorted', label: 'Sorted array' }, { code: '// Array must have unique elements', label: 'Unique elements' }, { code: '// Array must be small', label: 'Small array' }, { code: '// No precondition', label: 'Works on anything' }], correct: 0 },
        { type: 'bug', prompt: 'Infinite loop bug — which line?', code: [{ text: 'function bs(arr, t) {', hasError: false }, { text: '    let lo = 0, hi = arr.length;', hasError: false }, { text: '    while (lo < hi) {', hasError: false }, { text: '        const mid = (lo + hi) >> 1;', hasError: false }, { text: '        if (arr[mid] < t) lo = mid;', hasError: true }, { text: '        else hi = mid;', hasError: false }, { text: '    }', hasError: false }], correctLine: 4 },
    ],
    23: [
        { type: 'trace', prompt: 'Time complexity?', code: [{ text: 'for (let i = 0; i < n; i++) {' }, { text: '    for (let j = 0; j < n; j++) {' }, { text: '        console.log(i, j);' }, { text: '    }' }, { text: '}' }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'], correct: 1 },
        { type: 'pair', prompt: 'Match complexity', pairs: [{ id: 1, left: 'Binary Search', right: 'O(log n)' }, { id: 2, left: 'Bubble Sort', right: 'O(n²)' }, { id: 3, left: 'Merge Sort', right: 'O(n log n)' }, { id: 4, left: 'Map/Set lookup', right: 'O(1) avg' }] },
        { type: 'trace', prompt: 'This loop complexity?', code: [{ text: 'let i = n;' }, { text: 'while (i > 0) {' }, { text: '    console.log(i);' }, { text: '    i = Math.floor(i / 2);', highlight: true }, { text: '}' }], options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
        { type: 'refactor', prompt: 'Faster membership check?', originalCode: '// Check if x exists in array\nif (arr.includes(x)) { // O(n) }', options: [{ code: 'const mySet = new Set(arr);\nif (mySet.has(x)) { // O(1) }', label: 'Set — O(1) lookup' }, { code: 'arr.sort();\n// then binary search — O(n log n)', label: 'Sort + search' }, { code: 'for (const item of arr) {\n    if (item === x) break;\n}', label: 'Still O(n)' }], correct: 0 },
        { type: 'output', prompt: 'What is the space complexity?', code: [{ text: 'function reverse(str) {' }, { text: '    return [...str].reverse().join("");' }, { text: '}' }], terminalOutput: 'O(n)', options: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'], correct: 1 },
    ],
    24: [
        { type: 'trace', prompt: 'Two-sum brute force?', code: [{ text: 'function twoSum(nums, t) {' }, { text: '    for (let i = 0; i < nums.length; i++) {' }, { text: '        for (let j = i+1; j < nums.length; j++) {' }, { text: '            if (nums[i]+nums[j] === t)' }, { text: '                return [i, j];' }, { text: '        }' }, { text: '    }' }, { text: '}' }, { text: 'console.log(twoSum([2,7,11,15], 9));', highlight: true }], options: ['[0, 1]', '[1, 2]', '[0, 3]', 'undefined'], correct: 0 },
        { type: 'refactor', prompt: 'O(n²)→O(n) two-sum?', originalCode: '// O(n²)\nfor (let i=0; i<nums.length; i++)\n    for (let j=i+1; j<nums.length; j++)\n        if (nums[i]+nums[j]===target) return [i,j];', options: [{ code: 'const seen = new Map();\nfor (let i = 0; i < nums.length; i++) {\n    const comp = target - nums[i];\n    if (seen.has(comp)) return [seen.get(comp), i];\n    seen.set(nums[i], i);\n}', label: 'Map — O(n)' }, { code: 'nums.sort((a,b)=>a-b);\n// two pointer', label: 'Sort + two pointer' }, { code: 'nums.map(n => nums.indexOf(target-n));', label: 'Still O(n²)' }], correct: 0 },
        { type: 'scramble', prompt: 'Build O(n) two-sum', pieces: [{ id: 'a', text: 'function twoSum(nums, target) {' }, { id: 'b', text: '    const seen = new Map();' }, { id: 'c', text: '    for (let i = 0; i < nums.length; i++) {' }, { id: 'd', text: '        const comp = target - nums[i];' }, { id: 'e', text: '        if (seen.has(comp)) {' }, { id: 'f', text: '            return [seen.get(comp), i];' }, { id: 'g', text: '        }' }, { id: 'h', text: '        seen.set(nums[i], i);' }, { id: 'i', text: '    }' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        seen.set(i, nums[i]);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'bug', prompt: 'Why does this two-sum fail?', code: [{ text: 'function twoSum(nums, t) {', hasError: false }, { text: '    const map = {};', hasError: false }, { text: '    for (const n of nums) {', hasError: true }, { text: '        if (map[t-n] !== undefined) return [map[t-n], ???];', hasError: false }], correctLine: 2 },
    ],
    // ═══ CH7: DATA STRUCTURES II ═══
    25: [
        { type: 'trace', prompt: 'Stack: push 1,2,3 then pop twice?', code: [{ text: 'const stack = [];' }, { text: 'stack.push(1); stack.push(2); stack.push(3);' }, { text: 'stack.pop(); stack.pop();' }, { text: 'console.log(stack);', highlight: true }], options: ['[1]', '[3]', '[1,2]', '[]'], correct: 0 },
        { type: 'pair', prompt: 'Match concepts', pairs: [{ id: 1, left: 'Stack', right: 'LIFO' }, { id: 2, left: 'Queue', right: 'FIFO' }, { id: 3, left: 'Deque', right: 'Double-ended' }, { id: 4, left: 'Priority Queue', right: 'Min/Max first' }] },
        { type: 'scramble', prompt: 'Check balanced brackets', pieces: [{ id: 'a', text: 'function isValid(s) {' }, { id: 'b', text: '    const stack = [];' }, { id: 'c', text: '    const pairs = {")":"(", "]":"[", "}":"{"};' }, { id: 'd', text: '    for (const c of s) {' }, { id: 'e', text: '        if ("([{".includes(c)) stack.push(c);' }, { id: 'f', text: '        else if (!stack.length || stack.pop() !== pairs[c])' }, { id: 'g', text: '            return false;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return stack.length === 0;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '    return true;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'realworld', prompt: 'Where are stacks used? (CS50)', scenario: '🧠 Real applications of LIFO', options: [{ code: '// Undo/Redo, call stack, bracket matching', label: 'Undo, call stack, brackets ✓' }, { code: '// Sorting data', label: 'Sorting — no' }, { code: '// Database queries', label: 'SQL — no' }, { code: '// Random access', label: 'Array is better' }], correct: 0 },
        { type: 'errordecode', prompt: 'Decode stack error', errorText: 'RangeError: Maximum call stack size exceeded\n    at factorial (main.js:2)', question: 'Cause?', options: ['Infinite recursion — no base case', 'Array too large', 'Memory leak', 'Syntax error'], correct: 0 },
    ],
    26: [
        { type: 'trace', prompt: 'head.next.val?', code: [{ text: 'class Node {' }, { text: '    constructor(val) { this.val=val; this.next=null; }' }, { text: '}' }, { text: 'const a=new Node(1), b=new Node(2), c=new Node(3);' }, { text: 'a.next=b; b.next=c;' }, { text: 'console.log(a.next.val);', highlight: true }], options: ['1', '2', '3', 'null'], correct: 1 },
        { type: 'scramble', prompt: 'Traverse linked list', pieces: [{ id: 'a', text: 'function traverse(head) {' }, { id: 'b', text: '    let curr = head;' }, { id: 'c', text: '    while (curr) {' }, { id: 'd', text: '        console.log(curr.val);' }, { id: 'e', text: '        curr = curr.next;' }, { id: 'f', text: '    }' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '        curr = curr.prev;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'realworld', prompt: 'When use linked list over array?', scenario: '🤔 Which scenario benefits from linked list?', options: [{ code: '// Frequent insert/delete at beginning: O(1)', label: 'Fast insert at head' }, { code: '// Random access by index', label: 'Index access — array better' }, { code: '// Sorting data', label: 'Sorting — array better' }, { code: '// Binary search', label: 'Binary search — array' }], correct: 0 },
        { type: 'bug', prompt: 'Reverse linked list — bug?', code: [{ text: 'function reverse(head) {', hasError: false }, { text: '    let prev = null, curr = head;', hasError: false }, { text: '    while (curr) {', hasError: false }, { text: '        curr.next = prev;', hasError: true }, { text: '        prev = curr; curr = curr.next;', hasError: false }], correctLine: 3 },
    ],
    27: [
        { type: 'trace', prompt: 'In-order BST traversal?', code: [{ text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '//    / \\' }, { text: '//   1   3' }, { text: '// In-order: L→Root→R', highlight: true }], options: ['4 2 1 3 6', '1 2 3 4 6', '1 3 2 6 4', '4 2 6 1 3'], correct: 1 },
        { type: 'pair', prompt: 'Match traversals', pairs: [{ id: 1, left: 'In-order', right: 'L→Root→R (sorted!)' }, { id: 2, left: 'Pre-order', right: 'Root→L→R' }, { id: 3, left: 'Post-order', right: 'L→R→Root' }, { id: 4, left: 'Level-order', right: 'BFS layer by layer' }] },
        { type: 'fillgap', prompt: 'Complete BST search', codeParts: [{ text: 'function search(node, val) {\n    if (!node) return null;\n    if (val === node.val) return node;\n    return val < node.val\n        ? ', type: 'fixed' }, { text: 'search(node.left, val)', type: 'gap', id: 'g1' }, { text: '\n        : search(node.right, val);\n}', type: 'fixed' }], bank: ['search(node.left, val)', 'search(node.right, val)', 'search(node, val-1)', 'node.left'], correctFill: { g1: 'search(node.left, val)' } },
        { type: 'output', prompt: 'BST insert: where does 5 go?', code: [{ text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '// Insert 5: 5<6 → go left' }, { text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '//        /' }, { text: '//       5', highlight: true }], terminalOutput: 'Left child of 6', options: ['Left child of 6', 'Right child of 4', 'Left child of 2', 'Root'], correct: 0 },
    ],
    28: [
        { type: 'video', title: 'Data Structures Visualized', description: 'Stacks, queues, linked lists, trees — when to use each, trade-offs, and real-world applications.', duration: '4:00', thumbnail: '🎥' },
        { type: 'pair', prompt: 'Match structure to operation speed', pairs: [{ id: 1, left: 'Array[i]', right: 'O(1)' }, { id: 2, left: 'LinkedList insert head', right: 'O(1)' }, { id: 3, left: 'BST search', right: 'O(log n) avg' }, { id: 4, left: 'Array unshift()', right: 'O(n)' }] },
        { type: 'realworld', prompt: 'Which DS for browser history?', scenario: '🌐 Back/Forward navigation needs...', options: [{ code: '// Two stacks: back stack + forward stack', label: 'Two stacks ✓' }, { code: '// Single array', label: 'Array — complex' }, { code: '// Queue', label: 'Queue — wrong order' }, { code: '// Linked list', label: 'Possible but overkill' }], correct: 0 },
        { type: 'trace', prompt: 'Queue operations?', code: [{ text: 'const q = [];' }, { text: 'q.push(1); q.push(2); q.push(3);' }, { text: 'q.shift(); // removes 1' }, { text: 'q.push(4);' }, { text: 'console.log(q);', highlight: true }], options: ['[2,3,4]', '[1,2,3,4]', '[4,3,2]', '[1,3,4]'], correct: 0 },
    ],
    // ═══ CH8: ALGORITHMS II ═══
    29: [
        { type: 'trace', prompt: 'Tower of Hanoi: 3 disks = ? moves', code: [{ text: 'function hanoi(n) {' }, { text: '    if (n === 1) return 1;' }, { text: '    return 2 * hanoi(n-1) + 1;' }, { text: '}' }, { text: 'console.log(hanoi(3));', highlight: true }], options: ['3', '5', '7', '8'], correct: 2 },
        { type: 'trace', prompt: 'sumDigits(1234)?', code: [{ text: 'function sumDigits(n) {' }, { text: '    if (n < 10) return n;' }, { text: '    return n%10 + sumDigits(Math.floor(n/10));' }, { text: '}' }, { text: 'console.log(sumDigits(1234));', highlight: true }], options: ['10', '1234', '4', '24'], correct: 0 },
        { type: 'output', prompt: 'Recursive power complexity?', code: [{ text: 'function power(b, e) {' }, { text: '    if (e === 0) return 1;' }, { text: '    if (e % 2 === 0) {' }, { text: '        const h = power(b, e/2);' }, { text: '        return h * h;' }, { text: '    }' }, { text: '    return b * power(b, e-1);' }, { text: '}' }], terminalOutput: 'O(log n)', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
        { type: 'bug', prompt: 'Recursion bug — why infinite?', code: [{ text: 'function flatten(arr) {', hasError: false }, { text: '    const result = [];', hasError: false }, { text: '    for (const item of arr) {', hasError: false }, { text: '        if (Array.isArray(item)) result.push(...flatten(item));', hasError: false }, { text: '        else result.push(item);', hasError: false }, { text: '    }', hasError: false }, { text: '    return result;', hasError: false }, { text: '}', hasError: false }, { text: '// What if arr contains itself? arr.push(arr)', hasError: true }], correctLine: 8 },
        { type: 'fillgap', prompt: 'Recursive array sum', codeParts: [{ text: 'function sum(arr) {\n    if (arr.length === 0) return 0;\n    return ', type: 'fixed' }, { text: 'arr[0] + sum(arr.slice(1));', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['arr[0] + sum(arr.slice(1));', 'sum(arr) + arr[0];', 'arr.reduce((a,b)=>a+b);', 'arr[0] + arr[1];'], correctFill: { g1: 'arr[0] + sum(arr.slice(1));' } },
    ],
    30: [
        { type: 'algostep', prompt: 'Merge [1,3,5] and [2,4,6]', array: [1, 3, 5, 2, 4, 6], step: 1, description: 'Compare: 1<2, take 1.', question: 'Next comparison?', options: ['3 vs 2', '1 vs 2', '5 vs 6', '3 vs 4'], correct: 0 },
        { type: 'trace', prompt: 'Merge sort time complexity?', code: [{ text: '// Divide in half: log₂(n) levels' }, { text: '// Merge: O(n) per level' }, { text: '// Total: O(n × log n)', highlight: true }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'], correct: 2 },
        { type: 'pair', prompt: 'Divide & Conquer examples', pairs: [{ id: 1, left: 'Merge Sort', right: 'Split array, sort halves' }, { id: 2, left: 'Quick Sort', right: 'Partition around pivot' }, { id: 3, left: 'Binary Search', right: 'Halve search space' }, { id: 4, left: 'Strassen', right: 'Matrix multiply' }] },
        { type: 'scramble', prompt: 'Build merge function', pieces: [{ id: 'a', text: 'function merge(left, right) {' }, { id: 'b', text: '    const result = [];' }, { id: 'c', text: '    let i = 0, j = 0;' }, { id: 'd', text: '    while (i < left.length && j < right.length) {' }, { id: 'e', text: '        if (left[i] <= right[j]) result.push(left[i++]);' }, { id: 'f', text: '        else result.push(right[j++]);' }, { id: 'g', text: '    }' }, { id: 'h', text: '    return [...result, ...left.slice(i), ...right.slice(j)];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    return left.concat(right).sort();' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
    ],
    31: [
        { type: 'trace', prompt: 'fib(5) calls WITHOUT memo?', code: [{ text: 'function fib(n) {' }, { text: '    if (n <= 1) return n;' }, { text: '    return fib(n-1) + fib(n-2);' }, { text: '}' }, { text: '// fib(5) call tree has 15 calls!', highlight: true }], options: ['5', '9', '15', '25'], correct: 2 },
        { type: 'refactor', prompt: 'O(2ⁿ) fib → O(n)?', originalCode: 'function fib(n) {\n    if (n<=1) return n;\n    return fib(n-1)+fib(n-2);\n}', options: [{ code: 'const memo = {};\nfunction fib(n) {\n    if (n in memo) return memo[n];\n    if (n<=1) return n;\n    memo[n] = fib(n-1)+fib(n-2);\n    return memo[n];\n}', label: 'Memoization — O(n)' }, { code: 'const fib = n => n<=1 ? n : fib(n-1)+fib(n-2);', label: 'Still O(2ⁿ)' }, { code: 'const fib = n => Math.factorial(n);', label: 'Wrong formula' }], correct: 0 },
        { type: 'fillgap', prompt: 'Complete: climbing stairs DP', codeParts: [{ text: 'function climb(n) {\n    if (n <= 2) return n;\n    const dp = new Array(n+1).fill(0);\n    dp[1] = 1; dp[2] = 2;\n    for (let i = 3; i <= n; i++) {\n        ', type: 'fixed' }, { text: 'dp[i] = dp[i-1] + dp[i-2];', type: 'gap', id: 'g1' }, { text: '\n    }\n    return dp[n];\n}', type: 'fixed' }], bank: ['dp[i] = dp[i-1] + dp[i-2];', 'dp[i] = dp[i-1] * 2;', 'dp[i] = i;', 'dp[i] = dp[i-1];'], correctFill: { g1: 'dp[i] = dp[i-1] + dp[i-2];' } },
        { type: 'errordecode', prompt: 'Why does memoized fib still crash for fib(100000)?', errorText: 'RangeError: Maximum call stack size exceeded', question: 'Root cause?', options: ['Recursion depth limit — use tabulation instead', 'Memo object too large', 'fib(100000) is too big', 'JavaScript cant do math'], correct: 0 },
        { type: 'realworld', prompt: 'Memoization vs Tabulation?', scenario: '🧠 Two DP approaches', options: [{ code: '// Memo: top-down + cache\n// Tab: bottom-up + table\n// Tab avoids stack overflow!', label: 'Top-down vs bottom-up ✓' }, { code: '// Same thing', label: 'Not the same' }, { code: '// Memo is always better', label: 'Not always' }, { code: '// Tab is always better', label: 'Depends on problem' }], correct: 0 },
    ],
    32: [
        { type: 'trace', prompt: 'Fast power: power(2,10)?', code: [{ text: 'function power(b, e) {' }, { text: '    if (e===0) return 1;' }, { text: '    if (e%2===0) { const h=power(b,e/2); return h*h; }' }, { text: '    return b*power(b,e-1);' }, { text: '}' }, { text: 'console.log(power(2, 10));', highlight: true }], options: ['20', '100', '512', '1024'], correct: 3 },
        { type: 'realworld', prompt: 'When does DP help?', scenario: '🧠 DP works when problem has...', options: [{ code: '// 1. Overlapping subproblems\n// 2. Optimal substructure', label: 'Both conditions ✓' }, { code: '// Only overlapping subproblems', label: 'One condition' }, { code: '// Any recursive problem', label: 'Not always' }, { code: '// Only sorting problems', label: 'Sorting only' }], correct: 0 },
        { type: 'scramble', prompt: 'Build coin change DP', pieces: [{ id: 'a', text: 'function coinChange(coins, amount) {' }, { id: 'b', text: '    const dp = new Array(amount+1).fill(Infinity);' }, { id: 'c', text: '    dp[0] = 0;' }, { id: 'd', text: '    for (let i = 1; i <= amount; i++) {' }, { id: 'e', text: '        for (const c of coins) {' }, { id: 'f', text: '            if (i-c >= 0) dp[i] = Math.min(dp[i], dp[i-c]+1);' }, { id: 'g', text: '        }' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return dp[amount] === Infinity ? -1 : dp[amount];' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '    dp[0] = 1;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'trace', prompt: 'Coin change: coins=[1,5,6], amount=11?', code: [{ text: '// dp[11] = min coins' }, { text: '// Greedy: 6+5 = 2 coins ✓' }, { text: '// dp approach confirms: 2', highlight: true }], options: ['3', '2', '11', '6'], correct: 1 },
    ],
    // ═══ CH9: ADVANCED ═══
    33: [
        { type: 'pair', prompt: 'Match graph terms', pairs: [{ id: 1, left: 'Adjacency List', right: 'Object of arrays' }, { id: 2, left: 'Adjacency Matrix', right: '2D array' }, { id: 3, left: 'Directed', right: 'One-way edges' }, { id: 4, left: 'Undirected', right: 'Two-way edges' }] },
        { type: 'output', prompt: 'Adjacency list for A→B, A→C, B→C?', code: [{ text: 'const graph = {' }, { text: '    A: ["B", "C"],' }, { text: '    B: ["C"],' }, { text: '    C: []' }, { text: '};' }, { text: 'console.log(graph.A.length);' }], terminalOutput: '2', options: ['1', '2', '3', '0'], correct: 1 },
        { type: 'fillgap', prompt: 'Build adjacency list from edges', codeParts: [{ text: 'function buildGraph(edges) {\n    const graph = {};\n    for (const [u, v] of edges) {\n        if (!graph[u]) graph[u] = [];\n        if (!graph[v]) graph[v] = [];\n        ', type: 'fixed' }, { text: 'graph[u].push(v);', type: 'gap', id: 'g1' }, { text: '\n    }\n    return graph;\n}', type: 'fixed' }], bank: ['graph[u].push(v);', 'graph[v].push(u);', 'graph[u] = v;', 'graph.push([u,v]);'], correctFill: { g1: 'graph[u].push(v);' } },
        { type: 'realworld', prompt: 'Graph in real life?', scenario: '🌍 Real-world graph applications', options: [{ code: '// Social network: users=nodes, friends=edges\n// Maps: intersections=nodes, roads=edges', label: 'Social networks, maps ✓' }, { code: '// Sorting numbers', label: 'No graph needed' }, { code: '// Reading files', label: 'Sequential, not graph' }, { code: '// Calculator', label: 'No relationships' }], correct: 0 },
    ],
    34: [
        { type: 'trace', prompt: 'BFS from A. Visit order?', code: [{ text: '// A→[B,C], B→[D], C→[D], D→[]' }, { text: 'function bfs(start, graph) {' }, { text: '    const q = [start]; const seen = new Set([start]);' }, { text: '    while (q.length) {' }, { text: '        const node = q.shift(); console.log(node);' }, { text: '        for (const n of graph[node]) {' }, { text: '            if (!seen.has(n)) { seen.add(n); q.push(n); }' }, { text: '        }' }, { text: '    }', highlight: true }, { text: '}' }], options: ['A B C D', 'A B D C', 'A C B D', 'D B C A'], correct: 0 },
        { type: 'pair', prompt: 'BFS vs DFS', pairs: [{ id: 1, left: 'BFS', right: 'Queue (FIFO)' }, { id: 2, left: 'DFS', right: 'Stack (LIFO)' }, { id: 3, left: 'BFS use', right: 'Shortest path' }, { id: 4, left: 'DFS use', right: 'Cycle detection' }] },
        { type: 'bug', prompt: 'BFS bug — why visit nodes twice?', code: [{ text: 'function bfs(graph, start) {', hasError: false }, { text: '    const q = [start];', hasError: false }, { text: '    while (q.length) {', hasError: false }, { text: '        const node = q.shift();', hasError: false }, { text: '        console.log(node);', hasError: false }, { text: '        for (const n of graph[node]) q.push(n);', hasError: true }], correctLine: 5 },
        { type: 'scramble', prompt: 'Build DFS with stack', pieces: [{ id: 'a', text: 'function dfs(graph, start) {' }, { id: 'b', text: '    const stack = [start];' }, { id: 'c', text: '    const visited = new Set();' }, { id: 'd', text: '    while (stack.length) {' }, { id: 'e', text: '        const node = stack.pop();' }, { id: 'f', text: '        if (visited.has(node)) continue;' }, { id: 'g', text: '        visited.add(node);' }, { id: 'h', text: '        for (const n of graph[node]) stack.push(n);' }, { id: 'i', text: '    }' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        const node = stack.shift();' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
    ],
    35: [
        { type: 'trace', prompt: 'Two-pointer: pair summing to 6 in [1,2,3,4,6]?', code: [{ text: 'let lo = 0, hi = 4; // 1+6=7>6' }, { text: 'hi--;              // 1+4=5<6' }, { text: 'lo++;              // 2+4=6 ✓', highlight: true }], options: ['indices [1,5]', 'indices [0,4]', 'indices [1,3]', 'indices [2,3]'], correct: 2 },
        { type: 'refactor', prompt: 'O(n²) duplicates → O(n)?', originalCode: 'for (let i = 0; i < arr.length; i++)\n    for (let j = i+1; j < arr.length; j++)\n        if (arr[i]===arr[j]) return true;', options: [{ code: 'return arr.length !== new Set(arr).size;', label: 'Set — O(n)' }, { code: 'arr.sort();\nfor (let i=0;i<arr.length-1;i++)\n    if (arr[i]===arr[i+1]) return true;', label: 'Sort — O(n log n)' }, { code: 'return [...new Set(arr)].length < arr.length;', label: 'Set spread — O(n)' }], correct: 0 },
        { type: 'fillgap', prompt: 'Sliding window: max sum of k consecutive', codeParts: [{ text: 'function maxSum(arr, k) {\n    let window = arr.slice(0,k).reduce((a,b)=>a+b,0);\n    let best = window;\n    for (let i = k; i < arr.length; i++) {\n        ', type: 'fixed' }, { text: 'window += arr[i] - arr[i-k];', type: 'gap', id: 'g1' }, { text: '\n        best = Math.max(best, window);\n    }\n    return best;\n}', type: 'fixed' }], bank: ['window += arr[i] - arr[i-k];', 'window = arr.slice(i-k,i).reduce((a,b)=>a+b);', 'window += arr[i];', 'window = arr[i];'], correctFill: { g1: 'window += arr[i] - arr[i-k];' } },
        { type: 'realworld', prompt: 'Sliding window best for?', scenario: '🔍 When to use sliding window pattern', options: [{ code: '// Contiguous subarray problems:\n// max sum, min length, longest substring', label: 'Contiguous subarray/substring ✓' }, { code: '// Tree traversal', label: 'Trees — different' }, { code: '// Sorting', label: 'Sorting — different' }, { code: '// Hash table', label: 'Different pattern' }], correct: 0 },
    ],
    36: [
        { type: 'scramble', prompt: 'Build BFS shortest path', pieces: [{ id: 'a', text: 'function bfs(graph, start) {' }, { id: 'b', text: '    const q = [start];' }, { id: 'c', text: '    const visited = new Set([start]);' }, { id: 'd', text: '    while (q.length) {' }, { id: 'e', text: '        const node = q.shift();' }, { id: 'f', text: '        for (const nb of graph[node]) {' }, { id: 'g', text: '            if (!visited.has(nb)) {' }, { id: 'h', text: '                visited.add(nb); q.push(nb);' }, { id: 'i', text: '            }' }, { id: 'j', text: '        }' }, { id: 'k', text: '    }' }, { id: 'l', text: '}' }], distractors: [{ id: 'm', text: '        q.push(node);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'] },
        { type: 'trace', prompt: 'DFS from A?', code: [{ text: '// A→[B,C], B→[D], C→[], D→[]' }, { text: 'function dfs(node, graph, seen=new Set()) {' }, { text: '    if (seen.has(node)) return;' }, { text: '    seen.add(node); console.log(node);' }, { text: '    for (const n of graph[node]) dfs(n,graph,seen);', highlight: true }, { text: '}' }], options: ['A B D C', 'A B C D', 'A C B D', 'D B C A'], correct: 0 },
        { type: 'errordecode', prompt: 'Graph cycle detection issue', errorText: 'InternalError: too much recursion\n    at dfs (graph.js:3)', question: 'Cause?', options: ['No visited check — cycles cause infinite recursion', 'Graph too large', 'Wrong data type', 'Missing return'], correct: 0 },
        { type: 'pair', prompt: 'Graph algorithm applications', pairs: [{ id: 1, left: 'BFS', right: 'Shortest path unweighted' }, { id: 2, left: 'DFS', right: 'Topological sort' }, { id: 3, left: 'Dijkstra', right: 'Shortest weighted path' }, { id: 4, left: 'Union-Find', right: 'Connected components' }] },
    ],
    // ═══ CH10: MASTERY ═══
    37: [
        { type: 'trace', prompt: 'Climbing stairs n=4?', code: [{ text: '// dp[0]=1, dp[1]=1' }, { text: '// dp[2] = dp[1]+dp[0] = 2' }, { text: '// dp[3] = dp[2]+dp[1] = 3' }, { text: '// dp[4] = dp[3]+dp[2] = ?', highlight: true }], options: ['4', '5', '6', '8'], correct: 1 },
        { type: 'pair', prompt: 'Match DP patterns', pairs: [{ id: 1, left: 'Fibonacci', right: 'dp[i]=dp[i-1]+dp[i-2]' }, { id: 2, left: 'Knapsack', right: 'Include or exclude item' }, { id: 3, left: 'LCS', right: 'Match or skip chars' }, { id: 4, left: 'Coin Change', right: 'min(dp[amt-coin]+1)' }] },
        { type: 'fillgap', prompt: 'Longest Common Subsequence', codeParts: [{ text: 'function lcs(a, b) {\n    const dp = Array(a.length+1).fill(null).map(()=>Array(b.length+1).fill(0));\n    for (let i=1; i<=a.length; i++)\n        for (let j=1; j<=b.length; j++)\n            dp[i][j] = a[i-1]===b[j-1]\n                ? ', type: 'fixed' }, { text: 'dp[i-1][j-1] + 1', type: 'gap', id: 'g1' }, { text: '\n                : Math.max(dp[i-1][j], dp[i][j-1]);\n    return dp[a.length][b.length];\n}', type: 'fixed' }], bank: ['dp[i-1][j-1] + 1', 'dp[i][j] + 1', 'dp[i-1][j-1]', 'i + j'], correctFill: { g1: 'dp[i-1][j-1] + 1' } },
        { type: 'bug', prompt: '0-1 Knapsack bug?', code: [{ text: 'for (let i = 1; i <= n; i++)', hasError: false }, { text: '    for (let w = 0; w <= W; w++)', hasError: true }, { text: '        if (weights[i-1] <= w)', hasError: false }, { text: '            dp[i][w] = Math.max(dp[i-1][w], values[i-1]+dp[i-1][w-weights[i-1]]);', hasError: false }], correctLine: 1 },
    ],
    38: [
        { type: 'pair', prompt: 'Match pattern to problem', pairs: [{ id: 1, left: 'Sliding window', right: 'Max subarray of size k' }, { id: 2, left: 'Two pointer', right: 'Pair sum sorted' }, { id: 3, left: 'BFS', right: 'Shortest path unweighted' }, { id: 4, left: 'DP', right: 'Min coins for amount' }] },
        { type: 'realworld', prompt: 'Problem-solving strategy?', scenario: '🎯 You get a hard problem in an interview.', options: [{ code: '// 1. Brute force first\n// 2. Identify pattern\n// 3. Optimize with right DS\n// 4. Code + test edge cases', label: 'Structured approach ✓' }, { code: '// Jump to optimal solution', label: 'Risky' }, { code: '// Give up', label: 'Never!' }, { code: '// Memorize solutions', label: 'Not scalable' }], correct: 0 },
        { type: 'refactor', prompt: 'Max subarray — which algo?', originalCode: '// Brute: O(n²)\nfor (let i=0;i<n;i++) {\n    let curr = 0;\n    for (let j=i;j<n;j++) {\n        curr += arr[j];\n        best = Math.max(best, curr);\n    }\n}', options: [{ code: "// Kadane's: O(n)\nlet curr = arr[0], best = arr[0];\nfor (let i=1; i<arr.length; i++) {\n    curr = Math.max(arr[i], curr+arr[i]);\n    best = Math.max(best, curr);\n}", label: "Kadane's — O(n)" }, { code: '// Sort + take last k', label: 'Sorting' }, { code: '// Recursion no memo', label: 'O(2ⁿ)' }], correct: 0 },
        { type: 'trace', prompt: 'Kadane on [-2,1,-3,4,-1,2,1,-5,4]?', code: [{ text: '// curr: -2,1,-2,4,3,5,6,1,5' }, { text: '// best: -2,1,1,4,4,5,6,6,6', highlight: true }], options: ['6', '5', '4', '7'], correct: 0 },
    ],
    39: [
        { type: 'fillgap', prompt: 'Reverse string in-place', codeParts: [{ text: 'function reverse(arr) {\n    let lo = 0, hi = arr.length - 1;\n    while (lo < hi) {\n        ', type: 'fixed' }, { text: '[arr[lo], arr[hi]] = [arr[hi], arr[lo]];', type: 'gap', id: 'g1' }, { text: '\n        lo++; hi--;\n    }\n}', type: 'fixed' }], bank: ['[arr[lo], arr[hi]] = [arr[hi], arr[lo]];', 'arr.reverse();', 'lo, hi = hi, lo;', 'arr[lo] = arr[hi];'], correctFill: { g1: '[arr[lo], arr[hi]] = [arr[hi], arr[lo]];' } },
        { type: 'trace', prompt: 'Valid palindrome check?', code: [{ text: 'function isPalindrome(s) {' }, { text: '    s = s.toLowerCase().replace(/[^a-z0-9]/g, "");' }, { text: '    return s === [...s].reverse().join("");' }, { text: '}' }, { text: 'console.log(isPalindrome("A man, a plan, a canal: Panama"));', highlight: true }], options: ['true', 'false', 'Error', 'undefined'], correct: 0 },
        { type: 'scramble', prompt: 'Build valid anagram checker', pieces: [{ id: 'a', text: 'function isAnagram(s, t) {' }, { id: 'b', text: '    if (s.length !== t.length) return false;' }, { id: 'c', text: '    return [...s].sort().join("") === [...t].sort().join("");' }, { id: 'd', text: '}' }], distractors: [{ id: 'e', text: '    return s === t;' }], correctOrder: ['a', 'b', 'c', 'd'] },
        { type: 'bug', prompt: 'Why is this O(n²) not O(n)?', code: [{ text: 'function removeDuplicates(arr) {', hasError: false }, { text: '    return arr.filter((item, index) =>', hasError: false }, { text: '        arr.indexOf(item) === index', hasError: true }, { text: '    );', hasError: false }], correctLine: 2 },
    ],
    40: [
        { type: 'trace', prompt: 'Matrix search (sorted rows+cols)?', code: [{ text: 'function search(m, t) {' }, { text: '    let r = 0, c = m[0].length - 1;' }, { text: '    while (r < m.length && c >= 0) {' }, { text: '        if (m[r][c] === t) return true;' }, { text: '        else if (m[r][c] > t) c--;' }, { text: '        else r++;' }, { text: '    }' }, { text: '    return false;' }, { text: '}' }, { text: 'console.log(search([[1,4,7],[2,5,8],[3,6,9]], 5));', highlight: true }], options: ['true', 'false', 'Error', '[1,1]'], correct: 0 },
        { type: 'refactor', prompt: 'Max subarray — Kadane vs brute?', originalCode: '// Brute: O(n²)', options: [{ code: "// Kadane's: O(n)\nlet curr = arr[0], best = arr[0];\nfor (let i=1; i<arr.length; i++) {\n    curr = Math.max(arr[i], curr+arr[i]);\n    best = Math.max(best, curr);\n}", label: "Kadane's — O(n)" }, { code: '// Sort + take last k', label: 'Sorting' }, { code: '// Recursion no memo', label: 'O(2ⁿ)' }], correct: 0 },
        { type: 'scramble', prompt: 'Build binary search iterative', pieces: [{ id: 'a', text: 'function search(nums, target) {' }, { id: 'b', text: '    let lo = 0, hi = nums.length - 1;' }, { id: 'c', text: '    while (lo <= hi) {' }, { id: 'd', text: '        const mid = lo + ((hi - lo) >> 1);' }, { id: 'e', text: '        if (nums[mid] === target) return mid;' }, { id: 'f', text: '        else if (nums[mid] < target) lo = mid + 1;' }, { id: 'g', text: '        else hi = mid - 1;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return -1;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        lo = mid;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'errordecode', prompt: 'Why does this give wrong answer?', errorText: 'Expected: [0,1] for twoSum([3,2,4], 6)\nGot: undefined', question: 'Fix?', options: ['HashMap approach needed — [3,2,4] has no sorted guarantee', 'Sort first', 'Use binary search', 'Use brute force'], correct: 0 },
    ],
    41: [
        { type: 'pair', prompt: 'Advanced concepts', pairs: [{ id: 1, left: 'Amortized O(1)', right: 'Avg cost over many ops' }, { id: 2, left: 'NP-Complete', right: 'No known fast solution' }, { id: 3, left: 'Space-Time Tradeoff', right: 'Memory saves time' }, { id: 4, left: 'Greedy', right: 'Local optimal choices' }] },
        { type: 'trace', prompt: 'Greedy: activity selection?', code: [{ text: '// Activities: (start, end)' }, { text: '// [(1,4),(3,5),(0,6),(5,7),(8,9),(5,9)]' }, { text: '// Sort by end time, pick non-overlapping' }, { text: '// Pick: (1,4),(5,7),(8,9)', highlight: true }], options: ['3 activities', '2 activities', '4 activities', '6 activities'], correct: 0 },
        { type: 'realworld', prompt: 'When does greedy FAIL?', scenario: '⚠️ Greedy doesnt always give optimal.', options: [{ code: '// Coin change: coins=[1,3,4], amount=6\n// Greedy: 4+1+1=3 coins\n// Optimal: 3+3=2 coins!', label: 'Coin change with special coins' }, { code: '// Activity selection', label: 'Greedy works here' }, { code: '// Making change with [1,5,10,25]', label: 'Standard coins work' }, { code: '// Huffman coding', label: 'Greedy optimal' }], correct: 0 },
        { type: 'fillgap', prompt: 'Greedy: fractional knapsack', codeParts: [{ text: '// Sort by value/weight ratio descending\n// Take items greedily\nfunction fractKnapsack(items, W) {\n    items.sort((a,b) => ', type: 'fixed' }, { text: 'b.val/b.wt - a.val/a.wt', type: 'gap', id: 'g1' }, { text: ');\n    // ... take as much as fits\n}', type: 'fixed' }], bank: ['b.val/b.wt - a.val/a.wt', 'a.val - b.val', 'a.wt - b.wt', 'b.wt/b.val - a.wt/a.val'], correctFill: { g1: 'b.val/b.wt - a.val/a.wt' } },
    ],
    42: [
        { type: 'realworld', prompt: 'Journey complete! Next step?', scenario: '🎓 You mastered: variables→loops→functions→DS→algorithms→DP→graphs!', options: [{ code: '// Build real projects!\n// Apply to apps, APIs, open source', label: 'Build projects! 🚀' }, { code: '// Review everything', label: 'Review' }, { code: '// Just read more', label: 'More books' }, { code: '// Stop forever', label: 'Never stop!' }], correct: 0 },
        { type: 'pair', prompt: 'Your journey recap', pairs: [{ id: 1, left: 'CH1-2', right: 'Variables & Flow' }, { id: 2, left: 'CH3-4', right: 'Loops & Functions' }, { id: 3, left: 'CH5-7', right: 'Data Structures' }, { id: 4, left: 'CH8-10', right: 'Algorithms & DP' }] },
        { type: 'trace', prompt: 'Final puzzle: what does this return?', code: [{ text: 'function mystery(n) {' }, { text: '    if (n === 0) return 1;' }, { text: '    return n * mystery(n - 1);' }, { text: '}' }, { text: 'console.log(mystery(5));', highlight: true }], options: ['5', '15', '120', '720'], correct: 2 },
        { type: 'scramble', prompt: 'Final: build memoized fibonacci', pieces: [{ id: 'a', text: 'function fib(n, memo = {}) {' }, { id: 'b', text: '    if (n in memo) return memo[n];' }, { id: 'c', text: '    if (n <= 1) return n;' }, { id: 'd', text: '    memo[n] = fib(n-1, memo) + fib(n-2, memo);' }, { id: 'e', text: '    return memo[n];' }, { id: 'f', text: '}' }], distractors: [{ id: 'g', text: '    return fib(n-1) + fib(n-2);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
    ],
}
