/* ══════════════════════════════════════════════════
   PYTHON EXERCISES — CH6-CH10 (nodes 21-42)
   ══════════════════════════════════════════════════ */
export const pyExercisesCh6to10 = {
        21: [
            { type: 'algostep', prompt: 'Selection sort: find min in [64,25,12,22,11]', array: [64, 25, 12, 22, 11], step: 1, description: 'Scanning for minimum...', question: 'Min goes where?', options: ['11→index 0', '12→index 0', '22→index 1', '25→index 0'], correct: 0 },
            { type: 'trace', prompt: 'After ONE bubble sort pass on [5,1,4,2,8]?', code: [{ text: '# Compare adjacent, swap if needed' }, { text: '[5,1]→swap [1,5,4,2,8]' }, { text: '[5,4]→swap [1,4,5,2,8]' }, { text: '[5,2]→swap [1,4,2,5,8]' }, { text: '[5,8]→ok   [1,4,2,5,8]', highlight: true }], options: ['Largest at end', 'Array sorted', 'Smallest at start', 'Nothing guaranteed'], correct: 0 },
            { type: 'realworld', prompt: 'Best sort for nearly-sorted data?', scenario: '📊 Array 95% sorted, 2 elements misplaced.', options: [{ code: '# Insertion sort: O(n) best case', label: 'Insertion sort' }, { code: '# Merge sort: O(n log n) always', label: 'Merge sort' }, { code: '# Quick sort: O(n²) worst case', label: 'Quick sort' }, { code: '# Selection sort: O(n²) always', label: 'Selection sort' }], correct: 0 },
            { type: 'pair', prompt: 'Match sort to worst case', pairs: [{ id: 1, left: 'Bubble', right: 'O(n²)' }, { id: 2, left: 'Merge', right: 'O(n log n)' }, { id: 3, left: 'Insertion (best)', right: 'O(n)' }, { id: 4, left: 'Python sorted()', right: 'Timsort O(n log n)' }] },
            { type: 'scramble', prompt: 'Build insertion sort', pieces: [{ id: 'a', text: 'def insertion_sort(arr):' }, { id: 'b', text: '    for i in range(1, len(arr)):' }, { id: 'c', text: '        key = arr[i]' }, { id: 'd', text: '        j = i - 1' }, { id: 'e', text: '        while j >= 0 and arr[j] > key:' }, { id: 'f', text: '            arr[j+1] = arr[j]; j -= 1' }, { id: 'g', text: '        arr[j+1] = key' }], distractors: [{ id: 'h', text: '        arr[j] = key' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        ],
        22: [
            { type: 'algostep', prompt: 'Binary search for 7 in [1,3,5,7,9,11,13]', array: [1, 3, 5, 7, 9, 11, 13], step: 1, description: 'Lo=0 Hi=6 Mid=3 arr[3]=7=target!', question: 'Comparisons needed?', options: ['1', '2', '3', '7'], correct: 0 },
            { type: 'trace', prompt: 'Search for 6 in [1,3,5,7,9]?', code: [{ text: 'def bsearch(arr, t):' }, { text: '    lo, hi = 0, len(arr)-1' }, { text: '    while lo <= hi:' }, { text: '        mid = (lo+hi)//2' }, { text: '        if arr[mid]==t: return mid' }, { text: '        elif arr[mid]<t: lo=mid+1' }, { text: '        else: hi=mid-1' }, { text: '    return -1', highlight: true }], options: ['Returns 2', 'Returns 3', 'Returns -1', 'Infinite loop'], correct: 2 },
            { type: 'errordecode', prompt: 'Why can binary search fail?', errorText: 'mid = (lo + hi) / 2  # float in Python 3!\n# In Java/C: (lo+hi) can overflow!', question: 'Safe mid calc?', options: ['lo + (hi-lo)//2', '(lo+hi) % 2', 'hi - lo', 'lo * hi'], correct: 0 },
            { type: 'realworld', prompt: 'Binary search requires what?', scenario: '⚠️ Precondition for binary search to work.', options: [{ code: '# Array MUST be sorted', label: 'Sorted array' }, { code: '# Array must have unique elements', label: 'Unique elements' }, { code: '# Array must be small', label: 'Small array' }, { code: '# No precondition', label: 'Works on anything' }], correct: 0 },
            { type: 'fillgap', prompt: 'Complete: find first occurrence', codeParts: [{ text: 'def first_occur(arr, t):\n    lo, hi, result = 0, len(arr)-1, -1\n    while lo <= hi:\n        mid = (lo+hi)//2\n        if arr[mid] == t:\n            ', type: 'fixed' }, { text: 'result = mid; hi = mid - 1', type: 'gap', id: 'g1' }, { text: '\n        elif arr[mid] < t: lo = mid+1\n        else: hi = mid-1\n    return result', type: 'fixed' }], bank: ['result = mid; hi = mid - 1', 'return mid', 'lo = mid + 1', 'break'], correctFill: { g1: 'result = mid; hi = mid - 1' } },
        ],
        23: [
            { type: 'trace', prompt: 'Time complexity?', code: [{ text: 'for i in range(n):' }, { text: '    for j in range(n):' }, { text: '        print(i, j)' }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'], correct: 1 },
            { type: 'realworld', prompt: 'Search 1M sorted items?', scenario: '🔍 1,000,000 sorted integers.', options: [{ code: '# Binary: O(log n) ≈ 20 steps', label: '~20 comparisons' }, { code: '# Linear: O(n) ≈ 1M steps', label: '~1M comparisons' }, { code: '# Same in practice', label: 'Same speed' }, { code: '# Hash: always O(1)', label: 'Instant' }], correct: 0 },
            { type: 'pair', prompt: 'Match complexity', pairs: [{ id: 1, left: 'Binary Search', right: 'O(log n)' }, { id: 2, left: 'Bubble Sort', right: 'O(n²)' }, { id: 3, left: 'Merge Sort', right: 'O(n log n)' }, { id: 4, left: 'Hash Lookup', right: 'O(1) avg' }] },
            { type: 'trace', prompt: 'This loop complexity?', code: [{ text: 'i = n' }, { text: 'while i > 0:' }, { text: '    print(i)' }, { text: '    i = i // 2', highlight: true }], options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
            { type: 'refactor', prompt: 'Which is faster for checking membership?', originalCode: '# Check if x exists in list\nif x in my_list:  # O(n)', options: [{ code: 'my_set = set(my_list)\nif x in my_set:  # O(1)', label: 'Convert to set — O(1) lookup' }, { code: 'my_list.sort()\nbisect.bisect(my_list, x)', label: 'Sort + bisect — O(n log n)' }, { code: 'for item in my_list:\n    if item == x: break', label: 'Still O(n)' }], correct: 0 },
        ],
        24: [
            { type: 'trace', prompt: 'Two-sum brute force?', code: [{ text: 'def two_sum(nums, t):' }, { text: '    for i in range(len(nums)):' }, { text: '        for j in range(i+1, len(nums)):' }, { text: '            if nums[i]+nums[j]==t:' }, { text: '                return [i,j]' }, { text: 'print(two_sum([2,7,11,15], 9))', highlight: true }], options: ['[0, 1]', '[1, 2]', '[0, 3]', 'None'], correct: 0 },
            { type: 'refactor', prompt: 'O(n²)→O(n) two-sum?', originalCode: '# O(n²)\nfor i in range(len(nums)):\n    for j in range(i+1, len(nums)):\n        if nums[i]+nums[j]==target: return [i,j]', options: [{ code: 'seen = {}\nfor i, n in enumerate(nums):\n    comp = target - n\n    if comp in seen: return [seen[comp], i]\n    seen[n] = i', label: 'Hash map — O(n)' }, { code: 'nums.sort()\nlo, hi = 0, len(nums)-1', label: 'Sort + two pointer' }, { code: '[nums.index(target-n) for n in nums]', label: 'Still O(n²)' }], correct: 0 },
            { type: 'scramble', prompt: 'Build O(n) two-sum', pieces: [{ id: 'a', text: 'def two_sum(nums, target):' }, { id: 'b', text: '    seen = {}' }, { id: 'c', text: '    for i, n in enumerate(nums):' }, { id: 'd', text: '        comp = target - n' }, { id: 'e', text: '        if comp in seen:' }, { id: 'f', text: '            return [seen[comp], i]' }, { id: 'g', text: '        seen[n] = i' }], distractors: [{ id: 'h', text: '        seen[i] = n' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
            { type: 'output', prompt: 'Complexity of this?', code: [{ text: '# Hash map solution' }, { text: '# One pass through array: O(n)' }, { text: '# Each lookup in dict: O(1)' }, { text: '# Total:', highlight: true }], terminalOutput: 'O(n)', options: ['O(n²)', 'O(n)', 'O(n log n)', 'O(1)'], correct: 1 },
        ],
        // ═══ CH7: DATA STRUCTURES II ⭐⭐⭐ ═══
        25: [
            { type: 'trace', prompt: 'Stack: push 1,2,3 then pop twice?', code: [{ text: 'stack = []' }, { text: 'stack.append(1); stack.append(2); stack.append(3)' }, { text: 'stack.pop(); stack.pop()' }, { text: 'print(stack)', highlight: true }], options: ['[1]', '[3]', '[1,2]', '[]'], correct: 0 },
            { type: 'realworld', prompt: 'Balanced parentheses?', scenario: '🔍 "({[]})" → True, "({[)}" → False', options: [{ code: '# Stack: push open, pop on close', label: 'Stack — LIFO' }, { code: '# Queue: FIFO', label: 'Queue' }, { code: '# Counter only', label: 'Counter' }, { code: '# Set', label: 'Set' }], correct: 0 },
            { type: 'pair', prompt: 'Match concepts', pairs: [{ id: 1, left: 'Stack', right: 'LIFO' }, { id: 2, left: 'Queue', right: 'FIFO' }, { id: 3, left: 'Deque', right: 'Double-ended' }, { id: 4, left: 'Priority Queue', right: 'Min/Max first' }] },
            { type: 'scramble', prompt: 'Check balanced brackets', pieces: [{ id: 'a', text: 'def is_valid(s):' }, { id: 'b', text: '    stack = []' }, { id: 'c', text: '    pairs = {")":"(", "]":"[", "}":"{"}' }, { id: 'd', text: '    for c in s:' }, { id: 'e', text: '        if c in "([{": stack.append(c)' }, { id: 'f', text: '        elif not stack or stack.pop() != pairs[c]:' }, { id: 'g', text: '            return False' }, { id: 'h', text: '    return len(stack) == 0' }], distractors: [{ id: 'i', text: '    return True' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
            { type: 'trace', prompt: 'Queue with deque?', code: [{ text: 'from collections import deque' }, { text: 'q = deque()' }, { text: 'q.append("A"); q.append("B"); q.append("C")' }, { text: 'print(q.popleft(), q.popleft())', highlight: true }], options: ['A B', 'C B', 'A C', 'B C'], correct: 0 },
        ],
        26: [
            { type: 'trace', prompt: 'head.next.val?', code: [{ text: 'class Node:' }, { text: '    def __init__(self, val): self.val=val; self.next=None' }, { text: 'a=Node(1); b=Node(2); c=Node(3)' }, { text: 'a.next=b; b.next=c' }, { text: 'print(a.next.val)', highlight: true }], options: ['1', '2', '3', 'None'], correct: 1 },
            { type: 'scramble', prompt: 'Traverse linked list', pieces: [{ id: 'a', text: 'def traverse(head):' }, { id: 'b', text: '    curr = head' }, { id: 'c', text: '    while curr:' }, { id: 'd', text: '        print(curr.val)' }, { id: 'e', text: '        curr = curr.next' }], distractors: [{ id: 'f', text: '        curr = curr.prev' }], correctOrder: ['a', 'b', 'c', 'd', 'e'] },
            { type: 'realworld', prompt: 'When use linked list over array?', scenario: '🤔 Which scenario benefits from linked list?', options: [{ code: '# Frequent insert/delete at beginning: O(1)', label: 'Fast insert at head' }, { code: '# Random access by index', label: 'Index access — array better' }, { code: '# Sorting data', label: 'Sorting — array better' }, { code: '# Binary search', label: 'Binary search — array' }], correct: 0 },
            { type: 'trace', prompt: 'Reverse a linked list — what happens?', code: [{ text: 'prev = None; curr = head' }, { text: 'while curr:' }, { text: '    nxt = curr.next' }, { text: '    curr.next = prev' }, { text: '    prev = curr' }, { text: '    curr = nxt' }, { text: '# prev is now new head', highlight: true }], options: ['List reversed in O(n)', 'List unchanged', 'Error', 'O(n²)'], correct: 0 },
        ],
        27: [
            { type: 'trace', prompt: 'In-order BST traversal?', code: [{ text: '#       4' }, { text: '#' }, { text: '#     2   6' }, { text: '#' }, { text: '#   1   3' }, { text: '# In-order: L→Root→R', highlight: true }], options: ['4 2 1 3 6', '1 2 3 4 6', '1 3 2 6 4', '4 2 6 1 3'], correct: 1 },
            { type: 'pair', prompt: 'Match traversals', pairs: [{ id: 1, left: 'In-order', right: 'L→Root→R (sorted!)' }, { id: 2, left: 'Pre-order', right: 'Root→L→R' }, { id: 3, left: 'Post-order', right: 'L→R→Root' }, { id: 4, left: 'Level-order', right: 'BFS layer by layer' }] },
            { type: 'realworld', prompt: 'Why is BST in-order special?', scenario: '🌳 Binary Search Tree in-order traversal gives...', options: [{ code: '# Sorted order! O(n) to get all sorted', label: 'Sorted output' }, { code: '# Reverse order', label: 'Reverse sorted' }, { code: '# Random order', label: 'Random' }, { code: '# Level by level', label: 'BFS order' }], correct: 0 },
            { type: 'trace', prompt: 'BST search for 3?', code: [{ text: '#     4 → 3<4, go left' }, { text: '#' }, { text: '#   2   6 → 3>2, go right' }, { text: '#' }, { text: '# 1   3 → Found! O(log n)', highlight: true }], options: ['2 comparisons', '3 comparisons', '4 comparisons', '1 comparison'], correct: 0 },
        ],
        28: [
            { type: 'video', title: 'Data Structures Visualized', description: 'Stacks, queues, linked lists, trees — when to use each, trade-offs, and real-world applications.', duration: '4:00', thumbnail: '🎥' },
            { type: 'pair', prompt: 'Match structure to operation speed', pairs: [{ id: 1, left: 'Array[i]', right: 'O(1)' }, { id: 2, left: 'LinkedList insert at head', right: 'O(1)' }, { id: 3, left: 'BST search', right: 'O(log n) avg' }, { id: 4, left: 'Array insert at start', right: 'O(n)' }] },
        ],
        // ═══ CH8: ALGORITHMS II ⭐⭐⭐⭐ ═══
        29: [
            { type: 'trace', prompt: 'Tower of Hanoi: 3 disks = ? moves', code: [{ text: 'def hanoi(n):' }, { text: '    if n == 1: return 1' }, { text: '    return 2 * hanoi(n-1) + 1' }, { text: 'print(hanoi(3))', highlight: true }], options: ['3', '5', '7', '8'], correct: 2 },
            { type: 'realworld', prompt: 'Which is naturally recursive?', scenario: '🤔 Same-type subproblems?', options: [{ code: '# Directory tree: folders in folders', label: 'File system ✓' }, { code: '# Read file line by line', label: 'Sequential' }, { code: '# Print "Hi" 5 times', label: 'Loop' }, { code: '# Add two nums', label: 'Simple op' }], correct: 0 },
            { type: 'trace', prompt: 'sum_digits(1234)?', code: [{ text: 'def sum_digits(n):' }, { text: '    if n < 10: return n' }, { text: '    return n%10 + sum_digits(n//10)' }, { text: 'print(sum_digits(1234))', highlight: true }], options: ['10', '1234', '4', '24'], correct: 0 },
            { type: 'output', prompt: 'Recursive power complexity?', code: [{ text: 'def power(b, e):' }, { text: '    if e == 0: return 1' }, { text: '    if e % 2 == 0:' }, { text: '        h = power(b, e//2)' }, { text: '        return h * h' }, { text: '    return b * power(b, e-1)' }, { text: '# Halves each time!', highlight: true }], terminalOutput: 'O(log n)', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
            { type: 'scramble', prompt: 'Build binary search recursively', pieces: [{ id: 'a', text: 'def bsearch(arr, t, lo, hi):' }, { id: 'b', text: '    if lo > hi: return -1' }, { id: 'c', text: '    mid = (lo+hi)//2' }, { id: 'd', text: '    if arr[mid] == t: return mid' }, { id: 'e', text: '    elif arr[mid] < t: return bsearch(arr,t,mid+1,hi)' }, { id: 'f', text: '    else: return bsearch(arr,t,lo,mid-1)' }], distractors: [{ id: 'g', text: '    return bsearch(arr,t,lo,hi)' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        ],
        30: [
            { type: 'algostep', prompt: 'Merge [1,3,5] and [2,4,6]', array: [1, 3, 5, 2, 4, 6], step: 1, description: 'Compare: 1<2, take 1. Left:[3,5] Right:[2,4,6]', question: 'Next comparison?', options: ['3 vs 2', '1 vs 2', '5 vs 6', '3 vs 4'], correct: 0 },
            { type: 'trace', prompt: 'Merge sort time complexity?', code: [{ text: '# Divide in half: log₂(n) levels' }, { text: '# Merge: O(n) per level' }, { text: '# Total: O(n × log n)', highlight: true }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'], correct: 2 },
            { type: 'scramble', prompt: 'Build merge function', pieces: [{ id: 'a', text: 'def merge(left, right):' }, { id: 'b', text: '    result = []; i = j = 0' }, { id: 'c', text: '    while i<len(left) and j<len(right):' }, { id: 'd', text: '        if left[i]<=right[j]: result.append(left[i]); i+=1' }, { id: 'e', text: '        else: result.append(right[j]); j+=1' }, { id: 'f', text: '    result += left[i:] + right[j:]' }, { id: 'g', text: '    return result' }], distractors: [{ id: 'h', text: '    return left + right' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
            { type: 'pair', prompt: 'Divide & Conquer examples', pairs: [{ id: 1, left: 'Merge Sort', right: 'Split array, sort halves' }, { id: 2, left: 'Quick Sort', right: 'Partition around pivot' }, { id: 3, left: 'Binary Search', right: 'Halve search space' }, { id: 4, left: 'Strassen', right: 'Matrix multiply' }] },
        ],
        31: [
            { type: 'trace', prompt: 'fib(5) calls WITHOUT memo?', code: [{ text: 'def fib(n):' }, { text: '    if n<=1: return n' }, { text: '    return fib(n-1)+fib(n-2)' }, { text: '# fib(5) call tree has 15 calls!', highlight: true }], options: ['5', '9', '15', '25'], correct: 2 },
            { type: 'refactor', prompt: 'O(2ⁿ) fib → O(n)?', originalCode: 'def fib(n):\n    if n<=1: return n\n    return fib(n-1)+fib(n-2)', options: [{ code: 'memo = {}\ndef fib(n):\n    if n in memo: return memo[n]\n    if n<=1: return n\n    memo[n] = fib(n-1)+fib(n-2)\n    return memo[n]', label: 'Memoization — O(n)' }, { code: 'def fib(n):\n    return n if n<=1 else fib(n-1)+fib(n-2)', label: 'Still O(2ⁿ)' }, { code: 'import math\ndef fib(n): return math.factorial(n)', label: 'Wrong formula' }], correct: 0 },
            { type: 'realworld', prompt: 'Min coins for 11 using [1,5,6]?', scenario: '💰 Coins: [1,5,6]. Make 11.', options: [{ code: '# DP: dp[11] = min(dp[10]+1, dp[6]+1, dp[5]+1)\n# = min(3, 2, 3) = 2 coins (6+5)', label: '2 coins (6+5)' }, { code: '# Greedy: 6+5 = 2 (works here)', label: '2 (greedy=DP here)' }, { code: '# 11 ones', label: '11 coins' }, { code: '# 5+5+1', label: '3 coins' }], correct: 0 },
            { type: 'fillgap', prompt: 'Complete: climbing stairs DP', codeParts: [{ text: 'def climb(n):\n    if n<=2: return n\n    dp = [0]*(n+1)\n    dp[1], dp[2] = 1, 2\n    for i in range(3, n+1):\n        ', type: 'fixed' }, { text: 'dp[i] = dp[i-1] + dp[i-2]', type: 'gap', id: 'g1' }, { text: '\n    return dp[n]', type: 'fixed' }], bank: ['dp[i] = dp[i-1] + dp[i-2]', 'dp[i] = dp[i-1] * 2', 'dp[i] = i', 'dp[i] = dp[i-1]'], correctFill: { g1: 'dp[i] = dp[i-1] + dp[i-2]' } },
            { type: 'trace', prompt: 'Climbing stairs n=5?', code: [{ text: '# dp[1]=1, dp[2]=2' }, { text: '# dp[3]=3, dp[4]=5' }, { text: '# dp[5] = dp[4]+dp[3] = ?', highlight: true }], options: ['5', '7', '8', '13'], correct: 2 },
        ],
        32: [
            { type: 'trace', prompt: 'Fast power: power(2,10)?', code: [{ text: 'def power(b, e):' }, { text: '    if e==0: return 1' }, { text: '    if e%2==0: h=power(b,e//2); return h*h' }, { text: '    return b*power(b,e-1)' }, { text: 'print(power(2, 10))', highlight: true }], options: ['20', '100', '512', '1024'], correct: 3 },
            { type: 'output', prompt: 'Its complexity?', code: [{ text: '# power(2,10)→power(2,5)→power(2,4)' }, { text: '# →power(2,2)→power(2,1)→power(2,0)', highlight: true }], terminalOutput: 'O(log n)', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1 },
            { type: 'scramble', prompt: 'Build memoized fibonacci', pieces: [{ id: 'a', text: 'memo = {}' }, { id: 'b', text: 'def fib(n):' }, { id: 'c', text: '    if n in memo: return memo[n]' }, { id: 'd', text: '    if n <= 1: return n' }, { id: 'e', text: '    memo[n] = fib(n-1) + fib(n-2)' }, { id: 'f', text: '    return memo[n]' }], distractors: [{ id: 'g', text: '    return fib(n)' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
            { type: 'realworld', prompt: 'When does DP help?', scenario: '🧠 DP works when problem has...', options: [{ code: '# 1. Overlapping subproblems\n# 2. Optimal substructure', label: 'Both conditions ✓' }, { code: '# Only overlapping subproblems', label: 'One condition' }, { code: '# Any recursive problem', label: 'Not always' }, { code: '# Only sorting problems', label: 'Sorting only' }], correct: 0 },
        ],
        // ═══ CH9: ADVANCED ⭐⭐⭐⭐ ═══
        33: [
            { type: 'pair', prompt: 'Match graph terms', pairs: [{ id: 1, left: 'Adjacency List', right: 'Dict of neighbors' }, { id: 2, left: 'Adjacency Matrix', right: '2D array' }, { id: 3, left: 'Directed', right: 'One-way edges' }, { id: 4, left: 'Undirected', right: 'Two-way edges' }] },
            { type: 'realworld', prompt: 'Best graph application?', scenario: '🌍 Real-world graph.', options: [{ code: '# Social network: users=nodes, friends=edges', label: 'Social network' }, { code: '# To-do list', label: 'List' }, { code: '# Calculator', label: 'Calculator' }, { code: '# Timer', label: 'Counter' }], correct: 0 },
            { type: 'output', prompt: 'Adjacency list for A→B, A→C, B→C?', code: [{ text: 'graph = {' }, { text: '    "A": ["B", "C"],' }, { text: '    "B": ["C"],' }, { text: '    "C": []' }, { text: '}' }, { text: 'print(len(graph["A"]))' }], terminalOutput: '2', options: ['1', '2', '3', '0'], correct: 1 },
            { type: 'trace', prompt: 'How many edges in this undirected graph?', code: [{ text: '# A--B, A--C, B--C (triangle)' }, { text: '# Each edge stored twice in adj list' }, { text: '# Total entries in adj lists: 6' }, { text: '# Actual edges:', highlight: true }], options: ['3', '6', '2', '9'], correct: 0 },
        ],
        34: [
            { type: 'trace', prompt: 'BFS from A. Visit order?', code: [{ text: '# A→[B,C], B→[D], C→[D], D→[]' }, { text: 'def bfs(start, graph):' }, { text: '    q = deque([start]); seen = {start}' }, { text: '    while q:' }, { text: '        node = q.popleft(); print(node)' }, { text: '        for n in graph[node]:' }, { text: '            if n not in seen:' }, { text: '                seen.add(n); q.append(n)', highlight: true }], options: ['A B C D', 'A B D C', 'A C B D', 'D B C A'], correct: 0 },
            { type: 'refactor', prompt: 'Cycle detection in directed graph?', originalCode: '# Naive: just "visited" set\n# Cannot distinguish exploring vs explored', options: [{ code: '# 3-color: WHITE→GRAY→BLACK\n# Cycle = visiting GRAY node', label: 'Three-color ✓' }, { code: '# Simple visited set', label: 'Incomplete' }, { code: '# Count edges vs nodes', label: 'Wrong' }], correct: 0 },
            { type: 'realworld', prompt: 'BFS vs DFS — when use BFS?', scenario: '🗺️ Finding shortest path in unweighted graph.', options: [{ code: '# BFS: guarantees shortest path\n# Explores level by level', label: 'BFS — shortest path' }, { code: '# DFS: goes deep first', label: 'DFS — no shortest guarantee' }, { code: '# Both give same path', label: 'Same result' }, { code: '# Neither works', label: 'Neither' }], correct: 0 },
            { type: 'pair', prompt: 'BFS vs DFS', pairs: [{ id: 1, left: 'BFS', right: 'Queue (FIFO)' }, { id: 2, left: 'DFS', right: 'Stack (LIFO)' }, { id: 3, left: 'BFS use', right: 'Shortest path' }, { id: 4, left: 'DFS use', right: 'Cycle detection' }] },
        ],
        35: [
            { type: 'trace', prompt: 'Two-pointer: pair summing to 6 in [1,2,3,4,6]?', code: [{ text: 'lo, hi = 0, 4  # 1+6=7>6' }, { text: 'hi -= 1        # 1+4=5<6' }, { text: 'lo += 1        # 2+4=6 ✓', highlight: true }], options: ['indices [1,5]', 'indices [0,4]', 'indices [1,3]', 'indices [2,3]'], correct: 2 },
            { type: 'refactor', prompt: 'O(n²) duplicates → O(n)?', originalCode: 'for i in range(len(arr)):\n    for j in range(i+1, len(arr)):\n        if arr[i]==arr[j]: return True', options: [{ code: 'return len(arr) != len(set(arr))', label: 'Set — O(n)' }, { code: 'arr.sort()\nfor i in range(len(arr)-1):\n    if arr[i]==arr[i+1]: return True', label: 'Sort — O(n log n)' }, { code: 'from collections import Counter\nreturn max(Counter(arr).values())>1', label: 'Counter — O(n)' }], correct: 0 },
            { type: 'fillgap', prompt: 'Sliding window: max sum of k consecutive', codeParts: [{ text: 'def max_sum(arr, k):\n    window = sum(arr[:k])\n    best = window\n    for i in range(k, len(arr)):\n        ', type: 'fixed' }, { text: 'window += arr[i] - arr[i-k]', type: 'gap', id: 'g1' }, { text: '\n        best = max(best, window)\n    return best', type: 'fixed' }], bank: ['window += arr[i] - arr[i-k]', 'window = sum(arr[i-k:i])', 'window += arr[i]', 'window = arr[i]'], correctFill: { g1: 'window += arr[i] - arr[i-k]' } },
            { type: 'realworld', prompt: 'Sliding window complexity?', scenario: '📊 Instead of recalculating sum each time...', options: [{ code: '# Slide: add new, remove old = O(n)\n# vs recalculate: O(n*k)', label: 'O(n) — add/remove trick' }, { code: '# O(n*k) — recompute each time', label: 'O(n*k)' }, { code: '# O(n²)', label: 'O(n²)' }, { code: '# O(1)', label: 'O(1)' }], correct: 0 },
            { type: 'trace', prompt: 'Remove duplicates in-place from sorted?', code: [{ text: 'arr = [1,1,2,2,3]' }, { text: 'w = 1  # write pointer' }, { text: 'for r in range(1, len(arr)):' }, { text: '    if arr[r] != arr[r-1]:' }, { text: '        arr[w] = arr[r]; w += 1' }, { text: 'print(arr[:w])', highlight: true }], options: ['[1,2,3]', '[1,1,2]', '[2,3]', '[1,2,2,3]'], correct: 0 },
        ],
        36: [
            { type: 'scramble', prompt: 'Build BFS', pieces: [{ id: 'a', text: 'from collections import deque' }, { id: 'b', text: 'def bfs(graph, start):' }, { id: 'c', text: '    q = deque([start])' }, { id: 'd', text: '    visited = {start}' }, { id: 'e', text: '    while q:' }, { id: 'f', text: '        node = q.popleft()' }, { id: 'g', text: '        for nb in graph[node]:' }, { id: 'h', text: '            if nb not in visited:' }, { id: 'i', text: '                visited.add(nb); q.append(nb)' }], distractors: [{ id: 'j', text: '        q.append(node)' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
            { type: 'trace', prompt: 'DFS from A?', code: [{ text: '# A→[B,C], B→[D], C→[], D→[]' }, { text: 'def dfs(node, graph, seen=set()):' }, { text: '    if node in seen: return' }, { text: '    seen.add(node); print(node)' }, { text: '    for n in graph[node]: dfs(n, graph, seen)', highlight: true }], options: ['A B D C', 'A B C D', 'A C B D', 'D B C A'], correct: 0 },
            { type: 'realworld', prompt: 'Graph for GPS navigation?', scenario: '🗺️ Find shortest route between cities.', options: [{ code: '# Weighted graph + Dijkstra\n# Nodes=cities, edges=roads with distance', label: 'Weighted graph ✓' }, { code: '# Simple array of cities', label: 'Array' }, { code: '# Unweighted BFS', label: 'Missing distances' }, { code: '# Binary tree', label: 'Not a tree' }], correct: 0 },
        ],
        // ═══ CH10: MASTERY ⭐⭐⭐⭐ ═══
        37: [
            { type: 'trace', prompt: 'Climbing stairs n=4?', code: [{ text: '# dp[0]=1, dp[1]=1' }, { text: '# dp[2] = dp[1]+dp[0] = 2' }, { text: '# dp[3] = dp[2]+dp[1] = 3' }, { text: '# dp[4] = dp[3]+dp[2] = ?', highlight: true }], options: ['4', '5', '6', '8'], correct: 1 },
            { type: 'realworld', prompt: 'Which is a DP problem?', scenario: '🧠 Overlapping subproblems + optimal substructure?', options: [{ code: '# Longest Common Subsequence\n# LCS("ABCDE","ACE")="ACE"', label: 'LCS — classic DP' }, { code: '# Find max in array', label: 'Simple scan' }, { code: '# Print all elements', label: 'Traverse' }, { code: '# Swap variables', label: 'Basic op' }], correct: 0 },
            { type: 'pair', prompt: 'Match DP patterns', pairs: [{ id: 1, left: 'Fibonacci', right: 'dp[i]=dp[i-1]+dp[i-2]' }, { id: 2, left: 'Knapsack', right: 'Include or exclude item' }, { id: 3, left: 'LCS', right: 'Match or skip chars' }, { id: 4, left: 'Coin Change', right: 'min(dp[amt-coin]+1)' }] },
            { type: 'fillgap', prompt: 'Complete: 0/1 Knapsack', codeParts: [{ text: 'def knapsack(W, wt, val, n):\n    dp = [[0]*(W+1) for _ in range(n+1)]\n    for i in range(1, n+1):\n        for w in range(1, W+1):\n            if wt[i-1] <= w:\n                ', type: 'fixed' }, { text: 'dp[i][w] = max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w])', type: 'gap', id: 'g1' }, { text: '\n            else:\n                dp[i][w] = dp[i-1][w]\n    return dp[n][W]', type: 'fixed' }], bank: ['dp[i][w] = max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w])', 'dp[i][w] = val[i-1]', 'dp[i][w] = dp[i-1][w] + 1', 'dp[i][w] = w'], correctFill: { g1: 'dp[i][w] = max(val[i-1]+dp[i-1][w-wt[i-1]], dp[i-1][w])' } },
        ],
        38: [
            { type: 'refactor', prompt: 'Primes up to n — best approach?', originalCode: '# Brute: O(n√n)\nfor i in range(2, n+1):\n    if is_prime(i): result.append(i)', options: [{ code: '# Sieve of Eratosthenes: O(n log log n)\nsieve = [True]*(n+1)\nfor i in range(2, int(n**0.5)+1):\n    if sieve[i]:\n        for j in range(i*i, n+1, i):\n            sieve[j] = False', label: 'Sieve — much faster' }, { code: '# Check all divisors', label: 'Still brute' }, { code: '# Random testing', label: 'Probabilistic' }], correct: 0 },
            { type: 'pair', prompt: 'Match pattern to problem', pairs: [{ id: 1, left: 'Sliding window', right: 'Max subarray of size k' }, { id: 2, left: 'Two pointer', right: 'Pair sum sorted' }, { id: 3, left: 'BFS', right: 'Shortest path unweighted' }, { id: 4, left: 'DP', right: 'Min coins for amount' }] },
            { type: 'realworld', prompt: 'Problem-solving strategy?', scenario: '🎯 You get a hard problem in an interview.', options: [{ code: '# 1. Brute force first\n# 2. Identify pattern\n# 3. Optimize with right DS\n# 4. Code + test edge cases', label: 'Structured approach ✓' }, { code: '# Jump to optimal solution', label: 'Risky' }, { code: '# Give up', label: 'Never!' }, { code: '# Memorize solutions', label: 'Not scalable' }], correct: 0 },
            { type: 'scramble', prompt: 'Build Sieve of Eratosthenes', pieces: [{ id: 'a', text: 'def sieve(n):' }, { id: 'b', text: '    is_prime = [True] * (n+1)' }, { id: 'c', text: '    is_prime[0] = is_prime[1] = False' }, { id: 'd', text: '    for i in range(2, int(n**0.5)+1):' }, { id: 'e', text: '        if is_prime[i]:' }, { id: 'f', text: '            for j in range(i*i, n+1, i):' }, { id: 'g', text: '                is_prime[j] = False' }, { id: 'h', text: '    return [i for i in range(n+1) if is_prime[i]]' }], distractors: [{ id: 'i', text: '            is_prime[i] = False' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
        ],
        39: [
            { type: 'fillgap', prompt: 'Reverse string in-place', codeParts: [{ text: 'def reverse(s):\n    lo, hi = 0, len(s)-1\n    while lo < hi:\n        ', type: 'fixed' }, { text: 's[lo], s[hi] = s[hi], s[lo]', type: 'gap', id: 'g1' }, { text: '\n        lo += 1; hi -= 1', type: 'fixed' }], bank: ['s[lo], s[hi] = s[hi], s[lo]', 's.reverse()', 'lo, hi = hi, lo', 's[lo] = s[hi]'], correctFill: { g1: 's[lo], s[hi] = s[hi], s[lo]' } },
            { type: 'terminal', prompt: 'FizzBuzz 1-15', expectedCommands: ['for i in range(1, 16):', '    if i%15==0: print("FizzBuzz")', '    elif i%3==0: print("Fizz")', '    elif i%5==0: print("Buzz")', '    else: print(i)'], hint: 'Check 15 first!', terminalHistory: [{ type: 'system', text: '>>> Interview: FizzBuzz' }] },
            { type: 'trace', prompt: 'Valid palindrome check?', code: [{ text: 'def is_palindrome(s):' }, { text: '    s = s.lower()' }, { text: '    s = "".join(c for c in s if c.isalnum())' }, { text: '    return s == s[::-1]' }, { text: 'print(is_palindrome("A man, a plan, a canal: Panama"))', highlight: true }], options: ['True', 'False', 'Error', 'None'], correct: 0 },
            { type: 'scramble', prompt: 'Build valid anagram checker', pieces: [{ id: 'a', text: 'def is_anagram(s, t):' }, { id: 'b', text: '    if len(s) != len(t): return False' }, { id: 'c', text: '    from collections import Counter' }, { id: 'd', text: '    return Counter(s) == Counter(t)' }], distractors: [{ id: 'e', text: '    return s == t' }], correctOrder: ['a', 'b', 'c', 'd'] },
            { type: 'realworld', prompt: 'Most asked interview pattern?', scenario: '💼 Top coding interview topics.', options: [{ code: '# Arrays + Hash Maps: ~40% of problems\n# Two pointer, sliding window, sorting', label: 'Arrays + Hashing ✓' }, { code: '# Graph algorithms only', label: 'Graphs (~15%)' }, { code: '# Dynamic Programming only', label: 'DP (~20%)' }, { code: '# Linked lists only', label: 'LL (~10%)' }], correct: 0 },
        ],
        40: [
            { type: 'trace', prompt: 'Matrix search (sorted rows+cols)?', code: [{ text: 'def search(m, t):' }, { text: '    r, c = 0, len(m[0])-1' }, { text: '    while r<len(m) and c>=0:' }, { text: '        if m[r][c]==t: return True' }, { text: '        elif m[r][c]>t: c-=1' }, { text: '        else: r+=1' }, { text: '    return False' }, { text: 'print(search([[1,4,7],[2,5,8],[3,6,9]], 5))', highlight: true }], options: ['True', 'False', 'Error', '[1,1]'], correct: 0 },
            { type: 'output', prompt: 'Its complexity?', code: [{ text: '# Start top-right' }, { text: '# Each step: eliminate row or col' }, { text: '# At most m+n steps', highlight: true }], terminalOutput: 'O(m+n)', options: ['O(m×n)', 'O(m+n)', 'O(log(mn))', 'O(1)'], correct: 1 },
            { type: 'refactor', prompt: 'Max subarray — which algo?', originalCode: '# Brute: O(n²)\nfor i in range(n):\n    curr = 0\n    for j in range(i, n):\n        curr += arr[j]\n        best = max(best, curr)', options: [{ code: "# Kadane's: O(n)\ncurr = best = arr[0]\nfor x in arr[1:]:\n    curr = max(x, curr+x)\n    best = max(best, curr)", label: "Kadane's — O(n)" }, { code: '# Sort + take last k', label: 'Sorting' }, { code: '# Recursion no memo', label: 'O(2ⁿ)' }], correct: 0 },
            { type: 'trace', prompt: "Kadane's on [-2,1,-3,4,-1,2,1,-5,4]?", code: [{ text: '# curr: -2→1→-2→4→3→5→6→1→5' }, { text: '# best: -2→1→ 1→4→4→5→6→6→6' }, { text: 'print(best)', highlight: true }], options: ['4', '6', '7', '5'], correct: 1 },
            { type: 'scramble', prompt: "Build Kadane's algorithm", pieces: [{ id: 'a', text: 'def max_subarray(nums):' }, { id: 'b', text: '    curr = best = nums[0]' }, { id: 'c', text: '    for x in nums[1:]:' }, { id: 'd', text: '        curr = max(x, curr + x)' }, { id: 'e', text: '        best = max(best, curr)' }, { id: 'f', text: '    return best' }], distractors: [{ id: 'g', text: '        curr += x' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        ],
        41: [
            { type: 'pair', prompt: 'Advanced concepts', pairs: [{ id: 1, left: 'Amortized O(1)', right: 'Avg cost over many ops' }, { id: 2, left: 'NP-Complete', right: 'No known fast solution' }, { id: 3, left: 'Space-Time Tradeoff', right: 'Memory saves time' }, { id: 4, left: 'Greedy', right: 'Local optimal choices' }] },
            { type: 'trace', prompt: 'Greedy: activity selection?', code: [{ text: '# Activities: (start, end)' }, { text: '# [(1,4),(3,5),(0,6),(5,7),(8,9),(5,9)]' }, { text: '# Sort by end time, pick non-overlapping' }, { text: '# Pick: (1,4),(5,7),(8,9)', highlight: true }], options: ['3 activities', '2 activities', '4 activities', '6 activities'], correct: 0 },
            { type: 'realworld', prompt: 'When does greedy FAIL?', scenario: '⚠️ Greedy doesnt always give optimal.', options: [{ code: '# Coin change: coins=[1,3,4], amount=6\n# Greedy: 4+1+1=3 coins\n# Optimal: 3+3=2 coins!', label: 'Coin change with special coins' }, { code: '# Activity selection', label: 'Greedy works here' }, { code: '# Making change with [1,5,10,25]', label: 'Standard coins work' }, { code: '# Huffman coding', label: 'Greedy optimal' }], correct: 0 },
        ],
        42: [
            { type: 'realworld', prompt: 'Journey complete! Next step?', scenario: '🎓 You mastered: variables→loops→functions→DS→algorithms→DP→graphs!', options: [{ code: '# Build real projects!\n# Apply to apps, APIs, open source', label: 'Build projects! 🚀' }, { code: '# Review everything', label: 'Review' }, { code: '# Just read more', label: 'More books' }, { code: '# Stop forever', label: 'Never stop!' }], correct: 0 },
            { type: 'pair', prompt: 'Your journey recap', pairs: [{ id: 1, left: 'CH1-2', right: 'Variables & Flow' }, { id: 2, left: 'CH3-4', right: 'Loops & Functions' }, { id: 3, left: 'CH5-7', right: 'Data Structures' }, { id: 4, left: 'CH8-10', right: 'Algorithms & DP' }] },
            { type: 'trace', prompt: 'Final puzzle: what does this return?', code: [{ text: 'def mystery(n):' }, { text: '    if n == 0: return 1' }, { text: '    return n * mystery(n-1)' }, { text: 'print(mystery(5))', highlight: true }], options: ['5', '15', '120', '720'], correct: 2 },
        ],
}
