/* ══════════════════════════════════════════════════
   JAVA EXERCISES — CH6-CH10 (nodes 21-42)
   Expanded: 4-5 exercises per node, diverse types
   University-aligned: MIT 6.031, Princeton COS226
   ══════════════════════════════════════════════════ */
export const javaExercisesCh6to10 = {
    // ═══ CH6: ALGORITHMS I ═══
    21: [
        { type: 'algostep', prompt: 'Selection sort begins on [64,25,12,22,11]', array: [64, 25, 12, 22, 11], step: 1, description: 'Pass 1 scans the whole array for the smallest value, then swaps it to the front.', question: 'What does the array look like after pass 1?', options: ['[11,25,12,22,64]', '[11,64,25,22,12]', '[12,25,64,22,11]', '[11,25,64,22,12]'], correct: 0, explanation: 'Pass 1 finds the minimum (11) and SWAPS it with whatever occupies index 0 — so 64 lands where 11 was, giving [11,25,12,22,64]. Only that one swap happens per pass; everything else stays put. The second option shuffles more than one element, which selection sort never does in a single pass.', hint: 'One swap per pass: the minimum and the front element trade places. Nothing else moves.' },
        { type: 'pair', prompt: 'Match each sort call to what actually runs', pairs: [{ id: 1, left: 'Arrays.sort(int[])', right: 'Dual-Pivot Quicksort' }, { id: 2, left: 'Collections.sort()', right: 'TimSort' }, { id: 3, left: 'Insertion, best case', right: 'O(n) on sorted input' }, { id: 4, left: 'Bubble, worst case', right: 'O(n²)' }], explanation: 'The JDK runs two different algorithms depending on what you sort: primitives get Dual-Pivot Quicksort (stability is meaningless for an int), while objects get TimSort, because stability matters when equal elements are distinguishable. That is why Arrays.sort on an Integer[] and an int[] are not the same routine.' },
        { type: 'trace', prompt: 'Insertion sort inserts 3 into sorted [1,2,5,7]. What results?', code: [{ text: '// sorted part: [1,2,5,7], key = 3' }, { text: '// walk left from the end, shifting anything > key' }, { text: '// stop at the first element <= key, drop key in', highlight: true }], options: ['[1,2,3,5,7]', '[3,1,2,5,7]', '[1,2,5,3,7]', '[1,3,2,5,7]'], correct: 0, explanation: '7 and 5 are both bigger than 3, so each shifts one slot right; 2 is not, so the walk stops and 3 drops into the hole after it — [1,2,3,5,7]. The third option is what you get if you stop shifting one element too early, and the second is inserting at the front unconditionally.', hint: 'Which elements are bigger than 3? Each of those shifts right. Where does the walking stop?' },
        { type: 'bug', prompt: 'This comparator is a time bomb. Which line?', code: [{ text: 'Integer[] arr = {10, 9, 1, 2, 100};', hasError: false }, { text: 'Arrays.sort(arr, (a,b) -> a - b);', hasError: true }, { text: '// fine on this data...', hasError: false }, { text: '// then someone passes Integer.MIN_VALUE', hasError: false }], correctLine: 1, explanation: 'a - b overflows: Integer.MIN_VALUE minus any positive number wraps around to a POSITIVE value, so the comparator reports the wrong order and the sort quietly corrupts. It works on every test with small numbers, which is exactly why it ships. The fix costs nothing: Integer.compare(a, b) — or Comparator.naturalOrder().', hint: 'What is Integer.MIN_VALUE - 1 in 32-bit arithmetic? Which sign does it have?' },
        { type: 'realworld', prompt: 'Sorting orders by amount must not scramble same-amount rows. Which sorts promise that?', scenario: '⚖️ Rows already ordered by date; equal amounts must stay date-ordered.', options: [{ code: 'mergeSort(rows); timSort(rows); insertionSort(rows);', label: 'Merge, Tim, Insertion' }, { code: 'quickSort(rows);', label: 'Quicksort' }, { code: 'heapSort(rows);', label: 'Heapsort' }, { code: 'shellSort(rows);', label: 'Shellsort' }], correct: 0, explanation: 'Stability means equal elements keep their original relative order — which is invisible on plain ints and crucial when rows carry more data than the sort key. Merge-family sorts (including TimSort) and insertion sort preserve it; quicksort, heapsort and shellsort move elements across long distances and can flip equal ones. This is why Collections.sort guarantees stability and why sorting by B after sorting by A gives "B, then A within ties" only with a stable sort.', hint: 'Stability is about equal elements. Which algorithms only ever move an element past its neighbours?' },
    ],
    22: [
        { type: 'algostep', prompt: 'Binary search for 7 in [1,3,5,7,9,11,13]', array: [1, 3, 5, 7, 9, 11, 13], step: 1, description: 'lo=0, hi=6, so mid=3 — and arr[3] is checked first.', question: 'How many comparisons does finding 7 take?', options: ['1', '2', '3', '7'], correct: 0, explanation: 'The first midpoint of a 7-element array is index 3, and arr[3] happens to BE the 7 — one comparison, done. That is luck, not the general cost: the guarantee is at most ⌈log₂(n)⌉+1 comparisons, about 3 here. 7 is what linear search would need if the target were last.', hint: 'Work out which index gets checked first. What value lives there?' },
        { type: 'trace', prompt: '6 is not in the array. What does the search do?', code: [{ text: 'int lo=0, hi=4;' }, { text: 'while (lo <= hi) {' }, { text: '    int mid = lo + (hi-lo)/2;' }, { text: '    if (arr[mid]==6) return mid;' }, { text: '    else if (arr[mid]<6) lo=mid+1;' }, { text: '    else hi=mid-1;' }, { text: '}' }, { text: 'return -1;', highlight: true }], options: ['Returns 2', 'Returns 3', 'Returns -1', 'Infinite loop'], correct: 2, explanation: 'Trace it: mid=2 → arr[2]=5 < 6 so lo=3; mid=3 → arr[3]=7 > 6 so hi=2. Now lo > hi, the while fails, -1 comes back. Termination is no accident — the +1/-1 on every move is what guarantees the window closes. Note the mid formula is already the overflow-safe form.', hint: 'Run two iterations by hand. What are lo and hi after each, and when does the while stop?' },
        { type: 'errordecode', prompt: 'This overflow hid in the JDK for nine years. What is the safe form?', errorText: 'int mid = (lo + hi) / 2;\n// lo = 1_500_000_000, hi = 2_000_000_000\n// lo + hi = 3_500_000_000 > Integer.MAX_VALUE (2_147_483_647)\n// wraps NEGATIVE -> mid < 0 -> ArrayIndexOutOfBoundsException', question: 'Safe formula?', options: ['lo + (hi - lo) / 2', '(lo + hi) % 2', 'hi - lo', 'lo >>> 1'], correct: 0, explanation: 'The sum overflows int and wraps negative even though BOTH operands and the true midpoint fit comfortably. lo + (hi-lo)/2 never forms the big sum: the difference always fits. This exact bug sat in java.util.Arrays.binarySearch until 2006 — proof that it survives review. % 2 gives a parity bit, hi - lo is a width, and lo >>> 1 halves the wrong thing.', hint: 'Both lo and hi fit in an int. What intermediate value does not?' },
        { type: 'scramble', prompt: 'Assemble the iterative binary search', pieces: [{ id: 'a', text: 'static int bsearch(int[] arr, int t) {' }, { id: 'b', text: '    int lo = 0, hi = arr.length - 1;' }, { id: 'c', text: '    while (lo <= hi) {' }, { id: 'd', text: '        int mid = lo + (hi - lo) / 2;' }, { id: 'e', text: '        if (arr[mid] == t) return mid;' }, { id: 'f', text: '        else if (arr[mid] < t) lo = mid + 1;' }, { id: 'g', text: '        else hi = mid - 1;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return -1;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        lo = mid;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'The equality check must come before the two moves, and both moves must EXCLUDE mid — it was just examined. The spare line lo = mid is the classic infinite loop: on a two-element window mid equals lo, so nothing changes. And return -1 sits after the loop, reachable only when the window has closed empty.', hint: 'Each branch must shrink the window. Which piece fails to?' },
    ],
    23: [
        { type: 'trace', prompt: 'How does the work grow when n doubles?', code: [{ text: 'for (int i=0; i<n; i++)' }, { text: '    for (int j=0; j<n; j++)' }, { text: '        System.out.println(i+","+j);' }], options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(2ⁿ)'], correct: 1, explanation: 'The inner loop runs n times for each of the n outer passes — n × n = n². The practical meaning: double n and the work quadruples. O(n log n) would need the inner range to shrink or halve; O(2ⁿ) is a different universe, where adding ONE to n doubles the work.', hint: 'Count total prints for n=10, then for n=20. What is the ratio?' },
        { type: 'pair', prompt: 'Match each lookup to its cost', pairs: [{ id: 1, left: 'HashMap.get()', right: 'O(1) amortized' }, { id: 2, left: 'TreeMap.get()', right: 'O(log n)' }, { id: 3, left: 'ArrayList.get(i)', right: 'O(1)' }, { id: 4, left: 'LinkedList.get(i)', right: 'O(n)' }], explanation: 'The pair worth remembering is the last two: both are Lists with the same interface, but get(i) on a LinkedList walks the chain from the nearest end every single call. Loop over indices on a LinkedList and an innocent-looking O(n) loop silently becomes O(n²). TreeMap pays log n for what HashMap does in O(1) — its purchase is sorted order and range queries.', hint: 'Same interface does not mean same cost. Which one has to walk to reach index i?' },
        { type: 'trace', prompt: 'i is halved each pass. What is the complexity?', code: [{ text: 'int i = n;' }, { text: 'while (i > 0) {' }, { text: '    System.out.println(i);' }, { text: '    i = i / 2;', highlight: true }, { text: '}' }], options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correct: 1, explanation: 'The loop variable is divided, not decremented — that single character difference is the whole answer. From n it takes log₂(n) halvings to reach 0, and integer division is what guarantees the loop terminates: 1/2 is exactly 0 in int arithmetic, no floor call needed.', hint: 'Look only at the highlighted line. Is i shrinking by a constant amount, or by a constant factor?' },
        { type: 'refactor', prompt: 'The check runs thousands of times. Which rewrite is both correct and fast?', originalCode: '// runs in a hot loop:\nfor (int x : arr)\n    if (x == target) return true;\nreturn false;', options: [{ code: 'Set<Integer> set = new HashSet<>();      // once\nfor (int x : arr) set.add(x);\nreturn set.contains(target);             // O(1)', label: 'Fill a HashSet, then contains' }, { code: 'Set<Integer> set =\n    new HashSet<>(Arrays.asList(arr));\nreturn set.contains(target);', label: 'HashSet from Arrays.asList' }, { code: 'Arrays.sort(arr);\nreturn Arrays.binarySearch(arr, target) >= 0;', label: 'Sort, then binarySearch' }], correct: 0, explanation: 'The explicit loop boxes each int and gives O(1) contains. The Arrays.asList version COMPILES and always returns false: asList on an int[] produces a one-element List<int[]>, so the set contains an array object, never your numbers — contains(Object) accepts anything, so the compiler stays silent. That trap shipping as a plausible option is the point. Sort+binarySearch works but mutates the caller\'s array and pays log n per check.', hint: 'One option compiles cleanly and is wrong on every input. What does Arrays.asList do to a primitive array?' },
    ],
    24: [
        { type: 'trace', prompt: 'Which pair does the brute force return first?', code: [{ text: 'int[] nums = {2,7,11,15};' }, { text: 'int target = 9;' }, { text: 'for (int i=0; i<nums.length; i++)' }, { text: '    for (int j=i+1; j<nums.length; j++)' }, { text: '        if (nums[i]+nums[j]==target)' }, { text: '            return new int[]{i,j};', highlight: true }], options: ['[0,1]', '[1,2]', '[0,3]', 'null'], correct: 0, explanation: 'The very first pair tried is i=0, j=1: 2+7 = 9 — immediate hit, and the method returns INDICES, not values. j starts at i+1, which prevents both using the same element twice and checking each pair twice. null is what a fall-through return would give when every pair misses.', hint: 'What is the first (i, j) the loops generate, and what do those two values sum to?' },
        { type: 'refactor', prompt: 'Which rewrite makes two-sum a single pass AND keeps the indices right?', originalCode: 'for (int i=0; i<nums.length; i++)\n    for (int j=i+1; j<nums.length; j++)\n        if (nums[i]+nums[j]==target)\n            return new int[]{i,j};', options: [{ code: 'Map<Integer,Integer> map = new HashMap<>();\nfor (int i=0; i<nums.length; i++) {\n    int comp = target - nums[i];\n    if (map.containsKey(comp))\n        return new int[]{map.get(comp), i};\n    map.put(nums[i], i);\n}', label: 'HashMap of value→index' }, { code: 'Arrays.sort(nums);\nint lo = 0, hi = nums.length - 1;\n// walk pointers inward', label: 'Sort, then two pointers' }, { code: 'Set<Integer> seen = new HashSet<>();\nfor (int n : nums)\n    if (seen.contains(target - n)) return ...;\n    else seen.add(n);', label: 'HashSet of values' }], correct: 0, explanation: 'The map answers "have I already seen my complement, and WHERE?" in O(1) — one pass, indices intact. The two-pointer version is genuinely O(n log n), but Arrays.sort mutates nums and destroys the original indices the problem asks for. The set version detects that a pair EXISTS but cannot say where either element was: a set remembers membership, not position.', hint: 'All three can detect the pair. Which ones can still tell you the two original positions?' },
        { type: 'scramble', prompt: 'Assemble the one-pass two-sum', pieces: [{ id: 'a', text: 'Map<Integer,Integer> map = new HashMap<>();' }, { id: 'b', text: 'for (int i = 0; i < nums.length; i++) {' }, { id: 'c', text: '    int complement = target - nums[i];' }, { id: 'd', text: '    if (map.containsKey(complement)) {' }, { id: 'e', text: '        return new int[]{map.get(complement), i};' }, { id: 'f', text: '    }' }, { id: 'g', text: '    map.put(nums[i], i);' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '    map.put(i, nums[i]);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], explanation: 'The containsKey check must come BEFORE the put — check-then-add is what stops an element pairing with itself when target is twice its value. The map goes value→index so map.get(complement) retrieves a position. The spare line stores index→value, backwards: containsKey(complement) would then ask whether the complement is an INDEX, silently wrong on most inputs.', hint: 'The map is asked "where did I see this VALUE?". Which way round must the keys go?' },
        { type: 'realworld', prompt: 'When does a HashMap lookup stop being O(1)?', scenario: '⚠️ The average-case guarantee has a failure mode.', options: [{ code: '// many keys hash to the same bucket\n// lookups walk the collision chain', label: 'Under heavy collisions' }, { code: '// the map grows past a million entries', label: 'When it gets large' }, { code: '// keys are negative numbers', label: 'With negative keys' }, { code: '// values are null', label: 'With null values' }], correct: 0, explanation: 'O(1) assumes keys spread evenly across buckets. When many keys collide — bad hashCode, or adversarial inputs — lookups walk a chain, degrading toward O(n). Java 8 caps the damage by turning long chains into red-black trees, making the worst case O(log n). Size alone does not hurt (that is what amortized O(1) means), and negative keys or null values are perfectly legal.', hint: 'The guarantee says "average". What assumption about the keys does the average rest on?' },
    ],
    // ═══ CH7: DATA STRUCTURES II ═══
    25: [
        { type: 'trace', prompt: 'Push 1, 2, 3, pop twice — what does peek see?', code: [{ text: 'Deque<Integer> stack = new ArrayDeque<>();' }, { text: 'stack.push(1); stack.push(2); stack.push(3);' }, { text: 'stack.pop(); stack.pop();' }, { text: 'System.out.println(stack.peek());', highlight: true }], options: ['1', '2', '3', 'null'], correct: 0, explanation: 'push adds at the head of the deque, so the order inside is 3,2,1 — the pops remove 3 then 2, and peek reads (without removing) the remaining 1. null is what peek returns on an EMPTY ArrayDeque, one more pop away. Note pop() on empty throws instead; the peek/poll family returns null — a deliberate API split worth knowing.', hint: 'Two questions: which element survives both pops, and does peek remove it?' },
        { type: 'pair', prompt: 'Match each class to its role', pairs: [{ id: 1, left: 'ArrayDeque', right: 'The stack/deque to reach for' }, { id: 2, left: 'Stack class', right: 'Legacy, extends Vector' }, { id: 3, left: 'LinkedList', right: 'Deque with linked storage' }, { id: 4, left: 'PriorityQueue', right: 'Heap — best out first' }], explanation: 'The JDK\'s own Javadoc for Stack says to use Deque instead: Stack extends Vector, so every operation takes a lock nobody asked for, and its iterator walks bottom-to-top — the reverse of what a stack means. PriorityQueue is not FIFO at all: poll() returns the smallest element, regardless of arrival.' },
        { type: 'scramble', prompt: 'Assemble the balanced-brackets checker', pieces: [{ id: 'a', text: 'boolean isValid(String s) {' }, { id: 'b', text: '    Deque<Character> stack = new ArrayDeque<>();' }, { id: 'c', text: '    Map<Character,Character> pairs = Map.of(\')\',\'(\', \']\',\'[\', \'}\',\'{\');' }, { id: 'd', text: '    for (char c : s.toCharArray()) {' }, { id: 'e', text: '        if ("([{".indexOf(c) >= 0) stack.push(c);' }, { id: 'f', text: '        else if (stack.isEmpty() || stack.pop() != pairs.get(c))' }, { id: 'g', text: '            return false;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return stack.isEmpty();' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '    return true;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'isEmpty must be checked before popping — a closer with nothing open would otherwise throw NoSuchElementException. The final line must verify emptiness: plain return true passes "(((". One Java-specific footnote: stack.pop() != pairs.get(c) compares a char against an unboxed Character here; with boxed Characters on both sides, != would compare references and lie.', hint: 'Three ways to be unbalanced: wrong match, closer-first, opener never closed. Find the line that catches each.' },
        { type: 'bug', prompt: 'Code review rejects this line. Why?', code: [{ text: 'Stack<Integer> s = new Stack<>();', hasError: true }, { text: 's.push(1); s.push(2);', hasError: false }, { text: 'for (int x : s) System.out.println(x);', hasError: false }], correctLine: 0, explanation: 'Stack extends Vector, a Java 1.0 relic: every method is synchronized (a cost single-threaded code pays for nothing), and — the trap in line 3 — its for-each iterates BOTTOM-to-top, printing 1 then 2, the opposite of stack order. Deque<Integer> s = new ArrayDeque<>() fixes both: faster, and its iterator goes top-down as a stack should read.', hint: 'Run line 3 mentally. Which element prints first, and is that the order a stack should show?' },
    ],
    26: [
        { type: 'trace', prompt: 'What is a.next.val in this chain?', code: [{ text: 'class Node { int val; Node next; }' }, { text: 'Node a=new Node(1), b=new Node(2), c=new Node(3);' }, { text: 'a.next=b; b.next=c;' }, { text: 'System.out.println(a.next.val);', highlight: true }], options: ['1', '2', '3', 'NPE'], correct: 1, explanation: 'a.next points at b, and b.val is 2. Reading a chain of dots left to right — a, then .next (b), then .val — is the core skill for every linked-structure problem. The NPE option becomes real one link further: c.next is null, so c.next.val throws. Every dot after a possibly-null reference is a hazard.', hint: 'Resolve one dot at a time: what object is a.next? Then take its val.' },
        { type: 'scramble', prompt: 'Assemble the in-place list reversal', pieces: [{ id: 'a', text: 'Node reverse(Node head) {' }, { id: 'b', text: '    Node prev = null, curr = head;' }, { id: 'c', text: '    while (curr != null) {' }, { id: 'd', text: '        Node next = curr.next;' }, { id: 'e', text: '        curr.next = prev;' }, { id: 'f', text: '        prev = curr;' }, { id: 'g', text: '        curr = next;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return prev;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        curr.next = next;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], explanation: 'The save (Node next = curr.next) must come before the overwrite (curr.next = prev) — reversed, the rest of the list is unreachable. When the loop ends curr is null, so the new head is prev, not curr: returning curr returns null and the reversal vanishes. The spare line undoes the flip it follows.', hint: 'Why is next saved first? And when the loop exits, which variable is holding the last real node?' },
        { type: 'realworld', prompt: 'General-purpose list in Java — which default, and why?', scenario: '🤔 Both implement List. The costs differ underneath.', options: [{ code: 'new ArrayList<>()  // contiguous array', label: 'ArrayList' }, { code: 'new LinkedList<>() // node chain', label: 'LinkedList' }, { code: 'new Vector<>()     // synchronized array', label: 'Vector' }, { code: 'new int[16]        // raw array', label: 'A raw array' }], correct: 0, explanation: 'ArrayList wins almost always, and the deep reason is hardware: contiguous memory means cache hits, while every LinkedList node is a separate allocation with a pointer hop — even its theoretical O(1) head-insert often loses in practice. LinkedList earns its keep only for heavy add/remove at both ends, and even there ArrayDeque is usually better. Vector is the legacy synchronized relic, and a raw array cannot grow.', hint: 'Think about where the elements live in memory, and what the CPU cache thinks of that.' },
        { type: 'bug', prompt: 'This crashes on an empty list. Which line?', code: [{ text: 'Node curr = head;', hasError: false }, { text: 'while (curr.next != null) {', hasError: true }, { text: '    curr = curr.next;', hasError: false }, { text: '}', hasError: false }], correctLine: 1, explanation: 'If head is null, curr.next dereferences null on the very first check — NullPointerException. The condition must be curr != null, which also fixes a second, quieter bug: curr.next != null stops AT the last node instead of after it, so the final element never gets processed. One wrong condition, two distinct failures.', hint: 'Feed an empty list (head = null) into line 2. What does curr.next try to do?' },
    ],
    27: [
        { type: 'trace', prompt: 'In-order traversal of this BST prints what?', code: [{ text: '//       4' }, { text: '//      / \\' }, { text: '//     2   6' }, { text: '//    / \\' }, { text: '//   1   3' }, { text: '// in-order: visit left subtree, node, right subtree', highlight: true }], options: ['4 2 1 3 6', '1 2 3 4 6', '1 3 2 6 4', '4 2 6 1 3'], correct: 1, explanation: 'In-order goes fully left first: 1, back to 2, then 3, up to 4, then 6 — ascending order. That is not luck: BST invariant plus in-order = sorted output, always. This is literally what TreeMap does when you iterate it — its keys arrive sorted because the iterator is an in-order walk of a red-black tree.', hint: 'Fully left before every node, right after. Start at the deepest left leaf.' },
        { type: 'pair', prompt: 'Match each class to what is underneath', pairs: [{ id: 1, left: 'TreeMap', right: 'Red-black BST' }, { id: 2, left: 'PriorityQueue', right: 'Binary heap' }, { id: 3, left: 'TreeSet', right: 'TreeMap with values ignored' }, { id: 4, left: 'HashMap', right: 'Hash table — no tree' }], explanation: 'The implementation dictates the contract: TreeMap iterates in sorted key order and offers firstKey/subMap because a red-black tree can, PriorityQueue only ever promises the TOP element (iterating it is NOT sorted — a heap is not a sorted structure), and HashMap promises no order at all. TreeSet is literally a TreeMap wearing a Set interface.', hint: 'Ask what each one can promise about ORDER. The underlying structure decides.' },
        { type: 'fillgap', prompt: 'val is SMALLER than this node — which way does the search go?', codeParts: [{ text: 'Node search(Node root, int val) {\n    if (root == null || root.val == val) return root;\n    return val < root.val\n        ? ', type: 'fixed' }, { text: 'search(root.left, val)', type: 'gap', id: 'g1' }, { text: '\n        : search(root.right, val);\n}', type: 'fixed' }], bank: ['search(root.left, val)', 'search(root.right, val)', 'search(root, val-1)', 'root.left'], correctFill: { g1: 'search(root.left, val)' }, explanation: 'Smaller values live left — the BST invariant; the recursion just follows it. Recursing right searches where the value cannot be. search(root, val-1) mutates the TARGET and loops on the same node forever. Bare root.left type-checks here (it is a Node) but returns the child UNEXAMINED — a subtle one, since the compiler will not save you.', hint: 'The condition already told you val < root.val. Where does the invariant say smaller values live?' },
        { type: 'realworld', prompt: 'Which task actually needs a TreeMap?', scenario: '🌳 HashMap gives O(1); TreeMap charges O(log n). What justifies the price?', options: [{ code: 'prices.subMap(10, 20)   // all keys in a range\nprices.firstKey()       // smallest key', label: 'Range queries over sorted keys' }, { code: 'cache.get(userId)       // point lookups only', label: 'Point lookups by id' }, { code: 'counts.merge(w, 1, Integer::sum)', label: 'Frequency counting' }, { code: 'seen.containsKey(x)     // membership only', label: 'Membership checks' }], correct: 0, explanation: 'subMap and firstKey only exist because a red-black tree keeps keys sorted — a hash table fundamentally cannot answer "everything between 10 and 20" without scanning. The other three are point operations where sorted order buys nothing, so TreeMap\'s O(log n) is pure overhead. Pick the structure by the QUERIES you need, not by the data.', hint: 'Three of these ask about one key at a time. Which one asks about many keys at once, in order?' },
    ],
    28: [
        { type: 'video', title: 'Data Structures Visualized', description: 'Stacks (ArrayDeque), Queues (PriorityQueue), LinkedList, Trees (TreeMap) — Java implementations, trade-offs.', duration: '4:00', thumbnail: '🎥' },
        { type: 'pair', prompt: 'Match each operation to its cost', pairs: [{ id: 1, left: 'ArrayList.get(i)', right: 'O(1)' }, { id: 2, left: 'LinkedList.addFirst(x)', right: 'O(1), two pointers move' }, { id: 3, left: 'TreeMap.get(key)', right: 'O(log n)' }, { id: 4, left: 'ArrayList.add(0, x)', right: 'O(n), everything shifts' }], explanation: 'Each structure buys one cheap operation by making another expensive: ArrayList\'s O(1) indexing costs it O(n) front-insertion via System.arraycopy, and LinkedList makes the opposite trade. TreeMap\'s log n is the toll for keeping keys permanently sorted.' },
        { type: 'trace', prompt: 'add 5, 1, 3 — what does poll() return?', code: [{ text: 'PriorityQueue<Integer> pq = new PriorityQueue<>();' }, { text: 'pq.add(5); pq.add(1); pq.add(3);' }, { text: 'System.out.println(pq.poll());', highlight: true }], options: ['5', '1', '3', 'Error'], correct: 1, explanation: 'PriorityQueue is a min-heap by default: poll() returns the SMALLEST element, not the first inserted (that would be a queue) nor the last (a stack). For largest-first, pass Comparator.reverseOrder(). One trap worth knowing: iterating a PriorityQueue does NOT visit elements in sorted order — only poll() drains it sorted.', hint: 'Neither arrival order nor reverse arrival — what ordering does a heap maintain?' },
        { type: 'realworld', prompt: 'A FIFO queue for BFS — which do you instantiate?', scenario: '📋 Millions of offer/poll operations.', options: [{ code: 'Deque<Integer> q = new ArrayDeque<>();', label: 'ArrayDeque' }, { code: 'Queue<Integer> q = new LinkedList<>();', label: 'LinkedList' }, { code: 'Deque<Integer> q = new Stack<>();', label: 'Stack' }, { code: 'List<Integer> q = new ArrayList<>();', label: 'ArrayList' }], correct: 0, explanation: 'ArrayDeque is a ring buffer: O(1) at both ends, contiguous memory, no per-node allocation — the JDK docs themselves say it is faster than LinkedList as a queue. LinkedList works but allocates a node per element. Stack does not even compile as a Deque (it is not one), and ArrayList makes dequeue O(n) via remove(0).', hint: 'One does not compile, one is O(n) per dequeue, one allocates per element. What remains?' },
    ],
    // ═══ CH8: ALGORITHMS II ═══
    29: [
        { type: 'trace', prompt: 'Tower of Hanoi: 3 disks = ? moves', code: [{ text: 'int hanoi(int n) {' }, { text: '    if (n == 1) return 1;' }, { text: '    return 2 * hanoi(n-1) + 1;' }, { text: '}' }, { text: 'System.out.println(hanoi(3));', highlight: true }], options: ['3', '5', '7', '8'], correct: 2 },
        { type: 'fillgap', prompt: 'Recursive sum of digits', codeParts: [{ text: 'int sumDigits(int n) {\n    if (n < 10) return n;\n    return ', type: 'fixed' }, { text: 'n % 10 + sumDigits(n / 10);', type: 'gap', id: 'g1' }, { text: '\n}', type: 'fixed' }], bank: ['n % 10 + sumDigits(n / 10);', 'n + sumDigits(n - 1);', 'sumDigits(n % 10);', 'n / 10 + n % 10;'], correctFill: { g1: 'n % 10 + sumDigits(n / 10);' } },
        { type: 'errordecode', prompt: 'StackOverflowError cause?', errorText: 'Exception in thread "main" java.lang.StackOverflowError\n    at Recursion.factorial(Recursion.java:3)', question: 'Root cause?', options: ['Missing base case or recursion too deep', 'Array too large', 'Null pointer', 'Syntax error'], correct: 0 },
        { type: 'bug', prompt: 'Factorial bug — which line?', code: [{ text: 'int factorial(int n) {', hasError: false }, { text: '    return n * factorial(n - 1);', hasError: true }, { text: '}', hasError: false }], correctLine: 1 },
    ],
    30: [
        { type: 'algostep', prompt: 'Merge [1,3,5] and [2,4,6]', array: [1, 3, 5, 2, 4, 6], step: 1, description: 'Compare 1 vs 2, take 1.', question: 'Next?', options: ['3 vs 2', '1 vs 2', '5 vs 6', '3 vs 4'], correct: 0 },
        { type: 'pair', prompt: 'Divide & Conquer', pairs: [{ id: 1, left: 'Merge Sort', right: 'O(n log n) stable' }, { id: 2, left: 'Quick Sort', right: 'O(n log n) avg, unstable' }, { id: 3, left: 'Binary Search', right: 'O(log n)' }, { id: 4, left: 'Karatsuba', right: 'Fast multiplication' }] },
        { type: 'trace', prompt: 'Merge sort space complexity?', code: [{ text: '// Creates new arrays at each level' }, { text: '// Peak extra space held at once = ?', highlight: true }], options: ['O(1)', 'O(n)', 'O(n²)', 'O(log n)'], correct: 1 },
        { type: 'scramble', prompt: 'Build merge function', pieces: [{ id: 'a', text: 'void merge(int[] arr, int l, int m, int r) {' }, { id: 'b', text: '    int[] left = Arrays.copyOfRange(arr, l, m+1);' }, { id: 'c', text: '    int[] right = Arrays.copyOfRange(arr, m+1, r+1);' }, { id: 'd', text: '    int i=0, j=0, k=l;' }, { id: 'e', text: '    while (i<left.length && j<right.length)' }, { id: 'f', text: '        arr[k++] = left[i]<=right[j] ? left[i++] : right[j++];' }, { id: 'g', text: '    while (i<left.length) arr[k++] = left[i++];' }, { id: 'h', text: '    while (j<right.length) arr[k++] = right[j++];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    Arrays.sort(arr, l, r+1);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
    ],
    31: [
        { type: 'refactor', prompt: 'O(2ⁿ) fib → O(n) with memo', originalCode: 'int fib(int n) {\n    if (n<=1) return n;\n    return fib(n-1)+fib(n-2);\n}', options: [{ code: 'Map<Integer,Integer> memo = new HashMap<>();\nint fib(int n) {\n    if (memo.containsKey(n)) return memo.get(n);\n    if (n<=1) return n;\n    int val = fib(n-1)+fib(n-2);\n    memo.put(n, val);\n    return val;\n}', label: 'Memoization' }, { code: 'Same recursive code', label: 'Still O(2ⁿ)' }, { code: 'int fib = Math.factorial(n);', label: 'Wrong' }], correct: 0 },
        { type: 'fillgap', prompt: 'Tabulation — bottom-up DP', codeParts: [{ text: 'int fib(int n) {\n    if (n <= 1) return n;\n    int[] dp = new int[n+1];\n    dp[0]=0; dp[1]=1;\n    for (int i=2; i<=n; i++)\n        ', type: 'fixed' }, { text: 'dp[i] = dp[i-1] + dp[i-2];', type: 'gap', id: 'g1' }, { text: '\n    return dp[n];\n}', type: 'fixed' }], bank: ['dp[i] = dp[i-1] + dp[i-2];', 'dp[i] = dp[i-1] * 2;', 'dp[i] = i;', 'dp[i] = dp[i-1];'], correctFill: { g1: 'dp[i] = dp[i-1] + dp[i-2];' } },
        { type: 'realworld', prompt: 'Memoization vs Tabulation?', scenario: '🧠 Two DP approaches in Java', options: [{ code: '// Memo: HashMap + recursion (top-down)\n// Tab: array + iteration (bottom-up)\n// Tab avoids StackOverflow!', label: 'Top-down vs bottom-up' }, { code: '// Same thing', label: 'Different approaches' }, { code: '// Always use memo', label: 'Tab better for large n' }, { code: '// Always use tab', label: 'Depends on problem' }], correct: 0 },
        { type: 'trace', prompt: 'Climbing stairs dp[4]?', code: [{ text: '// dp[1]=1, dp[2]=2' }, { text: '// dp[3]=dp[2]+dp[1]=3' }, { text: '// dp[4]=dp[3]+dp[2]=?', highlight: true }], options: ['4', '5', '6', '8'], correct: 1 },
    ],
    32: [
        { type: 'trace', prompt: 'Fast exponentiation: power(2,10)?', code: [{ text: 'long power(long b, int e) {' }, { text: '    if (e==0) return 1;' }, { text: '    if (e%2==0) { long h=power(b,e/2); return h*h; }' }, { text: '    return b*power(b,e-1);' }, { text: '}' }, { text: '// power(2,10) = ?', highlight: true }], options: ['20', '100', '512', '1024'], correct: 3 },
        { type: 'scramble', prompt: 'Build coin change DP', pieces: [{ id: 'a', text: 'int coinChange(int[] coins, int amount) {' }, { id: 'b', text: '    int[] dp = new int[amount+1];' }, { id: 'c', text: '    Arrays.fill(dp, amount+1);' }, { id: 'd', text: '    dp[0] = 0;' }, { id: 'e', text: '    for (int i=1; i<=amount; i++)' }, { id: 'f', text: '        for (int c : coins)' }, { id: 'g', text: '            if (c<=i) dp[i] = Math.min(dp[i], dp[i-c]+1);' }, { id: 'h', text: '    return dp[amount]>amount ? -1 : dp[amount];' }, { id: 'i', text: '}' }], distractors: [{ id: 'j', text: '    dp[0] = 1;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'] },
        { type: 'realworld', prompt: 'When does DP help?', scenario: '🧠 DP requires...', options: [{ code: '// 1. Overlapping subproblems\n// 2. Optimal substructure', label: 'Both conditions' }, { code: '// Any recursive problem', label: 'Not always' }, { code: '// Sorting only', label: 'Much broader' }, { code: '// Only Fibonacci', label: 'Many applications' }], correct: 0 },
    ],
    // ═══ CH9: ADVANCED ═══
    33: [
        { type: 'pair', prompt: 'Graph representations', pairs: [{ id: 1, left: 'Adjacency List', right: 'List<List<Integer>>' }, { id: 2, left: 'Adjacency Matrix', right: 'int[][]' }, { id: 3, left: 'Edge List', right: 'List<int[]>' }, { id: 4, left: 'Space: List vs Matrix', right: 'O(V+E) vs O(V²)' }] },
        { type: 'fillgap', prompt: 'Build adjacency list', codeParts: [{ text: 'List<List<Integer>> buildGraph(int n, int[][] edges) {\n    List<List<Integer>> g = new ArrayList<>();\n    for (int i=0; i<n; i++) g.add(new ArrayList<>());\n    for (int[] e : edges) {\n        ', type: 'fixed' }, { text: 'g.get(e[0]).add(e[1]);', type: 'gap', id: 'g1' }, { text: '\n    }\n    return g;\n}', type: 'fixed' }], bank: ['g.get(e[0]).add(e[1]);', 'g.add(e[0]);', 'g[e[0]] = e[1];', 'g.set(e[0], e[1]);'], correctFill: { g1: 'g.get(e[0]).add(e[1]);' } },
        { type: 'realworld', prompt: 'Adjacency list vs matrix?', scenario: '🤔 When which?', options: [{ code: '// List: sparse graphs (V+E << V²)\n// Matrix: dense graphs, fast edge lookup', label: 'Sparse→List, Dense→Matrix' }, { code: '// Always use list', label: 'Matrix better for dense' }, { code: '// Always use matrix', label: 'Wastes space for sparse' }, { code: '// Use edge list', label: 'Slowest lookups' }], correct: 0 },
        { type: 'output', prompt: 'Graph neighbors?', code: [{ text: 'Map<String,List<String>> g = Map.of(' }, { text: '    "A", List.of("B","C"),' }, { text: '    "B", List.of("C"),' }, { text: '    "C", List.of()' }, { text: ');' }, { text: 'System.out.println(g.get("A").size());' }], terminalOutput: '2', options: ['1', '2', '3', '0'], correct: 1 },
    ],
    34: [
        { type: 'trace', prompt: 'BFS from A: visit order?', code: [{ text: '// A→[B,C], B→[D], C→[D], D→[]' }, { text: 'Queue<String> q = new LinkedList<>();' }, { text: 'q.add("A"); Set<String> seen = new HashSet<>();' }, { text: 'seen.add("A");' }, { text: '// Process: A→enqueue B,C → B→enqueue D → C→D already seen', highlight: true }], options: ['A B C D', 'A B D C', 'A C B D', 'D B C A'], correct: 0 },
        { type: 'pair', prompt: 'BFS vs DFS in Java', pairs: [{ id: 1, left: 'BFS', right: 'Queue (ArrayDeque)' }, { id: 2, left: 'DFS iterative', right: 'Stack (ArrayDeque)' }, { id: 3, left: 'DFS recursive', right: 'Call stack' }, { id: 4, left: 'BFS finds', right: 'Shortest path unweighted' }] },
        { type: 'scramble', prompt: 'BFS with Java Queue', pieces: [{ id: 'a', text: 'void bfs(Map<String,List<String>> g, String start) {' }, { id: 'b', text: '    Queue<String> q = new ArrayDeque<>();' }, { id: 'c', text: '    Set<String> visited = new HashSet<>();' }, { id: 'd', text: '    q.add(start); visited.add(start);' }, { id: 'e', text: '    while (!q.isEmpty()) {' }, { id: 'f', text: '        String node = q.poll();' }, { id: 'g', text: '        for (String nb : g.get(node)) {' }, { id: 'h', text: '            if (!visited.contains(nb)) {' }, { id: 'i', text: '                visited.add(nb); q.add(nb);' }, { id: 'j', text: '            }' }, { id: 'k', text: '        }' }, { id: 'l', text: '    }' }, { id: 'm', text: '}' }], distractors: [{ id: 'n', text: '        String node = q.peek();' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm'] },
        { type: 'bug', prompt: 'ConcurrentModificationException risk?', code: [{ text: 'for (String node : graph.keySet()) {', hasError: true }, { text: '    if (condition) graph.remove(node);', hasError: false }], correctLine: 0 },
    ],
    35: [
        { type: 'trace', prompt: 'Two-pointer: pair=6 in [1,2,3,4,6]?', code: [{ text: 'int lo=0, hi=4; // 1+6=7>6' }, { text: 'hi--;           // 1+4=5<6' }, { text: 'lo++;           // 2+4=6 ✓', highlight: true }], options: ['[1,5]', '[0,4]', '[1,3]', '[2,3]'], correct: 2 },
        { type: 'fillgap', prompt: 'Sliding window max sum', codeParts: [{ text: 'int maxSum(int[] arr, int k) {\n    int window = 0;\n    for (int i=0; i<k; i++) window += arr[i];\n    int best = window;\n    for (int i=k; i<arr.length; i++) {\n        ', type: 'fixed' }, { text: 'window += arr[i] - arr[i-k];', type: 'gap', id: 'g1' }, { text: '\n        best = Math.max(best, window);\n    }\n    return best;\n}', type: 'fixed' }], bank: ['window += arr[i] - arr[i-k];', 'window = arr[i];', 'window += arr[i];', 'window -= arr[i-k];'], correctFill: { g1: 'window += arr[i] - arr[i-k];' } },
        { type: 'refactor', prompt: 'Contains duplicate — O(n)?', originalCode: '// O(n²)\nfor (int i=0; i<n; i++)\n    for (int j=i+1; j<n; j++)\n        if (arr[i]==arr[j]) return true;', options: [{ code: 'Set<Integer> seen = new HashSet<>();\nfor (int x : arr)\n    if (!seen.add(x)) return true;', label: 'HashSet.add returns false if exists' }, { code: 'Arrays.sort(arr);\n// check adjacent', label: 'O(n log n)' }, { code: 'return new HashSet<>(Arrays.asList(arr)).size() != arr.length;', label: 'Also O(n) but autoboxes' }], correct: 0 },
        { type: 'realworld', prompt: 'Two-pointer vs HashMap?', scenario: '🤔 Which approach when?', options: [{ code: '// Two-pointer: sorted input\n// HashMap: unsorted, need O(1) lookup', label: 'Sorted→pointers, Unsorted→map' }, { code: '// Always use HashMap', label: 'Two-pointer saves space' }, { code: '// Always use two-pointer', label: 'Needs sorted input' }, { code: '// Same thing', label: 'Different approaches' }], correct: 0 },
    ],
    36: [
        { type: 'scramble', prompt: 'DFS recursive', pieces: [{ id: 'a', text: 'void dfs(int node, List<List<Integer>> g, boolean[] vis) {' }, { id: 'b', text: '    vis[node] = true;' }, { id: 'c', text: '    System.out.println(node);' }, { id: 'd', text: '    for (int nb : g.get(node)) {' }, { id: 'e', text: '        if (!vis[nb]) dfs(nb, g, vis);' }, { id: 'f', text: '    }' }, { id: 'g', text: '}' }], distractors: [{ id: 'h', text: '        dfs(nb, g, vis);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
        { type: 'pair', prompt: 'Graph algorithm applications', pairs: [{ id: 1, left: 'BFS', right: 'Shortest unweighted path' }, { id: 2, left: 'DFS', right: 'Topological sort (COS226)' }, { id: 3, left: 'Dijkstra', right: 'Shortest weighted path' }, { id: 4, left: 'Union-Find', right: 'Connected components' }] },
        { type: 'trace', prompt: 'DFS from 0: visit order?', code: [{ text: '// 0→[1,2], 1→[3], 2→[], 3→[]' }, { text: '// DFS: 0 → 1 → 3 → backtrack → 2', highlight: true }], options: ['0 1 3 2', '0 1 2 3', '0 2 1 3', '3 1 2 0'], correct: 0 },
        { type: 'errordecode', prompt: 'Graph cycle → infinite recursion', errorText: 'StackOverflowError at dfs(Graph.java:5)', question: 'Fix?', options: ['Add visited[] check before recursing', 'Increase stack size', 'Use BFS instead', 'Remove edges'], correct: 0 },
    ],
    // ═══ CH10: MASTERY ═══
    37: [
        { type: 'pair', prompt: 'DP patterns (MIT 6.006)', pairs: [{ id: 1, left: 'Fibonacci', right: 'dp[i]=dp[i-1]+dp[i-2]' }, { id: 2, left: '0-1 Knapsack', right: 'Include or exclude' }, { id: 3, left: 'LCS', right: 'Match chars or skip' }, { id: 4, left: 'Coin Change', right: 'min(dp[amt-c]+1)' }] },
        { type: 'fillgap', prompt: 'LCS in Java', codeParts: [{ text: 'int lcs(String a, String b) {\n    int[][] dp = new int[a.length()+1][b.length()+1];\n    for (int i=1; i<=a.length(); i++)\n        for (int j=1; j<=b.length(); j++)\n            dp[i][j] = a.charAt(i-1)==b.charAt(j-1)\n                ? ', type: 'fixed' }, { text: 'dp[i-1][j-1] + 1', type: 'gap', id: 'g1' }, { text: '\n                : Math.max(dp[i-1][j], dp[i][j-1]);\n    return dp[a.length()][b.length()];\n}', type: 'fixed' }], bank: ['dp[i-1][j-1] + 1', 'dp[i][j] + 1', 'dp[i-1][j-1]', 'i + j'], correctFill: { g1: 'dp[i-1][j-1] + 1' } },
        { type: 'trace', prompt: 'LCS of "ABCBDAB" and "BDCAB"?', code: [{ text: '// LCS = "BCAB" or "BDAB" → length 4', highlight: true }], options: ['3', '4', '5', '7'], correct: 1 },
        { type: 'realworld', prompt: 'DP in production?', scenario: '🏭 Real DP applications', options: [{ code: '// Git diff: longest common subsequence\n// Spell check: edit distance\n// Knapsack: resource allocation', label: 'Diff, spell check, allocation' }, { code: '// Only academic', label: 'Very practical!' }, { code: '// Only Fibonacci', label: 'Many applications' }, { code: '// Only in Java', label: 'Language-agnostic' }], correct: 0 },
    ],
    38: [
        { type: 'pair', prompt: 'Pattern → problem', pairs: [{ id: 1, left: 'Sliding window', right: 'Max subarray size k' }, { id: 2, left: 'Two pointer', right: 'Pair sum sorted' }, { id: 3, left: 'BFS', right: 'Shortest unweighted' }, { id: 4, left: 'DP', right: 'Min coins' }] },
        { type: 'realworld', prompt: 'Interview strategy?', scenario: '🎯 Hard problem approach', options: [{ code: '// 1. Brute force\n// 2. Find pattern\n// 3. Optimize DS\n// 4. Code + edge cases', label: 'Structured' }, { code: '// Jump to optimal', label: 'Risky' }, { code: '// Give up', label: 'Never!' }, { code: '// Memorize', label: 'Not scalable' }], correct: 0 },
        { type: 'trace', prompt: 'Kadane max subarray [-2,1,-3,4,-1,2,1,-5,4]?', code: [{ text: '// curr max at each step:' }, { text: '// -2,1,-2,4,3,5,6,1,5' }, { text: '// global max = 6', highlight: true }], options: ['6', '5', '4', '7'], correct: 0 },
        { type: 'scramble', prompt: 'Kadane algorithm', pieces: [{ id: 'a', text: 'int maxSubArray(int[] nums) {' }, { id: 'b', text: '    int curr = nums[0], best = nums[0];' }, { id: 'c', text: '    for (int i = 1; i < nums.length; i++) {' }, { id: 'd', text: '        curr = Math.max(nums[i], curr + nums[i]);' }, { id: 'e', text: '        best = Math.max(best, curr);' }, { id: 'f', text: '    }' }, { id: 'g', text: '    return best;' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '        curr += nums[i];' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
    ],
    39: [
        { type: 'fillgap', prompt: 'Reverse array in-place', codeParts: [{ text: 'void reverse(int[] arr) {\n    int lo = 0, hi = arr.length - 1;\n    while (lo < hi) {\n        ', type: 'fixed' }, { text: 'int tmp = arr[lo]; arr[lo] = arr[hi]; arr[hi] = tmp;', type: 'gap', id: 'g1' }, { text: '\n        lo++; hi--;\n    }\n}', type: 'fixed' }], bank: ['int tmp = arr[lo]; arr[lo] = arr[hi]; arr[hi] = tmp;', 'arr[lo] = arr[hi];', 'swap(lo, hi);', 'Collections.swap(arr, lo, hi);'], correctFill: { g1: 'int tmp = arr[lo]; arr[lo] = arr[hi]; arr[hi] = tmp;' } },
        { type: 'trace', prompt: 'Palindrome check?', code: [{ text: 'boolean isPalindrome(String s) {' }, { text: '    s = s.toLowerCase().replaceAll("[^a-z0-9]","");' }, { text: '    return new StringBuilder(s).reverse().toString().equals(s);' }, { text: '}' }, { text: '// isPalindrome("A man, a plan, a canal: Panama")', highlight: true }], options: ['true', 'false', 'Error', 'null'], correct: 0 },
        { type: 'scramble', prompt: 'Valid anagram', pieces: [{ id: 'a', text: 'boolean isAnagram(String s, String t) {' }, { id: 'b', text: '    if (s.length() != t.length()) return false;' }, { id: 'c', text: '    char[] a = s.toCharArray(), b = t.toCharArray();' }, { id: 'd', text: '    Arrays.sort(a); Arrays.sort(b);' }, { id: 'e', text: '    return Arrays.equals(a, b);' }, { id: 'f', text: '}' }], distractors: [{ id: 'g', text: '    return s.equals(t);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
        { type: 'bug', prompt: 'Contains duplicate — why slow?', code: [{ text: 'for (int i=0; i<n; i++)', hasError: false }, { text: '    for (int j=i+1; j<n; j++)', hasError: true }, { text: '        if (arr[i]==arr[j]) return true;', hasError: false }], correctLine: 1 },
    ],
    40: [
        { type: 'trace', prompt: 'Matrix search O(m+n)?', code: [{ text: '// Start top-right corner' }, { text: '// > target: go left' }, { text: '// < target: go down', highlight: true }], options: ['O(m+n)', 'O(m*n)', 'O(log(mn))', 'O(1)'], correct: 0 },
        { type: 'scramble', prompt: 'Binary search iterative', pieces: [{ id: 'a', text: 'int search(int[] nums, int target) {' }, { id: 'b', text: '    int lo = 0, hi = nums.length - 1;' }, { id: 'c', text: '    while (lo <= hi) {' }, { id: 'd', text: '        int mid = lo + (hi - lo) / 2;' }, { id: 'e', text: '        if (nums[mid] == target) return mid;' }, { id: 'f', text: '        else if (nums[mid] < target) lo = mid + 1;' }, { id: 'g', text: '        else hi = mid - 1;' }, { id: 'h', text: '    }' }, { id: 'i', text: '    return -1;' }, { id: 'j', text: '}' }], distractors: [{ id: 'k', text: '        lo = mid;' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] },
        { type: 'realworld', prompt: 'Final boss tip?', scenario: '🏆 What makes a great solution?', options: [{ code: '// Correct + readable + optimal\n// Handle edge cases\n// Explain time/space complexity', label: 'All three matter' }, { code: '// Just make it work', label: 'Correctness alone insufficient' }, { code: '// Fastest possible', label: 'Readability matters too' }, { code: '// Shortest code', label: 'Code golf ≠ production' }], correct: 0 },
        { type: 'errordecode', prompt: 'ArrayIndexOutOfBoundsException', errorText: 'java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5', question: 'Cause?', options: ['Array indices are 0 to length-1, not 1 to length', 'Array too small', 'Null array', 'Wrong type'], correct: 0 },
    ],
    41: [
        { type: 'pair', prompt: 'Advanced CS concepts', pairs: [{ id: 1, left: 'Amortized O(1)', right: 'ArrayList.add avg' }, { id: 2, left: 'NP-Complete', right: 'TSP, SAT, Clique' }, { id: 3, left: 'Space-Time', right: 'HashMap caches results' }, { id: 4, left: 'Greedy', right: 'Local optimal choices' }] },
        { type: 'trace', prompt: 'Greedy activity selection?', code: [{ text: '// Sort by end time' }, { text: '// [(1,4),(3,5),(0,6),(5,7),(8,9)]' }, { text: '// Pick: (1,4),(5,7),(8,9)', highlight: true }], options: ['3', '2', '4', '5'], correct: 0 },
        { type: 'realworld', prompt: 'On which of these problems does a greedy choice give the wrong answer?', scenario: '⚠️ Greedy is optimal for some problems and merely fast for others.', options: [{ code: 'coins = [1, 3, 4], amount = 6', label: 'Coin change' }, { code: 'pick the meeting that finishes earliest, repeat', label: 'Activity selection' }, { code: 'merge the two least frequent nodes, repeat', label: 'Huffman coding' }, { code: 'add the cheapest edge that creates no cycle', label: "Kruskal's MST" }], correct: 0, explanation: 'Activity selection, Huffman and Kruskal all have the greedy-choice property — proven optimal. Coin change does not: on [1,3,4] greedy takes 4+1+1 (3 coins) while 3+3 (2 coins) is optimal. That is the whole reason coin change is taught as a DP problem.', hint: 'Three of these are classic proofs that greedy IS optimal. Which one is the classic counterexample?' },
    ],
    42: [
        { type: 'realworld', prompt: 'Journey complete! Next step?', scenario: '🎓 Mastered: variables→loops→functions→DS→algorithms→DP→graphs!', options: [{ code: '// Build real projects!\n// Contribute to open source\n// Apply concepts to real applications', label: 'Build projects! 🚀' }, { code: '// Review everything', label: 'Review' }, { code: '// Just read more', label: 'More books' }, { code: '// Stop forever', label: 'Never stop!' }], correct: 0 },
        { type: 'pair', prompt: 'Journey recap', pairs: [{ id: 1, left: 'CH1-2', right: 'Variables & Flow' }, { id: 2, left: 'CH3-4', right: 'Loops & Functions' }, { id: 3, left: 'CH5-7', right: 'Data Structures' }, { id: 4, left: 'CH8-10', right: 'Algorithms & DP' }] },
        { type: 'trace', prompt: 'Final puzzle: mystery(5)?', code: [{ text: 'static int mystery(int n) {' }, { text: '    if (n == 0) return 1;' }, { text: '    return n * mystery(n - 1);' }, { text: '}' }, { text: 'System.out.println(mystery(5));', highlight: true }], options: ['5', '15', '120', '720'], correct: 2 },
        { type: 'scramble', prompt: 'Final: memoized fibonacci', pieces: [{ id: 'a', text: 'static Map<Integer,Integer> memo = new HashMap<>();' }, { id: 'b', text: 'static int fib(int n) {' }, { id: 'c', text: '    if (memo.containsKey(n)) return memo.get(n);' }, { id: 'd', text: '    if (n <= 1) return n;' }, { id: 'e', text: '    int val = fib(n-1) + fib(n-2);' }, { id: 'f', text: '    memo.put(n, val);' }, { id: 'g', text: '    return val;' }, { id: 'h', text: '}' }], distractors: [{ id: 'i', text: '    return fib(n-1) + fib(n-2);' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] },
    ],
}
