/* ══════════════════════════════════════════════════
   PYTHON EXERCISES — CH1-CH5 (nodes 1-20)
   ══════════════════════════════════════════════════ */
export const pyExercises = {
        1: [
            { type: 'trace', prompt: 'What is the value of `count`?', code: [{ text: 'count = 0' }, { text: 'for i in range(5):' }, { text: '    if i % 2 == 0:' }, { text: '        count += 1' }, { text: 'print(count)', highlight: true }], options: ['2', '3', '5', '4'], correct: 1 },
            { type: 'realworld', prompt: 'Which code counts total items in a cart?', scenario: '🛒 Cart: 3 apples, 2 oranges, 1 banana.', options: [{ code: 'cart = [3, 2, 1]\ntotal = sum(cart)', label: 'Sum list' }, { code: 'cart = 3 + 2 + 1\ntotal = len(cart)', label: 'len() on int' }, { code: 'cart = "3 2 1"\ntotal = len(cart)', label: 'String length' }, { code: 'cart = {3, 2, 1}\ntotal = max(cart)', label: 'Max of set' }], correct: 0 },
            { type: 'pair', prompt: 'Match concepts', pairs: [{ id: 1, left: 'Variable', right: 'Stores a value' }, { id: 2, left: 'String', right: 'Text data' }, { id: 3, left: 'Integer', right: 'Whole number' }, { id: 4, left: 'Boolean', right: 'True or False' }] },
            { type: 'output', prompt: 'What does this print?', code: [{ text: 'x = 7' }, { text: 'y = 2' }, { text: 'print(x // y, x % y)' }], terminalOutput: '3 1', options: ['3.5 1', '3 1', '3.5 0', '3 0'], correct: 1 },
            { type: 'fillgap', prompt: 'Complete: swap two variables without a temp', codeParts: [{ text: 'a = 5\nb = 10\n', type: 'fixed' }, { text: 'a, b = b, a', type: 'gap', id: 'g1' }], bank: ['a, b = b, a', 'a = b; b = a', 'swap(a, b)', 'a == b'], correctFill: { g1: 'a, b = b, a' } },
            { type: 'scramble', prompt: 'Build code to calculate BMI', pieces: [{ id: 'a', text: 'weight = 70' }, { id: 'b', text: 'height = 1.75' }, { id: 'c', text: 'bmi = weight' }, { id: 'd', text: 'print(round(bmi, 1))' }], distractors: [{ id: 'e', text: 'bmi = weight * height' }], correctOrder: ['a', 'b', 'c', 'd'] },
        ],
        2: [
            { type: 'bug', prompt: 'Find the syntax error', code: [{ text: 'def greet(name):', hasError: false }, { text: '    msg = "Hello " + name', hasError: false }, { text: '    print(msg', hasError: true }, { text: '    return msg', hasError: false }], correctLine: 2 },
            { type: 'errordecode', prompt: 'Decode this error', errorText: 'Traceback (most recent call last):\n  File "main.py", line 3\n    print(message\n         ^\nSyntaxError: unexpected EOF while parsing', question: 'What caused this?', options: ['Missing closing parenthesis', 'Undefined variable', 'Wrong indentation', 'Invalid string'], correct: 0 },
            { type: 'refactor', prompt: 'Which is the cleanest?', originalCode: 'x = 10\nif x > 5:\n    r = "big"\nelse:\n    r = "small"\nprint(r)', options: [{ code: 'x = 10\nr = "big" if x > 5 else "small"\nprint(r)', label: 'Ternary expression' }, { code: 'x = 10\nresult = ""\nif x > 5: result = "big"\nif x <= 5: result = "small"', label: 'Two ifs' }, { code: 'print("big") if 10 > 5 else print("small")', label: 'Print in ternary' }], correct: 0 },
            { type: 'bug', prompt: 'Why does this crash?', code: [{ text: 'age = input("Age: ")', hasError: false }, { text: 'if age > 18:', hasError: true }, { text: '    print("Adult")', hasError: false }], correctLine: 1 },
            { type: 'output', prompt: 'What does this print?', code: [{ text: 'x = "5"' }, { text: 'y = 3' }, { text: 'print(x * y)' }], terminalOutput: '555', options: ['15', '555', '53', 'Error'], correct: 1 },
            { type: 'trace', prompt: 'What is the type of result?', code: [{ text: 'a = 10' }, { text: 'b = 3' }, { text: 'result = a' }, { text: 'print(type(result))', highlight: true }], options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "3.33"], correct: 1 },
        ],
        3: [
            { type: 'video', title: 'Variables & Data Types', description: 'Variables store data. Python is dynamically typed — no type declarations needed. int, float, str, bool are the basics.', duration: '2:45', thumbnail: '🎬' },
            { type: 'output', prompt: 'What does this print?', code: [{ text: 'name = "Rheo"' }, { text: 'age = 3' }, { text: 'print(type(age))' }], terminalOutput: "<class 'int'>", options: ["<class 'str'>", "<class 'int'>", "3", "Error"], correct: 1 },
            { type: 'pair', prompt: 'Match Python types', pairs: [{ id: 1, left: 'int', right: '42' }, { id: 2, left: 'float', right: '3.14' }, { id: 3, left: 'str', right: '"hello"' }, { id: 4, left: 'bool', right: 'True' }] },
        ],
        4: [
            { type: 'pair', prompt: 'Match operators', pairs: [{ id: 1, left: '==', right: 'Equals' }, { id: 2, left: '!=', right: 'Not equals' }, { id: 3, left: '**', right: 'Power' }, { id: 4, left: '//', right: 'Floor divide' }] },
            { type: 'trace', prompt: 'What is the output?', code: [{ text: 'x = 17' }, { text: 'print(x % 5, x // 5)', highlight: true }], options: ['2 3', '3 2', '2 4', '17 5'], correct: 0 },
            { type: 'fillgap', prompt: 'Complete: convert Celsius to Fahrenheit', codeParts: [{ text: 'celsius = 25\n', type: 'fixed' }, { text: 'fahrenheit = celsius * 9/5 + 32', type: 'gap', id: 'g1' }, { text: '\nprint(fahrenheit)', type: 'fixed' }], bank: ['celsius * 9/5 + 32', 'celsius + 32', 'celsius * 1.8', 'celsius / 5 * 9'], correctFill: { g1: 'celsius * 9/5 + 32' } },
        ],
        // ═══ CH2: FLOW CONTROL ⭐ ═══
        5: [
            { type: 'trace', prompt: 'What does this nested condition print?', code: [{ text: 'x = 15' }, { text: 'if x > 20:' }, { text: '    print("A")' }, { text: 'elif x > 10:' }, { text: '    if x % 2 == 0:' }, { text: '        print("B")' }, { text: '    else:' }, { text: '        print("C")', highlight: true }], options: ['A', 'B', 'C', 'None'], correct: 2 },
            { type: 'bug', prompt: 'Voting check bug — 18 year olds should vote!', code: [{ text: 'age = 18', hasError: false }, { text: 'if age > 18:', hasError: true }, { text: '    print("Can vote")', hasError: false }], correctLine: 1 },
            { type: 'output', prompt: 'Short-circuit: what prints?', code: [{ text: 'a = 0' }, { text: 'b = 5' }, { text: 'result = a and b/a' }, { text: 'print(result)' }], terminalOutput: '0', options: ['0', 'Error: ZeroDivision', '5', 'False'], correct: 0 },
            { type: 'realworld', prompt: 'Which handles login correctly?', scenario: '🔐 3 password attempts, then lock.', options: [{ code: 'attempts = 0\nwhile attempts < 3:\n    pwd = input()\n    if pwd == secret: break\n    attempts += 1', label: 'Counter + break' }, { code: 'for i in range(3):\n    pwd = input()\n    if pwd != secret: continue', label: 'Continue loop' }, { code: 'pwd = input()\nif pwd == secret: print("OK")', label: 'Single attempt' }, { code: 'while True:\n    pwd = input()\n    break', label: 'Infinite + break' }], correct: 0 },
            { type: 'scramble', prompt: 'Build a grade calculator', pieces: [{ id: 'a', text: 'score = 75' }, { id: 'b', text: 'if score >= 90: grade = "A"' }, { id: 'c', text: 'elif score >= 80: grade = "B"' }, { id: 'd', text: 'elif score >= 70: grade = "C"' }, { id: 'e', text: 'else: grade = "F"' }, { id: 'f', text: 'print(grade)' }], distractors: [{ id: 'g', text: 'if score == 90: grade = "A"' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f'] },
            { type: 'trace', prompt: 'What does this ternary chain produce?', code: [{ text: 'n = 0' }, { text: 'label = "positive" if n > 0 else "negative" if n < 0 else "zero"' }, { text: 'print(label)', highlight: true }], options: ['positive', 'negative', 'zero', 'Error'], correct: 2 },
        ],
        6: [
            { type: 'trace', prompt: 'Truthiness check — what prints?', code: [{ text: 'x = [1, 2, 3]' }, { text: 'y = []' }, { text: 'print(bool(x), bool(y))', highlight: true }], options: ['True True', 'True False', 'False True', 'False False'], correct: 1 },
            { type: 'refactor', prompt: 'Pythonic emptiness check?', originalCode: 'if len(my_list) > 0:\n    do_something()', options: [{ code: 'if my_list:\n    do_something()', label: 'Truthy check' }, { code: 'if my_list != []:\n    do_something()', label: 'Compare to empty' }, { code: 'if my_list is not None:\n    do_something()', label: 'None check' }], correct: 0 },
            { type: 'fillgap', prompt: 'Check if number is in range 1-100', codeParts: [{ text: 'def in_range(n):\n    return ', type: 'fixed' }, { text: '1 <= n <= 100', type: 'gap', id: 'g1' }], bank: ['1 <= n <= 100', 'n > 0 and n < 101', 'n in range(100)', '1 < n < 100'], correctFill: { g1: '1 <= n <= 100' } },
            { type: 'output', prompt: 'What values are truthy in Python?', code: [{ text: 'values = [0, "", [], None, 1, "hi", [0]]' }, { text: 'truthy = [v for v in values if v]' }, { text: 'print(len(truthy))' }], terminalOutput: '3', options: ['2', '3', '4', '7'], correct: 1 },
            { type: 'pair', prompt: 'Match falsy values', pairs: [{ id: 1, left: '0', right: 'Falsy integer' }, { id: 2, left: '""', right: 'Falsy string' }, { id: 3, left: '[]', right: 'Falsy list' }, { id: 4, left: 'None', right: 'Falsy null' }] },
        ],
        7: [
            { type: 'terminal', prompt: 'Create a variable and print it', expectedCommands: ['name = "Otter"', 'print(name)'], hint: 'Assign then print', terminalHistory: [{ type: 'system', text: '>>> Daily Challenge' }] },
            { type: 'trace', prompt: 'What is `result`?', code: [{ text: 'result = ""' }, { text: 'for c in "hello":' }, { text: '    result += c.upper()' }, { text: 'print(result)', highlight: true }], options: ['hello', 'HELLO', 'Hello', 'hELLO'], correct: 1 },
            { type: 'output', prompt: 'What does this f-string print?', code: [{ text: 'name = "Otter"' }, { text: 'age = 5' }, { text: 'print(f"{name} is {age*7} in human years")' }], terminalOutput: 'Otter is 35 in human years', options: ['Otter is 35 in human years', 'Otter is 5 in human years', '{name} is {age*7}', 'Error'], correct: 0 },
        ],
        8: [
            { type: 'video', title: 'Conditional Logic Deep Dive', description: 'if/elif/else chains, ternary, truthiness, short-circuit evaluation, match-case (3.10+).', duration: '3:00', thumbnail: '🎥' },
            { type: 'trace', prompt: 'Match-case: what prints?', code: [{ text: 'status = 404' }, { text: 'match status:' }, { text: '    case 200: msg = "OK"' }, { text: '    case 404: msg = "Not Found"' }, { text: '    case _: msg = "Unknown"' }, { text: 'print(msg)', highlight: true }], options: ['OK', 'Not Found', 'Unknown', 'Error'], correct: 1 },
        ],
        // ═══ CH3: LOOPS ⭐⭐ ═══
        9: [
            { type: 'scramble', prompt: 'Print numbers 1-5', pieces: [{ id: 'a', text: 'for i in range(1, 6):' }, { id: 'b', text: '    print(i)' }], distractors: [{ id: 'c', text: '    print(i + 1)' }, { id: 'd', text: 'while i < 5:' }], correctOrder: ['a', 'b'] },
            { type: 'bug', prompt: 'Off-by-one: should print 1-10', code: [{ text: 'for i in range(1, 10):', hasError: true }, { text: '    print(i)', hasError: false }], correctLine: 0 },
            { type: 'trace', prompt: 'How many iterations?', code: [{ text: 'n = 64' }, { text: 'count = 0' }, { text: 'while n > 1:' }, { text: '    n = n // 2' }, { text: '    count += 1' }, { text: 'print(count)', highlight: true }], options: ['5', '6', '7', '32'], correct: 1 },
            { type: 'fillgap', prompt: 'Complete the sum loop', codeParts: [{ text: 'total = 0\nfor num in ', type: 'fixed' }, { text: '[1,2,3,4]', type: 'gap', id: 'g1' }, { text: ':\n    total += num', type: 'fixed' }], bank: ['[1,2,3,4]', 'range(4)', '(1,2,3)', '{1:4}'], correctFill: { g1: '[1,2,3,4]' } },
            { type: 'realworld', prompt: 'Which finds the max in a list?', scenario: '📊 Find biggest number in [3, 7, 2, 9, 4]', options: [{ code: 'nums = [3,7,2,9,4]\nbest = nums[0]\nfor n in nums:\n    if n > best: best = n', label: 'Manual scan' }, { code: 'nums = [3,7,2,9,4]\nbest = nums[-1]', label: 'Last element' }, { code: 'nums = [3,7,2,9,4]\nnums.sort()', label: 'Sort only' }, { code: 'nums = [3,7,2,9,4]\nbest = sum(nums)', label: 'Sum' }], correct: 0 },
            { type: 'output', prompt: 'What prints?', code: [{ text: 'for i in range(5):' }, { text: '    if i == 3: break' }, { text: '    print(i, end=" ")' }], terminalOutput: '0 1 2 ', options: ['0 1 2 ', '0 1 2 3', '0 1 2 3 4', '3'], correct: 0 },
        ],
        10: [
            { type: 'trace', prompt: 'How many times does print() run?', code: [{ text: 'for i in range(3):' }, { text: '    for j in range(4):' }, { text: '        print(i, j)', highlight: true }], options: ['7', '12', '9', '16'], correct: 1 },
            { type: 'output', prompt: 'What pattern prints?', code: [{ text: 'for i in range(1, 4):' }, { text: '    print("*" * i)' }], terminalOutput: '*\n**\n***', options: ['***\n**\n*', '*\n**\n***', '***', '* * *'], correct: 1 },
            { type: 'realworld', prompt: 'Flatten a 2D matrix?', scenario: '📊 [[1,2],[3,4],[5,6]] → [1,2,3,4,5,6]', options: [{ code: 'flat = [x for row in m for x in row]', label: 'List comprehension' }, { code: 'flat = sum(m)', label: 'Sum matrix' }, { code: 'flat = m.flatten()', label: '.flatten()' }, { code: 'flat = list(m)', label: 'list()' }], correct: 0 },
            { type: 'scramble', prompt: 'Build a multiplication table row', pieces: [{ id: 'a', text: 'n = 5' }, { id: 'b', text: 'for i in range(1, 11):' }, { id: 'c', text: '    print(f"{n} x {i} = {n*i}")' }], distractors: [{ id: 'd', text: '    print(n + i)' }], correctOrder: ['a', 'b', 'c'] },
            { type: 'trace', prompt: 'What does enumerate give?', code: [{ text: 'fruits = ["apple", "banana", "cherry"]' }, { text: 'for i, f in enumerate(fruits):' }, { text: '    print(i, f)', highlight: true }], options: ['0 apple\n1 banana\n2 cherry', 'apple 0\nbanana 1', '1 apple\n2 banana\n3 cherry', 'Error'], correct: 0 },
        ],
        11: [
            { type: 'scramble', prompt: 'Build a prime checker', pieces: [{ id: 'a', text: 'def is_prime(n):' }, { id: 'b', text: '    if n < 2: return False' }, { id: 'c', text: '    for i in range(2, int(n**0.5)+1):' }, { id: 'd', text: '        if n % i == 0: return False' }, { id: 'e', text: '    return True' }], distractors: [{ id: 'f', text: '    for i in range(n):' }], correctOrder: ['a', 'b', 'c', 'd', 'e'] },
            { type: 'trace', prompt: 'List comprehension — what\'s the result?', code: [{ text: 'nums = [1, 2, 3, 4, 5, 6]' }, { text: 'evens = [n for n in nums if n % 2 == 0]' }, { text: 'print(evens)', highlight: true }], options: ['[2, 4, 6]', '[1, 3, 5]', '[1, 2, 3, 4, 5, 6]', '3'], correct: 0 },
            { type: 'fillgap', prompt: 'Complete: list comprehension to square numbers', codeParts: [{ text: 'squares = ', type: 'fixed' }, { text: '[x**2 for x in range(1,6)]', type: 'gap', id: 'g1' }], bank: ['[x**2 for x in range(1,6)]', 'map(x**2, range(5))', '[x*x in range(5)]', 'range(1,6)**2'], correctFill: { g1: '[x**2 for x in range(1,6)]' } },
            { type: 'realworld', prompt: 'Which filters students who passed?', scenario: '📝 scores = [45, 78, 92, 33, 88]. Passing = 60+', options: [{ code: 'passed = [s for s in scores if s >= 60]', label: 'List comp filter' }, { code: 'passed = scores.filter(60)', label: '.filter()' }, { code: 'passed = scores > 60', label: 'Direct compare' }, { code: 'passed = max(scores)', label: 'Max only' }], correct: 0 },
        ],
        12: [
            { type: 'pair', prompt: 'Match loop tools', pairs: [{ id: 1, left: 'break', right: 'Exit loop' }, { id: 2, left: 'continue', right: 'Skip iteration' }, { id: 3, left: 'enumerate()', right: 'Index + value' }, { id: 4, left: 'zip()', right: 'Parallel iterate' }] },
            { type: 'trace', prompt: 'What does zip produce?', code: [{ text: 'names = ["Ali", "Ece"]' }, { text: 'ages = [20, 22]' }, { text: 'for n, a in zip(names, ages):' }, { text: '    print(f"{n}:{a}")', highlight: true }], options: ['Ali:20\nEce:22', 'Ali Ece\n20 22', '(Ali,20)', 'Error'], correct: 0 },
            { type: 'output', prompt: 'What prints with continue?', code: [{ text: 'for i in range(5):' }, { text: '    if i == 2: continue' }, { text: '    print(i, end=" ")' }], terminalOutput: '0 1 3 4 ', options: ['0 1 3 4 ', '0 1 2 3 4', '2', '0 1'], correct: 0 },
        ],
        // ═══ CH4: FUNCTIONS ⭐⭐ ═══
        13: [
            { type: 'trace', prompt: 'Default args — what returns?', code: [{ text: 'def add(a, b=10):' }, { text: '    return a + b' }, { text: 'print(add(3))', highlight: true }], options: ['3', '10', '13', 'Error'], correct: 2 },
            { type: 'bug', prompt: 'Should return sum, not print it', code: [{ text: 'def add(a, b):', hasError: false }, { text: '    result = a + b', hasError: false }, { text: '    print(result)', hasError: true }], correctLine: 2 },
            { type: 'refactor', prompt: 'Pick the cleanest', originalCode: 'def calc(a, b, op):\n    if op == "add": return a+b\n    if op == "sub": return a-b\n    if op == "mul": return a*b', options: [{ code: 'ops = {"add": lambda a,b: a+b,\n       "sub": lambda a,b: a-b,\n       "mul": lambda a,b: a*b}\ndef calc(a,b,op): return ops[op](a,b)', label: 'Dict dispatch' }, { code: 'def calc(a,b,op): return eval(f"{a}{op}{b}")', label: 'eval()' }, { code: 'def calc(a,b,op):\n    match op:\n        case "+": return a+b', label: 'Match' }], correct: 0 },
            { type: 'output', prompt: '*args — what prints?', code: [{ text: 'def total(*nums):' }, { text: '    return sum(nums)' }, { text: 'print(total(1, 2, 3, 4))' }], terminalOutput: '10', options: ['(1,2,3,4)', '10', '4', 'Error'], correct: 1 },
            { type: 'scramble', prompt: 'Build a function with default + kwargs', pieces: [{ id: 'a', text: 'def greet(name, greeting="Hello"):' }, { id: 'b', text: '    return f"{greeting}, {name}!"' }, { id: 'c', text: 'print(greet("Furkan"))' }, { id: 'd', text: 'print(greet("Arda", greeting="Hey"))' }], distractors: [{ id: 'e', text: '    return name + greeting' }], correctOrder: ['a', 'b', 'c', 'd'] },
            { type: 'trace', prompt: 'Lambda — what returns?', code: [{ text: 'double = lambda x: x * 2' }, { text: 'nums = [1, 2, 3]' }, { text: 'result = list(map(double, nums))' }, { text: 'print(result)', highlight: true }], options: ['[2, 4, 6]', '[1, 2, 3]', '6', 'Error'], correct: 0 },
        ],
        14: [
            { type: 'trace', prompt: 'Global or local?', code: [{ text: 'x = "global"' }, { text: 'def f():' }, { text: '    x = "local"' }, { text: '    print(x)', highlight: true }, { text: 'f()' }], options: ['global', 'local', 'Error', 'None'], correct: 1 },
            { type: 'output', prompt: 'Closure counter', code: [{ text: 'def make_counter():' }, { text: '    count = 0' }, { text: '    def inc():' }, { text: '        nonlocal count' }, { text: '        count += 1' }, { text: '        return count' }, { text: '    return inc' }, { text: 'c = make_counter()' }, { text: 'print(c(), c(), c())' }], terminalOutput: '1 2 3', options: ['0 0 0', '1 1 1', '1 2 3', 'Error'], correct: 2 },
            { type: 'bug', prompt: 'Why does this fail?', code: [{ text: 'total = 0', hasError: false }, { text: 'def add(n):', hasError: false }, { text: '    total += n', hasError: true }, { text: 'add(5)', hasError: false }], correctLine: 2 },
            { type: 'errordecode', prompt: 'Decode this scope error', errorText: "UnboundLocalError: cannot access local variable 'total' where it is not associated with a value", question: 'Fix?', options: ['Add "global total" or "nonlocal total"', 'Use total = 0 inside function', 'Import total', 'Delete total'], correct: 0 },
            { type: 'realworld', prompt: 'When to use closures?', scenario: '🧠 You need a function that remembers state between calls.', options: [{ code: 'def make_multiplier(factor):\n    def multiply(x):\n        return x * factor\n    return multiply\ndouble = make_multiplier(2)', label: 'Closure — captures factor' }, { code: 'factor = 2\ndef multiply(x):\n    return x * factor', label: 'Global variable' }, { code: 'class Mult:\n    def __init__(self, f): self.f = f', label: 'Class (overkill)' }, { code: 'multiply = lambda x: x * 2', label: 'Hardcoded lambda' }], correct: 0 },
        ],
        15: [
            { type: 'video', title: 'Functions Deep Dive', description: 'Parameters, defaults, *args, **kwargs, closures, decorators, and first-class functions.', duration: '3:30', thumbnail: '🎥' },
            { type: 'pair', prompt: 'Match function concepts', pairs: [{ id: 1, left: 'def', right: 'Declare function' }, { id: 2, left: 'return', right: 'Send value back' }, { id: 3, left: '*args', right: 'Variable positional' }, { id: 4, left: '**kwargs', right: 'Variable keyword' }] },
            { type: 'trace', prompt: 'Decorator — what prints?', code: [{ text: 'def shout(func):' }, { text: '    def wrapper(name):' }, { text: '        return func(name).upper()' }, { text: '    return wrapper' }, { text: '@shout' }, { text: 'def greet(name):' }, { text: '    return f"hello {name}"' }, { text: 'print(greet("Otter"))', highlight: true }], options: ['hello Otter', 'HELLO OTTER', 'Hello Otter', 'Error'], correct: 1 },
        ],
        16: [
            { type: 'trace', prompt: 'What does fib(5) return?', code: [{ text: 'def fib(n):' }, { text: '    if n <= 1: return n' }, { text: '    return fib(n-1) + fib(n-2)' }, { text: 'print(fib(5))', highlight: true }], options: ['3', '5', '8', '13'], correct: 1 },
            { type: 'algostep', prompt: 'fib(4) call tree', array: ['fib(4)', 'fib(3)+fib(2)', '(fib(2)+fib(1))+(fib(1)+fib(0))', '(1+1)+(1+0)=3'], step: 3, description: 'fib(4) = fib(3) + fib(2). Expanding...', question: 'What is fib(3)?', options: ['1', '2', '3', '5'], correct: 1 },
            { type: 'errordecode', prompt: 'Decode recursion error', errorText: 'RecursionError: maximum recursion depth exceeded', question: 'Cause?', options: ['Missing base case', 'Wrong return type', 'Too many params', 'Import error'], correct: 0 },
            { type: 'scramble', prompt: 'Build factorial', pieces: [{ id: 'a', text: 'def factorial(n):' }, { id: 'b', text: '    if n <= 1: return 1' }, { id: 'c', text: '    return n * factorial(n-1)' }], distractors: [{ id: 'd', text: '    return n + factorial(n)' }], correctOrder: ['a', 'b', 'c'] },
            { type: 'trace', prompt: 'What does sum_digits(123) return?', code: [{ text: 'def sum_digits(n):' }, { text: '    if n < 10: return n' }, { text: '    return n % 10 + sum_digits(n // 10)' }, { text: 'print(sum_digits(123))', highlight: true }], options: ['6', '123', '3', '12'], correct: 0 },
            { type: 'realworld', prompt: 'Which is naturally recursive?', scenario: '🤔 Which breaks into same-type subproblems?', options: [{ code: '# File system: folders contain folders', label: 'Directory traversal ✓' }, { code: '# Read file line by line', label: 'File reading' }, { code: '# Print "Hello" 5 times', label: 'Simple loop' }, { code: '# Add two numbers', label: 'Addition' }], correct: 0 },
        ],
        // ═══ CH5: DATA STRUCTURES I ⭐⭐ ═══
        17: [
            { type: 'trace', prompt: 'References! What prints?', code: [{ text: 'a = [1, 2, 3]' }, { text: 'b = a' }, { text: 'b.append(4)' }, { text: 'print(len(a))', highlight: true }], options: ['3', '4', 'Error', '[1,2,3]'], correct: 1 },
            { type: 'output', prompt: 'Slicing result?', code: [{ text: 'x = [10, 20, 30, 40, 50]' }, { text: 'print(x[1:4])' }], terminalOutput: '[20, 30, 40]', options: ['[10, 20, 30]', '[20, 30, 40]', '[20, 30, 40, 50]', '[10, 20, 30, 40]'], correct: 1 },
            { type: 'realworld', prompt: 'Reverse without mutating?', scenario: '🔄 Original must stay unchanged', options: [{ code: 'original = [1,2,3]\nrev = original[::-1]', label: 'Slice copy' }, { code: 'original = [1,2,3]\noriginal.reverse()', label: '.reverse() mutates!' }, { code: 'original = [1,2,3]\nrev = reversed(original)', label: 'Iterator only' }, { code: 'original = [1,2,3]\noriginal = original[::-1]', label: 'Reassign' }], correct: 0 },
            { type: 'bug', prompt: 'Why does b change a?', code: [{ text: 'a = [1, 2, 3]', hasError: false }, { text: 'b = a', hasError: true }, { text: 'b.append(4)', hasError: false }, { text: 'print(a)  # [1,2,3,4] !', hasError: false }], correctLine: 1 },
            { type: 'refactor', prompt: 'How to properly copy a list?', originalCode: 'original = [1, 2, 3]\ncopy = original  # This is a reference!', options: [{ code: 'copy = original[:]  # or list(original)\n# or original.copy()', label: 'Shallow copy ✓' }, { code: 'copy = original', label: 'Still a reference' }, { code: 'copy = &original', label: 'Not Python syntax' }], correct: 0 },
        ],
        18: [
            { type: 'trace', prompt: 'Frequency counter?', code: [{ text: 'word = "banana"' }, { text: 'freq = {}' }, { text: 'for c in word:' }, { text: '    freq[c] = freq.get(c, 0) + 1' }, { text: 'print(freq["a"])', highlight: true }], options: ['1', '2', '3', 'Error'], correct: 2 },
            { type: 'refactor', prompt: 'Most Pythonic char counting?', originalCode: 'freq = {}\nfor c in word:\n    if c in freq: freq[c] += 1\n    else: freq[c] = 1', options: [{ code: 'from collections import Counter\nfreq = Counter(word)', label: 'Counter class ✓' }, { code: 'freq = {c: word.count(c) for c in word}', label: 'O(n²) comprehension' }, { code: 'freq = dict.fromkeys(word, 0)', label: 'fromkeys + loop' }], correct: 0 },
            { type: 'fillgap', prompt: 'Check anagram', codeParts: [{ text: 'def is_anagram(a, b):\n    return ', type: 'fixed' }, { text: 'sorted(a) == sorted(b)', type: 'gap', id: 'g1' }], bank: ['sorted(a) == sorted(b)', 'a == b', 'len(a) == len(b)', 'set(a) == set(b)'], correctFill: { g1: 'sorted(a) == sorted(b)' } },
            { type: 'output', prompt: 'Dict comprehension?', code: [{ text: 'squares = {x: x**2 for x in range(1,5)}' }, { text: 'print(squares)' }], terminalOutput: '{1: 1, 2: 4, 3: 9, 4: 16}', options: ['{1:1, 2:4, 3:9, 4:16}', '[1, 4, 9, 16]', '{1,4,9,16}', 'Error'], correct: 0 },
            { type: 'realworld', prompt: 'Which finds most common word?', scenario: '📝 words = ["the","cat","the","dog","the"]', options: [{ code: 'from collections import Counter\nmost = Counter(words).most_common(1)', label: 'Counter.most_common()' }, { code: 'most = max(words)', label: 'Alphabetical max' }, { code: 'most = words[0]', label: 'First element' }, { code: 'most = len(words)', label: 'Count total' }], correct: 0 },
            { type: 'pair', prompt: 'Match set operations', pairs: [{ id: 1, left: 'a | b', right: 'Union' }, { id: 2, left: 'a & b', right: 'Intersection' }, { id: 3, left: 'a - b', right: 'Difference' }, { id: 4, left: 'a ^ b', right: 'Symmetric diff' }] },
        ],
        19: [
            { type: 'scramble', prompt: 'Find duplicates in a list', pieces: [{ id: 'a', text: 'def find_dupes(lst):' }, { id: 'b', text: '    seen = set()' }, { id: 'c', text: '    dupes = set()' }, { id: 'd', text: '    for x in lst:' }, { id: 'e', text: '        if x in seen: dupes.add(x)' }, { id: 'f', text: '        seen.add(x)' }, { id: 'g', text: '    return list(dupes)' }], distractors: [{ id: 'h', text: '    return lst' }], correctOrder: ['a', 'b', 'c', 'd', 'e', 'f', 'g'] },
            { type: 'trace', prompt: 'Set operations?', code: [{ text: 'a = {1, 2, 3, 4}' }, { text: 'b = {3, 4, 5, 6}' }, { text: 'print(a & b)', highlight: true }], options: ['{3, 4}', '{1,2,3,4,5,6}', '{1,2}', '{5,6}'], correct: 0 },
            { type: 'realworld', prompt: 'Remove duplicates preserving order?', scenario: '📋 [3, 1, 4, 1, 5, 9, 2, 6, 5] → [3,1,4,5,9,2,6]', options: [{ code: 'seen = set()\nresult = []\nfor x in lst:\n    if x not in seen:\n        seen.add(x)\n        result.append(x)', label: 'Set + list (ordered)' }, { code: 'result = list(set(lst))', label: 'set() — loses order' }, { code: 'result = sorted(set(lst))', label: 'sorted set' }, { code: 'result = lst', label: 'No change' }], correct: 0 },
            { type: 'output', prompt: 'Dictionary merge?', code: [{ text: 'a = {"x": 1, "y": 2}' }, { text: 'b = {"y": 3, "z": 4}' }, { text: 'merged = {**a, **b}' }, { text: 'print(merged["y"])' }], terminalOutput: '3', options: ['2', '3', '[2,3]', 'Error'], correct: 1 },
        ],
        20: [
            { type: 'pair', prompt: 'Best use-case for each', pairs: [{ id: 1, left: 'List', right: 'Ordered, index access' }, { id: 2, left: 'Set', right: 'Unique + fast lookup' }, { id: 3, left: 'Dict', right: 'Key-value mapping' }, { id: 4, left: 'Tuple', right: 'Immutable sequence' }] },
            { type: 'trace', prompt: 'Tuple unpacking?', code: [{ text: 'point = (3, 7)' }, { text: 'x, y = point' }, { text: 'print(x + y)', highlight: true }], options: ['(3,7)', '10', '37', 'Error'], correct: 1 },
            { type: 'realworld', prompt: 'Which data structure for a phone book?', scenario: '📱 Look up phone number by name.', options: [{ code: 'phonebook = {"Ali": "555-1234", "Ece": "555-5678"}', label: 'Dict — O(1) lookup' }, { code: 'phonebook = [("Ali","555-1234"), ("Ece","555-5678")]', label: 'List of tuples — O(n)' }, { code: 'phonebook = {"555-1234", "555-5678"}', label: 'Set — no keys' }, { code: 'phonebook = ["Ali", "555-1234"]', label: 'Flat list' }], correct: 0 },
        ],
}
